// data_g3.js — AMEB Grade 3 Piano Syllabus Data (2026)
// Exam code: 9943  |  Three lists: A, B, C
// Sources: Series 19 (S19), Series 18 (S18), Series 17 (S17), Manual, Aust Anthology

const DATA_G3 = [

  // ═══════════════════════════════════════════════════
  //  LIST A  — Baroque / Classical technique & études
  // ═══════════════════════════════════════════════════

  // --- List A · S19 ---
  { "l":"A","s":"S19","c":"BURGMÜLLER, F.","t":"La tarantelle (Tarantella) No 20 from 25 études faciles et progressives Op.100","nat":"German","era":"Romantic","key":"A minor","focus":["Dance character","Staccato technique","Rhythmic drive"] },
  { "l":"A","s":"S19","c":"HANDEL, G.F.","t":"Sarabande II from Suite HWV 448","nat":"German","era":"Baroque","key":"D minor","focus":["Baroque dance","Ornamentation","Sustained tone"] },
  { "l":"A","s":"S19","c":"HENGEVELD, G.","t":"Maestoso No 15 from 15 polyphonic studies","nat":"Dutch","era":"Modern","key":"Variable","focus":["Polyphonic texture","Voice independence","Stately character"] },
  { "l":"A","s":"S19","c":"RYBICKI, F.","t":"Prelude from I am already playing Op.21","nat":"Polish","era":"Modern","key":"Variable","focus":["Lyrical melody","Expressive playing","Contemporary idiom"] },

  // --- List A · S18 ---
  { "l":"A","s":"S18","c":"CONCONE, G.","t":"Study No 5 from 30 melodious studies Op.24","nat":"Italian","era":"Romantic","key":"Variable","focus":["Cantabile melody","Tone shaping","Legato playing"] },
  { "l":"A","s":"S18","c":"HANDEL, G.F.","t":"Preludio from Chaconne HWV 442","nat":"German","era":"Baroque","key":"G major","focus":["Baroque preludio","Ornamentation","Keyboard fluency"] },
  { "l":"A","s":"S18","c":"SCHOENMEHL, M.","t":"Banjo tune","nat":"German","era":"Modern","key":"Variable","focus":["Rhythmic character","Modern idiom","Light touch"] },
  { "l":"A","s":"S18","c":"TELEMANN, G.P.","t":"Loure 3rd movement from Overture TWV 32:12","nat":"German","era":"Baroque","key":"Variable","focus":["Baroque dance","Stylistic awareness","Dotted rhythm"] },

  // --- List A · S17 ---
  { "l":"A","s":"S17","c":"BURGMÜLLER, F.","t":"Ballade No 15 from 25 easy and progressive studies Op.100","nat":"German","era":"Romantic","key":"G minor","focus":["Narrative character","Dynamic shaping","Romantic drama"] },
  { "l":"A","s":"S17","c":"HANDEL, G.F.","t":"Sonatina HWV 585","nat":"German","era":"Baroque","key":"Variable","focus":["Baroque clarity","Ornamentation","Formal structure"] },
  { "l":"A","s":"S17","c":"HUMMEL, J.N.","t":"Etude No 32 from Ausführlich theoretisch-practische Anweisung Op.s157","nat":"Austrian","era":"Classical","key":"Variable","focus":["Finger technique","Classical elegance","Velocity control"] },
  { "l":"A","s":"S17","c":"RAICHEV, A.","t":"The water mill","nat":"Bulgarian","era":"Modern","key":"Variable","focus":["Musical imagery","Rhythmic motion","Modern character"] },

  // --- List A · Manual (45 pieces) ---
  { "l":"A","s":"Manual","c":"ANON.","t":"Polonaise in G minor BWV Anh 119 from Clavierbüchlein für Anna Magdalena Bach","nat":"German","era":"Baroque","key":"G minor","focus":["Baroque dance","Stylistic clarity","Rhythmic precision"] },
  { "l":"A","s":"Manual","c":"BACH, C.P.E.","t":"Polonaise in G minor BWV Anh 125 from Clavierbüchlein für Anna Magdalena Bach","nat":"German","era":"Baroque","key":"G minor","focus":["Baroque dance","Galant style","Articulation"] },
  { "l":"A","s":"Manual","c":"BACH, J.C.F.","t":"Solfeggio","nat":"German","era":"Classical","key":"Variable","focus":["Keyboard fluency","Classical clarity","Finger technique"] },
  { "l":"A","s":"Manual","c":"BACH, J.S.","t":"Minuet in G minor BWV 842 from Clavier-Büchlein für Wilhelm Friedemann Bach","nat":"German","era":"Baroque","key":"G minor","focus":["Baroque minuet","Polyphonic texture","Stylistic grace"] },
  { "l":"A","s":"Manual","c":"BACH, J.S.","t":"Polonaise 5th movement from French Suite in E major BWV 817","nat":"German","era":"Baroque","key":"E major","focus":["Baroque dance","Ornamentation","Rhythmic drive"] },
  { "l":"A","s":"Manual","c":"BACH, J.S.","t":"Præambulum in C major BWV 924 from Clavier-Büchlein für Wilhelm Friedemann Bach","nat":"German","era":"Baroque","key":"C major","focus":["Baroque preludio","Finger independence","Voice leading"] },
  { "l":"A","s":"Manual","c":"BACH, J.S.","t":"Prelude in C major BWV 939","nat":"German","era":"Baroque","key":"C major","focus":["Baroque clarity","Broken chord texture","Even tone"] },
  { "l":"A","s":"Manual","c":"BACH, J.S.","t":"Prelude in C minor BWV 999","nat":"German","era":"Baroque","key":"C minor","focus":["Broken chord pattern","Baroque style","Tonal colour"] },
  { "l":"A","s":"Manual","c":"BACH, W.F.","t":"Allemande in G minor BWV 836 from Clavier-Büchlein für Wilhelm Friedemann Bach","nat":"German","era":"Baroque","key":"G minor","focus":["Baroque allemande","Ornamentation","Stylistic clarity"] },
  { "l":"A","s":"Manual","c":"BAUSTETTER, J.","t":"Spanish folia","nat":"German","era":"Baroque","key":"Variable","focus":["Baroque variations","Dance character","Keyboard style"] },
  { "l":"A","s":"Manual","c":"BERTINI, H.","t":"Andantino quasi allegretto in G major No 16 from 25 études Op.100","nat":"French","era":"Romantic","key":"G major","focus":["Lyrical étude","Singing melody","Legato playing"] },
  { "l":"A","s":"Manual","c":"BERTINI, H.","t":"Movimento di Valtzer in D major No 10 from 25 études Op.100","nat":"French","era":"Romantic","key":"D major","focus":["Waltz character","Light touch","Rhythmic grace"] },
  { "l":"A","s":"Manual","c":"BRANDMAN, M.","t":"The ring-tail 'possum No 9 from Contemporary modal pieces","nat":"Australian","era":"Contemporary","key":"Modal","focus":["Modal writing","Australian character","Contemporary idiom"] },
  { "l":"A","s":"Manual","c":"BURGMÜLLER, J.","t":"Le courant limpide (The limpid stream) No 7 from 25 easy and progressive studies Op.100","nat":"German","era":"Romantic","key":"A major","focus":["Flowing texture","Legato playing","Tonal colour"] },
  { "l":"A","s":"Manual","c":"BURGMÜLLER, J.","t":"La chasse (The chase) No 9 from 25 easy and progressive studies Op.100","nat":"German","era":"Romantic","key":"E major","focus":["Hunt character","Staccato technique","Rhythmic drive"] },
  { "l":"A","s":"Manual","c":"BURGMÜLLER, J.","t":"Douce plainte (Sweet sorrow) No 16 from 25 easy and progressive studies Op.100","nat":"German","era":"Romantic","key":"B minor","focus":["Expressive melody","Romantic phrasing","Cantabile"] },
  { "l":"A","s":"Manual","c":"COBURN, W.","t":"Frolicky rollicky wind","nat":"American","era":"Modern","key":"Variable","focus":["Musical imagery","Light character","Contemporary style"] },
  { "l":"A","s":"Manual","c":"CZERNY, C.","t":"Etude in B♭ major No 83 from Practical exercises for beginners Op.599","nat":"Austrian","era":"Romantic","key":"B♭ major","focus":["Finger technique","Velocity","Technical fluency"] },
  { "l":"A","s":"Manual","c":"CZERNY, C.","t":"Etude in B minor No 98 from 100 progressive studies Op.139","nat":"Austrian","era":"Romantic","key":"B minor","focus":["Finger independence","Technical agility","Rhythmic precision"] },
  { "l":"A","s":"Manual","c":"DUVERNOY, J.","t":"Allegretto in A minor No 18 from 25 elementary studies Op.176","nat":"French","era":"Romantic","key":"A minor","focus":["Étude technique","Musical expression","Tone shaping"] },
  { "l":"A","s":"Manual","c":"GURLITT, C.","t":"Stormy Weather (Hurry skurry) No 20 from Album for the young Op.140","nat":"German","era":"Romantic","key":"Variable","focus":["Dramatic character","Rhythmic drive","Dynamic shaping"] },
  { "l":"A","s":"Manual","c":"HANDEL, G.F.","t":"Minuet in A minor HWV 549","nat":"German","era":"Baroque","key":"A minor","focus":["Baroque minuet","Ornamentation","Stylistic grace"] },
  { "l":"A","s":"Manual","c":"HANDEL, G.F.","t":"Sarabande 3rd movement from Suite in D minor HWV 447","nat":"German","era":"Baroque","key":"D minor","focus":["Baroque sarabande","Sustained melody","Ornamentation"] },
  { "l":"A","s":"Manual","c":"HELLER, S.","t":"Etude (Allegro vivace) in A minor No 2 from 25 études mélodiques Op.45","nat":"German","era":"Romantic","key":"A minor","focus":["Velocity","Finger technique","Rhythmic energy"] },
  { "l":"A","s":"Manual","c":"HELLER, S.","t":"Etude (Allegretto) in C major No 1 from 25 études Op.47","nat":"German","era":"Romantic","key":"C major","focus":["Rhythmic étude","Musical character","Light touch"] },
  { "l":"A","s":"Manual","c":"HELLER, S.","t":"Etude (Allegretto con moto) in A minor No 3 from 25 études Op.47","nat":"German","era":"Romantic","key":"A minor","focus":["Expressive étude","Melodic shaping","Tone control"] },
  { "l":"A","s":"Manual","c":"HELLER, S.","t":"Etude (Andante quasi Allegretto) in C minor No 16 from 24 études Op.125","nat":"German","era":"Romantic","key":"C minor","focus":["Cantabile melody","Accompaniment balance","Lyrical phrasing"] },
  { "l":"A","s":"Manual","c":"HOEY, D.","t":"Lydian No 3 from Five moods in five modes","nat":"Australian","era":"Contemporary","key":"Lydian","focus":["Modal writing","Contemporary idiom","Australian music"] },
  { "l":"A","s":"Manual","c":"KABALEVSKY, D.","t":"A little joke No 13 from 30 pieces for children Op.27","nat":"Russian","era":"Modern","key":"Variable","focus":["Playful character","Light staccato","Modern style"] },
  { "l":"A","s":"Manual","c":"KIRCHNER, T.","t":"Study in D minor No 24 from 100 kleine Studien Op.71","nat":"German","era":"Romantic","key":"D minor","focus":["Étude technique","Tone equality","Finger training"] },
  { "l":"A","s":"Manual","c":"KIRNBERGER, J.P.","t":"Invention","nat":"German","era":"Baroque","key":"Variable","focus":["Baroque invention","Counterpoint","Voice independence"] },
  { "l":"A","s":"Manual","c":"KIRNBERGER, J.P.","t":"La lutine from Clavierstücke","nat":"German","era":"Baroque","key":"Variable","focus":["Baroque dance","Light character","Keyboard style"] },
  { "l":"A","s":"Manual","c":"LABURDA, J.","t":"Gavotte No 6 from 10 little polyphonic pieces","nat":"Czech","era":"Modern","key":"Variable","focus":["Polyphonic texture","Modern character","Dance style"] },
  { "l":"A","s":"Manual","c":"MAYER, C.","t":"Study in A minor Op.340 No 2","nat":"German","era":"Romantic","key":"A minor","focus":["Étude technique","Legato playing","Tone shaping"] },
  { "l":"A","s":"Manual","c":"NEUGASIMOV, V.","t":"Butterfly","nat":"Russian","era":"Modern","key":"Variable","focus":["Musical imagery","Light touch","Modern character"] },
  { "l":"A","s":"Manual","c":"PESKANOV, A.","t":"Invention – Tribute to J.S. Bach","nat":"American","era":"Contemporary","key":"Variable","focus":["Neo-Baroque style","Counterpoint","Contemporary voice"] },
  { "l":"A","s":"Manual","c":"PURCELL, H.","t":"Hornpipe in E minor Z T685 (arr. MILNE)","nat":"English","era":"Baroque","key":"E minor","focus":["Baroque hornpipe","Dance character","Articulation"] },
  { "l":"A","s":"Manual","c":"ROLLIN, C.","t":"Winter wind","nat":"American","era":"Contemporary","key":"Variable","focus":["Musical imagery","Technical agility","Contemporary style"] },
  { "l":"A","s":"Manual","c":"SCARLATTI, A.","t":"Aria in D minor","nat":"Italian","era":"Baroque","key":"D minor","focus":["Baroque aria","Singing melody","Ornament clarity"] },
  { "l":"A","s":"Manual","c":"SCARLATTI, A.","t":"Folia","nat":"Italian","era":"Baroque","key":"D minor","focus":["Baroque variations","Dance character","Stylistic awareness"] },
  { "l":"A","s":"Manual","c":"SEIXAS, C. de.","t":"Toccata in C major","nat":"Portuguese","era":"Baroque","key":"C major","focus":["Baroque toccata","Finger velocity","Keyboard brilliance"] },
  { "l":"A","s":"Manual","c":"SOLER, A.","t":"Sonata in D minor R115","nat":"Spanish","era":"Baroque","key":"D minor","focus":["Spanish Baroque","Stylistic character","Keyboard technique"] },
  { "l":"A","s":"Manual","c":"STREABBOG, L.","t":"Allegretto No 11 from 12 very easy and melodious studies Op.63","nat":"Belgian","era":"Romantic","key":"Variable","focus":["Lyrical étude","Melodic shaping","Light touch"] },
  { "l":"A","s":"Manual","c":"STREABBOG, L.","t":"Allegro moderato No 9 from 12 easy and melodious studies Op.64","nat":"Belgian","era":"Romantic","key":"Variable","focus":["Technical agility","Musical character","Tone evenness"] },
  { "l":"A","s":"Manual","c":"ZILCHER, P.","t":"The gossip (Die Schwätzerin) No 4 from Op.55","nat":"German","era":"Romantic","key":"Variable","focus":["Humorous character","Light staccato","Musical wit"] },

  // ═══════════════════════════════════════════════════
  //  LIST B  — Classical / Romantic character pieces
  // ═══════════════════════════════════════════════════

  // --- List B · S19 ---
  { "l":"B","s":"S19","c":"BALUTET, M.","t":"Villanelle from Quatre petites pièces en clef de sol","nat":"French","era":"Modern","key":"Variable","focus":["Lyrical character","French style","Melodic shaping"] },
  { "l":"B","s":"S19","c":"HOOK, J.","t":"Allegro First movement of Sonatina Op.12 No 5","nat":"English","era":"Classical","key":"Variable","focus":["Classical sonatina","Clarity","Finger technique"] },
  { "l":"B","s":"S19","c":"RIES, F.","t":"Polonaise Op.124 No 3","nat":"German","era":"Romantic","key":"Variable","focus":["Dance character","Romantic style","Musical phrasing"] },
  { "l":"B","s":"S19","c":"WEBER, C.M. von.","t":"Scherzo Second movement of Divertimento assai facile Op.38","nat":"German","era":"Romantic","key":"Variable","focus":["Playful character","Light touch","Rhythmic precision"] },

  // --- List B · S18 ---
  { "l":"B","s":"S18","c":"BEACH, A.","t":"Gavotte No 2 from Children's album Op.36","nat":"American","era":"Romantic","key":"Variable","focus":["Dance elegance","Romantic character","Musical shaping"] },
  { "l":"B","s":"S18","c":"BENDA, G.","t":"Sonatina No 11 from 34 Sonatinas","nat":"Czech","era":"Classical","key":"Variable","focus":["Classical sonatina","Clarity","Formal structure"] },
  { "l":"B","s":"S18","c":"ELGAR, E.","t":"Andantino 1st movement from Sonatina","nat":"English","era":"Romantic","key":"Variable","focus":["Lyrical melody","English Romantic","Cantabile"] },
  { "l":"B","s":"S18","c":"HAYDN, J.","t":"Menuet and Trio 3rd movement from Divertimento Hob XVI:1","nat":"Austrian","era":"Classical","key":"C major","focus":["Classical minuet","Elegance","Articulation"] },

  // --- List B · S17 ---
  { "l":"B","s":"S17","c":"BENDA, G.","t":"Sonatine No 3 from 34 Sonatines","nat":"Czech","era":"Classical","key":"Variable","focus":["Classical form","Clarity","Technical fluency"] },
  { "l":"B","s":"S17","c":"DIABELLI, A.","t":"Allegro moderato 1st movement of Sonatina No 2 from Op.168","nat":"Austrian","era":"Classical","key":"Variable","focus":["Classical sonatina","Balanced texture","Elegant articulation"] },
  { "l":"B","s":"S17","c":"LICHNER, H.","t":"Rondo 3rd movement of Sonatina No 3 from Op.4","nat":"German","era":"Romantic","key":"Variable","focus":["Rondo form","Light character","Rhythmic energy"] },
  { "l":"B","s":"S17","c":"VANHAL, J.","t":"Alla tedesca 2nd movement of Sonatina No 9 from Op.41","nat":"Austrian","era":"Classical","key":"Variable","focus":["Dance character","Classical style","Graceful phrasing"] },

  // --- List B · Manual (47 pieces) ---
  { "l":"B","s":"Manual","c":"BEETHOVEN, L. van (attrib.)","t":"Allegro assai 1st movement from Sonatina in F major WoO Anh 5/2","nat":"German","era":"Classical","key":"F major","focus":["Classical sonatina","Finger technique","Articulation"] },
  { "l":"B","s":"Manual","c":"BEETHOVEN, L. van (attrib.)","t":"Rondo 2nd movement from Sonatina in F major WoO Anh 5/2","nat":"German","era":"Classical","key":"F major","focus":["Rondo character","Light touch","Classical elegance"] },
  { "l":"B","s":"Manual","c":"BACH, C.P.E.","t":"La Pott H 80/W 117.18","nat":"German","era":"Classical","key":"Variable","focus":["Galant style","Expressive playing","Ornamentation"] },
  { "l":"B","s":"Manual","c":"BEETHOVEN, L. van.","t":"German dance (Deutscher Tanz) in B♭ major No 6 from 12 German dances WoO 13","nat":"German","era":"Classical","key":"B♭ major","focus":["Dance character","Classical clarity","Rhythmic precision"] },
  { "l":"B","s":"Manual","c":"BENDA, G.","t":"Sonatina in G minor No 16 from 34 piano sonatinas","nat":"Czech","era":"Classical","key":"G minor","focus":["Classical form","Minor character","Expressive playing"] },
  { "l":"B","s":"Manual","c":"BENDA, G.","t":"Sonatina in F major No 10 from 34 piano sonatinas","nat":"Czech","era":"Classical","key":"F major","focus":["Classical sonatina","Clarity","Formal structure"] },
  { "l":"B","s":"Manual","c":"BENDA, G.","t":"Sonatina in D major No 17 from 34 piano sonatinas","nat":"Czech","era":"Classical","key":"D major","focus":["Classical form","Elegance","Balanced texture"] },
  { "l":"B","s":"Manual","c":"CHOPIN, F.","t":"Wiosna (Spring) Op.74 No 2/CT 130","nat":"Polish","era":"Romantic","key":"A minor","focus":["Lyrical melody","Romantic character","Expressive phrasing"] },
  { "l":"B","s":"Manual","c":"CLEMENTI, M.","t":"Waltz in G major No 8 from 12 waltzes Op.38","nat":"Italian","era":"Classical","key":"G major","focus":["Waltz elegance","Classical clarity","Light touch"] },
  { "l":"B","s":"Manual","c":"DIABELLI, A.","t":"Moderato cantabile 1st movement from Sonatina in F major Op.168 No 1","nat":"Austrian","era":"Classical","key":"F major","focus":["Singing melody","Classical sonatina","Cantabile"] },
  { "l":"B","s":"Manual","c":"DIABELLI, A.","t":"Scherzo 2nd movement from Sonatina in G major Op.151 No 1","nat":"Austrian","era":"Classical","key":"G major","focus":["Playful character","Light staccato","Classical wit"] },
  { "l":"B","s":"Manual","c":"GRECHANINOV, A.","t":"My dear mother No 1 from Grandfather's Album Op.119","nat":"Russian","era":"Romantic","key":"Variable","focus":["Expressive melody","Romantic character","Singing tone"] },
  { "l":"B","s":"Manual","c":"GRECHANINOV, A.","t":"Orientale No 11 from Historiettes Op.118","nat":"Russian","era":"Romantic","key":"Variable","focus":["Eastern character","Romantic colour","Musical imagery"] },
  { "l":"B","s":"Manual","c":"GURLITT, C.","t":"In the garden No 4 from Album for the young Op.140","nat":"German","era":"Romantic","key":"Variable","focus":["Lyrical melody","Romantic phrasing","Melodic shaping"] },
  { "l":"B","s":"Manual","c":"GURLITT, C.","t":"Andantino (Wild Mignonette) No 1 from Kleine Blumen Op.205","nat":"German","era":"Romantic","key":"Variable","focus":["Flowing melody","Romantic character","Singing tone"] },
  { "l":"B","s":"Manual","c":"GURLITT, C.","t":"Longing No 11 from Album for the young Op.140","nat":"German","era":"Romantic","key":"Variable","focus":["Romantic expression","Expressive phrasing","Emotional depth"] },
  { "l":"B","s":"Manual","c":"GURLITT, C.","t":"Träumerei No 32 from Der erste Vortrag Op.210","nat":"German","era":"Romantic","key":"Variable","focus":["Dreamy character","Soft tone","Romantic style"] },
  { "l":"B","s":"Manual","c":"HAYDN, J.","t":"Menuetto and Trio in C minor","nat":"Austrian","era":"Classical","key":"C minor","focus":["Classical minuet","Minor character","Formal elegance"] },
  { "l":"B","s":"Manual","c":"HAYDN, J.","t":"Piano piece in D Major","nat":"Austrian","era":"Classical","key":"D major","focus":["Classical clarity","Elegant character","Balanced texture"] },
  { "l":"B","s":"Manual","c":"HOOK, J.","t":"Rondo from Sonatina Op.12 No 9","nat":"English","era":"Classical","key":"Variable","focus":["Rondo form","Classical elegance","Light character"] },
  { "l":"B","s":"Manual","c":"IORDANSKY, M.","t":"An old ballad from Op.24","nat":"Russian","era":"Romantic","key":"Variable","focus":["Ballad character","Romantic melody","Expressive playing"] },
  { "l":"B","s":"Manual","c":"KIRCHNER, T.","t":"Andantino No 3 from Neue Kinderszenen Op.55","nat":"German","era":"Romantic","key":"Variable","focus":["Lyrical melody","Romantic phrasing","Singing tone"] },
  { "l":"B","s":"Manual","c":"KIRCHNER, T.","t":"Allegretto No 10 from Neue Kinderszenen Op.55","nat":"German","era":"Romantic","key":"Variable","focus":["Light character","Melodic shaping","Romantic style"] },
  { "l":"B","s":"Manual","c":"KIRCHNER, T.","t":"Ruhig, ausdrucksvoll No 8 from Miniaturen Op.62","nat":"German","era":"Romantic","key":"Variable","focus":["Expressive playing","Quiet character","Tonal colour"] },
  { "l":"B","s":"Manual","c":"KIRCHNER, T.","t":"Allegretto, poco agitato No 9 from Miniaturen Op.62","nat":"German","era":"Romantic","key":"Variable","focus":["Agitated character","Rhythmic energy","Romantic expression"] },
  { "l":"B","s":"Manual","c":"KOZELUCH, L.","t":"Menuetto 2nd movement from Sonata No 37 in G major","nat":"Czech","era":"Classical","key":"G major","focus":["Classical minuet","Elegance","Formal clarity"] },
  { "l":"B","s":"Manual","c":"KUHLAU, F.","t":"Allegro 1st movement from Sonatina in C major Op.55 No 1","nat":"Danish","era":"Classical","key":"C major","focus":["Classical sonatina","Finger technique","Clarity"] },
  { "l":"B","s":"Manual","c":"KUHLAU, F.","t":"Rondo – Vivace 2nd movement from Sonatina in C major Op.55 No 1","nat":"Danish","era":"Classical","key":"C major","focus":["Rondo form","Light character","Technical fluency"] },
  { "l":"B","s":"Manual","c":"KULLAK, T.","t":"Die Wanduhr (The clock) No 2 from Kinderleben Op.62","nat":"German","era":"Romantic","key":"Variable","focus":["Musical imagery","Even touch","Rhythmic precision"] },
  { "l":"B","s":"Manual","c":"LICHNER, H.","t":"Allegro moderato 1st movement from Sonatina in F major Op.4 No 2","nat":"German","era":"Romantic","key":"F major","focus":["Classical sonatina","Finger technique","Elegance"] },
  { "l":"B","s":"Manual","c":"LICHNER, H.","t":"Moderato 1st movement from Sonatina in G major Op.4 No 3","nat":"German","era":"Romantic","key":"G major","focus":["Lyrical melody","Classical form","Cantabile"] },
  { "l":"B","s":"Manual","c":"LICHNER, H.","t":"Moderato 1st movement from Sonatina in G major Op.49 No 2","nat":"German","era":"Romantic","key":"G major","focus":["Singing tone","Classical sonatina","Musical shaping"] },
  { "l":"B","s":"Manual","c":"LICHNER, H.","t":"Moderato 1st movement from Sonatina in G major Op.66 No 3","nat":"German","era":"Romantic","key":"G major","focus":["Romantic character","Lyrical playing","Formal clarity"] },
  { "l":"B","s":"Manual","c":"MENDELSSOHN, F.","t":"Romanze","nat":"German","era":"Romantic","key":"Variable","focus":["Romantic melody","Singing tone","Expressive phrasing"] },
  { "l":"B","s":"Manual","c":"MOROVSKY, A.","t":"Valsette","nat":"Russian","era":"Romantic","key":"Variable","focus":["Waltz elegance","Light touch","Romantic character"] },
  { "l":"B","s":"Manual","c":"MOZART, W.","t":"Larghetto 1st movement from Viennese sonatina No 5 in F major","nat":"Austrian","era":"Classical","key":"F major","focus":["Singing melody","Classical elegance","Cantabile"] },
  { "l":"B","s":"Manual","c":"MOZART, W.","t":"Polonaise 3rd movement from Viennese sonatina No 5 in F major","nat":"Austrian","era":"Classical","key":"F major","focus":["Dance character","Classical clarity","Elegant articulation"] },
  { "l":"B","s":"Manual","c":"MOZART, W.","t":"Rondo in C major","nat":"Austrian","era":"Classical","key":"C major","focus":["Rondo form","Classical wit","Light touch"] },
  { "l":"B","s":"Manual","c":"REBIKOV, V.","t":"Shepherd playing his pipe No 8 from Op.31","nat":"Russian","era":"Romantic","key":"Variable","focus":["Pastoral character","Lyrical melody","Singing tone"] },
  { "l":"B","s":"Manual","c":"REINECKE, C.","t":"Scherzo 3rd movement from Serenade Op.183 No 5","nat":"German","era":"Romantic","key":"Variable","focus":["Playful character","Light touch","Rhythmic energy"] },
  { "l":"B","s":"Manual","c":"SANDRÉ, G.","t":"Go to sleep","nat":"French","era":"Romantic","key":"Variable","focus":["Lullaby character","Soft tone","Gentle phrasing"] },
  { "l":"B","s":"Manual","c":"SCHUBERT, F.","t":"Waltz Op.18 No 6 D 145","nat":"Austrian","era":"Romantic","key":"Variable","focus":["Viennese waltz","Romantic character","Lyrical melody"] },
  { "l":"B","s":"Manual","c":"SCHUMANN, R.","t":"Erster Verlust (First loss) No 16 from Album für die Jugend Op.68","nat":"German","era":"Romantic","key":"E minor","focus":["Expressive melody","Romantic emotion","Singing tone"] },
  { "l":"B","s":"Manual","c":"SCHUMANN, R.","t":"Schnitterliedchen (Reaper's song) No 18 from Album für die Jugend Op.68","nat":"German","era":"Romantic","key":"C major","focus":["Song character","Light touch","Rhythmic energy"] },
  { "l":"B","s":"Manual","c":"SCHUMANN, R.","t":"Wilder Reiter (Wild horseman) No 8 from Album für die Jugend Op.68","nat":"German","era":"Romantic","key":"A minor","focus":["Energetic character","Rhythmic drive","Dynamic shaping"] },
  { "l":"B","s":"Manual","c":"SPINDLER, F.","t":"Flying Leaf Op.123 No 10","nat":"German","era":"Romantic","key":"Variable","focus":["Light character","Melodic shaping","Romantic style"] },
  { "l":"B","s":"Manual","c":"TCHAIKOVSKY, P.","t":"Chanson italienne (Italian song) No 15 from Album pour enfants Op.39","nat":"Russian","era":"Romantic","key":"D major","focus":["Italian character","Singing melody","Lyrical phrasing"] },

  // ═══════════════════════════════════════════════════
  //  LIST C  — Modern / Contemporary / Creative
  // ═══════════════════════════════════════════════════

  // --- List C · S19 ---
  { "l":"C","s":"S19","c":"KABALEVSKY, D.","t":"A short story No 22 from 24 pieces for children Op.39","nat":"Russian","era":"Modern","key":"Variable","focus":["Lyrical character","Expressive playing","Modern style"] },
  { "l":"C","s":"S19","c":"MILNE, E.","t":"Scoot from Pepperbox jazz Book 1","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Jazz idiom","Rhythmic energy","Contemporary character"] },
  { "l":"C","s":"S19","c":"SEROCKI, K.","t":"Mazurka No 3 from Krasnoludki (Dwarves)","nat":"Polish","era":"Modern","key":"Variable","focus":["Polish dance","Rhythmic precision","Modern character"] },
  { "l":"C","s":"S19","c":"YU, J.","t":"A phone call to Mozart from Cutetudes","nat":"Chinese-Australian","era":"Contemporary","key":"Variable","focus":["Humorous character","Contemporary idiom","Musical imagination"] },

  // --- List C · S18 ---
  { "l":"C","s":"S18","c":"BENJAMIN, A.","t":"A song with a sad ending No 3 from Fantasies","nat":"Australian","era":"Modern","key":"Variable","focus":["Expressive melody","Modern character","Musical narrative"] },
  { "l":"C","s":"S18","c":"HILLER, W.","t":"Butterfly waltz from 2 Miniaturen für Kinder","nat":"German","era":"Contemporary","key":"Variable","focus":["Delicate character","Waltz style","Contemporary idiom"] },
  { "l":"C","s":"S18","c":"MUCZYNSKI, R.","t":"Fable No 9 from Fables","nat":"American","era":"Modern","key":"Variable","focus":["Narrative character","Modern style","Expressive playing"] },
  { "l":"C","s":"S18","c":"TANSMAN, A.","t":"La poupée No 2 from Pour les enfants","nat":"Polish","era":"Modern","key":"Variable","focus":["Gentle character","Modern idiom","Musical imagination"] },

  // --- List C · S17 ---
  { "l":"C","s":"S17","c":"BENJAMIN, A.","t":"Soldiers in the distance No 3 from Fantasies","nat":"Australian","era":"Modern","key":"Variable","focus":["Musical imagery","Australian music","Modern character"] },
  { "l":"C","s":"S17","c":"KOEHNE, G.","t":"A closed world of fine feelings and grand design No 2 from Aphorisms","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary idiom","Australian character","Expressive playing"] },
  { "l":"C","s":"S17","c":"SEIBER, M.","t":"Foxtrot No 2 from Leichte Tänze","nat":"Hungarian","era":"Modern","key":"Variable","focus":["Jazz-influenced","Dance character","Rhythmic energy"] },
  { "l":"C","s":"S17","c":"SHOSTAKOVICH, D.","t":"Eine lustige Geschichte No 4 from Detskaya tetrad'","nat":"Russian","era":"Modern","key":"Variable","focus":["Humorous character","Modern style","Rhythmic drive"] },

  // --- List C · Aust Anthology (5 pieces) ---
  { "l":"C","s":"AustAnth","c":"BRANDMAN, M.","t":"Spider on the mirror","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary idiom","Australian music","Musical imagery"] },
  { "l":"C","s":"AustAnth","c":"BROADSTOCK, B.","t":"Cool...","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary style","Expressive freedom","Australian character"] },
  { "l":"C","s":"AustAnth","c":"HINDSON, M.","t":"Gentle giant","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Musical character","Contemporary idiom","Australian music"] },
  { "l":"C","s":"AustAnth","c":"POLDEN, A.","t":"5 to 4","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Rhythmic character","Contemporary style","Australian music"] },
  { "l":"C","s":"AustAnth","c":"SYMONS, J.","t":"Ambling along","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Relaxed character","Australian idiom","Contemporary style"] },

  // --- List C · Manual (63 pieces) ---
  { "l":"C","s":"Manual","c":"BAILEY, K.","t":"Breezin' from Jazzin' around 2","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Jazz character","Relaxed style","Australian music"] },
  { "l":"C","s":"Manual","c":"BAILEY, K.","t":"Study in Latin from Jazzin' around 2","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Latin rhythm","Contemporary idiom","Australian music"] },
  { "l":"C","s":"Manual","c":"BARTÓK, B.","t":"Little study No 77 from Mikrokosmos Volume III","nat":"Hungarian","era":"Modern","key":"Variable","focus":["Modern technique","Legato study","Contemporary awareness"] },
  { "l":"C","s":"Manual","c":"BARTÓK, B.","t":"Moderato No 26 from Gyermekeknek (For children) Volume 1","nat":"Hungarian","era":"Modern","key":"Variable","focus":["Folk character","Modern style","Musical imagination"] },
  { "l":"C","s":"Manual","c":"BARTÓK, B.","t":"Lassú vergődés (Frustration) No 2 from Ten easy pieces","nat":"Hungarian","era":"Modern","key":"Variable","focus":["Expressive character","Modern idiom","Emotional depth"] },
  { "l":"C","s":"Manual","c":"BARTÓK, B.","t":"Tót legények tánca (Slovak boys' dance) No 3 from Ten easy pieces","nat":"Hungarian","era":"Modern","key":"Variable","focus":["Folk dance","Rhythmic energy","Modern character"] },
  { "l":"C","s":"Manual","c":"BARTÓK, B.","t":"Teasing song No 18 from Gyermekeknek (For children) Volume 2","nat":"Hungarian","era":"Modern","key":"Variable","focus":["Playful character","Folk idiom","Modern style"] },
  { "l":"C","s":"Manual","c":"BRANDMAN, M.","t":"The squirrel glider from Contemporary modal pieces","nat":"Australian","era":"Contemporary","key":"Modal","focus":["Modal writing","Australian character","Contemporary idiom"] },
  { "l":"C","s":"Manual","c":"CAPERS, V.","t":"Ella scats the little lamb from Portraits in jazz","nat":"American","era":"Contemporary","key":"Variable","focus":["Jazz idiom","Creative character","Contemporary style"] },
  { "l":"C","s":"Manual","c":"CHUA, S.","t":"Midnight snack from Scenes of childhood","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary character","Australian music","Musical imagination"] },
  { "l":"C","s":"Manual","c":"CORNICK, M.","t":"Ballad from Easy jazzy piano","nat":"English","era":"Contemporary","key":"Variable","focus":["Jazz ballad","Lyrical playing","Contemporary idiom"] },
  { "l":"C","s":"Manual","c":"CORNICK, M.","t":"Blues in two from Easy jazzy piano","nat":"English","era":"Contemporary","key":"Variable","focus":["Blues character","Jazz idiom","Contemporary style"] },
  { "l":"C","s":"Manual","c":"CORNICK, M.","t":"Minor event from Dixieland piano","nat":"English","era":"Contemporary","key":"Variable","focus":["Jazz idiom","Contemporary style","Rhythmic drive"] },
  { "l":"C","s":"Manual","c":"CORNICK, M.","t":"Tango in A minor from In the groove and more","nat":"English","era":"Contemporary","key":"A minor","focus":["Dance character","Tango style","Contemporary idiom"] },
  { "l":"C","s":"Manual","c":"DIEMER, E.L.","t":"Serenade from Anthology of 20th century piano music","nat":"American","era":"Modern","key":"Variable","focus":["Modern idiom","Lyrical playing","Expressive character"] },
  { "l":"C","s":"Manual","c":"DIEMER, E.L.","t":"Gigue from Anthology of 20th century piano music","nat":"American","era":"Modern","key":"Variable","focus":["Dance character","Modern style","Rhythmic energy"] },
  { "l":"C","s":"Manual","c":"FORD, A.","t":"A life in a shell No 14 from The waltz book","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Australian character","Contemporary idiom","Lyrical playing"] },
  { "l":"C","s":"Manual","c":"GILLOCK, W.","t":"Autumn sketch from Toll in Moll","nat":"American","era":"Contemporary","key":"Variable","focus":["Impressionist character","Contemporary style","Tonal colour"] },
  { "l":"C","s":"Manual","c":"GILLOCK, W.","t":"Castanets from Getting to grade three","nat":"American","era":"Contemporary","key":"Variable","focus":["Dance character","Contemporary style","Rhythmic energy"] },
  { "l":"C","s":"Manual","c":"GILLOCK, W.","t":"Flamenco from William Gillock recital collection","nat":"American","era":"Contemporary","key":"Variable","focus":["Spanish character","Contemporary idiom","Expressive playing"] },
  { "l":"C","s":"Manual","c":"GILLOCK, W.","t":"Valse triste from William Gillock recital collection","nat":"American","era":"Contemporary","key":"Variable","focus":["Waltz character","Lyrical melody","Romantic expression"] },
  { "l":"C","s":"Manual","c":"GOLDSTON, M.","t":"Tumbling waterfall from The virtuosic performer Book 2","nat":"American","era":"Contemporary","key":"Variable","focus":["Flowing character","Contemporary style","Technical fluency"] },
  { "l":"C","s":"Manual","c":"HANNAN, M.","t":"Full sail from Fortune pieces","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Australian character","Contemporary idiom","Musical imagery"] },
  { "l":"C","s":"Manual","c":"HOLLAND, D.","t":"Popcorn from Lucky dip","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Playful character","Contemporary style","Rhythmic energy"] },
  { "l":"C","s":"Manual","c":"HOLLAND, D.","t":"Sailor song from Tale of a mouse","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Character piece","Australian music","Contemporary idiom"] },
  { "l":"C","s":"Manual","c":"HYDE, M.","t":"Eastern temple from Little sketchbook","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Impressionist character","Australian music","Modal writing"] },
  { "l":"C","s":"Manual","c":"JACOBY, H.","t":"Sonatina from The developing artist: Piano literature Book 3","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary idiom","Sonatina style","Musical expression"] },
  { "l":"C","s":"Manual","c":"KABALEVSKY, D.","t":"Sad story No 6 from 30 pieces for children Op. 27","nat":"Russian","era":"Modern","key":"Variable","focus":["Expressive melody","Modern character","Musical narrative"] },
  { "l":"C","s":"Manual","c":"KABALEVSKY, D.","t":"Toccatina No 12 from 30 pieces for children Op. 27","nat":"Russian","era":"Modern","key":"Variable","focus":["Modern technique","Rhythmic drive","Stylistic clarity"] },
  { "l":"C","s":"Manual","c":"KABALEVSKY, D.","t":"Slow waltz No 23 from 24 pieces for children Op. 39","nat":"Russian","era":"Modern","key":"Variable","focus":["Waltz character","Lyrical melody","Expressive playing"] },
  { "l":"C","s":"Manual","c":"KHACHATURIAN, A.","t":"Melody from Getting to grade three","nat":"Armenian","era":"Modern","key":"Variable","focus":["Lyrical melody","Modern character","Expressive playing"] },
  { "l":"C","s":"Manual","c":"LINN, J.","t":"La marée de soir [Evening tide] from Les petites impressions","nat":"American","era":"Contemporary","key":"Variable","focus":["Impressionist character","Contemporary idiom","Expressive tone"] },
  { "l":"C","s":"Manual","c":"MAYKAPAR, S.","t":"Fleeting vision from Getting to grade three","nat":"Russian","era":"Romantic","key":"Variable","focus":["Lyrical character","Romantic expression","Musical sensitivity"] },
  { "l":"C","s":"Manual","c":"MENOTTI, G.","t":"Winter wind from Poemetti","nat":"Italian","era":"Modern","key":"Variable","focus":["Atmospheric character","Modern idiom","Expressive playing"] },
  { "l":"C","s":"Manual","c":"NIELSEN, C.","t":"Marziale No 7 from Piano music for young and old Volume I Op. 53","nat":"Danish","era":"Modern","key":"Variable","focus":["March character","Modern style","Rhythmic energy"] },
  { "l":"C","s":"Manual","c":"NORTON, C.","t":"A spy story (Funky rock) No 25 from The microstyles collection","nat":"English","era":"Contemporary","key":"Variable","focus":["Contemporary style","Rhythmic drive","Character piece"] },
  { "l":"C","s":"Manual","c":"NORTON, C.","t":"A whimsy (12/8 ragtime) No 26 from The microstyles collection","nat":"English","era":"Contemporary","key":"Variable","focus":["Ragtime character","Contemporary idiom","Rhythmic energy"] },
  { "l":"C","s":"Manual","c":"NORTON, C.","t":"Heavy work (Mancini stomp) No 38 from The microstyles collection","nat":"English","era":"Contemporary","key":"Variable","focus":["Rhythmic drive","Contemporary style","Musical energy"] },
  { "l":"C","s":"Manual","c":"NORTON, C.","t":"Hebridean song (Slow waltz) No 36 from The microstyles collection","nat":"English","era":"Contemporary","key":"Variable","focus":["Lyrical melody","Waltz character","Contemporary idiom"] },
  { "l":"C","s":"Manual","c":"NORTON, C.","t":"Piano exchange rag (4/4 ragtime) No 20 from The microstyles collection","nat":"English","era":"Contemporary","key":"Variable","focus":["Ragtime style","Contemporary idiom","Rhythmic awareness"] },
  { "l":"C","s":"Manual","c":"NORTON, C.","t":"Plus fives (5/4 jazz) No 35 from The microstyles collection","nat":"English","era":"Contemporary","key":"Variable","focus":["Jazz character","Rhythmic complexity","Contemporary style"] },
  { "l":"C","s":"Manual","c":"NORTON, C.","t":"Rhapsody (romantic piano style) No 11 from The microstyles collection","nat":"English","era":"Contemporary","key":"Variable","focus":["Romantic character","Lyrical expression","Contemporary idiom"] },
  { "l":"C","s":"Manual","c":"PEETERS, F.","t":"Valse enfantine [Children's waltz] No 10 from Sketches from childhood Op. 27","nat":"Belgian","era":"Modern","key":"Variable","focus":["Waltz character","Modern style","Delicate touch"] },
  { "l":"C","s":"Manual","c":"PEETERS, F.","t":"Conte [Fairy tale] No 6 from Sketches from childhood Op. 27","nat":"Belgian","era":"Modern","key":"Variable","focus":["Narrative character","Modern idiom","Expressive playing"] },
  { "l":"C","s":"Manual","c":"PEETERS, F.","t":"Berceuse de la petite poupée [Lullaby for the little doll] No 9 from Sketches from childhood Op. 27","nat":"Belgian","era":"Modern","key":"Variable","focus":["Lullaby character","Gentle touch","Modern style"] },
  { "l":"C","s":"Manual","c":"POLDINI, E.","t":"The enchanted castle from Musical moments","nat":"Hungarian","era":"Romantic","key":"Variable","focus":["Romantic character","Musical imagery","Lyrical expression"] },
  { "l":"C","s":"Manual","c":"PROKOFIEV, S.","t":"Promenade No 2 from Music for children Op. 65","nat":"Russian","era":"Modern","key":"Variable","focus":["Modern character","March style","Rhythmic clarity"] },
  { "l":"C","s":"Manual","c":"RIEGGER, W.","t":"The tritone from Anthology of 20th century piano music","nat":"American","era":"Modern","key":"Variable","focus":["Modern idiom","Dissonant character","Stylistic awareness"] },
  { "l":"C","s":"Manual","c":"ROLLIN, C.","t":"Jazz cat from Best of Catherine Rollin Book 1","nat":"American","era":"Contemporary","key":"Variable","focus":["Jazz character","Contemporary style","Rhythmic energy"] },
  { "l":"C","s":"Manual","c":"ROLLIN, C.","t":"Rockin' in New Orleans from Best of Catherine Rollin Book 2","nat":"American","era":"Contemporary","key":"Variable","focus":["Rock character","Contemporary idiom","Rhythmic drive"] },
  { "l":"C","s":"Manual","c":"SCHMITZ, M.","t":"Tango Aurora (Miti tango) Book 1","nat":"German","era":"Contemporary","key":"Variable","focus":["Tango character","Contemporary style","Dance energy"] },
  { "l":"C","s":"Manual","c":"SCHOENMEHL, M.","t":"Melancholy reflections from Studies in pop","nat":"German","era":"Contemporary","key":"Variable","focus":["Lyrical character","Contemporary idiom","Expressive playing"] },
  { "l":"C","s":"Manual","c":"SCULTHORPE, P.","t":"Koori dancing No 5 from A little book of hours","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Australian character","Contemporary idiom","Rhythmic energy"] },
  { "l":"C","s":"Manual","c":"SCULTHORPE, P.","t":"Left bank waltz No 2 from Two easy pieces","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Waltz character","Australian music","Contemporary style"] },
  { "l":"C","s":"Manual","c":"SCULTHORPE, P.","t":"Sea chant No 1 from Two easy pieces","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Australian character","Atmospheric character","Contemporary idiom"] },
  { "l":"C","s":"Manual","c":"SHEFTEL, P.","t":"Tango from Preludes, interludes and a postlude: Studies in styles for piano","nat":"American","era":"Contemporary","key":"Variable","focus":["Tango style","Contemporary character","Dance energy"] },
  { "l":"C","s":"Manual","c":"SHOSTAKOVICH, D.","t":"Sad story No 5 from Detskaya tetrad' [Children's notebook] Op. 69","nat":"Russian","era":"Modern","key":"Variable","focus":["Expressive melody","Modern character","Musical narrative"] },
  { "l":"C","s":"Manual","c":"SLAVICKÝ, K.","t":"Im Wechseltakt No 27 from Das Pianobuch: Klaviermusik für Neugierige Volume 1","nat":"Czech","era":"Modern","key":"Variable","focus":["Modern idiom","Rhythmic complexity","Stylistic clarity"] },
  { "l":"C","s":"Manual","c":"TANSMAN, A.","t":"Des vacances [Vacation is over] No 8 from Pour les enfants Book 1","nat":"Polish","era":"Modern","key":"Variable","focus":["Playful character","Modern style","Musical imagination"] },
  { "l":"C","s":"Manual","c":"TSITSAROS, C.","t":"Little mazurka from Piano recital showcase Book 3","nat":"Cypriot","era":"Contemporary","key":"Variable","focus":["Dance character","Contemporary idiom","Rhythmic energy"] },
  { "l":"C","s":"Manual","c":"WAXMAN, D.","t":"The mosquito from The new recital pageants Book 3","nat":"American","era":"Contemporary","key":"Variable","focus":["Character piece","Contemporary style","Musical imagery"] },
  { "l":"C","s":"Manual","c":"WESLEY-SMITH, M.","t":"Grey's beach from Three little piano pieces","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Australian character","Contemporary idiom","Atmospheric character"] },
  { "l":"C","s":"Manual","c":"YU, J.","t":"Flower riddle No 6 from 24 Chinese folk songs","nat":"Chinese-Australian","era":"Contemporary","key":"Variable","focus":["Folk character","Contemporary idiom","Australian music"] },
];
