// ─── AMEB Grade 8 Piano — Piano for Leisure Syllabus Data ────────────────────
// Exam code: 6338 | Source: Piano for Leisure Syllabus 2026, manual pages 99–100
// Series 4 / Series 2 / Series 1 / Manual  (Series 3 books only go up to Grade 7)

const DATA_G8_LEISURE = [

  // ── SERIES 4 ───────────────────────────────────────────────────────────────
  { "l": "S4", "s": "Series 4", "c": "BACHARACH, B.", "t": "A little prayer (arr. COATES)", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Pop classic", "Melody", "Style"] },
  { "l": "S4", "s": "Series 4", "c": "BEETHOVEN, L. van.", "t": "Andante", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Classical style", "Cantabile", "Phrasing"] },
  { "l": "S4", "s": "Series 4", "c": "HORNSBY, B.", "t": "The way it is (arr. HOWELL)", "nat": "American", "era": "Contemporary", "key": "Variable", "focus": ["Contemporary pop", "Melody", "Style"] },
  { "l": "S4", "s": "Series 4", "c": "MACDOWELL, E.", "t": "Alexander rag", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Ragtime style", "Rhythm", "Character"] },
  { "l": "S4", "s": "Series 4", "c": "PESKANOV, A.", "t": "Sonnet 140 of Petrarch", "nat": "American", "era": "Contemporary", "key": "Variable", "focus": ["Romantic character", "Lyricism", "Expression"] },
  { "l": "S4", "s": "Series 4", "c": "SATIE, E.", "t": "Sonatine bureaucratique", "nat": "French", "era": "Modern", "key": "Variable", "focus": ["Humor", "Parody", "French style"] },
  { "l": "S4", "s": "Series 4", "c": "SCHMIDT, J.", "t": "All of me", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz standard", "Melody", "Style"] },
  { "l": "S4", "s": "Series 4", "c": "SCHUBERT, F.", "t": "Allegretto quasi andantino", "nat": "Austrian", "era": "Romantic", "key": "Variable", "focus": ["Schubert lyricism", "Gentle character", "Phrasing"] },
  { "l": "S4", "s": "Series 4", "c": "TCHAIKOVSKY, P.I.", "t": "June – Barcarolle from Les saisons Op. 37b", "nat": "Russian", "era": "Romantic", "key": "G minor", "focus": ["Barcarolle", "Romantic lyricism", "Russian character"] },
  { "l": "S4", "s": "Series 4", "c": "TIZOL, J.", "t": "Perdido (arr. BOOTH)", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz standard", "Swing feel", "Style"] },
  { "l": "S4", "s": "Series 4", "c": "WOOD, S.J.", "t": "Stomp", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Blues/stomp character", "Rhythm", "Style"] },

  // ── SERIES 2 ───────────────────────────────────────────────────────────────
  { "l": "S2", "s": "Series 2", "c": "ATWELL, W.", "t": "Dixie boogie", "nat": "Trinidadian", "era": "Modern", "key": "Variable", "focus": ["Boogie woogie", "Rhythm", "Style"] },
  { "l": "S2", "s": "Series 2", "c": "BAILEY, J.", "t": "The sprightly ones (arr. BISHOP)", "nat": "British", "era": "Modern", "key": "Variable", "focus": ["Light character", "Elegance", "Style"] },
  { "l": "S2", "s": "Series 2", "c": "BEETHOVEN, L. van.", "t": "Allegro molto e con brio", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Classical vigour", "Articulation", "Energy"] },
  { "l": "S2", "s": "Series 2", "c": "BRAHMS, J.", "t": "Ballade", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Ballad character", "Depth", "Romantic expression"] },
  { "l": "S2", "s": "Series 2", "c": "FINA, J.", "t": "Bumble boogie", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Boogie style", "Virtuosity", "Rhythm"] },
  { "l": "S2", "s": "Series 2", "c": "FISHER, M.", "t": "When Sunny gets blue", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz ballad", "Lyricism", "Style"] },
  { "l": "S2", "s": "Series 2", "c": "GERSHWIN, G.", "t": "I got rhythm", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz style", "Syncopation", "Rhythm"] },
  { "l": "S2", "s": "Series 2", "c": "GRANADOS, E.", "t": "Villanesca", "nat": "Spanish", "era": "Romantic", "key": "Variable", "focus": ["Spanish character", "Folk influence", "Rhythm"] },
  { "l": "S2", "s": "Series 2", "c": "GRIEG, E.", "t": "An den Frühling [To spring]", "nat": "Norwegian", "era": "Romantic", "key": "A major", "focus": ["Nordic lyricism", "Spring imagery", "Cantabile"] },
  { "l": "S2", "s": "Series 2", "c": "RUBINSTEIN, A.", "t": "Mélodie", "nat": "Russian", "era": "Romantic", "key": "F major", "focus": ["Romantic melody", "Cantabile", "Expression"] },
  { "l": "S2", "s": "Series 2", "c": "SCHUBERT, F.", "t": "Ständchen [Serenade] (arr. LISZT)", "nat": "Austrian", "era": "Romantic", "key": "D minor", "focus": ["Transcription", "Romantic lyricism", "Arrangement"] },
  { "l": "S2", "s": "Series 2", "c": "WILLIAMS, C.", "t": "The dream of Olwen", "nat": "British", "era": "Modern", "key": "Variable", "focus": ["Romantic film music", "Lyricism", "Style"] },

  // ── SERIES 1 ───────────────────────────────────────────────────────────────
  { "l": "S1", "s": "Series 1", "c": "ALBÉNIZ, I.", "t": "Sevilla sevillanas", "nat": "Spanish", "era": "Romantic", "key": "Variable", "focus": ["Spanish character", "Flamenco influence", "Rhythm"] },
  { "l": "S1", "s": "Series 1", "c": "BEETHOVEN, L. van.", "t": "Andante", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Classical style", "Cantabile", "Phrasing"] },
  { "l": "S1", "s": "Series 1", "c": "BERNIE, B.", "t": "Sweet Georgia Brown", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz standard", "Swing feel", "Style"] },
  { "l": "S1", "s": "Series 1", "c": "BRUBECK, D.", "t": "Far more blue", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz style", "Blues influence", "Character"] },
  { "l": "S1", "s": "Series 1", "c": "CHOPIN, F.", "t": "Polonaise", "nat": "Polish", "era": "Romantic", "key": "Variable", "focus": ["Polish character", "Dance rhythm", "Romantic style"] },
  { "l": "S1", "s": "Series 1", "c": "ELLINGTON, D.", "t": "Satin doll", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz standard", "Sophistication", "Style"] },
  { "l": "S1", "s": "Series 1", "c": "GERSHWIN, G.", "t": "Prelude", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz influence", "Character piece", "Style"] },
  { "l": "S1", "s": "Series 1", "c": "GRAINGER, P.", "t": "Country gardens", "nat": "Australian", "era": "Modern", "key": "Variable", "focus": ["Australian music", "Folk melody", "Virtuosity"] },
  { "l": "S1", "s": "Series 1", "c": "HANDEL, G.", "t": "Air and variations", "nat": "German", "era": "Baroque", "key": "Variable", "focus": ["Baroque variation form", "Ornamentation", "Style"] },
  { "l": "S1", "s": "Series 1", "c": "MOZART, W.", "t": "Fantasy", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Classical style", "Fantasy form", "Expression"] },
  { "l": "S1", "s": "Series 1", "c": "SCHUBERT, F.", "t": "Impromptu", "nat": "Austrian", "era": "Romantic", "key": "Variable", "focus": ["Romantic style", "Lyricism", "Expression"] },
  { "l": "S1", "s": "Series 1", "c": "SINDING, C.", "t": "Rustle of spring", "nat": "Norwegian", "era": "Romantic", "key": "C♯ minor", "focus": ["Virtuosity", "Arpeggios", "Spring imagery"] },

  // ── MANUAL ─────────────────────────────────────────────────────────────────
  { "l": "Manual", "s": "Manual", "c": "ALBÉNIZ, I.", "t": "Sevilla No 3 from Suite española Op. 47", "nat": "Spanish", "era": "Romantic", "key": "Variable", "focus": ["Spanish character", "Flamenco influence", "Rhythm"] },
  { "l": "Manual", "s": "Manual", "c": "BACH, J.S.", "t": "1st movement from Concerto nach italienischen Gusto BWV 971", "nat": "German", "era": "Baroque", "key": "F major", "focus": ["Concerto style", "Cantabile", "Baroque virtuosity"] },
  { "l": "Manual", "s": "Manual", "c": "BACH, J.S.", "t": "Andante 2nd movement from Concerto nach italienischen Gusto BWV 971", "nat": "German", "era": "Baroque", "key": "D minor", "focus": ["Baroque cantabile", "Singing tone", "Style"] },
  { "l": "Manual", "s": "Manual", "c": "BACH, J.S.", "t": "Presto 3rd movement from Concerto nach italienischen Gusto BWV 971", "nat": "German", "era": "Baroque", "key": "F major", "focus": ["Baroque virtuosity", "Technical drive", "Rhythmic precision"] },
  { "l": "Manual", "s": "Manual", "c": "BACH, J.S.", "t": "Duetto in G major BWV 804", "nat": "German", "era": "Baroque", "key": "G major", "focus": ["Two-part counterpoint", "Baroque style", "Independence of voices"] },
  { "l": "Manual", "s": "Manual", "c": "BACH, J.S.", "t": "Passepied I en rondeau 5th movement and Passepied II 6th movement from English Suite in E minor BWV 810", "nat": "German", "era": "Baroque", "key": "E minor", "focus": ["Dance suite", "Baroque character", "Ornamentation"] },
  { "l": "Manual", "s": "Manual", "c": "BEETHOVEN, L. van.", "t": "Allegro molto e con brio 1st movement from Sonata in C minor Op. 10 No 1", "nat": "German", "era": "Classical", "key": "C minor", "focus": ["Classical sonata", "Dramatic energy", "Development"] },
  { "l": "Manual", "s": "Manual", "c": "BEETHOVEN, L. van.", "t": "Presto con fuoco 4th movement from Sonata in E♭ major Op. 31 No 3", "nat": "German", "era": "Classical", "key": "E♭ major", "focus": ["Tarantella character", "Energy", "Virtuosity"] },
  { "l": "Manual", "s": "Manual", "c": "BENJAMIN, A.", "t": "Jamaican rumba", "nat": "British", "era": "Modern", "key": "Variable", "focus": ["Caribbean influence", "Rhythm", "Character piece"] },
  { "l": "Manual", "s": "Manual", "c": "BERNARD, F.", "t": "Winter wonderland (arr. BRUBECK)", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz arrangement", "Holiday character", "Style"] },
  { "l": "Manual", "s": "Manual", "c": "BLAND, E.", "t": "Cell phone blues from Piano music of Africa and the African diaspora Volume 3", "nat": "American", "era": "Contemporary", "key": "Variable", "focus": ["Blues style", "African diaspora music", "Rhythm"] },
  { "l": "Manual", "s": "Manual", "c": "BRAHMS, J.", "t": "Andante in D minor No 1 from Ballades Op. 10", "nat": "German", "era": "Romantic", "key": "D minor", "focus": ["Ballade character", "Depth", "Romantic expression"] },
  { "l": "Manual", "s": "Manual", "c": "BRAHMS, J.", "t": "Intermezzo in E minor No 5 from Fantasien Op. 116", "nat": "German", "era": "Romantic", "key": "E minor", "focus": ["Intermezzo", "Introspection", "Late Brahms"] },
  { "l": "Manual", "s": "Manual", "c": "BROWN, R.", "t": "Gravy waltz (arr. PETERSON) from Oscar Peterson jazz piano solo", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz waltz", "Swing feel", "Style"] },
  { "l": "Manual", "s": "Manual", "c": "BRUBECK, D.", "t": "Fast life from The giants of jazz piano", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz style", "Energy", "Character"] },
  { "l": "Manual", "s": "Manual", "c": "BRUBECK, D.", "t": "Weep no more from The genius of Dave Brubeck: The piano solos Book 1", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz ballad", "Lyricism", "Style"] },
  { "l": "Manual", "s": "Manual", "c": "CARTER-VARNEY, G.", "t": "Blue samba", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Australian music", "Samba influence", "Rhythm"] },
  { "l": "Manual", "s": "Manual", "c": "CETERA, P.", "t": "You're the inspiration (arr. ROED)", "nat": "American", "era": "Contemporary", "key": "Variable", "focus": ["Pop ballad", "Melody", "Style"] },
  { "l": "Manual", "s": "Manual", "c": "CHUA, S.", "t": "Siesta from Red hot rhapsodies", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Australian music", "Relaxed character", "Imagery"] },
  { "l": "Manual", "s": "Manual", "c": "CHOPIN, F.", "t": "Lento con espressione ('Nocturne') in C♯ minor CT 127/BI 49", "nat": "Polish", "era": "Romantic", "key": "C♯ minor", "focus": ["Nocturne style", "Deep expression", "Romantic lyricism"] },
  { "l": "Manual", "s": "Manual", "c": "CHOPIN, F.", "t": "Nocturne in B major Op. 32 No 1/CT 116", "nat": "Polish", "era": "Romantic", "key": "B major", "focus": ["Nocturne", "Cantabile", "Introspection"] },
  { "l": "Manual", "s": "Manual", "c": "CHOPIN, F.", "t": "Nocturne in E♭ major Op. 9 No 2/CT 109", "nat": "Polish", "era": "Romantic", "key": "E♭ major", "focus": ["Nocturne", "Ornamental melody", "Cantabile"] },
  { "l": "Manual", "s": "Manual", "c": "CHOPIN, F.", "t": "Waltz in A♭ major Op. 69 No 1/CT 215", "nat": "Polish", "era": "Romantic", "key": "A♭ major", "focus": ["Waltz", "Romantic elegance", "Lyricism"] },
  { "l": "Manual", "s": "Manual", "c": "COLERIDGE-TAYLOR, S.", "t": "Deep river No 10 from 24 Negro melodies Op. 59 No 1", "nat": "British", "era": "Romantic", "key": "Variable", "focus": ["Spiritual arrangement", "Lyricism", "Expression"] },
  { "l": "Manual", "s": "Manual", "c": "CONFREY, Z.", "t": "Kitten on the keys", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Novelty piano", "Syncopation", "Wit"] },
  { "l": "Manual", "s": "Manual", "c": "COUPERIN, F.", "t": "Les barricades mistérieuses from Pièces de clavecin", "nat": "French", "era": "Baroque", "key": "B minor", "focus": ["Baroque character piece", "Atmosphere", "Ornamentation"] },
  { "l": "Manual", "s": "Manual", "c": "GERSHWIN, G.", "t": "Fascinating rhythm from Gershwin at the keyboard", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz style", "Syncopation", "Rhythm"] },
  { "l": "Manual", "s": "Manual", "c": "GERSHWIN, G.", "t": "I got rhythm from Gershwin at the keyboard", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz style", "Rhythm", "Character"] },
  { "l": "Manual", "s": "Manual", "c": "GERSHWIN, G.", "t": "Swanee from Gershwin at the keyboard", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz style", "Lively character", "Melody"] },
  { "l": "Manual", "s": "Manual", "c": "HAYDN, J.", "t": "Presto 3rd movement from Parthia in E major Hob. XVI:13", "nat": "Austrian", "era": "Classical", "key": "E major", "focus": ["Classical wit", "Articulation", "Energy"] },
  { "l": "Manual", "s": "Manual", "c": "HYDE, M.", "t": "Water nymph from Piano works of Miriam Hyde", "nat": "Australian", "era": "Modern", "key": "Variable", "focus": ["Australian music", "Women composers", "Imagery"] },
  { "l": "Manual", "s": "Manual", "c": "HYDE, M.", "t": "Reflected reeds from Piano works of Miriam Hyde", "nat": "Australian", "era": "Modern", "key": "Variable", "focus": ["Australian music", "Women composers", "Tone painting"] },
  { "l": "Manual", "s": "Manual", "c": "JOBIM, A.", "t": "Wave (arr. BOOTH)", "nat": "Brazilian", "era": "Modern", "key": "Variable", "focus": ["Bossa nova", "Lyricism", "Style"] },
  { "l": "Manual", "s": "Manual", "c": "JONES, Q. and TEMPERTON, R.", "t": "Miss Celie's blues (Dan Coates complete advanced piano solos)", "nat": "American", "era": "Contemporary", "key": "Variable", "focus": ["Blues ballad", "Film music", "Expression"] },
  { "l": "Manual", "s": "Manual", "c": "LISZT, F.", "t": "Consolation in D♭ major No 3 from Consolations S 172/LW A111a", "nat": "Hungarian", "era": "Romantic", "key": "D♭ major", "focus": ["Romantic lyricism", "Cantabile", "Consolation"] },
  { "l": "Manual", "s": "Manual", "c": "MANZANO, M.", "t": "Baile llano No 11 from Spanish preludes", "nat": "Spanish", "era": "Modern", "key": "Variable", "focus": ["Spanish character", "Rhythm", "Folk influence"] },
  { "l": "Manual", "s": "Manual", "c": "MARTINŮ, B.", "t": "The puppet dances No 5 from Loutky H 137", "nat": "Czech", "era": "Modern", "key": "Variable", "focus": ["Playful character", "Czech music", "Modern style"] },
  { "l": "Manual", "s": "Manual", "c": "MENDELSSOHN, F.", "t": "Duetto in A♭ major No 6 from Lieder ohne Worte Op. 38", "nat": "German", "era": "Romantic", "key": "A♭ major", "focus": ["Song without words", "Cantabile", "Two-voice texture"] },
  { "l": "Manual", "s": "Manual", "c": "MENDELSSOHN, F.", "t": "Lied ohne Worte in C major No 4 from Lieder ohne Worte Op. 67", "nat": "German", "era": "Romantic", "key": "C major", "focus": ["Song without words", "Simplicity", "Lyricism"] },
  { "l": "Manual", "s": "Manual", "c": "NORTON, C.", "t": "Prelude III (Rock preludes)", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Rock influence", "Contemporary style", "Rhythm"] },
  { "l": "Manual", "s": "Manual", "c": "PUCCINI, G.", "t": "Piccolo tango", "nat": "Italian", "era": "Modern", "key": "Variable", "focus": ["Tango character", "Expressive melody", "Style"] },
  { "l": "Manual", "s": "Manual", "c": "SCHUBERT, F.", "t": "Impromptu in A♭ major No 4 from 4 impromptus Op. 90/D899", "nat": "Austrian", "era": "Romantic", "key": "A♭ major", "focus": ["Impromptu", "Romantic lyricism", "Technical brilliance"] },
  { "l": "Manual", "s": "Manual", "c": "SCHUBERT, F.", "t": "Impromptu in A♭ major No 2 from 4 impromptus Op. 142/D935", "nat": "Austrian", "era": "Romantic", "key": "A♭ major", "focus": ["Impromptu", "Romantic lyricism", "Flowing melody"] },
  { "l": "Manual", "s": "Manual", "c": "SCHUMANN, R.", "t": "Verrufene Stelle [Haunted spot] No 4 from Waldszenen Op. 82", "nat": "German", "era": "Romantic", "key": "D minor", "focus": ["Atmospheric character", "Nature imagery", "Harmonic colour"] },
  { "l": "Manual", "s": "Manual", "c": "TRADITIONAL", "t": "Nobody knows the trouble I've seen (arr. WOLF) from Spirituals", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Spiritual", "Arrangement", "Expression"] },
  { "l": "Manual", "s": "Manual", "c": "TRADITIONAL", "t": "Down by the riverside (arr. WOLF) from Spirituals", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Spiritual", "Arrangement", "Rhythm"] },
  { "l": "Manual", "s": "Manual", "c": "VAUGHAN WILLIAMS, R.", "t": "The lake in the mountains", "nat": "British", "era": "Modern", "key": "Variable", "focus": ["Tone painting", "British music", "Atmosphere"] },
  { "l": "Manual", "s": "Manual", "c": "MACDOWELL, E.", "t": "Improvisation No 4 from Zwölf Virtuosen-Etüden Op. 46", "nat": "American", "era": "Romantic", "key": "Variable", "focus": ["Virtuoso étude", "Improvisation character", "Brilliance"] },
  { "l": "Manual", "s": "Manual", "c": "MOZART, W.", "t": "Marcia in C major K 408/1", "nat": "Austrian", "era": "Classical", "key": "C major", "focus": ["March character", "Classical style", "Clarity"] },
  { "l": "Manual", "s": "Manual", "c": "MOZART, W.", "t": "Minuet in D major K 355", "nat": "Austrian", "era": "Classical", "key": "D major", "focus": ["Minuet", "Classical elegance", "Ornamentation"] },
  { "l": "Manual", "s": "Manual", "c": "MOZART, W.", "t": "Rondeau en polonaise 2nd movement from Sonata in D major K 284", "nat": "Austrian", "era": "Classical", "key": "D major", "focus": ["Polonaise character", "Classical elegance", "Melody"] },
  { "l": "Manual", "s": "Manual", "c": "MOZART, W.", "t": "Variations on 'Ah, vous dirai-je, maman' K 265", "nat": "Austrian", "era": "Classical", "key": "C major", "focus": ["Variation form", "Classical clarity", "Ornamentation"] },
  { "l": "Manual", "s": "Manual", "c": "MUSORGSKY, M.", "t": "Il vecchio castello No 2 from Kartinki s vistavki (Pictures at an exhibition)", "nat": "Russian", "era": "Romantic", "key": "G♯ minor", "focus": ["Programme music", "Medieval character", "Atmosphere"] },
  { "l": "Manual", "s": "Manual", "c": "NORTON, C.", "t": "Prelude VII (Samba) from Latin preludes 2", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Samba rhythm", "Latin character", "Contemporary style"] },
  { "l": "Manual", "s": "Manual", "c": "PAUL, D.", "t": "Happy birthday, Amadeus! Eine heitere Geburtstagssonatine", "nat": "German", "era": "Contemporary", "key": "Variable", "focus": ["Sonatina form", "Humor", "Classical homage"] },
  { "l": "Manual", "s": "Manual", "c": "RACHMANINOFF, S.", "t": "18th variation from Rhapsody on a theme of Paganini (arr. LONG)", "nat": "Russian", "era": "Romantic", "key": "D♭ major", "focus": ["Romantic lyricism", "Transcription", "Famous melody"] },
  { "l": "Manual", "s": "Manual", "c": "RUSSELL, O.", "t": "Jamaican dance No 2 from Piano music of Africa and the African diaspora Volume 3", "nat": "Jamaican", "era": "Modern", "key": "Variable", "focus": ["Caribbean character", "Rhythm", "Dance style"] },
  { "l": "Manual", "s": "Manual", "c": "SCHUMANN, R.", "t": "Herberge [Wayside inn] No 6 from Waldszenen Op. 82", "nat": "German", "era": "Romantic", "key": "B♭ major", "focus": ["Character piece", "Warmth", "Romantic expression"] },
  { "l": "Manual", "s": "Manual", "c": "SCULTHORPE, P.", "t": "Stars No 3 from Night pieces", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Australian music", "Night imagery", "Contemporary style"] },
  { "l": "Manual", "s": "Manual", "c": "SONDHEIM, S.", "t": "Send in the clowns (arr. COATES) from Complete advanced piano solos", "nat": "American", "era": "Contemporary", "key": "Variable", "focus": ["Musical theatre", "Ballad", "Expression"] },

];
