// ABRSM Piano 2025 & 2026 — G1
// Total: 47 pieces  A:16 B:16 C:15
// Generated from official ABRSM Piano 2025 & 2026 Syllabus PDF

const DATA_ABRSM_G1 = [
  // LIST A — 16 pieces
{"l":"A","c":"HANDEL","t":"Fireworks Minuet (from Music for the Royal Fireworks)","nat":"German","era":"Baroque","focus":["Baroque style", "Dance character", "Keyboard clarity"]},
{"l":"A","c":"KÖHLER, L.","t":"Melody in F, Op.","nat":"German","era":"Classical","focus":["Classical phrasing", "Singing tone", "Formal structure"]},
{"l":"A","c":"TRAD. GERMAN","t":"Muss i denn","nat":"German","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"A","c":"ALEXANDER, Dennis","t":"Sonatina","nat":"American","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"A","c":"BACH, J.S. (attrib.)","t":"Choral ‘Deal with Me, Lord’, BWV","nat":"German","era":"Baroque","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
{"l":"A","c":"BULLARD, Alan","t":"Climbing High","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"A","c":"GURLITT","t":"The Chase/The Hunt (No. 15 from First Lessons)","nat":"German","era":"Classical","focus":["Classical phrasing", "Hand coordination", "Formal structure"]},
{"l":"A","c":"HANDEL","t":"Gavotte in C","nat":"German","era":"Baroque","focus":["Baroque style", "Dance character", "Keyboard clarity"]},
{"l":"A","c":"HELYER, M.","t":"Haymaking (from The Greenwood Tree)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"A","c":"HOOK","t":"Gavotte in C (No. 3 from 24 Progressive Lessons)","nat":"English","era":"Baroque","focus":["Baroque style", "Dance character", "Keyboard clarity"]},
{"l":"A","c":"MOZART, L.","t":"Minuet in F (No. 6 from Nannerl-Notenbuch)","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Dance character", "Formal structure"]},
{"l":"A","c":"MOZART","t":"Allegro (No. 8 from 12 Duos, K.)","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"PURCELL","t":"Minuet in A minor, Z.","nat":"English","era":"Baroque","focus":["Baroque style", "Dance character", "Keyboard clarity"]},
{"l":"A","c":"RICHERT, Teresa","t":"Comical Cat (from Copycat Copycat)","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"A","c":"TÜRK","t":"Arioso in F (No. 1 from 12 Handstücke)","nat":"German","era":"Classical","focus":["Classical phrasing", "Singing tone", "Formal structure"]},
{"l":"A","c":"WELLS, Elsie","t":"Courante","nat":"English","era":"Baroque","focus":["Baroque style", "Dance character", "Keyboard clarity"]},
  // LIST B — 16 pieces
{"l":"B","c":"DUNHILL","t":"A Song of Erin (No. 8 from)","nat":"English","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"B","c":"ANDERSON-LOPEZ, Kristen & Robert","t":"Remember Me (from Coco), arr. L’Estrange","nat":"International","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"MARMION, Bernadette","t":"Winter (from Allsorts)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"ALEXANDER, Dennis","t":"Reflections (from Just for You and Me)","nat":"American","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"ALWYN","t":"The Trees are Heavy with Snow","nat":"English","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"BENNETT, R.R.","t":"Friday (from Seven Days a Week)","nat":"English","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"BLAKE, Jessie","t":"The Little White Cloud","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"GRECHANINOV","t":"Fairy Tale (No. 1 from Children’s Album, Op. 98)","nat":"Russian","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"B","c":"LASKO, Agnieszka","t":"Fountain (from Little Stories)","nat":"Polish","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"LENNON","t":"Imagine","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"MADDEN, Helen","t":"The Forgotten Forest","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"MENKEN, Alan","t":"Beauty and the Beast (from Beauty and)","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"PROUDLER, Victoria","t":"Silver Lining (from Piano Grades Are Go! Initial–Grade 1)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"SIEGMEISTER","t":"Song of the Dark Woods","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Singing tone", "Musical expression"]},
{"l":"B","c":"SPINDLER","t":"Song without Words","nat":"German","era":"Classical","focus":["Classical phrasing", "Singing tone", "Formal structure"]},
{"l":"B","c":"TANEVA, Borislava","t":"Small Valse","nat":"Bulgarian","era":"Contemporary","focus":["Contemporary idiom", "Dance character", "Musical expression"]},
  // LIST C — 15 pieces
{"l":"C","c":"ANAND, Amit","t":"Cyberspace Detective","nat":"Indian","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"TAN, Chee-Hwa","t":"The Wind (from A Child’s Garden of Verses)","nat":"Singaporean","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"YEOH, Nikki","t":"Berry’s Smoothie","nat":"Malaysian","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"ANDERSON-LOPEZ, Kristen & Robert","t":"Let It Go (from Frozen)","nat":"International","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"TIMBERLAKE, Justin","t":"Can’t Stop the Feeling!","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"ARMSTRONG, June","t":"Sunlight Through the Trees","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"BARRATT, Carol","t":"Cheesecake-Walk (from Get It Together!)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"DAVIDSSON, Elias","t":"The Frog (from The Gift of Music)","nat":"Icelandic","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"GILLOCK","t":"Swinging Beat","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Jazz/Pop style", "Musical expression"]},
{"l":"C","c":"HIDY, Diane","t":"Dotty’s Nightmare (from All Cooped Up)","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"MATHEWS, Alison","t":"Woodland Folk Song","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Singing tone", "Musical expression"]},
{"l":"C","c":"TRAD. EWE","t":"Tu tu Gbovi","nat":"Ewe","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"SNOW, Barbara","t":"Jazzy Dragon (from Animal Jazz)","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Jazz/Pop style", "Musical expression"]},
{"l":"C","c":"TAN, Chee-Hwa","t":"At the Seaside (from A Child’s Garden of Verses)","nat":"Singaporean","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"SEBBA, Jane","t":"Latin Laughter","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Rhythmic precision", "Musical expression"]},
{"l":"C","c":"TRAD. JAMAICAN","t":"Mango Walk, arr. Cornick","nat":"Jamaican","era":"Contemporary","focus":["Contemporary idiom", "Dance character", "Musical expression"]},
];
