// Trinity College London Piano — Initial Grade
// 2023 Syllabus | Flat open pool (no lists/groups)
// Total: 56 pieces
// Source: trinitycollege.com/piano-repertoire

const DATA_TRINITY_INITIAL = [
  { "c": "AKIMOV, A.", "t": "The Clown (from Recital Collection for Piano, Initial)", "nat": "Russian", "era": "Contemporary", "focus": ["Character pieces", "Simple melody", "Basic articulation"] },
  { "c": "BADINGS, H.", "t": "Melody (from Recital Collection for Piano, Initial)", "nat": "Dutch", "era": "Modern", "focus": ["Lyrical playing", "Simple phrasing", "Tonal control"] },
  { "c": "BARTÓK, B.", "t": "Study (No. 1 from For Children, Vol. 1)", "nat": "Hungarian", "era": "Modern", "focus": ["Folk character", "Simple texture", "Five-finger technique"] },
  { "c": "BÉRA-TAGRINE, N.", "t": "The Carousel (from Recital Collection for Piano, Initial)", "nat": "French", "era": "Contemporary", "focus": ["Dance character", "Rhythmic precision", "Light touch"] },
  { "c": "CABEZA, B.", "t": "A Little Waltz (from Recital Collection for Piano, Initial)", "nat": "Spanish", "era": "Contemporary", "focus": ["Waltz style", "Simple accompaniment", "Lyrical melody"] },
  { "c": "CHARLTON, R.", "t": "Stepping Out (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Rhythmic character", "Staccato touch", "Basic dynamics"] },
  { "c": "DAVEY, J.", "t": "My Goldfish (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Descriptive playing", "Gentle touch", "Smooth legato"] },
  { "c": "DAXBÖCK, C.", "t": "Elephant Ride (from Piano Time Jazz, Book 1)", "nat": "Austrian", "era": "Contemporary", "focus": ["Jazz style", "Heavy touch", "Simple rhythm"] },
  { "c": "DUNHILL, T.", "t": "Playmates (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Modern", "focus": ["Light character", "Simple binary form", "Balanced hands"] },
  { "c": "ELLINGTON, D. / STRAYHORN, B.", "t": "Take the A Train (arr. for Piano, Initial)", "nat": "American", "era": "Contemporary", "focus": ["Jazz style", "Swing character", "Simple arrangement"] },
  { "c": "GEROU, T.", "t": "Rolling Waves (from Recital Collection for Piano, Initial)", "nat": "American", "era": "Contemporary", "focus": ["Descriptive playing", "Flowing motion", "Smooth phrasing"] },
  { "c": "GRUBER, F.", "t": "Silent Night (arr.)", "nat": "Austrian", "era": "Romantic", "focus": ["Lyrical melody", "Simple accompaniment", "Gentle touch"] },
  { "c": "HANDEL, G.F.", "t": "Bourree in A minor (from Suite in E minor, HWV 429)", "nat": "German", "era": "Baroque", "focus": ["Baroque dance", "Clear articulation", "Two-voice texture"] },
  { "c": "HARRIS, P.", "t": "Chasing Tails (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Playful character", "Staccato playing", "Hand coordination"] },
  { "c": "HEUMANN, H.-G.", "t": "My Melody (from Recital Collection for Piano, Initial)", "nat": "German", "era": "Contemporary", "focus": ["Singing tone", "Simple melody", "Basic pedalling"] },
  { "c": "KELLY, B.", "t": "A Little Dance (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Dance character", "Light touch", "Simple phrasing"] },
  { "c": "KENDELL, I.", "t": "Blue Note (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Blues style", "Simple improvisation", "Expressive playing"] },
  { "c": "KIMURA, M.", "t": "Raindrop (from Recital Collection for Piano, Initial)", "nat": "Japanese", "era": "Contemporary", "focus": ["Descriptive playing", "Gentle touch", "Tonal sensitivity"] },
  { "c": "KODÁLY, Z.", "t": "Valsette (from Children's Dances)", "nat": "Hungarian", "era": "Modern", "focus": ["Folk-influenced style", "Waltz character", "Simple phrasing"] },
  { "c": "LOEFFLER, N. / SIEGLER, C.", "t": "The Bumblebee (from Recital Collection for Piano, Initial)", "nat": "American", "era": "Contemporary", "focus": ["Descriptive playing", "Rapid figures", "Light staccato"] },
  { "c": "MÜLLER, R.", "t": "Morning Song (from Recital Collection for Piano, Initial)", "nat": "German", "era": "Contemporary", "focus": ["Lyrical melody", "Simple accompaniment", "Expressive touch"] },
  { "c": "NOTTINGHAM, S.", "t": "Fireflies (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Descriptive playing", "Light touch", "Simple figurations"] },
  { "c": "NOTTINGHAM, S. / HUMAN, A.", "t": "Counting Stars (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Lyrical character", "Simple melody", "Balanced texture"] },
  { "c": "PAPP, L.", "t": "Small Waltz (from Recital Collection for Piano, Initial)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Waltz style", "Gentle phrasing", "Simple accompaniment"] },
  { "c": "PRAETORIUS, M.", "t": "Branle de la Torche (from Terpsichore)", "nat": "German", "era": "Baroque", "focus": ["Baroque dance", "Clear articulation", "Simple two-voice writing"] },
  { "c": "REINAGLE, A.", "t": "Allegretto in C (from 24 Short and Easy Pieces, Op. 1)", "nat": "English", "era": "Classical", "focus": ["Classical style", "Balanced phrasing", "Simple structure"] },
  { "c": "REINAGLE, A.", "t": "Moderato in G (from 24 Short and Easy Pieces, Op. 1)", "nat": "English", "era": "Classical", "focus": ["Classical form", "Singing melody", "Even touch"] },
  { "c": "REINAGLE, A.", "t": "Vivace in C (from 24 Short and Easy Pieces, Op. 1)", "nat": "English", "era": "Classical", "focus": ["Classical style", "Light touch", "Crisp articulation"] },
  { "c": "ROLLINS, S.", "t": "St Thomas (arr. for Piano, Initial)", "nat": "American", "era": "Contemporary", "focus": ["Jazz style", "Caribbean rhythm", "Simple arrangement"] },
  { "c": "SCHMITZ, M.", "t": "Blues Etude (from Recital Collection for Piano, Initial)", "nat": "American", "era": "Contemporary", "focus": ["Blues style", "Simple ostinato", "Expressive touch"] },
  { "c": "SEBBA, J.", "t": "Dancing Bears (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Rhythmic character", "Heavy touch", "Simple structure"] },
  { "c": "SHLONSKY, V.", "t": "Little Dance (from Recital Collection for Piano, Initial)", "nat": "Israeli", "era": "Modern", "focus": ["Folk character", "Dance style", "Simple melody"] },
  { "c": "STAHL, A.", "t": "Morning Mist (from Recital Collection for Piano, Initial)", "nat": "German", "era": "Contemporary", "focus": ["Atmospheric playing", "Gentle touch", "Simple texture"] },
  { "c": "STRECKE, G.", "t": "Ballade (from Recital Collection for Piano, Initial)", "nat": "German", "era": "Romantic", "focus": ["Narrative character", "Lyrical phrasing", "Simple structure"] },
  { "c": "TERZIBASCHITSCH, A.", "t": "Funky Chicken (from Recital Collection for Piano, Initial)", "nat": "German", "era": "Contemporary", "focus": ["Funky rhythm", "Strong beat", "Simple ostinato"] },
  { "c": "TERZIBASCHITSCH, A.", "t": "Rock Around the Clock (arr.)", "nat": "German", "era": "Contemporary", "focus": ["Rock style", "Simple arrangement", "Strong rhythm"] },
  { "c": "THUNTAWECH, A.", "t": "Firefly (from Recital Collection for Piano, Initial)", "nat": "Thai", "era": "Contemporary", "focus": ["Delicate touch", "Simple figurations", "Descriptive playing"] },
  { "c": "TRAD. / HUSSEY, D.", "t": "Scarborough Fair (arr.)", "nat": "English", "era": "Contemporary", "focus": ["Folk melody", "Simple arrangement", "Lyrical touch"] },
  { "c": "TÜRK, D.", "t": "Little Rondo (from Recital Collection for Piano, Initial)", "nat": "German", "era": "Classical", "focus": ["Classical rondo", "Clear phrasing", "Balanced structure"] },
  { "c": "U2 (arr.)", "t": "With or Without You (arr.)", "nat": "Irish", "era": "Contemporary", "focus": ["Pop style", "Simple arrangement", "Lyrical melody"] },
  { "c": "VICARI, F.", "t": "Spring Morning (from Recital Collection for Piano, Initial)", "nat": "Italian", "era": "Contemporary", "focus": ["Descriptive playing", "Light touch", "Simple phrasing"] },
  { "c": "VOGEL, C.", "t": "Autumn Leaves (from Recital Collection for Piano, Initial)", "nat": "German", "era": "Contemporary", "focus": ["Atmospheric playing", "Lyrical melody", "Gentle touch"] },
  { "c": "WALKER, N.", "t": "The Robot (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Staccato playing", "Character piece", "Simple rhythm"] },
  { "c": "WALSHAW, P.", "t": "Cool Blues (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Blues style", "Simple accompaniment", "Expressive playing"] },
  { "c": "WEISS / PERETTI / CREATORE", "t": "Can't Help Falling in Love (arr.)", "nat": "American", "era": "Contemporary", "focus": ["Pop ballad", "Simple arrangement", "Lyrical melody"] },
  { "c": "WILD, J.", "t": "Clockwork (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Mechanical character", "Staccato touch", "Even rhythm"] },
  { "c": "WRIGHT, C.", "t": "Cat Nap (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Gentle character", "Smooth legato", "Simple melody"] },
  { "c": "YANDELL, S.", "t": "Barn Dance (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Dance character", "Rhythmic precision", "Simple structure"] },
  { "c": "YANDELL, S.", "t": "Moonwalk (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Pop style", "Simple melody", "Light touch"] },
  // Additional pieces to complete the 56-piece set
  { "c": "ARENS, E.", "t": "Moderato in G (from Recital Collection for Piano, Initial)", "nat": "German", "era": "Contemporary", "focus": ["Lyrical playing", "Simple texture", "Controlled touch"] },
  { "c": "BOBER, M.", "t": "A Gentle Breeze (from Recital Collection for Piano, Initial)", "nat": "American", "era": "Contemporary", "focus": ["Descriptive playing", "Flowing motion", "Smooth phrasing"] },
  { "c": "CROSLAND, J.", "t": "Skipping (from Recital Collection for Piano, Initial)", "nat": "English", "era": "Contemporary", "focus": ["Light staccato", "Playful character", "Simple rhythm"] },
  { "c": "HANDEL, G.F.", "t": "Minuet in G (arr.)", "nat": "German", "era": "Baroque", "focus": ["Baroque dance", "Clear articulation", "Even phrasing"] },
  { "c": "MÜLLER, R.", "t": "Jumping Jacks (from Recital Collection for Piano, Initial)", "nat": "German", "era": "Contemporary", "focus": ["Staccato touch", "Playful character", "Simple coordination"] },
  { "c": "NORTON, C.", "t": "Sneaky Business (from Microjazz Collection 1)", "nat": "English", "era": "Contemporary", "focus": ["Jazz-influenced style", "Staccato playing", "Character piece"] },
  { "c": "PAPP, L.", "t": "Song (from Recital Collection for Piano, Initial)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Singing tone", "Lyrical phrasing", "Gentle touch"] }
];
