// Trinity College London Piano — Grade 5
// 2023 Syllabus | Flat open pool (no lists/groups)
// Total: 58 pieces
// Source: trinitycollege.com/piano-repertoire

const DATA_TRINITY_G5 = [
  { "c": "ARENS, E.", "t": "Scherzo (from Recital Collection for Piano, Grade 5)", "nat": "German", "era": "Contemporary", "focus": ["Playful character", "Light touch", "Simple coordination"] },
  { "c": "BACH, J.S.", "t": "Two-Part Invention No. 8 in F, BWV 779", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Finger independence", "Two-voice texture"] },
  { "c": "BACH, J.S.", "t": "Prelude in C, BWV 846 (from Well-Tempered Clavier, Book 1)", "nat": "German", "era": "Baroque", "focus": ["Broken chord figurations", "Smooth legato", "Harmonic awareness"] },
  { "c": "BARTÓK, B.", "t": "Evening in the Country (No. 5 from Ten Easy Pieces)", "nat": "Hungarian", "era": "Modern", "focus": ["Folk character", "Modal harmony", "Expressive phrasing"] },
  { "c": "BEETHOVEN, L. van", "t": "Bagatelle in A minor, Op. 119 No. 9", "nat": "German", "era": "Classical", "focus": ["Character piece", "Simple phrasing", "Dynamic contrast"] },
  { "c": "BRAHMS, J.", "t": "Waltz in A flat, Op. 39 No. 15", "nat": "German", "era": "Romantic", "focus": ["Waltz style", "Lyrical phrasing", "Romantic touch"] },
  { "c": "BULLARD, A.", "t": "Footsteps in the Snow (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Simple ostinato", "Evocative character"] },
  { "c": "CAINE, U.", "t": "Jazz Nocturne (from Recital Collection for Piano, Grade 5)", "nat": "American", "era": "Contemporary", "focus": ["Jazz-influenced", "Night character", "Expressive phrasing"] },
  { "c": "CHOPIN, F.", "t": "Waltz in B minor, Op. 69 No. 2 (posth.)", "nat": "Polish", "era": "Romantic", "focus": ["Waltz style", "Expressive melody", "Romantic phrasing"] },
  { "c": "CLEMENTI, M.", "t": "Sonatina in C, Op. 36 No. 3 (1st mvt)", "nat": "Italian", "era": "Classical", "focus": ["Classical sonatina", "Scale technique", "Clear phrasing"] },
  { "c": "COPLAND, A.", "t": "Simple Gifts (from Appalachian Spring, simplified arr.)", "nat": "American", "era": "Modern", "focus": ["American folk style", "Simple arrangement", "Lyrical character"] },
  { "c": "CROSLAND, J.", "t": "Salsa Fever (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Latin character", "Rhythmic drive", "Simple syncopation"] },
  { "c": "DEBUSSY, C.", "t": "Rêverie", "nat": "French", "era": "Romantic", "focus": ["Impressionist colour", "Flowing figurations", "Atmospheric playing"] },
  { "c": "DVORAK, A.", "t": "Humoresque, Op. 101 No. 7 (simplified)", "nat": "Czech", "era": "Romantic", "focus": ["Character piece", "Lyrical melody", "Simple phrasing"] },
  { "c": "FAURÉ, G.", "t": "Nocturne No. 1, Op. 33 No. 1 (simplified)", "nat": "French", "era": "Romantic", "focus": ["Night character", "Lyrical melody", "Romantic phrasing"] },
  { "c": "GEROU, T.", "t": "In the Groove (from Recital Collection for Piano, Grade 5)", "nat": "American", "era": "Contemporary", "focus": ["Jazz style", "Swing character", "Simple syncopation"] },
  { "c": "GRANADOS, E.", "t": "Spanish Dance No. 5 (Andaluza)", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Guitar imitation", "Expressive phrasing"] },
  { "c": "GRIEG, E.", "t": "Lyric Piece: Nocturne, Op. 54 No. 4 (simplified)", "nat": "Norwegian", "era": "Romantic", "focus": ["Night character", "Romantic phrasing", "Lyrical melody"] },
  { "c": "HANDEL, G.F.", "t": "Air and Variations 'The Harmonious Blacksmith' (HWV 430)", "nat": "German", "era": "Baroque", "focus": ["Variation technique", "Baroque ornament", "Technical development"] },
  { "c": "HARRIS, P.", "t": "Café Rendezvous (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Jazz café style", "Atmospheric playing", "Expressive phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in C, Hob. XVI/10 (1st mvt)", "nat": "Austrian", "era": "Classical", "focus": ["Classical sonata form", "Clear phrasing", "Ornamentation"] },
  { "c": "JOPLIN, S.", "t": "Maple Leaf Rag", "nat": "American", "era": "Romantic", "focus": ["Ragtime style", "Syncopation", "Clear structure"] },
  { "c": "KABALEVSKY, D.", "t": "Sonatina in A minor, Op. 27 No. 18", "nat": "Russian", "era": "Modern", "focus": ["Classical sonatina form", "Folk-influenced character", "Clear phrasing"] },
  { "c": "KHACHATURIAN, A.", "t": "Toccata", "nat": "Armenian", "era": "Modern", "focus": ["Rhythmic drive", "Technical precision", "Dynamic contrast"] },
  { "c": "LANE, R.", "t": "Cool Blue (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Blues style", "Expressive playing", "Simple syncopation"] },
  { "c": "LISZT, F.", "t": "Consolation No. 3 in D flat (simplified)", "nat": "Hungarian", "era": "Romantic", "focus": ["Lyrical melody", "Romantic phrasing", "Cantabile touch"] },
  { "c": "MENDELSSOHN, F.", "t": "Song Without Words, Op. 30 No. 6 'Venetian Gondola Song'", "nat": "German", "era": "Romantic", "focus": ["Singing melody", "Barcarolle rhythm", "Romantic character"] },
  { "c": "MOZART, W.A.", "t": "Rondo alla Turca (from Sonata K. 331, simplified)", "nat": "Austrian", "era": "Classical", "focus": ["Turkish character", "Clear articulation", "Rhythmic precision"] },
  { "c": "NORTON, C.", "t": "City Blues (from Microjazz Collection 4)", "nat": "English", "era": "Contemporary", "focus": ["Blues style", "Simple syncopation", "Expressive playing"] },
  { "c": "PAPP, L.", "t": "Fantasia (from Recital Collection for Piano, Grade 5)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Expressive freedom", "Simple texture", "Atmospheric playing"] },
  { "c": "PROKOFIEV, S.", "t": "Visions Fugitives, Op. 22 No. 3 (simplified)", "nat": "Russian", "era": "Modern", "focus": ["Sarcastic character", "Simple texture", "Controlled touch"] },
  { "c": "PURCELL, H.", "t": "Suite in E minor: Sarabande (Z. 666)", "nat": "English", "era": "Baroque", "focus": ["Baroque dance", "Ornamentation", "Expressive playing"] },
  { "c": "RAMSKILL, T.", "t": "Storm Clouds (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Dramatic character", "Dynamic contrast", "Atmospheric playing"] },
  { "c": "RAVEL, M.", "t": "Pavane pour une infante défunte", "nat": "French", "era": "Romantic", "focus": ["Stately character", "Lyrical melody", "Atmospheric playing"] },
  { "c": "SATIE, E.", "t": "Gymnopédie No. 1", "nat": "French", "era": "Romantic", "focus": ["Atmospheric playing", "Simple texture", "Expressive freedom"] },
  { "c": "SCARLATTI, D.", "t": "Sonata in D minor, K. 9 (L. 413)", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Ornaments", "Binary form"] },
  { "c": "SCHUBERT, F.", "t": "Moment Musical, Op. 94 No. 3", "nat": "Austrian", "era": "Romantic", "focus": ["Dance character", "Clear phrasing", "Simple structure"] },
  { "c": "SCHUMANN, R.", "t": "Kinderszenen: Träumerei, Op. 15 No. 7", "nat": "German", "era": "Romantic", "focus": ["Dreamy character", "Inner voice balance", "Romantic phrasing"] },
  { "c": "SCHMITZ, M.", "t": "Late Night Jazz (from Recital Collection for Piano, Grade 5)", "nat": "American", "era": "Contemporary", "focus": ["Jazz style", "Atmospheric playing", "Expressive phrasing"] },
  { "c": "SEBBA, J.", "t": "Midnight Blues (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Blues style", "Night character", "Expressive playing"] },
  { "c": "SHOSTAKOVICH, D.", "t": "Prelude in D flat, Op. 34 No. 15", "nat": "Russian", "era": "Modern", "focus": ["Lyrical melody", "Simple texture", "Expressive playing"] },
  { "c": "STRECKE, G.", "t": "Ballade (from Recital Collection for Piano, Grade 5)", "nat": "German", "era": "Romantic", "focus": ["Narrative character", "Expressive phrasing", "Romantic character"] },
  { "c": "TANSMAN, A.", "t": "Mazurka (from Pour les Enfants, 3rd set)", "nat": "Polish", "era": "Modern", "focus": ["Folk-influenced dance", "Rhythmic character", "Simple phrasing"] },
  { "c": "TELEMANN, G.P.", "t": "Fantasia in G (TWV 33:1)", "nat": "German", "era": "Baroque", "focus": ["Baroque fantasia", "Ornament", "Two-voice writing"] },
  { "c": "TERZIBASCHITSCH, A.", "t": "Cool Jazz (from Recital Collection for Piano, Grade 5)", "nat": "German", "era": "Contemporary", "focus": ["Jazz style", "Simple syncopation", "Relaxed character"] },
  { "c": "VILLA-LOBOS, H.", "t": "Valsa da Dor (from Cirandinhas No. 4)", "nat": "Brazilian", "era": "Modern", "focus": ["Waltz character", "Lyrical melody", "Expressive phrasing"] },
  { "c": "WALLIS, E.", "t": "Northern Lights (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Simple texture", "Expressive touch"] },
  { "c": "WARLOCK, P.", "t": "Capriol Suite: Pavane", "nat": "English", "era": "Modern", "focus": ["Renaissance style", "Clear texture", "Stately character"] },
  { "c": "YANDELL, S.", "t": "Red Dragon (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Dramatic character", "Rhythmic drive", "Dynamic contrast"] },
  { "c": "NORTON, C.", "t": "In the Pink (from Microjazz Collection 4)", "nat": "English", "era": "Contemporary", "focus": ["Jazz style", "Lyrical melody", "Simple phrasing"] },
  { "c": "PAPP, L.", "t": "Bagatelle No. 2 (from Recital Collection for Piano, Grade 5)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Character piece", "Simple form", "Expressive touch"] },
  { "c": "HARRIS, P.", "t": "The Big Easy (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Jazz style", "Relaxed character", "Simple syncopation"] },
  { "c": "CAINE, U.", "t": "Modal Jazz (from Recital Collection for Piano, Grade 5)", "nat": "American", "era": "Contemporary", "focus": ["Modal harmony", "Jazz style", "Expressive freedom"] },
  { "c": "LANE, R.", "t": "Jungle Beat (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Rhythmic drive", "Simple ostinato", "Descriptive playing"] },
  { "c": "SCHMITZ, M.", "t": "Piano Rag (from Recital Collection for Piano, Grade 5)", "nat": "American", "era": "Contemporary", "focus": ["Ragtime style", "Syncopation", "Clear structure"] },
  { "c": "BULLARD, A.", "t": "Toccata Romana (from Recital Collection for Piano, Grade 5)", "nat": "English", "era": "Contemporary", "focus": ["Staccato technique", "Rhythmic drive", "Bright character"] },
  { "c": "BOBER, M.", "t": "Storm at Sea (from Recital Collection for Piano, Grade 5)", "nat": "American", "era": "Contemporary", "focus": ["Dramatic character", "Dynamic contrast", "Descriptive playing"] },
  { "c": "ARENS, E.", "t": "Arabesque (from Recital Collection for Piano, Grade 5)", "nat": "German", "era": "Contemporary", "focus": ["Flowing figurations", "Delicate touch", "Musical shape"] }
];
