// ABRSM Piano 2025 & 2026 — G6
// Total: 48 pieces  A:16 B:16 C:16
// Generated from official ABRSM Piano 2025 & 2026 Syllabus PDF

const DATA_ABRSM_G6 = [
  // LIST A — 16 pieces
{"l":"A","c":"BACH, J.S.","t":"Invention No. 14 in B flat, BWV","nat":"German","era":"Baroque","focus":["Baroque style", "Contrapuntal texture", "Keyboard clarity"]},
{"l":"A","c":"TAILLEFERRE","t":"Sonata alla Scarlatti","nat":"French","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"A","c":"NIELSEN, C.","t":"Spilleværket (No. 6 from Humoreske-Bagateller, Op. 11)","nat":"Danish","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"A","c":"BACH, C.P.E.","t":"Solfeggietto in C minor, Wq. 117/2 C.","nat":"German","era":"Baroque","focus":["Baroque style", "Contrapuntal texture", "Keyboard clarity"]},
{"l":"A","c":"BACH, J.S.","t":"Invention No. 6 in E, BWV 777 J. J.","nat":"German","era":"Baroque","focus":["Baroque style", "Contrapuntal texture", "Keyboard clarity"]},
{"l":"A","c":"BURGMÜLLER, J.F.F.","t":"Velocity, Op. 109 No. 10 J.","nat":"German","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"A","c":"CIMAROSA","t":"Allegro (1st movt from Sonata No. 6 in G)","nat":"Italian","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"HANDEL","t":"Fantasia in A","nat":"German","era":"Baroque","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
{"l":"A","c":"HAYDN","t":"Finale: Allegro molto (4th movt from Sonata Haydn: in G, Hob. XVI:6) Haydn","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"HUMMEL","t":"Rondo in C, Op. 52 No. 6 Hummel","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"PAINE, Knowles","t":"Village Dance (No. 5 from In the Country, Op. 26)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"A","c":"LINDEMAN","t":"Allegretto (from Character)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"A","c":"MARCELLO, B.","t":"Presto (2nd movt from Sonata in G) A","nat":"International","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"A","c":"SCARLATTI, D.","t":"Sonata in A, Kp. 208, L. 238 D.","nat":"Italian","era":"Baroque","focus":["Baroque style", "Formal structure", "Keyboard clarity"]},
{"l":"A","c":"SCHUBERT","t":"Moment musical in F minor (No. 3 from Schubert: Moments musicaux, D. 780) Schubert","nat":"Austrian","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"A","c":"TELEMANN","t":"Allegro (1st movt from Fantasia No. 1 in D, 1st Telemann: Dozen, TWV 33:1)","nat":"German","era":"Baroque","focus":["Baroque style", "Formal structure", "Keyboard clarity"]},
  // LIST B — 16 pieces
{"l":"B","c":"HENSEL, F.M.","t":"Bagatelle in F (No. 1 from Two Bagatelles)","nat":"German","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"GLIÈRE","t":"Esquisse in D (No. 9 from 12 esquisses, Op. 47)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"FFRENCH, Alexis","t":"Last Song (from The Secret)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Singing tone", "Musical expression"]},
{"l":"B","c":"ALBÉNIZ","t":"Tango (No. 2 from España, Op. 165)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"BONIS, Mel","t":"Interlude (from Interlude et Valse lente, Op. 38)","nat":"French","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"B","c":"BOWEN, Y.","t":"A Pastel Y.","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"CHOPIN","t":"Waltz in A minor, KK. IVb","nat":"Polish","era":"Romantic","focus":["Expressive tone", "Dance character", "Dynamic shaping"]},
{"l":"B","c":"JOIO, Dello","t":"Prayer of the Matador (No. 2 from Lyric Pieces The for the Young) from","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"GLIÈRE","t":"Prelude in D- (No. 1 from 8 Easy Pieces, Op. 43)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Contrapuntal texture", "Character contrast"]},
{"l":"B","c":"GUASTAVINO","t":"Cantilena No. 1 ‘Santa Fe para Ilorar’ (from Guastavino: 10 Cantilenas Argentinas)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"HARTMANN, C.","t":"Nocturne C.","nat":"International","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"B","c":"HOUGH, Stephen","t":"Little Lullaby (4th movt from Suite R-B) Stephen (Weinberger)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"B","c":"HOWELLS","t":"There Was a Most Beautiful Lady (No. 3 from Howells: Country Pageant)","nat":"International","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"KHACHATURIAN","t":"Legend (No. 6 from Pictures of Childhood) Khachaturian","nat":"Armenian","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"B","c":"SCHUMANN","t":"Einsame Blumen (No. 3 from Waldscenen, Op. 82)","nat":"German","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"WEDGWOOD, Sam","t":"Empty Rooms (from Chilling Out)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
  // LIST C — 16 pieces
{"l":"C","c":"BARTÓK","t":"Stamping Dance (No. 128 from Mikrokosmos, Vol. 5)","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"C","c":"RAHMAN, Zoe","t":"The Bounce","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Jazz/Pop style", "Musical expression"]},
{"l":"C","c":"KOMITAS","t":"Shushiki (No. 4 from Dances)","nat":"Armenian","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"C","c":"BERNSTEIN, L.","t":"Cool (from West Side Story)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
{"l":"C","c":"BERNSTEIN, L.","t":"For Stephen Sondheim (No. 3 from L. 13 Anniversaries)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"CAPERS, Valerie","t":"Mr “Satchmo” (from Portraits in Jazz) Valerie","nat":"International","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
{"l":"C","c":"CASELLA","t":"Galop Final (No. 11 from 11 Children's Pieces, Op. 35)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"C","c":"CROSLAND, Ben","t":"View from a Window (No. 12 from Cool Beans!, Pp. Vol. 1) (Editions)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Jazz/Pop style", "Musical expression"]},
{"l":"C","c":"HARVEY, Paul","t":"Rumba Toccata Paul","nat":"International","era":"Modern","focus":["Rhythmic precision", "Contrapuntal texture", "Character contrast"]},
{"l":"C","c":"ILES, Nikki","t":"East Coast Blues Jazz","nat":"English","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
{"l":"C","c":"MERCURY","t":"Somebody to Love","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"MONTAGUE, Stephen","t":"Tsunami","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"PROKOFIEV","t":"Cortège de sauterelles (No. 7 from Musiques d'enfants, Op. 65)","nat":"Russian","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"OKOYE, Nkeiru","t":"Dancing Barefoot in the Rain (from African Piano Sketches)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"RUDERS, Poul","t":"Shooting Stars","nat":"Danish","era":"Contemporary","focus":["Contemporary idiom", "Modern harmony", "Musical expression"]},
{"l":"C","c":"TAYLOR, Billy","t":"I Wish I Knew How It Would Feel to Be Free, arr. Churchill","nat":"American","era":"Modern","focus":["Jazz/Pop style", "Rhythmic precision", "Musical expression"]},
];
