// AMEB Piano 2026 — LMusA (Licentiate in Music, Australia) — Level 3
// Exam code: 9951
// Program: 35–50 min | 1 work from List A + at least 3 from Lists B/C/D
// Min 3 different styles/historical periods required | At least 1 complete work from memory
// Concert standard of performance expected
// Source: 2026 AMEB Manual of Syllabuses (Music) pp.81–83

const DATA_LMUSA = [
  // LIST A — Major Works (one required)
  {"l":"A","c":"BACH, J.S.","t":"'English' Suite No. 2 in A minor BWV 807","nat":"German","era":"Baroque","focus":["Baroque style","Formal structure","Keyboard clarity"]},
  {"l":"A","c":"BACH, J.S.","t":"Partita No. 4 in D major BWV 828","nat":"German","era":"Baroque","focus":["Baroque style","Formal structure","Keyboard clarity"]},
  {"l":"A","c":"BARBER, S.","t":"Sonata Op. 26","nat":"American","era":"Contemporary","focus":["Contemporary idiom","Formal structure","Musical expression"]},
  {"l":"A","c":"BARTÓK, B.","t":"Sonata BB 88","nat":"Hungarian","era":"Modern","focus":["Modern harmony","Rhythmic precision","Musical expression"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Sonata in C major Op. 2 No. 3","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Sonata in E♭ major Op. 7","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Sonata in D major Op. 10 No. 3","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Sonata in G major Op. 31 No. 1","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Sonata in D minor Op. 31 No. 2 ('Tempest')","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Sonata in E♭ major Op. 31 No. 3","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Six Variations on an Original Theme Op. 34","nat":"German","era":"Classical","focus":["Classical phrasing","Variation technique","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Sonata in E♭ major Op. 81a ('Les Adieux')","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Sonata in E major Op. 109","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Sonata in A♭ major Op. 110","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BRAHMS, J.","t":"Variations on a Theme by R. Schumann Op. 9","nat":"German","era":"Romantic","focus":["Expressive tone","Variation technique","Dynamic shaping"]},
  {"l":"A","c":"BRAHMS, J.","t":"4 Klavierstücke Op. 119 [complete]","nat":"German","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"A","c":"CHOPIN, F.","t":"Sonata in B♭ minor Op. 35 / CT 202","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"CHOPIN, F.","t":"Sonata in B minor Op. 58 / CT 203","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"CLEMENTI, M.","t":"Sonata in B minor Op. 40 No. 2","nat":"Italian","era":"Classical","focus":["Classical phrasing","Formal structure","Finger independence"]},
  {"l":"A","c":"COPLAND, A.","t":"Piano Variations","nat":"American","era":"Contemporary","focus":["Contemporary idiom","Variation technique","Musical expression"]},
  {"l":"A","c":"DUSSEK, J.","t":"Sonata in E♭ major Op. 44 ('The Farewell')","nat":"Czech","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"EDWARDS, R.","t":"Sonata (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"A","c":"FRANCK, C.","t":"Prélude, choral et fugue M 21","nat":"Belgian","era":"Romantic","focus":["Expressive tone","Contrapuntal texture","Dynamic shaping"]},
  {"l":"A","c":"GINASTERA, A.","t":"Piano Sonata No. 1 Op. 22","nat":"Argentine","era":"Modern","focus":["Rhythmic precision","Modern harmony","Musical expression"]},
  {"l":"A","c":"GRIEG, E.","t":"Sonata in E minor Op. 7","nat":"Norwegian","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"HAYDN, J.","t":"Sonata in C major Hob XVI:50","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"HAYDN, J.","t":"Sonata in E♭ major Hob XVI:52","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"HOLLAND, D.","t":"Sonata (EMI Music Publishing)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"A","c":"HYDE, M.","t":"Piano Sonata in G minor (Wirripang)","nat":"Australian","era":"Modern","focus":["Expressive tone","Australian character","Musical expression"]},
  {"l":"A","c":"KABALEVSKY, D.","t":"Sonata No. 3 in F major Op. 46","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Formal structure","Modern harmony"]},
  {"l":"A","c":"MEDTNER, N.","t":"Sonata tragica No. 5 from Vergessene Weisen Op. 39","nat":"Russian","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"MENDELSSOHN, F.","t":"Fantasia (Sonate écossaise) in F♯ minor Op. 28","nat":"German","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"MENDELSSOHN, F.","t":"Variations sérieuses Op. 54","nat":"German","era":"Romantic","focus":["Expressive tone","Variation technique","Dynamic shaping"]},
  {"l":"A","c":"MOZART, W.A.","t":"Sonata in D major K 311","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"MOZART, W.A.","t":"Sonata in C minor K 457","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"MOZART, W.A.","t":"Sonata in F major K 533","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"MOZART, W.A.","t":"Sonata in D major K 576","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"PROKOFIEV, S.","t":"Sonata No. 2 in D minor Op. 14","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Formal structure","Modern harmony"]},
  {"l":"A","c":"PROKOFIEV, S.","t":"Sonata No. 5 in C major Op. 38","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Formal structure","Modern harmony"]},
  {"l":"A","c":"PROKOFIEV, S.","t":"Sonata No. 6 in A major Op. 82","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Formal structure","Modern harmony"]},
  {"l":"A","c":"PROKOFIEV, S.","t":"Sonata No. 7 in B♭ major Op. 83","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Formal structure","Modern harmony"]},
  {"l":"A","c":"RACHMANINOFF, S.","t":"Sonata No. 2 in B♭ minor Op. 36 [1931 revised version]","nat":"Russian","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"SCHUBERT, F.","t":"Sonata in A minor D 845 / Op. 42","nat":"Austrian","era":"Romantic","focus":["Expressive tone","Formal structure","Lyrical phrasing"]},
  {"l":"A","c":"SCHUBERT, F.","t":"Sonata in E♭ major D 568 / Op. 122","nat":"Austrian","era":"Romantic","focus":["Expressive tone","Formal structure","Lyrical phrasing"]},
  {"l":"A","c":"SCHUBERT, F.","t":"Sonata in B major D 575 / Op. 147","nat":"Austrian","era":"Romantic","focus":["Expressive tone","Formal structure","Lyrical phrasing"]},
  {"l":"A","c":"SCHULTZ, H.","t":"Sea-Change Op. 32 (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"A","c":"SCHUMANN, C.","t":"Sonata in G minor (Breitkopf)","nat":"German","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"SCHUMANN, R.","t":"Sonata No. 2 in G minor Op. 22","nat":"German","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"SCHUMANN, R.","t":"Faschingsschwank aus Wien Op. 26","nat":"German","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"SCOTT, C.","t":"Sonata No. 3","nat":"English","era":"Modern","focus":["Modern harmony","Formal structure","Musical expression"]},
  {"l":"A","c":"SCRIABIN, A.","t":"Sonata No. 2 in G♯ minor ('Sonate-fantasie') Op. 19","nat":"Russian","era":"Modern","focus":["Expressive tone","Modern harmony","Musical expression"]},
  {"l":"A","c":"SCRIABIN, A.","t":"Sonata No. 3 in F♯ minor Op. 23","nat":"Russian","era":"Modern","focus":["Expressive tone","Modern harmony","Musical expression"]},
  {"l":"A","c":"VINE, C.","t":"Sonata No. 1 (Chester)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"A","c":"VINE, C.","t":"Sonata No. 3 (Chester)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"A","c":"WESTLAKE, N.","t":"Piano Sonata No. 2 (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},

  // LIST B — Contrapuntal Works
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in C♯ major BWV 848 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in C♯ minor BWV 849 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in E♭ major BWV 852 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in E♭ minor BWV 853 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in F minor BWV 857 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in E♭ major BWV 865 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in D♭ major BWV 874 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in F major BWV 880 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in F♯ major BWV 882 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in F♯ minor BWV 883 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in G minor BWV 885 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in A♭ major BWV 886 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in G♯ minor BWV 887 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in B♭ minor BWV 891 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in B major BWV 892 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Chromatic Fantasia and Fugue BWV 903","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Fantasia and Fugue in A minor BWV 944","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Toccata in C minor BWV 911","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Toccata in D♯ major BWV 912","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Toccata in G major BWV 916","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BUSONI, F.","t":"Prelude in C major and Fugue in C minor Op. 5","nat":"Italian","era":"Romantic","focus":["Contrapuntal texture","Dynamic shaping","Musical expression"]},
  {"l":"B","c":"MENDELSSOHN, F.","t":"Prelude and Fugue in E minor No. 1 from Six Preludes and Fugues Op. 35","nat":"German","era":"Romantic","focus":["Contrapuntal texture","Expressive tone","Dynamic shaping"]},
  {"l":"B","c":"MENOTTI, G.","t":"Ricercare and Toccata on a Theme from 'The Old Maid and the Thief'","nat":"American","era":"Modern","focus":["Contrapuntal texture","Modern harmony","Musical expression"]},
  {"l":"B","c":"RAVEL, M.","t":"Prélude No. 1 and Fugue No. 2 from Le tombeau de Couperin","nat":"French","era":"Modern","focus":["Impressionist style","Contrapuntal texture","Musical expression"]},
  {"l":"B","c":"SCHOENBERG, A.","t":"Präludium and Gavotte from Suite Op. 25","nat":"Austrian","era":"Contemporary","focus":["Contemporary idiom","Contrapuntal texture","Musical expression"]},
  {"l":"B","c":"SHOSTAKOVICH, D.","t":"Prelude and Fugue in G major No. 3 from 24 Preludes and Fugues Op. 87","nat":"Russian","era":"Modern","focus":["Contrapuntal texture","Modern harmony","Rhythmic precision"]},
  {"l":"B","c":"SHOSTAKOVICH, D.","t":"Prelude and Fugue in B minor No. 6 from 24 Preludes and Fugues Op. 87","nat":"Russian","era":"Modern","focus":["Contrapuntal texture","Modern harmony","Rhythmic precision"]},
  {"l":"B","c":"SHOSTAKOVICH, D.","t":"Prelude and Fugue in D♭ major No. 15 from 24 Preludes and Fugues Op. 87","nat":"Russian","era":"Modern","focus":["Contrapuntal texture","Modern harmony","Rhythmic precision"]},
  {"l":"B","c":"SHOSTAKOVICH, D.","t":"Prelude and Fugue in D minor No. 24 from 24 Preludes and Fugues Op. 87","nat":"Russian","era":"Modern","focus":["Contrapuntal texture","Modern harmony","Rhythmic precision"]},

  // LIST C — Romantic/Modern Virtuoso Works
  {"l":"C","c":"BRAHMS, J.","t":"Capriccio in B minor No. 2 from Klavierstücke Op. 76","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"BRAHMS, J.","t":"Rhapsody in B minor No. 1 from Two Rhapsodies Op. 79","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"BRAHMS, J.","t":"Capriccio in G minor No. 3 from Fantasien Op. 116","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"BRAHMS, J.","t":"Intermezzo in E minor No. 6 from Klavierstücke Op. 118","nat":"German","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Andante spianato and Grand Polonaise brillante Op. 22","nat":"Polish","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Allegro de concert Op. 46 / CT 1","nat":"Polish","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"CHOPIN, F.","t":"Ballade No. 1 in G minor Op. 23 / CT 2","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Ballade No. 2 in F major Op. 38 / CT 3","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Ballade No. 3 in A♭ major Op. 47 / CT 4","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Ballade No. 4 in F minor Op. 52 / CT 5","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Barcarolle in F♯ major Op. 60 / CT 6","nat":"Polish","era":"Romantic","focus":["Expressive tone","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"CHOPIN, F.","t":"Any two contrasting Etudes from Op. 10 and/or Op. 25","nat":"Polish","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Fantasy in F minor Op. 49 / CT 42","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Mazurkas Op. 59 / CT 86–88","nat":"Polish","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Nocturne in D♭ major Op. 27 No. 2 / CT 115","nat":"Polish","era":"Romantic","focus":["Expressive tone","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"CHOPIN, F.","t":"Nocturne in B major Op. 62 No. 1 / CT 124","nat":"Polish","era":"Romantic","focus":["Expressive tone","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"CHOPIN, F.","t":"Polonaise in A♭ major Op. 53 / CT 155","nat":"Polish","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Rondo with Introduction Op. 16 / CT 195","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Scherzo No. 1 in B minor Op. 20 / CT 197","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Scherzo No. 2 in B♭ minor Op. 31 / CT 198","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Scherzo No. 3 in C♯ minor Op. 39 / CT 199","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Scherzo No. 4 in E major Op. 54 / CT 200","nat":"Polish","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Waltz in E♭ major Op. 18 / CT 207","nat":"Polish","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Waltz in A♭ major Op. 42 / CT 211","nat":"Polish","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Variations brillantes in B♭ major Op. 12 / CT 226","nat":"Polish","era":"Romantic","focus":["Expressive tone","Variation technique","Dynamic shaping"]},
  {"l":"C","c":"FAURÉ, G.","t":"Valse-caprice No. 1 in A major Op. 30","nat":"French","era":"Romantic","focus":["Expressive tone","Dance character","Lyrical phrasing"]},
  {"l":"C","c":"GRANADOS, E.","t":"Los requiebros No. 1 from Goyescas Book 1","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Dance character","Musical expression"]},
  {"l":"C","c":"GRANADOS, E.","t":"Coloquio en la reja No. 2 from Goyescas Book 1","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Musical expression"]},
  {"l":"C","c":"GRANADOS, E.","t":"El fandango de candil No. 3 from Goyescas Book 1","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Dance character","Musical expression"]},
  {"l":"C","c":"GRANADOS, E.","t":"Quejas, o La maja y el ruiseñor No. 4 from Goyescas Book 1","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Singing tone","Musical expression"]},
  {"l":"C","c":"GRANADOS, E.","t":"El amor y la muerte No. 5 from Goyescas Book 2","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"GRANADOS, E.","t":"Epílogo No. 6 from Goyescas Book 2","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Musical expression"]},
  {"l":"C","c":"GRANADOS, E.","t":"Allegro di concierto","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"LISZT, F.","t":"Au bord d'une source No. 4 from Années de pèlerinage, Première année S 160","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"LISZT, F.","t":"Ballade No. 2 in B minor S 171","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"C","c":"LISZT, F.","t":"Hungarian Rhapsody No. 12 in C♯ minor L A132/12","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Rhythmic precision","Dynamic shaping"]},
  {"l":"C","c":"LISZT, F.","t":"Un sospiro No. 3 from Trois etudes de concert S 144","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"LISZT, F.","t":"St François de Paule marchant sur les flots No. 2 from Deux légendes S 175","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"LISZT, F.","t":"Ricordanza No. 9 from Etudes d'exécution transcendante S 139","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"LISZT, F.","t":"Etude in E♭ major No. 2 from Grandes études de Paganini S 141","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF, S.","t":"Any two contrasting Préludes from Op. 23 and/or Op. 32","nat":"Russian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF, S.","t":"Etude-tableau (Moderato) in D minor No. 5 from Etudes-tableaux Op. 33","nat":"Russian","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF, S.","t":"Etude-tableau (Allegro con fuoco) in E♭ major No. 7 from Etudes-tableaux Op. 33","nat":"Russian","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF, S.","t":"Etude-tableau (Allegro agitato) in C minor No. 1 from Etudes-tableaux Op. 39","nat":"Russian","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF, S.","t":"Etude-tableau (Lento assai) in A minor No. 2 from Etudes-tableaux Op. 39","nat":"Russian","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF, S.","t":"Etude-tableau (Allegro) in A minor No. 6 from Etudes-tableaux Op. 39","nat":"Russian","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"SCHUMANN, C.","t":"Variationen über ein Thema von Robert Schumann Op. 20","nat":"German","era":"Romantic","focus":["Expressive tone","Variation technique","Dynamic shaping"]},
  {"l":"C","c":"SCHUMANN, R.","t":"In der Nacht No. 5 from Fantasiestücke Op. 12","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"SCHUMANN, R.","t":"Traumes Wirren No. 7 from Fantasiestücke Op. 12","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"TCHAIKOVSKY, P.","t":"Dumka: Russian Rustic Scene Op. 59","nat":"Russian","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"VERDI, G. arr. LISZT, F.","t":"Rigoletto: paraphrase de concert S 434","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},

  // LIST D — Australian & Contemporary / 20th-Century Works
  {"l":"D","c":"AGNEW, R.","t":"Etude (Collected Edited Piano Works Vol. IV – Wirripang)","nat":"Australian","era":"Modern","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"ALBÉNIZ","t":"Triana No. 3 from Iberia Book 2","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Dance character","Musical expression"]},
  {"l":"D","c":"ALBÉNIZ","t":"El Albaicín No. 1 from Iberia Book 3","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Modern harmony","Musical expression"]},
  {"l":"D","c":"BARBER, S.","t":"Excursion No. 1 from Excursions Op. 20","nat":"American","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"BARBER, S.","t":"Excursion No. 4 from Excursions Op. 20","nat":"American","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"BARBER, S.","t":"Nocturne Op. 33","nat":"American","era":"Contemporary","focus":["Contemporary idiom","Singing tone","Musical expression"]},
  {"l":"D","c":"BARBER, S.","t":"Ballade Op. 46","nat":"American","era":"Contemporary","focus":["Contemporary idiom","Expressive tone","Musical expression"]},
  {"l":"D","c":"BARTÓK, B.","t":"Tizenöt magyar parasztdal [Fifteen Hungarian Peasant Songs] BB 79","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision","Modern harmony","Musical expression"]},
  {"l":"D","c":"BENNETT, R.R.","t":"Tango after Syrinx","nat":"English","era":"Contemporary","focus":["Contemporary idiom","Dance character","Musical expression"]},
  {"l":"D","c":"BERG, A.","t":"Sonata Op. 1","nat":"Austrian","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"BERNSTEIN, L.","t":"Touches","nat":"American","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"BOYD, B.","t":"Kabarli Meditation (Dawn) (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"BOWEN, Y.","t":"Toccata Op. 155","nat":"English","era":"Modern","focus":["Rhythmic precision","Modern harmony","Musical expression"]},
  {"l":"D","c":"CARMICHAEL, H.","t":"Maurice Ravel No. 4 from Hommages (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"CARMICHAEL, H.","t":"Toccata (3rd movt) from Sonatine (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Toccata No. 3 from Pour le piano L 95","nat":"French","era":"Modern","focus":["Impressionist style","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Pagodes No. 1 from Estampes L 100","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Jardins sous la pluie No. 3 from Estampes L 100","nat":"French","era":"Modern","focus":["Impressionist style","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"L'isle joyeuse L 106","nat":"French","era":"Modern","focus":["Impressionist style","Dynamic shaping","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Reflets dans l'eau No. 1 from Images 1ère série L 110","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Hommage à Rameau No. 2 from Images 1ère série L 110","nat":"French","era":"Modern","focus":["Impressionist style","Expressive tone","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Cloches à travers les feuilles No. 1 from Images 2ème série L 111","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Poissons d'or No. 3 from Images 2ème série L 111","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Feux d'artifice No. 12 from Préludes Book 2 L 123","nat":"French","era":"Modern","focus":["Impressionist style","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Pour les cinq doigts No. 1 from Etudes L 136","nat":"French","era":"Modern","focus":["Impressionist style","Finger independence","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Pour les sixtes No. 4 from Etudes L 136","nat":"French","era":"Modern","focus":["Impressionist style","Finger independence","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Pour les octaves No. 5 from Etudes L 136","nat":"French","era":"Modern","focus":["Impressionist style","Finger independence","Musical expression"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Pour les arpèges composés No. 11 from Etudes L 136","nat":"French","era":"Modern","focus":["Impressionist style","Finger independence","Musical expression"]},
  {"l":"D","c":"FALLA, M. de","t":"Aragonesa No. 1 from 4 pièces espagnoles","nat":"Spanish","era":"Modern","focus":["Modern harmony","Dance character","Musical expression"]},
  {"l":"D","c":"FALLA, M. de","t":"Cubana No. 2 from 4 pièces espagnoles","nat":"Spanish","era":"Modern","focus":["Rhythmic precision","Dance character","Musical expression"]},
  {"l":"D","c":"FALLA, M. de","t":"Fantasia baetica","nat":"Spanish","era":"Modern","focus":["Modern harmony","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"GINASTERA, A.","t":"Danza del gaucho matrero No. 3 from Danzas argentinas Op. 2","nat":"Argentine","era":"Modern","focus":["Rhythmic precision","Dance character","Musical expression"]},
  {"l":"D","c":"GINASTERA, A.","t":"Piano Sonata No. 3 in one movement Op. 55","nat":"Argentine","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"GINASTERA, A.","t":"Suite de danzas criollas Op. 15","nat":"Argentine","era":"Modern","focus":["Rhythmic precision","Dance character","Musical expression"]},
  {"l":"D","c":"GRAINGER, P.","t":"The Merry King","nat":"Australian","era":"Modern","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"GRAINGER, P.","t":"Colonial Song","nat":"Australian","era":"Modern","focus":["Expressive tone","Australian character","Musical expression"]},
  {"l":"D","c":"GRAINGER, P.","t":"In Dahomey (Cakewalk Smasher)","nat":"Australian","era":"Modern","focus":["Rhythmic precision","Dance character","Musical expression"]},
  {"l":"D","c":"GRIFFES, C.","t":"The Fountain of the Acqua Paola No. 3 from Roman Sketches Op. 7","nat":"American","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"HARVEY, M.","t":"Pink Nautilus (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"HUMBLE, K.","t":"Eight Bagatelles (Astra)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"HUMBLE, K.","t":"Sonata No. 3 (Astra)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"HYDE, M.","t":"Valley of Rocks (Wirripang)","nat":"Australian","era":"Modern","focus":["Expressive tone","Australian character","Musical expression"]},
  {"l":"D","c":"HYDE, M.","t":"Brownhill Creek in Spring (Wirripang)","nat":"Australian","era":"Modern","focus":["Expressive tone","Australian character","Musical expression"]},
  {"l":"D","c":"ISAACS, M.","t":"Theme and Variations: on 'The Snow it Melts the Soonest' (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Variation technique","Musical expression"]},
  {"l":"D","c":"JANÁČEK, L.","t":"1.X.1905 ('Sonata') VIII/19","nat":"Czech","era":"Modern","focus":["Modern harmony","Expressive tone","Musical expression"]},
  {"l":"D","c":"KAPUSTIN, N.","t":"Prelude No. 1 from 8 Concert Studies Op. 40","nat":"Russian","era":"Contemporary","focus":["Contemporary idiom","Jazz/Pop style","Musical expression"]},
  {"l":"D","c":"KAPUSTIN, N.","t":"Finale No. 8 from 8 Concert Studies Op. 40","nat":"Russian","era":"Contemporary","focus":["Contemporary idiom","Jazz/Pop style","Musical expression"]},
  {"l":"D","c":"KERRY, G.","t":"Figured in the Drift of Stars (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"LIGETI, G.","t":"Arc-en-ciel No. 5 from Etudes Book 1","nat":"Hungarian","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MESSIAEN, O.","t":"Regard de la Vierge No. 4 from Vingt regards sur l'enfant Jésus I/27","nat":"French","era":"Modern","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MESSIAEN, O.","t":"Première communion de la Vierge No. 11 from Vingt regards sur l'enfant Jésus I/27","nat":"French","era":"Modern","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MESSIAEN, O.","t":"Noël No. 13 from Vingt regards sur l'enfant Jésus I/27","nat":"French","era":"Modern","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MESSIAEN, O.","t":"Regard des anges No. 14 from Vingt regards sur l'enfant Jésus I/27","nat":"French","era":"Modern","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MESSIAEN, O.","t":"Je dors, mais mon cœur veille No. 19 from Vingt regards sur l'enfant Jésus I/27","nat":"French","era":"Modern","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MESSIAEN, O.","t":"Ile de feu I No. 1 from Quatre études de rythme I/32","nat":"French","era":"Modern","focus":["Contemporary idiom","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"MOREL, F.","t":"Etude de sonorité No. 2 from 2 études de sonorité","nat":"Canadian","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MUCZYNSKI, R.","t":"Toccata Op. 15","nat":"American","era":"Contemporary","focus":["Contemporary idiom","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"PERTOUT, A.","t":"L'architecture du cosmos (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"POULENC, F.","t":"Caprice italien No. 3 from Napoli","nat":"French","era":"Modern","focus":["Modern harmony","Character contrast","Musical expression"]},
  {"l":"D","c":"POULENC, F.","t":"Mélancolie","nat":"French","era":"Modern","focus":["Expressive tone","Modern harmony","Musical expression"]},
  {"l":"D","c":"PROKOFIEV, S.","t":"Sonata No. 3 in A minor Op. 28","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Formal structure","Modern harmony"]},
  {"l":"D","c":"PROKOFIEV, S.","t":"Sarcasms Op. 17 [complete]","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Modern harmony","Character contrast"]},
  {"l":"D","c":"PROKOFIEV, S.","t":"Toccata Op. 11","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Finger independence","Musical expression"]},
  {"l":"D","c":"RAVEL, M.","t":"Une barque sur l'ocean No. 3 from Miroirs","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"RAVEL, M.","t":"Alborada del gracioso No. 4 from Miroirs","nat":"French","era":"Modern","focus":["Impressionist style","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"RAVEL, M.","t":"Jeux d'eau","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"RAVEL, M.","t":"Toccata No. 6 from Le tombeau de Couperin","nat":"French","era":"Modern","focus":["Impressionist style","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"SANCAN, P.","t":"Mouvement (Durand)","nat":"French","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"SCHOENBERG, A.","t":"Mäßige No. 1 from Drei Klavierstücke Op. 11","nat":"Austrian","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"SCHOENBERG, A.","t":"Mäßige No. 2 from Drei Klavierstücke Op. 11","nat":"Austrian","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"SCHOENBERG, A.","t":"Bewegte No. 3 from Drei Klavierstücke Op. 11","nat":"Austrian","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"SCHULTZ, H.","t":"Sleepers Wake – Karalananga (Wirripang)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"SCULTHORPE, P.","t":"Mountains (Faber)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"SEIBER, M.","t":"Scherzando capriccioso (Schott)","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision","Modern harmony","Musical expression"]},
  {"l":"D","c":"SHCHEDRIN, R.","t":"Basso ostinato from Two Polyphonic Pieces (1961)","nat":"Russian","era":"Contemporary","focus":["Contemporary idiom","Contrapuntal texture","Musical expression"]},
  {"l":"D","c":"SCRIABIN, A.","t":"Patetico No. 12 from Douze études Op. 8","nat":"Russian","era":"Modern","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"D","c":"SCRIABIN, A.","t":"Sonata No. 5 Op. 53","nat":"Russian","era":"Modern","focus":["Expressive tone","Modern harmony","Musical expression"]},
  {"l":"D","c":"SCRIABIN, A.","t":"Poème-nocturne Op. 61","nat":"Russian","era":"Modern","focus":["Expressive tone","Modern harmony","Musical expression"]},
  {"l":"D","c":"SCRIABIN, A.","t":"Sonata No. 7 ('White Mass') Op. 64","nat":"Russian","era":"Modern","focus":["Expressive tone","Modern harmony","Musical expression"]},
  {"l":"D","c":"SMALLEY, R.","t":"Variations on a Theme of Chopin (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Variation technique","Musical expression"]},
  {"l":"D","c":"STRAUSS, R., arr. GRAINGER","t":"Ramble on the Love-Duet from Der Rosenkavalier","nat":"German","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Musical expression"]},
  {"l":"D","c":"STRAVINSKY, I.","t":"Danse russe from Three Movements from 'Petrushka'","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Dance character","Modern harmony"]},
  {"l":"D","c":"STRAVINSKY, I.","t":"Chez Petrouchka from Three Movements from 'Petrushka'","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Modern harmony","Musical expression"]},
  {"l":"D","c":"STRAVINSKY, I.","t":"La semaine grasse from Three Movements from 'Petrushka'","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Dance character","Modern harmony"]},
  {"l":"D","c":"STRAVINSKY, I.","t":"Circus Polka","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Dance character","Modern harmony"]},
  {"l":"D","c":"TERRY, J.","t":"Paradox I (Wirripang)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"VINE, C.","t":"Toccatissimo (Faber)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"WEBERN, A.","t":"Variations Op. 27","nat":"Austrian","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"WILCHER, P.","t":"Wind Chimes (Wirripang)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"YU, J.","t":"Impromptu Op. 9","nat":"Chinese-Australian","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"YU, J.","t":"China Rhapsody (AMC)","nat":"Chinese-Australian","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
];
