// ABRSM Piano 2025 & 2026 — G3
// Total: 45 pieces  A:15 B:16 C:14
// Generated from official ABRSM Piano 2025 & 2026 Syllabus PDF

const DATA_ABRSM_G3 = [
  // LIST A — 15 pieces
{"l":"A","c":"KÖHLER, L.","t":"Allegro moderato (1st movt from Sonatina in G, Op. 300 No. 1)","nat":"German","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"MOZART","t":"Allegro in F (from London Sketchbook, K. 15a)","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"PROUDLER, Victoria","t":"Tarantella Twist (from Piano Grades Are Go!, Grades 2–3)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Dance character", "Musical expression"]},
{"l":"A","c":"ANDRÉE","t":"Allegro moderato (No. 3 from Fem smärre tonbilder, Op. 14)","nat":"Swedish","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"BAKER, Sarah","t":"Shadows (from Night Time Impressions) Sarah","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"A","c":"HASLINGER","t":"2nd movt (from Sonatina in C) P. P.","nat":"International","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"A","c":"HEDGES, A.","t":"Hornpipe Rondo A.","nat":"International","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"A","c":"HOLST, I.","t":"Toccata","nat":"International","era":"Modern","focus":["Rhythmic precision", "Contrapuntal texture", "Character contrast"]},
{"l":"A","c":"MOZART, L.","t":"Angloise (from Notebook for Wolfgang) L.","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Hand coordination", "Formal structure"]},
{"l":"A","c":"MOZART","t":"Allegro in B-, K. 3 Mozart: Essential","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"NEUGASIMOV, Vitalij","t":"Moody Gigue (from Piano Sketches, Book 1)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"A","c":"PROKOFIEV","t":"Gavotte (from Classical Symphony, Op. 25), arr. Agay","nat":"Russian","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"A","c":"REINECKE","t":"Vivace (4th movt from Sonatina in A minor, Reinecke: Op. 136 No. 4) (Breitkopf Sonatinas)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"A","c":"SCHUMANN","t":"Wilder Reiter (The Wild Horseman) (No. 8 from Album für die Jugend, Op. 68)","nat":"German","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"A","c":"SEIBER","t":"Jazz Etudiette (from Easy Dances II)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
  // LIST B — 16 pieces
{"l":"B","c":"BARTÓK","t":"Where is love? (from Oliver!)","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"BONIS, Mel","t":"Douce amis (from Album pour les tout-petits, Op. 26)","nat":"French","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"KIMURA, Youmi","t":"Always with Me (from Spirited Away)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"ALEXANDER, Dennis","t":"Autumn Serenade","nat":"American","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"B","c":"BACH, J.S.","t":"Arioso","nat":"German","era":"Baroque","focus":["Baroque style", "Singing tone", "Keyboard clarity"]},
{"l":"B","c":"BARTÓK","t":"Andante (No. 2 from For Children, Vol. 2) Bartók","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"BULLARD, Janet & Alan","t":"Thames Sunrise Janet","nat":"International","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"CARROLL, W.","t":"Spraymist (No. 3 from In Southern Seas) W.","nat":"English","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"GURLITT","t":"Song, Op. 172 No. 1 More","nat":"German","era":"Classical","focus":["Classical phrasing", "Singing tone", "Formal structure"]},
{"l":"B","c":"HARRIS, Paul","t":"Indigo (No. 6 from Rainbow) Paul","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"HOFMANN, H.","t":"Melodie (No. 5 from Skizzen, Op. 77)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"MENDELSSOHN","t":"Romance","nat":"International","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"B","c":"MITCHELL, Joni","t":"Both Sides Now","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"TCHAIKOVSKY","t":"Chanson italienne (No. 15 from Album pour enfants, Op. 39)","nat":"Russian","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"B","c":"TRAD. IRISH","t":"She Moved Through the Fair","nat":"Irish","era":"Contemporary","focus":["Contemporary idiom", "Singing tone", "Musical expression"]},
{"l":"B","c":"TRAD. JAPANESE","t":"Sakura","nat":"Japanese","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
  // LIST C — 15 pieces
{"l":"C","c":"BARTÓK","t":"Allegretto (No. 3 from For Children, Vol. 2)","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"POTTLE, Henson &","t":"The Muppet Show Theme","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"RAJASEKAR, Shruthi","t":"The Quiet of the Night","nat":"Indian","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"AGAY","t":"Little Rhapsody on Hungarian Themes","nat":"Hungarian-American","era":"Contemporary","focus":["Contemporary idiom", "Singing tone", "Musical expression"]},
{"l":"C","c":"GORANSON, M. Bober & G.","t":"Rushing River Melody (FJH)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"C","c":"CAPERS, Valerie","t":"Ella Scats the Little Lamb (No. 1 from Portraits Valerie in Jazz)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
{"l":"C","c":"CARSE","t":"Csardas Carse","nat":"English","era":"Classical","focus":["Classical phrasing", "Hand coordination", "Formal structure"]},
{"l":"C","c":"CORNICK, Mike","t":"The Waltz of the Elephants (from Clever Cat Mike Goes on)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
,
{"l":"C","c":"HOFMANN, H.","t":"Waldvöglein (No. 15 from Skizzen, Op. 77)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"JOHN, Elton","t":"Can You Feel the Love Tonight? (from The Lion)","nat":"English","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"MERCER, H. Mancini & J.","t":"Moon River (from Breakfast at Tiffany’s), A","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"O’CONNELL, Billie Eilish & Finneas","t":"No Time to Die","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"SCOFIELD, John","t":"I’ll Take Les","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"TANAKA, Karen","t":"Northern Lights","nat":"Japanese","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
];
