// Trinity College London Piano — LTCL Diploma Repertoire
// 2026 edition | Open pool — 306 works
// Performance: 37–43 min performance
// Source: trinitycollege.com/resource?id=8546

const DATA_TRINITY_LTCL = [
  { "c": "ALBÉNIZ, I.", "t": "Iberia, any two contrasting pieces from books 1-4", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "ALBÉNIZ, I.", "t": "La Vega (from The Alhambra, Suite for Piano)", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "ALBÉNIZ, I.", "t": "Rapsodica Cubana, op. 66", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "ALKAN, C.-V.", "t": "Trois morceaux dans le genre pathétique, op. 15, no. 1: Aime-moi", "nat": "French", "era": "Romantic", "focus": ["Technical virtuosity", "Romantic expression", "Extended form"] },
  { "c": "ANDERSON, L.", "t": "Piano Etudes", "nat": "American", "era": "Contemporary", "focus": ["Contemporary etude", "Technical mastery", "Expressive phrasing"] },
  { "c": "AUERBACH, L.", "t": "24 Preludes, op. 41, no. 16 in B♭ minor", "nat": "Russian", "era": "Contemporary", "focus": ["Contemporary style", "Russian character", "Expressive phrasing"] },
  { "c": "BACH, J.S.", "t": "Aria variata alla maniera Italiana, BWV 989", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Capriccio in E, BWV 993", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Chromatic Fantasia & Fugue in D minor, BWV 903", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Concerto no. 3 in D minor, BWV 974 (after Marcello)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "English Suite no. 2 in A minor, BWV 807", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Partita no. 2 in C minor, BWV 826", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Partita no. 3 in A minor, BWV 827", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Partita no. 4 in D, BWV 828", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Partita no. 5 in G, BWV 829", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "The Well-Tempered Clavier book 1, any one or more of the following: - Prelude & Fugue in C# minor, BWV 849 - Prelude & Fugue in E♭, BWV 852 - Prelude & Fugue in E♭ minor, BWV 853 - Prelude & Fugue in G# minor, BWV 863 - Prelude & Fugue in B minor, BWV 869", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "The Well-Tempered Clavier book 2, any one or more of the following: - Prelude & Fugue in C#, BWV 872 - Prelude & Fugue in C# minor, BWV 873 - Prelude & Fugue in D# minor, BWV 877 - Prelude & Fugue in E minor, BWV 879 - Prelude & Fugue in G# minor, BWV 887 - Prelude & Fugue in B♭, BWV 890 - Prelude & Fugue in B♭ minor, BWV 891 - Prelude & Fugue in B, BWV 892 - Prelude & Fugue in B minor, BWV 893", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Toccata no. 1 in F# minor, BWV 910", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Toccata no. 2 in C minor, BWV 911", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Toccata no. 4 in D minor, BWV 913", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Toccata no. 6 in G minor, BWV 915", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Toccata no. 7 in G, BWV 916", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Toccata and Fugue in D minor, BWV 565 (both to be played)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Toccata in D minor (from The Alexander Siloti Collection)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BARBER, S.", "t": "Excursions, op. 20", "nat": "American", "era": "Modern", "focus": ["American Romantic style", "Lyrical expression", "Expressive phrasing"] },
  { "c": "BARBER, S.", "t": "Nocturne, op. 33", "nat": "American", "era": "Modern", "focus": ["American Romantic style", "Lyrical expression", "Expressive phrasing"] },
  { "c": "BARBER, S.", "t": "Souvenirs, op. 28, any three", "nat": "American", "era": "Modern", "focus": ["American Romantic style", "Lyrical expression", "Expressive phrasing"] },
  { "c": "BARTÓK, B.", "t": "Allegro Barbaro", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "BARTÓK, B.", "t": "3 Burlesques, op. 8c, Sz. 47", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "BARTÓK, B.", "t": "Out of Doors (Im Freien) (all 5 movts)", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "BARTÓK, B.", "t": "Two Romanian Dances, op. 8a, Sz. 43 Kalmus", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "BEACH, A.", "t": "Ballade in D♭, op. 6", "nat": "American", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "American style"] },
  { "c": "BEACH, A.", "t": "4 Sketches, op. 15, any two or more including no. 4", "nat": "American", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "American style"] },
  { "c": "BEETHOVEN, L.", "t": "Fantasia in G minor, op. 77", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in C, op. 2 no. 3", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in E♭, op. 7", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in D, op. 10 no. 3", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in B♭, op. 22", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in G, op. 31 no. 1", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in D minor, op. 31 no. 2 ‘Tempest’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in E♭, op. 31 no. 3 ‘Hunt’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in E♭, op. 81a ‘Les adieux’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BENNETT, R.R.", "t": "Sonata no. 1 in F minor, op. 13", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary technique", "Structural clarity"] },
  { "c": "BERG, A.", "t": "Sonata, op. 1", "nat": "Austrian", "era": "Modern", "focus": ["Expressionist style", "Atonal writing", "Romantic roots"] },
  { "c": "BERNSTEIN, L.", "t": "Touches: Chorale, 8 Variations and Coda", "nat": "American", "era": "Modern", "focus": ["American character", "Rhythmic vitality", "Jazz influence"] },
  { "c": "BOËLLMANN, L.", "t": "Sur la mer, op. 38", "nat": "French", "era": "Romantic", "focus": ["French character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "BORODIN, A.", "t": "Scherzo in A♭ (no. VIII from Petite Suite)", "nat": "Russian", "era": "Romantic", "focus": ["Russian character", "Romantic expression", "Colouristic writing"] },
  { "c": "BOULANGER, N.", "t": "Thème et variations Tonger", "nat": "French", "era": "Modern", "focus": ["French character", "Expressive phrasing", "Modern style"] },
  { "c": "BOWEN, Y.", "t": "Preludes, op. 102, any three", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Technical fluency"] },
  { "c": "BRAHMS, J.", "t": "Capriccio in B minor, op. 76 no. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Capriccio in C# minor, op. 76 no. 5", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Capriccio in C, op. 76 no. 8", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Capriccio in G minor, op. 116 no. 3", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Capriccio in D minor, op. 116 no. 7", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Etude no. 1 in F minor after Chopin’s op. 25 no. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Intermezzo in E♭ minor, op. 118 no. 6", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Rhapsodies, op. 79 (both to be played)", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Rhapsody, op. 119 no. 4", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Variations on a Theme by Robert Schumann, op. 9", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BUSONI, F.", "t": "Turandots Frauengemach (no. 4 from Elegies, BV 249)", "nat": "Italian", "era": "Modern", "focus": ["Transcription technique", "Virtuosic display", "Baroque transformation"] },
  { "c": "CASELLA, A.", "t": "Toccata, op. 6", "nat": "Italian", "era": "Modern", "focus": ["Italian character", "Modern harmony", "Neo-Classical style"] },
  { "c": "CHAMINADE, C.", "t": "Sonata in C minor, op. 21", "nat": "French", "era": "Romantic", "focus": ["French character", "Lyrical melody", "Salon style"] },
  { "c": "CHASINS, A.", "t": "3 Chinese Pieces, op. 5 (all 3)", "nat": "American", "era": "Modern", "focus": ["American style", "Chinese influence", "Atmospheric writing"] },
  { "c": "CHOPIN, F.", "t": "Ballades, any one of nos. 1, 2 or 4", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Barcarolle, op. 60", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Études, op. 10, any two contrasting", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Études, op. 25, any two contrasting", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Fantaisie in F minor, op. 49", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Introduction and Variations in E on a German Air, op. posth.", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in F, op. 15 no. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in C# minor, op. 27 no. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in D♭, op. 27 no. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in C minor, op. 48 no. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Polonaise in F# minor, op. 44", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Polonaise in A♭, op. 53", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Polonaise-fantasy in A♭, op. 61", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Rondo in C minor, op. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Any of the four Scherzi", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Variations brillantes on a theme from Hérold’s ‘Ludovic’, op. 12", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Romance from Piano Concerto no. 1 in E minor, op. 11", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CLEMENTI, M.", "t": "Sonata in G minor, op. 50 no. 3 ‘Didona abbandonata’", "nat": "Italian", "era": "Classical", "focus": ["Classical form", "Technical fluency", "Clear phrasing"] },
  { "c": "CONSTANTINESCU, P.", "t": "Joc Dobrogean – Toccata", "nat": "Romanian", "era": "Modern", "focus": ["Romanian character", "Rhythmic vitality", "Modern style"] },
  { "c": "COPLAND, A.", "t": "Sonata", "nat": "American", "era": "Modern", "focus": ["American character", "Rhythmic vitality", "Modern harmony"] },
  { "c": "COULTHARD, J.", "t": "Four Etudes for Piano", "nat": "Canadian", "era": "Modern", "focus": ["Canadian character", "Modern style", "Technical mastery"] },
  { "c": "COULTHARD, J.", "t": "Image astrale", "nat": "Canadian", "era": "Modern", "focus": ["Canadian character", "Modern style", "Technical mastery"] },
  { "c": "CRUMB, G.", "t": "A Little Suite for Christmas, any three movts", "nat": "American", "era": "Contemporary", "focus": ["Extended techniques", "Atmospheric writing", "Contemporary style"] },
  { "c": "CUMMING, R.", "t": "24 Preludes for Solo Piano, any six or more", "nat": "Canadian", "era": "Contemporary", "focus": ["Canadian character", "Contemporary style", "Prelude texture"] },
  { "c": "CZERNY, C.", "t": "Variations on a Theme by Rode, ‘La Ricordanza’, op. 33", "nat": "Austrian", "era": "Classical", "focus": ["Technical etude", "Rapid figurations", "Even tone"] },
  { "c": "DEBUSSY, C.", "t": "Estampes, any one or more", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "Images (book 1 or 2), any one or more movts", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "L’isle joyeuse", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "Masques", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "Preludes for Piano book 1, any one or more of the following: - Le vent dans la plaine (no. 3) - Ce qu’a vu le vent d’ouest (no. 7) - La danse de Puck (no. 11)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "Preludes for Piano book 2, any one or more of the following: - Les fées sont d’exquises danseuses (no. 4) - La terrasse des audiences (no. 7) - Ondine (no. 8) - Les tierces alternées (no. 11)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "Toccata (from Pour le piano)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DECAUX, A.", "t": "Clairs de lune, La mer (no. 4) plus at least one more from nos. 1, 2, 3 B-Note", "nat": "French", "era": "Modern", "focus": ["French Impressionism", "Atmospheric writing", "Modern harmony"] },
  { "c": "DELLO JOIO, N.", "t": "Two Concert Études", "nat": "American", "era": "Modern", "focus": ["American style", "Rhythmic vitality", "Neo-Classical writing"] },
  { "c": "DIEMER, E.L.", "t": "Toccata Arsis Press", "nat": "American", "era": "Contemporary", "focus": ["American character", "Contemporary style", "Rhythmic vitality"] },
  { "c": "DOHNÁNYI, E.", "t": "4 Rhapsodies, op. 11, any one", "nat": "Hungarian", "era": "Romantic", "focus": ["Romantic virtuosity", "Hungarian character", "Technical brilliance"] },
  { "c": "DOHNÁNYI, E.", "t": "6 Concert Etudes, op. 28, any one or more Masters", "nat": "Hungarian", "era": "Romantic", "focus": ["Romantic virtuosity", "Hungarian character", "Technical brilliance"] },
  { "c": "EMMANUEL, M.", "t": "Sonatine no. 5, Alla francese, op. 22 (all 6 movts) Lemoine", "nat": "French", "era": "Modern", "focus": ["French character", "Modal harmony", "Modern style"] },
  { "c": "ENGLUND, E.", "t": "Introduction and Toccata Fennica Gehrman", "nat": "Finnish", "era": "Modern", "focus": ["Finnish character", "Modern style", "Technical clarity"] },
  { "c": "FALLA, M. de", "t": "Piezas españolas, any two or more", "nat": "Spanish", "era": "Modern", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "FALLA, M. de", "t": "Spanish Dance no. 1 (from La vida breve)", "nat": "Spanish", "era": "Modern", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "FARRENC, L.", "t": "Air russe varié, op. 17", "nat": "French", "era": "Classical", "focus": ["French character", "Classical style", "Technical fluency"] },
  { "c": "FAURÉ, G.", "t": "Barcarolle no. 5 in F# minor, op. 66", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Impromptu in A♭, op. 34 no. 3", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Nocturne no. 2, op. 33 or Nocturne no. 5, op. 37", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Nocturne in D♭, op. 63", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Nocturne in B minor, op. 119", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Valse Caprice in A, op. 30 no. 1", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Dolly Suite for solo piano (all 6 movts) Hamelle", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Après un rêve and Nell (from Favourite Melodies arranged by Grainger)", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FERGUSON, H.", "t": "Piano Sonata in F minor, op. 8", "nat": "Irish", "era": "Modern", "focus": ["Dramatic expression", "Irish character", "Structural integrity"] },
  { "c": "FIŠER, L.", "t": "Sonata no. 1", "nat": "Czech", "era": "Modern", "focus": ["Contemporary technique", "Czech character", "Modern harmony"] },
  { "c": "FRICKER, P.R.", "t": "Studies, op. 38, nos. 2 and 4", "nat": "English", "era": "Modern", "focus": ["English character", "Modern technique", "Technical clarity"] },
  { "c": "GERSHWIN, G.", "t": "Rhapsody in Blue (original piano solo version)", "nat": "American", "era": "Modern", "focus": ["Jazz influence", "American character", "Rhythmic vitality"] },
  { "c": "GINASTERA, A.", "t": "12 American Preludes, any four or more contrasting", "nat": "Argentine", "era": "Modern", "focus": ["Argentine character", "Rhythmic vitality", "Modern technique"] },
  { "c": "GINASTERA, A.", "t": "Danzas Argentinas, op. 2", "nat": "Argentine", "era": "Modern", "focus": ["Argentine character", "Rhythmic vitality", "Modern technique"] },
  { "c": "GINASTERA, A.", "t": "Suite de danzas criollas, op. 15 (all 5 movts)", "nat": "Argentine", "era": "Modern", "focus": ["Argentine character", "Rhythmic vitality", "Modern technique"] },
  { "c": "GLAZUNOV, A.", "t": "Theme and Variations, op. 72", "nat": "Russian", "era": "Romantic", "focus": ["Russian character", "Romantic expression", "Technical brilliance"] },
  { "c": "GNATTALI, R.", "t": "Manhosamente Grupo Editorial Todamérica", "nat": "Brazilian", "era": "Modern", "focus": ["Brazilian character", "Jazz influence", "Expressive phrasing"] },
  { "c": "GODOWSKY, L.", "t": "Java Suite, any two or more movts", "nat": "Polish", "era": "Romantic", "focus": ["Transcription mastery", "Technical virtuosity", "Romantic style"] },
  { "c": "GÓRECKI, H.", "t": "Four Preludes, op. 1", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Modern style", "Stark expression"] },
  { "c": "GÓRECKI, H.", "t": "Sonata, op. 6", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Modern style", "Stark expression"] },
  { "c": "GOTTSCHALK, L.", "t": "Souvenir de Porto Rico (Marche des Gibaros), op. 31 or Souvenirs d’Andalousie, Caprice de concert sur la caña, op. 22", "nat": "American", "era": "Romantic", "focus": ["American character", "Creole influence", "Romantic virtuosity"] },
  { "c": "GOTTSCHALK, L.", "t": "The Banjo, op. 15", "nat": "American", "era": "Romantic", "focus": ["American character", "Creole influence", "Romantic virtuosity"] },
  { "c": "GRAINGER, P.", "t": "To a Nordic Princess", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Folk elements", "Energetic playing"] },
  { "c": "GRANADOS, E.", "t": "Allegro de concierto", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "GRANADOS, E.", "t": "Goyescas, any one or more", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "GRIEG, E.", "t": "Ballade in G minor, op. 24", "nat": "Norwegian", "era": "Romantic", "focus": ["Norwegian character", "Romantic expression", "Folk elements"] },
  { "c": "GRIEG, E.", "t": "Improvisations on 2 Norwegian Folk Songs, op. 29 (both)", "nat": "Norwegian", "era": "Romantic", "focus": ["Norwegian character", "Romantic expression", "Folk elements"] },
  { "c": "GRIFFES, C.", "t": "Roman Sketches, op. 7, The Fountain of the Acqua Paola (no. 3) plus one from nos. 1, 2, 4", "nat": "American", "era": "Modern", "focus": ["Impressionist colour", "American style", "Atmospheric writing"] },
  { "c": "HAMILTON, I.", "t": "September and October or November and December (from Months & Metamorphoses)", "nat": "Scottish", "era": "Modern", "focus": ["Scottish character", "Modern style", "Expressive phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in E♭, Hob XVI/45", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in C, Hob XVI/50", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in E♭, Hob XVI/52", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HINDEMITH, P.", "t": "Interludium and Fuga nona in B♭ (from Ludus Tonalis)", "nat": "German", "era": "Modern", "focus": ["Neo-Classical style", "Linear texture", "Modern harmony"] },
  { "c": "HINDEMITH, P.", "t": "Interludium and Fuga seconda in G (from Ludus Tonalis)", "nat": "German", "era": "Modern", "focus": ["Neo-Classical style", "Linear texture", "Modern harmony"] },
  { "c": "HINDEMITH, P.", "t": "Sonata no. 2 in G", "nat": "German", "era": "Modern", "focus": ["Neo-Classical style", "Linear texture", "Modern harmony"] },
  { "c": "HINDEMITH, P.", "t": "Tanzstücke, op. 19 (all 4 movts)", "nat": "German", "era": "Modern", "focus": ["Neo-Classical style", "Linear texture", "Modern harmony"] },
  { "c": "HOLLAND, D.", "t": "Sonata for Piano (1952) EMI Australia", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Expressive phrasing", "Modern style"] },
  { "c": "HONEGGER, A.", "t": "3 Pièces (Prélude, Hommage à Ravel, Danse)", "nat": "Swiss", "era": "Modern", "focus": ["Modern harmony", "Rhythmic drive", "Neo-Classical style"] },
  { "c": "HUMMEL, J.N.", "t": "Sonata no. 3 in F minor, op. 20", "nat": "Austrian", "era": "Classical", "focus": ["Classical brilliance", "Technical fluency", "Elegant phrasing"] },
  { "c": "HYDE, M.", "t": "Brownhill Creek in Spring", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Impressionist colour", "Expressive phrasing"] },
  { "c": "IRELAND, J.", "t": "Amberley Wild Brooks", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "IRELAND, J.", "t": "April", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "IRELAND, J.", "t": "Chelsea Reach (from London Pieces)", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "IRELAND, J.", "t": "Ragamuffin", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "IRELAND, J.", "t": "Rhapsody", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "IRELAND, J.", "t": "Sarnia", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "ITUARTE, E.", "t": "Ecos de México, Capricho de Concierto Performer’s Edition", "nat": "Mexican", "era": "Romantic", "focus": ["Mexican character", "Romantic expression", "Virtuosic display"] },
  { "c": "JANÁČEK, L.", "t": "Sonata I/X/1905", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Folk elements", "Modern harmony"] },
  { "c": "JANÁČEK, L.", "t": "Zdenčiny Variace (Zdenka’s Variations)", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Folk elements", "Modern harmony"] },
  { "c": "JOHNSON, J.", "t": "Jazz Impromptu no. 1 Score Exchange", "nat": "American", "era": "Contemporary", "focus": ["Jazz influence", "American character", "Improvisatory style"] },
  { "c": "JONGEN, J.", "t": "Two Pieces, op. 33, Clair de lune (no. 1) and Soleil à midi (no. 2)", "nat": "Belgian", "era": "Romantic", "focus": ["Belgian character", "Romantic expression", "Impressionist colour"] },
  { "c": "KABALEVSKY, D.", "t": "Sonata no. 3 in F, op. 46", "nat": "Russian", "era": "Modern", "focus": ["Soviet style", "Rhythmic vitality", "Clear texture"] },
  { "c": "KALOMIRIS, M.", "t": "Five Preludes, any three or more Piano Rare Scores", "nat": "Greek", "era": "Modern", "focus": ["Greek character", "Modern style", "Romantic expression"] },
  { "c": "KAPRÁLOVÁ, V.", "t": "Grotesque Passacaglia Amos", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Modern style", "Expressive intensity"] },
  { "c": "KNUSSEN, O.", "t": "Prayer Bell Sketch", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary style", "Atmospheric writing"] },
  { "c": "KURTÁG, G.", "t": "Les adieux (from Játékok (Games) vol. VI)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Hungarian character", "Contemporary miniature", "Expressive intensity"] },
  { "c": "LECUONA, E.", "t": "Ante el Escorial (original version, not ossia) (from Lecuona Piano Music) Hal Leonard", "nat": "Cuban", "era": "Modern", "focus": ["Cuban character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "LEIGHTON, K.", "t": "Fantasia contrappuntistica Novello", "nat": "English", "era": "Modern", "focus": ["English character", "Modern harmony", "Contrapuntal mastery"] },
  { "c": "LEIGHTON, K.", "t": "Six Studies (Study Variations), op. 56, any one or more Novello", "nat": "English", "era": "Modern", "focus": ["English character", "Modern harmony", "Contrapuntal mastery"] },
  { "c": "LEIGHTON, K.", "t": "Study no. 4 and Study no. 5 (from Five Studies) Novello", "nat": "English", "era": "Modern", "focus": ["English character", "Modern harmony", "Contrapuntal mastery"] },
  { "c": "LIEBERMANN, L.", "t": "Nocturne no. 2, op. 31 or Nocturne no. 8, op. 85", "nat": "American", "era": "Contemporary", "focus": ["Contemporary style", "Lyrical expression", "Technical mastery"] },
  { "c": "LIGETI, G.", "t": "Capriccios 1 and 2", "nat": "Hungarian", "era": "Contemporary", "focus": ["Micropolyphony", "Contemporary technique", "Complex texture"] },
  { "c": "LIGETI, G.", "t": "Musica ricercata (1951–53), any four", "nat": "Hungarian", "era": "Contemporary", "focus": ["Micropolyphony", "Contemporary technique", "Complex texture"] },
  { "c": "LILBURN, D.", "t": "Sonata (1949) or Sonata (1956)", "nat": "New Zealand", "era": "Modern", "focus": ["New Zealand character", "Modern style", "Expressive phrasing"] },
  { "c": "LISZT, F.", "t": "Aux cyprès de la Villa d’Este, I or II (from Années de pèlerinage, 3rd year)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Ballade no. 2 in B minor", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Bénédiction de Dieu dans la solitude (no. 3 from Harmonies poétiques et religieuses, S173)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Chapelle de Guillaume Tell, Vallée d’Obermann or Les cloches de Genève (from Années de pèlerinage, 1st year)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Concert Studies, any one or more", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Douze études d’exécution transcendente, any one or more", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Hungarian Rhapsodies, any one or more", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Les jeux d’eaux à la Villa d’Este (from Années de pèlerinage, 3rd year)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Paganini Studies, any one or more", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Rhapsodie Espagnole", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Rigoletto, Concert Paraphrase", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Sonetto del Petrarca 104 (from Années de pèlerinage, 2nd year)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Either of the Two Légendes", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LOUIE, A.", "t": "Put On Your Running Shoes", "nat": "Canadian", "era": "Contemporary", "focus": ["Canadian character", "Contemporary style", "Atmospheric writing"] },
  { "c": "MACDOWELL, E.", "t": "Etude de Concert, op. 36", "nat": "American", "era": "Romantic", "focus": ["American character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "MATHIAS, W.", "t": "Toccata alla danza Allegro/OUP archive", "nat": "Welsh", "era": "Modern", "focus": ["Welsh character", "Modern style", "Technical clarity"] },
  { "c": "MATTHEWS, C.", "t": "Eleven Studies in Velocity, any four or more", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary technique", "Technical mastery"] },
  { "c": "MENDELSSOHN, F.", "t": "Andante and Rondo Capriccioso, op. 14", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "MENDELSSOHN, F.", "t": "Fantasy in F# minor, op. 28", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "MENDELSSOHN, F.", "t": "Prelude & Fugue in E minor, op. 35 no. 1", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "MENDELSSOHN, F.", "t": "Prelude & Fugue in B minor, op. 35 no. 3", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "MENDELSSOHN, F.", "t": "Songs Without Words, op. 38 no. 5 in A minor and/or op. 53 no. 6 in A", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "MENDELSSOHN, F.", "t": "Variations serieuses, op. 54", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "MESSIAEN, O.", "t": "La buse variable (no. XI from Catalogue d’oiseaux 7e livre) Leduc", "nat": "French", "era": "Modern", "focus": ["Colour and rhythm", "Spiritual expression", "Modern harmony"] },
  { "c": "MESSIAEN, O.", "t": "Préludes, any one or more from nos. 2, 3, 4, 5, 6, 8", "nat": "French", "era": "Modern", "focus": ["Colour and rhythm", "Spiritual expression", "Modern harmony"] },
  { "c": "MESSIAEN, O.", "t": "Vingt regards sur l’enfant-Jésus, any one from nos. 8, 11, 13, 14, 15, 16", "nat": "French", "era": "Modern", "focus": ["Colour and rhythm", "Spiritual expression", "Modern harmony"] },
  { "c": "MONTSALVATGE, X.", "t": "Sonatina pour Yvette", "nat": "Spanish", "era": "Modern", "focus": ["Spanish character", "Cuban influence", "Modern style"] },
  { "c": "MOSZKOWSKI, M.", "t": "Caprice Espagnol, op. 37", "nat": "Polish", "era": "Romantic", "focus": ["Romantic virtuosity", "Technical brilliance", "Dance character"] },
  { "c": "MOZART, W.A.", "t": "Rondo in A minor, K 511", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MOZART, W.A.", "t": "Sonata in A minor, K 310", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MOZART, W.A.", "t": "Sonata in D, K 576", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MUCZYNSKI, R.", "t": "Desperate Measures (Paganini Variations), op. 48", "nat": "American", "era": "Modern", "focus": ["American character", "Modern harmony", "Clear texture"] },
  { "c": "NOVÁK, V.", "t": "Songs of Winter Nights (Písně zimních nocí), op. 30, any two contrasting", "nat": "Czech", "era": "Romantic", "focus": ["Czech character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "PADEREWSKI, I.", "t": "Caprice-Waltz (no. 5 from Album de Mai, op. 10)", "nat": "Polish", "era": "Romantic", "focus": ["Polish character", "Romantic expression", "Pianistic idiom"] },
  { "c": "PALMGREN, S.", "t": "En route, op. 9", "nat": "Finnish", "era": "Romantic", "focus": ["Finnish character", "Impressionist colour", "Lyrical phrasing"] },
  { "c": "PANN, C.", "t": "The Cheese Grater (a mean two-step for piano)", "nat": "American", "era": "Contemporary", "focus": ["American character", "Contemporary style", "Rhythmic vitality"] },
  { "c": "PIAZZOLLA, A.", "t": "Suite para piano, op. 2 (all 3 movts)", "nat": "Argentine", "era": "Contemporary", "focus": ["Argentine tango", "Rhythmic vitality", "Expressive phrasing"] },
  { "c": "PICK-MANGIAGALLI, R.", "t": "Danse d’Olaf (no. 2 from Deux lunaires, op. 33)", "nat": "Italian", "era": "Modern", "focus": ["Italian character", "Dance style", "Colouristic writing"] },
  { "c": "PIERNÉ, G.", "t": "Etude de concert in C minor, op. 13 Leduc", "nat": "French", "era": "Romantic", "focus": ["French character", "Technical virtuosity", "Romantic style"] },
  { "c": "PONCE, M.", "t": "Ballada Mexicana Peermusic", "nat": "Mexican", "era": "Romantic", "focus": ["Mexican character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "PONCE, M.", "t": "Jarabe (no. 10 from Etudes de concert) Piano Rare Scores", "nat": "Mexican", "era": "Romantic", "focus": ["Mexican character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "POULENC, F.", "t": "15 Improvisations, at least four movts", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "POULENC, F.", "t": "Intermezzo in A♭", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "POULENC, F.", "t": "Mélancolie", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "POULENC, F.", "t": "Napoli suite (all 3 movts)", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "PRICE, F.", "t": "Fantasie nègre no. 1 in E minor (from Black Women Composers: A Century of Piano Music, 1893-1990)", "nat": "American", "era": "Modern", "focus": ["African-American character", "Romantic expression", "Spiritual influence"] },
  { "c": "PROKOFIEV, S.", "t": "Romeo & Juliet, op. 75, any two movts", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "PROKOFIEV, S.", "t": "Sarcasms, op. 17 Forberg", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "PROKOFIEV, S.", "t": "Sonata no. 1 in F minor, op. 1", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "PROKOFIEV, S.", "t": "Sonata no. 2 in D minor, op. 14", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "PROKOFIEV, S.", "t": "Sonata no. 3 in A minor, op. 28", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "PROKOFIEV, S.", "t": "Sonata no. 4 in C minor, op. 29", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "PROKOFIEV, S.", "t": "Sonata no. 5 in C, op. 38", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "PROKOFIEV, S.", "t": "Suggestion diabolique, op. 4 no. 4", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "PROKOFIEV, S.", "t": "Toccata, op. 11 Forberg", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "RACHMANINOFF, S.", "t": "Études-tableaux, op. 33, any two contrasting pieces", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RACHMANINOFF, S.", "t": "Études-tableaux, op. 39, any one or more", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RACHMANINOFF, S.", "t": "Morceaux de salon, op. 10, no. 5 or no. 7", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RACHMANINOFF, S.", "t": "Preludes, op. 23, any one or more from nos. 2, 4, 5, 9", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RACHMANINOFF, S.", "t": "Preludes, op. 32, any one or more from nos. 1, 2, 3, 4, 6, 8, 9, 11, 13", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RACHMANINOFF, S.", "t": "Six moments musicaux, op. 16, any one or more from nos. 1, 2, 4, 6", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RAUTAVAARA, E.", "t": "Passionale", "nat": "Finnish", "era": "Contemporary", "focus": ["Finnish character", "Contemporary style", "Atmospheric writing"] },
  { "c": "RAVEL, M.", "t": "Jeux d’eau", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "RAVEL, M.", "t": "Menuet antique", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "RAVEL, M.", "t": "Miroirs, any one or more", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "RAVEL, M.", "t": "Ondine (from Gaspard de la nuit)", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "RAVEL, M.", "t": "Sonatine", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "RAVEL, M.", "t": "Toccata (from Le tombeau de Couperin)", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "RESPIGHI, O.", "t": "Six Pieces for Piano, Studio (no. 5) Ludwig 239. Rimsky-Korsakov, transc. Rachmaninov The Flight of the Bumblebee", "nat": "Italian", "era": "Modern", "focus": ["Italian character", "Romantic expression", "Colouristic writing"] },
  { "c": "RITCHIE, J.", "t": "24 Preludes, any three or more contrasting", "nat": "New Zealand", "era": "Contemporary", "focus": ["New Zealand character", "Contemporary style", "Expressive phrasing"] },
  { "c": "RITCHIE, J.", "t": "Music for Tristan (from Caricatures)", "nat": "New Zealand", "era": "Contemporary", "focus": ["New Zealand character", "Contemporary style", "Expressive phrasing"] },
  { "c": "RODGERS, R.", "t": "My Favorite Things", "nat": "American", "era": "Modern", "focus": ["American character", "Jazz influence", "Lyrical melody"] },
  { "c": "RODGERS, R.", "t": "The Carousel Waltz", "nat": "American", "era": "Modern", "focus": ["American character", "Jazz influence", "Lyrical melody"] },
  { "c": "ROXBURGH, E.", "t": "Sonata", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary style", "Technical clarity"] },
  { "c": "RZEWSKI, F.", "t": "Down by the Riverside (from Squares & North American Ballads)", "nat": "American", "era": "Contemporary", "focus": ["Political expression", "Extended techniques", "Contemporary style"] },
  { "c": "RZEWSKI, F.", "t": "Piano Piece IV (from 4 Pieces)", "nat": "American", "era": "Contemporary", "focus": ["Political expression", "Extended techniques", "Contemporary style"] },
  { "c": "SAINT-SAËNS, C.", "t": "Allegro appassionato, op. 70", "nat": "French", "era": "Romantic", "focus": ["French character", "Technical brilliance", "Elegant phrasing"] },
  { "c": "SAINT-SAËNS, C.", "t": "Études, op. 52 or op. 111, any one or more", "nat": "French", "era": "Romantic", "focus": ["French character", "Technical brilliance", "Elegant phrasing"] },
  { "c": "SAINT-SAËNS, C.", "t": "Études for left hand alone, op. 135, any one or more", "nat": "French", "era": "Romantic", "focus": ["French character", "Technical brilliance", "Elegant phrasing"] },
  { "c": "SANCAN, P.", "t": "Toccata", "nat": "French", "era": "Modern", "focus": ["French character", "Technical virtuosity", "Modern style"] },
  { "c": "SAY, F.", "t": "Paganini Jazz (without final ‘extra’ variations)", "nat": "Turkish", "era": "Contemporary", "focus": ["Turkish character", "Jazz influence", "Virtuosic display"] },
  { "c": "SCARLATTI, D.", "t": "Two Sonatas in C minor, K 115 and K 116", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "SCARLATTI, D.", "t": "Sonata in B♭, K 544 and Sonata in B♭, K 545", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "SCARLATTI, D.", "t": "Sonata in G minor, K 426 and Sonata in G, K 427", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "SCHMIDT, H.", "t": "Sprint Echo North Music", "nat": "Canadian", "era": "Contemporary", "focus": ["Canadian character", "Contemporary style", "Technical clarity"] },
  { "c": "SCHOENBERG, A.", "t": "5 Pieces, op. 23 Hansen", "nat": "Austrian", "era": "Modern", "focus": ["Atonal style", "Expressionist writing", "Twelve-tone technique"] },
  { "c": "SCHOENBERG, A.", "t": "Klavierstücke, op. 11", "nat": "Austrian", "era": "Modern", "focus": ["Atonal style", "Expressionist writing", "Twelve-tone technique"] },
  { "c": "SCHUBERT, F.", "t": "Impromptu in B♭, D 935", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "SCHUBERT, F.", "t": "Sonata in A minor, op. 143 D 784", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "SCHULHOFF, E.", "t": "5 études de jazz", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Jazz influence", "Modern style"] },
  { "c": "SCHULHOFF, E.", "t": "Sonata no. 1 Panton", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Jazz influence", "Modern style"] },
  { "c": "SCHUMANN, C.", "t": "Romance in G minor, op. 21 no. 3", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "Harmonic richness"] },
  { "c": "SCHUMANN, C.", "t": "Variations de concert sur la cavatine du Pirate de Bellini, op. 8", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "Harmonic richness"] },
  { "c": "SCHUMANN, R.", "t": "Abegg Variations, op. 1", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "SCHUMANN, R.", "t": "Allegro, op. 8", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "SCHUMANN, R.", "t": "Carnival Jest (from Vienna, op. 26)", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "SCHUMANN, R.", "t": "Novellette in D, op. 21 no. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "SCHUMANN, R.", "t": "Novellette in F# minor, op. 21 no. 8", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "SCHUMANN, R.", "t": "Papillons, op. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "SCHUMANN, R.", "t": "Sonata in G minor, op. 22", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "SCRIABIN, A.", "t": "Etude in D# minor, op. 8 no. 12", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "SCRIABIN, A.", "t": "Fantasie in B minor, op. 28", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "SCRIABIN, A.", "t": "Poème tragique, op. 34 Belaieff", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "SCRIABIN, A.", "t": "Sonata no. 1 in F minor, op. 6", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "SCRIABIN, A.", "t": "Sonata no. 4 in F#, op. 30", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "SCRIABIN, A.", "t": "Waltz in A♭, op. 38 Belaieff", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "SEIBER, M.", "t": "Scherzando capriccioso", "nat": "Hungarian", "era": "Modern", "focus": ["Hungarian character", "Jazz influence", "Modern style"] },
  { "c": "SEROCKI, K.", "t": "Suite of Preludes, nos. 1, 2 and 3", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Modern technique", "Structural clarity"] },
  { "c": "SHOSTAKOVICH, D.", "t": "Preludes and Fugues, op. 87, any one or more of the following: - no. 4 in E minor - no. 15 in D♭ - no. 17 in A♭ - no. 24 in D minor", "nat": "Russian", "era": "Modern", "focus": ["Soviet style", "Dramatic expression", "Modern harmony"] },
  { "c": "SIBELIUS, J.", "t": "Six Impromptus, op. 5, no. 5 in B minor", "nat": "Finnish", "era": "Romantic", "focus": ["Finnish character", "Romantic expression", "Atmospheric writing"] },
  { "c": "SKALKOTTAS, N.", "t": "Andante religioso (no. 1 from 32 Piano Pieces)", "nat": "Greek", "era": "Modern", "focus": ["Greek character", "Twelve-tone technique", "Expressive intensity"] },
  { "c": "SLAVICKÝ, K.", "t": "Variations on a Silent Chord Amos", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Contemporary style", "Variation technique"] },
  { "c": "SMETANA, B.", "t": "Concert Study: Na břehu mořském (On the Seashore) Bärenreiter Praha", "nat": "Czech", "era": "Romantic", "focus": ["Czech character", "Nationalist expression", "Romantic style"] },
  { "c": "STEVENSON, R.", "t": "Fugue on a Fragment of Chopin Ronald Stevenson", "nat": "Scottish", "era": "Modern", "focus": ["Scottish character", "Contrapuntal mastery", "Romantic expression"] },
  { "c": "STEVENSON, R.", "t": "Peter Grimes Fantasy", "nat": "Scottish", "era": "Modern", "focus": ["Scottish character", "Contrapuntal mastery", "Romantic expression"] },
  { "c": "STRAVINSKY, I.", "t": "Étude in F#, op. 7 no. 4 (from The Stravinsky Piano Collection)", "nat": "Russian", "era": "Modern", "focus": ["Neo-Classical style", "Rhythmic drive", "Modern harmony"] },
  { "c": "SZYMANOWSKI, K.", "t": "9 Preludes, op. 1, any two or more", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Impressionist colour", "Modern harmony"] },
  { "c": "SZYMANOWSKI, K.", "t": "Études, op. 4, either nos. 1 and 2 or nos. 2 and 3", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Impressionist colour", "Modern harmony"] },
  { "c": "TAKEMITSU, T.", "t": "Les yeux clos II", "nat": "Japanese", "era": "Contemporary", "focus": ["Japanese character", "Atmospheric writing", "Contemporary style"] },
  { "c": "TAKEMITSU, T.", "t": "Rain-Tree Sketches, no. 1 and/or no. 2", "nat": "Japanese", "era": "Contemporary", "focus": ["Japanese character", "Atmospheric writing", "Contemporary style"] },
  { "c": "TAKTAKISHVILI, O.", "t": "Poem Piano Rare Scores", "nat": "Georgian", "era": "Modern", "focus": ["Georgian character", "Modern style", "Lyrical expression"] },
  { "c": "TCHAIKOVSKY, P.", "t": "18 Pieces, op. 72, any one or more from: - Impromptu in F minor (no. 1) - Polacca de concert (no. 7) - Scherzo-fantasie (no. 10) - Chant élegiaque (no. 14)", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical expression", "Dramatic contrast"] },
  { "c": "TCHAIKOVSKY, P.", "t": "Theme and Variations in F, op. 19 no. 6", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical expression", "Dramatic contrast"] },
  { "c": "TIPPETT, M.", "t": "Sonata no. 2", "nat": "English", "era": "Modern", "focus": ["English character", "Complex rhythm", "Modern harmony"] },
  { "c": "TSONTAKIS, G.", "t": "Ghost Variations", "nat": "American", "era": "Contemporary", "focus": ["American character", "Contemporary style", "Variation technique"] },
  { "c": "TUBIN, E.", "t": "Ballade in the Form of a Chaconne on a Theme by Mart Saar", "nat": "Estonian", "era": "Modern", "focus": ["Estonian character", "Modern harmony", "Expressive phrasing"] },
  { "c": "VIERNE, L.", "t": "12 préludes, op. 36, any two or more contrasting", "nat": "French", "era": "Romantic", "focus": ["French organ style", "Romantic harmony", "Atmospheric writing"] },
  { "c": "VINE, C.", "t": "Bagatelles, any three or more", "nat": "Australian", "era": "Contemporary", "focus": ["Australian character", "Contemporary technique", "Modern harmony"] },
  { "c": "VLADIGEROV, P.", "t": "Autumn Elegy, op. 15 no. 2", "nat": "Bulgarian", "era": "Modern", "focus": ["Bulgarian character", "Romantic expression", "Technical brilliance"] },
  { "c": "VLADIGEROV, P.", "t": "Humoresque in A, op. 15 no. 3", "nat": "Bulgarian", "era": "Modern", "focus": ["Bulgarian character", "Romantic expression", "Technical brilliance"] },
  { "c": "VOŘÍŠEK, J.", "t": "Sonata quasi una Fantasia, op. 20", "nat": "Czech", "era": "Classical", "focus": ["Classical-Romantic style", "Technical fluency", "Expressive phrasing"] },
  { "c": "WALKER, R.", "t": "Five Capriccios, set 1 or set 2 Novello", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary style", "Technical mastery"] },
  { "c": "WEBER, C.M.", "t": "Rondo brillante in E♭, op. 62", "nat": "German", "era": "Romantic", "focus": ["Early Romantic style", "Brilliant passage work", "Dramatic expression"] },
  { "c": "WEBERN, A.", "t": "Variations, op. 27", "nat": "Austrian", "era": "Modern", "focus": ["Serial technique", "Twelve-tone style", "Concentrated expression"] },
  { "c": "VLADIGEROV, P.", "t": "Three Pieces, op. 15, any one or more", "nat": "Bulgarian", "era": "Modern", "focus": ["Bulgarian character", "Romantic expression", "Technical brilliance"] },
  { "c": "ZAHRA, J.", "t": "No. III from Constellations, op. 32", "nat": "Maltese", "era": "Contemporary", "focus": ["Maltese character", "Contemporary style", "Expressive phrasing"] },
  { "c": "ZHANG, Y.", "t": "In That Place Wholly Faraway", "nat": "Chinese", "era": "Contemporary", "focus": ["Chinese character", "Contemporary style", "Expressive phrasing"] },
];