// Trinity College London Piano — ATCL Diploma Repertoire
// 2026 edition | Open pool — 241 works
// Performance: 32–38 min performance
// Source: trinitycollege.com/resource?id=8546

const DATA_TRINITY_ATCL = [
  { "c": "ALBÉNIZ, I.", "t": "Mallorca (Barcarola), op. 202", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "ALKAN, C.-V.", "t": "Esquisses, op. 63, either book 1 nos. 1-6 or book 1 nos. 7-12 or book 2 nos. 13-18 or book 2 nos. 19-24", "nat": "French", "era": "Romantic", "focus": ["Technical virtuosity", "Romantic expression", "Extended form"] },
  { "c": "BABAJANIAN, A.", "t": "Dance of the Vagharshabad", "nat": "Armenian", "era": "Modern", "focus": ["Armenian character", "Lyrical expression", "Romantic style"] },
  { "c": "BABAJANIAN, A.", "t": "Elegy (in memory of Khachaturian)", "nat": "Armenian", "era": "Modern", "focus": ["Armenian character", "Lyrical expression", "Romantic style"] },
  { "c": "BACEWICZ, G.", "t": "Concert Krakowiak", "nat": "Polish", "era": "Modern", "focus": ["Contemporary technique", "Polish character", "Rhythmic drive"] },
  { "c": "BACH, C.P.E.", "t": "Sonata in A, Wq 55/4, H 186", "nat": "German", "era": "Classical", "focus": ["Early Classical style", "Expressive keyboard writing", "Formal innovation"] },
  { "c": "BACH, J.S.", "t": "Capriccio on the Departure of his Most Beloved Brother, BWV 992", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Fantasy and Fugue in A minor, BWV 904", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "French Suite no. 4 in E♭, BWV 815 (all 7 movts)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "French Suite no. 5 in G, BWV 816 (all 7 movts)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Overture (from Partita no. 4 in D, BWV 828)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "The Well-Tempered Clavier book 1, any one or more of the following: - Prelude & Fugue in D, BWV 850 - Prelude & Fugue in D minor, BWV 851 - Prelude & Fugue in F minor, BWV 857 - Prelude & Fugue in F# minor, BWV 859 - Prelude & Fugue in G minor, BWV 861 - Prelude & Fugue in A♭, BWV 862 - Prelude & Fugue in A, BWV 864 - Prelude & Fugue in B, BWV 868", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "The Well-Tempered Clavier book 2, any one or more of the following: - Prelude & Fugue in D, BWV 874 - Prelude & Fugue in D minor, BWV 875 - Prelude & Fugue in E, BWV 878 - Prelude & Fugue in F, BWV 880 - Prelude & Fugue in F# minor, BWV 883 - Prelude & Fugue in G minor, BWV 885 - Prelude & Fugue in A minor, BWV 889", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Prelude & Gigue (from Partita no. 1 in B♭, BWV 825)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Sinfonia, Allemande & Capriccio (from Partita no. 2 in C minor, BWV 826)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Toccata (from Partita no. 6, BWV 830)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Toccata no. 3 in D, BWV 912", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Toccata no. 5 in E minor, BWV 914", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Die Seele ruht in Jesu Händen, BWV 127", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Ich ruf zu dir, Herr Jesu Christ, BWV 639", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BACH, J.S.", "t": "Nun komm’ der Heiden Heiland, BWV 659", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "BALAKIREV, M.", "t": "Scherzo no. 2 or Toccata (from Selected Piano Pieces vol. 1)", "nat": "Russian", "era": "Romantic", "focus": ["Russian character", "Romantic virtuosity", "Technical brilliance"] },
  { "c": "BARTÓK, B.", "t": "Suite, op. 14 (all 4 movts)", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "BAX, A.", "t": "Lullaby Chappell", "nat": "Irish", "era": "Romantic", "focus": ["Lyrical expression", "Impressionist colour", "Irish character"] },
  { "c": "BEACH, A.", "t": "Nocturne, op. 107", "nat": "American", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "American style"] },
  { "c": "BEETHOVEN, L.", "t": "Bagatelles, op. 126", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Rondo a capriccio ‘Rage over a Lost Penny’, op. 129", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in C minor, op. 10 no. 1", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in F, op. 10 no. 2", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in C minor, op. 13 ‘Pathétique’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in E, op. 14 no. 1", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in G, op. 14 no. 2", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in A♭, op. 26", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in E♭, op. 27 no. 1 ‘Quasi una fantasia’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in G, op. 79", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "Sonata in E minor, op. 90", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BEETHOVEN, L.", "t": "32 Variations in C minor, WoO 80", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "BERKELEY, L.", "t": "Concert Study in E♭, op. 48 no. 2", "nat": "English", "era": "Modern", "focus": ["English character", "Neo-Classical style", "Technical clarity"] },
  { "c": "BERKELEY, L.", "t": "Preludes, nos. 1, 2 and 3", "nat": "English", "era": "Modern", "focus": ["English character", "Neo-Classical style", "Technical clarity"] },
  { "c": "BERKOVICH, I.", "t": "Variations on a Theme by Paganini (from Allegro: Intensive Course for Piano vol. 5)", "nat": "Ukrainian", "era": "Modern", "focus": ["Variation technique", "Technical brilliance", "Romantic style"] },
  { "c": "BONDS, M.", "t": "Troubled Water Classical Vocal Reprints", "nat": "American", "era": "Modern", "focus": ["African-American style", "Spiritual expression", "Expressive phrasing"] },
  { "c": "BONIS, M.", "t": "Carillon mystique, op. 31", "nat": "French", "era": "Romantic", "focus": ["French character", "Romantic miniature", "Atmospheric writing"] },
  { "c": "BORTKIEWICZ, S.", "t": "Lamentation no. 1 in D minor and Consolation no. 2 in D (from Lamentations and Consolations book 1)", "nat": "Ukrainian", "era": "Romantic", "focus": ["Romantic expression", "Technical brilliance", "Lyrical phrasing"] },
  { "c": "BOULANGER, N.", "t": "Trois morceaux pour piano", "nat": "French", "era": "Modern", "focus": ["French character", "Expressive phrasing", "Modern style"] },
  { "c": "BOWEN, Y.", "t": "Impromptu, op. 91 no. 2", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Technical fluency"] },
  { "c": "BOWEN, Y.", "t": "Toccata", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Technical fluency"] },
  { "c": "BRAHMS, J.", "t": "Ballade in G minor, op. 118 no. 3", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Capriccio in F# minor, op. 76 no. 1", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Intermezzo in B♭ minor, op. 117 no. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Intermezzo in A minor, op. 118 no. 1", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Intermezzo in A, op. 118 no. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Intermezzo in F minor, op. 118 no. 4", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Intermezzo in E minor, op. 119 no. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Rhapsody in G minor, op. 79 no. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRAHMS, J.", "t": "Romance in F, op. 118 no. 5", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "BRIDGE, F.", "t": "A Fairy Tale Suite, H. 128 (all 4 movts)", "nat": "English", "era": "Modern", "focus": ["Expressive phrasing", "English character", "Modern harmony"] },
  { "c": "CHABRIER, E.", "t": "Aubade", "nat": "French", "era": "Romantic", "focus": ["French character", "Wit and humour", "Rhythmic vitality"] },
  { "c": "CHABRIER, E.", "t": "Bourrée fantasque", "nat": "French", "era": "Romantic", "focus": ["French character", "Wit and humour", "Rhythmic vitality"] },
  { "c": "CHABRIER, E.", "t": "Cinq morceaux, any one or more of the following: Aubade (no. 1), Ballabile (no. 2), Caprice (no. 3)", "nat": "French", "era": "Romantic", "focus": ["French character", "Wit and humour", "Rhythmic vitality"] },
  { "c": "CHABRIER, E.", "t": "Scherzo-Valse (from Pièces pittoresques)", "nat": "French", "era": "Romantic", "focus": ["French character", "Wit and humour", "Rhythmic vitality"] },
  { "c": "CHAMINADE, C.", "t": "Automne, op. 35 no. 2", "nat": "French", "era": "Romantic", "focus": ["French character", "Lyrical melody", "Salon style"] },
  { "c": "CHAMINADE, C.", "t": "Guitare, op. 32", "nat": "French", "era": "Romantic", "focus": ["French character", "Lyrical melody", "Salon style"] },
  { "c": "CHAMINADE, C.", "t": "Toccata, op. 39", "nat": "French", "era": "Romantic", "focus": ["French character", "Lyrical melody", "Salon style"] },
  { "c": "CHAPPLE, B.", "t": "Bagatelles diverses, nos. 6 and 7", "nat": "English", "era": "Modern", "focus": ["English character", "Modern style", "Technical clarity"] },
  { "c": "CHOPIN, F.", "t": "Bolero, op. 19", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Fantaisie impromptu, op. 66", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Impromptu no. 3 in G♭, op. 51", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Mazurka in C# minor, op. 50 no. 3 and Mazurka in D, op. 33 no. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in B♭ minor, op. 9 no. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in B, op. 9 no. 3", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in F#, op. 15 no. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in A♭, op. 32 no. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in G, op. 37 no. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in F# minor, op. 48 no. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in B, op. 62 no. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Nocturne in E, op. 62 no. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Polonaise in C# minor, op. 26 no. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Polonaise in E♭ minor, op. 26 no. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Polonaise in A ‘Military’, op 40 no. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Polonaise in C minor, op. 40 no. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Tarantella in A♭, op. 43", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "CHOPIN, F.", "t": "Valse in E♭, op. 18", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Čiurlionis", "t": "The Sea, Cycle of Small Landscapes, nos. 1, 2 and 3 Jonas Petronis", "nat": "Lithuanian", "era": "Romantic", "focus": ["Lithuanian character", "Symbolist expression", "Atmospheric writing"] },
  { "c": "CLEMENTI, M.", "t": "Sonata in B♭, op. 12 no. 1 (from Sonatas vol. 1)", "nat": "Italian", "era": "Classical", "focus": ["Classical form", "Technical fluency", "Clear phrasing"] },
  { "c": "CLEMENTI, M.", "t": "Sonata in B minor, op. 40 no. 2 (from Sonatas vol. 2)", "nat": "Italian", "era": "Classical", "focus": ["Classical form", "Technical fluency", "Clear phrasing"] },
  { "c": "CLEMENTI, M.", "t": "Sonata in D, op. 40 no. 3 (from Sonatas vol. 2)", "nat": "Italian", "era": "Classical", "focus": ["Classical form", "Technical fluency", "Clear phrasing"] },
  { "c": "COLERIDGE-TAYLOR, S.", "t": "Deep River (no. 10 from Twenty-four Negro Melodies, op. 59)", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Folk elements"] },
  { "c": "COLLEY, B.", "t": "The Rob Colley Piano Collection: 10 contemporary, jazz-inspired pieces, any one or more of the following: - Firefly - Carousel - Tordion - Furiant - Funk Patrol - Round Dance - Action Song - The Toy Museum - La belle dame sans merci - Prayer", "nat": "English", "era": "Contemporary", "focus": ["Contemporary style", "English character", "Lyrical writing"] },
  { "c": "COPLAND, A.", "t": "The Cat and the Mouse, scherzo humoristique", "nat": "American", "era": "Modern", "focus": ["American character", "Rhythmic vitality", "Modern harmony"] },
  { "c": "DEBUSSY, C.", "t": "Danse (Tarantelle styrienne)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "La plus que lente", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "Minuet (from Suite bergamasque)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "Prelude and/or Sarabande (from Pour le piano)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "Preludes for Piano book 1, any one or more of the following: - Voiles (no. 2) - Les sons et les parfums tournent dans l’air du soir (no. 4) - La cathédrale engloutie (no. 10)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DEBUSSY, C.", "t": "Preludes for Piano book 2, any one or more of the following: - Feuilles mortes (no. 2) - La puerta del Vino (no. 3) - Général Lavine-eccentric (no. 6) - Homage à S. Pickwick Esq. PPMPC (no. 9)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "DELLO JOIO, N.", "t": "Suite for Piano (all 4 movts)", "nat": "American", "era": "Modern", "focus": ["American style", "Rhythmic vitality", "Neo-Classical writing"] },
  { "c": "DIBBLE, J.", "t": "24 Preludes and Fugues, any one of the following: - Prelude and Fugue on C#m3 - Prelude and Fugue on F#m3 - Prelude and Fugue on G#m3", "nat": "English", "era": "Contemporary", "focus": ["Contemporary counterpoint", "Fugue technique", "Technical clarity"] },
  { "c": "DOHNÁNYI, E.", "t": "Pastorale on a Hungarian Christmas Song, ‘The Angel is from Heaven’", "nat": "Hungarian", "era": "Romantic", "focus": ["Romantic virtuosity", "Hungarian character", "Technical brilliance"] },
  { "c": "DUBRA, R.", "t": "Etude in C", "nat": "Latvian", "era": "Contemporary", "focus": ["Latvian character", "Contemporary style", "Technical clarity"] },
  { "c": "EVANS, L.", "t": "Rhapsody", "nat": "Australian", "era": "Contemporary", "focus": ["Australian character", "Contemporary style", "Expressive phrasing"] },
  { "c": "FALLA, M. de", "t": "Serenata Andaluza", "nat": "Spanish", "era": "Modern", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "FARR, G.", "t": "The Horizon from Owhiro Bay", "nat": "New Zealand", "era": "Contemporary", "focus": ["New Zealand character", "Contemporary style", "Expressive phrasing"] },
  { "c": "FAURÉ, G.", "t": "Barcarolle no. 1 in A minor, op. 26", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Barcarolle no. 6 in E♭, op. 70", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Impromptu in F minor, op. 31 no. 2", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Nocturne no. 4 in E♭, op. 36", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "FAURÉ, G.", "t": "Romances sans paroles, op. 17 (all 3 movts)", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "GAMBE, R.", "t": "Three Poems, op. 9 Mother Earth", "nat": "French", "era": "Contemporary", "focus": ["Contemporary style", "Expressive phrasing", "Lyrical writing"] },
  { "c": "GARDINER, J.", "t": "Synergy", "nat": "Canadian", "era": "Contemporary", "focus": ["Canadian character", "Contemporary style", "Technical clarity"] },
  { "c": "GERSHWIN, G.", "t": "Any two transcriptions (from Meet George Gershwin at the Keyboard)", "nat": "American", "era": "Modern", "focus": ["Jazz influence", "American character", "Rhythmic vitality"] },
  { "c": "GINASTERA, A.", "t": "Malambo, op. 7 (final movt from Estancia, op. 8) Ricordi (out of print)", "nat": "Argentine", "era": "Modern", "focus": ["Argentine character", "Rhythmic vitality", "Modern technique"] },
  { "c": "GLINKA, M.", "t": "A Greeting to My Homeland, no. 4: Variations on a Scottish Theme (The Last Rose of Summer)", "nat": "Russian", "era": "Romantic", "focus": ["Russian character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "GLINKA, M.", "t": "The Lark", "nat": "Russian", "era": "Romantic", "focus": ["Russian character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "GODOWSKY, L.", "t": "Renaissance book 1, any one or two from: nos. 5, 6, 8, 9, 10, 11, 12", "nat": "Polish", "era": "Romantic", "focus": ["Transcription mastery", "Technical virtuosity", "Romantic style"] },
  { "c": "GRAINGER, P.", "t": "Molly on the Shore (from British Folk Music Settings)", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Folk elements", "Energetic playing"] },
  { "c": "GRAINGER, P.", "t": "Shepherd’s Hey (original version, not a simplified version)", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Folk elements", "Energetic playing"] },
  { "c": "GRANADOS, E.", "t": "Paisaje, op. 35", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "GRIEG, E.", "t": "4 Humoresques, op. 6, any two or more", "nat": "Norwegian", "era": "Romantic", "focus": ["Norwegian character", "Romantic expression", "Folk elements"] },
  { "c": "GRIEG, E.", "t": "Sonata in E minor, op. 7", "nat": "Norwegian", "era": "Romantic", "focus": ["Norwegian character", "Romantic expression", "Folk elements"] },
  { "c": "HANDEL, G.F.", "t": "Suite no. 1 in A, HWV 426 (all 4 movts)", "nat": "German", "era": "Baroque", "focus": ["Baroque style", "Ornamentation", "Structural clarity"] },
  { "c": "HANDEL, G.F.", "t": "Suite no. 6 in F# minor, HWV 431 (all 4 movts)", "nat": "German", "era": "Baroque", "focus": ["Baroque style", "Ornamentation", "Structural clarity"] },
  { "c": "HANDEL, G.F.", "t": "Suite no. 8 in F minor, HWV 433 (all 5 movts)", "nat": "German", "era": "Baroque", "focus": ["Baroque style", "Ornamentation", "Structural clarity"] },
  { "c": "HAYDN, J.", "t": "Sonata in C minor, Hob XVI/20", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in F, Hob XVI/23", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in B minor, Hob XVI/32", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in E minor, Hob XVI/34", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in E♭, Hob XVI/38", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in A♭, Hob XVI/43", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in A♭, Hob XVI/46", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in C, Hob XVI/48", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in E♭, Hob XVI/49", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HAYDN, J.", "t": "Sonata in D, Hob XVI/51", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "HENSEL, F.", "t": "Notturno in G minor (no. 5 from Selected Piano Works)", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "Song-like character"] },
  { "c": "HOFMEYR, H.", "t": "Chaconne, op. 43 Noten Roehr", "nat": "South African", "era": "Contemporary", "focus": ["South African character", "Contemporary style", "Variation technique"] },
  { "c": "HOWELLS, H.", "t": "Finzi’s Rest and Berkeley’s Hunt (from Howells’ Clavichord) Novello", "nat": "English", "era": "Modern", "focus": ["English character", "Impressionist colour", "Lyrical phrasing"] },
  { "c": "HYDE, M.", "t": "Valley of the Rocks", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Impressionist colour", "Expressive phrasing"] },
  { "c": "JANÁČEK, L.", "t": "V mlhách (In the Mists), any two movts Bärenreiter Praha", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Folk elements", "Modern harmony"] },
  { "c": "JENKINS, K.", "t": "Boogie Woogie Llanoogie", "nat": "Welsh", "era": "Contemporary", "focus": ["Welsh character", "Contemporary style", "Jazz influence"] },
  { "c": "KABALEVSKY, D.", "t": "Preludes, op. 38, nos. 5 and 6", "nat": "Russian", "era": "Modern", "focus": ["Soviet style", "Rhythmic vitality", "Clear texture"] },
  { "c": "KAPUSTIN, N.", "t": "Big Band Sounds, op. 46", "nat": "Ukrainian", "era": "Contemporary", "focus": ["Jazz influence", "Technical virtuosity", "Contemporary style"] },
  { "c": "LARREGLA, J.", "t": "Viva Navarra! Jota de Concierto", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Virtuosic display", "Dance character"] },
  { "c": "LECUONA, E.", "t": "Suite Andalucia, any two or more movts Edward B Marks", "nat": "Cuban", "era": "Modern", "focus": ["Cuban character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "LIEBERMANN, L.", "t": "Nocturne no. 1, op. 20", "nat": "American", "era": "Contemporary", "focus": ["Contemporary style", "Lyrical expression", "Technical mastery"] },
  { "c": "LILBURN, D.", "t": "From the Port Hills (no. 4 from Five Bagatelles) Sounz", "nat": "New Zealand", "era": "Modern", "focus": ["New Zealand character", "Modern style", "Expressive phrasing"] },
  { "c": "LILBURN, D.", "t": "Sonatina no. 1 or Sonatina no. 2", "nat": "New Zealand", "era": "Modern", "focus": ["New Zealand character", "Modern style", "Expressive phrasing"] },
  { "c": "LISZT, F.", "t": "Liebesträume, S541, one or both of the following: - Seliger Tod (no. 2), - O lieb, so lang du lieben kannst (no. 3)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LISZT, F.", "t": "Sonetto 123 del Petrarca (from Années de pèlerinage, 2nd year)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "LOUIE, A.", "t": "Enchanted Bells (from Music for Piano)", "nat": "Canadian", "era": "Contemporary", "focus": ["Canadian character", "Contemporary style", "Atmospheric writing"] },
  { "c": "LOURIÉ, A.", "t": "Cinq préludes fragiles, op. 1 Broude", "nat": "Russian", "era": "Modern", "focus": ["Russian character", "Impressionist style", "Atmospheric writing"] },
  { "c": "LYAPUNOV, S.", "t": "Nocturne in D♭, op. 8", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Technical brilliance", "Expressive phrasing"] },
  { "c": "MARTIN, F.", "t": "Jazz Scherzo (from New York Nights)", "nat": "Swiss", "era": "Modern", "focus": ["Swiss character", "Modern harmony", "Expressive phrasing"] },
  { "c": "MARTINŮ, B.", "t": "Prelude en forme de fox-trot (from Eight Preludes, H181) Leduc", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Neo-Classical style", "Rhythmic vitality"] },
  { "c": "MCDOWALL, C.", "t": "Shades of Solace and Vespers in Venice or Vespers in Venice and Tapsalteerie (from Four Piano Solos) Hunt", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary style", "Atmospheric writing"] },
  { "c": "MCLEOD, J.", "t": "24 Tone Clock Pieces, any two or more contrasting pieces", "nat": "New Zealand", "era": "Contemporary", "focus": ["New Zealand character", "Contemporary technique", "Tone clock system"] },
  { "c": "MEDTNER, N.", "t": "Danza festiva, op. 38 no. 3 Zimmermann", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Complex texture", "Structural integrity"] },
  { "c": "MENDELSSOHN, F.", "t": "Andante e Presto agitato in B, WoO6", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "MENDELSSOHN, F.", "t": "Prelude & Fugue in F minor, op. 35 no. 5", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "MENDELSSOHN, F.", "t": "Songs Without Words, any one or more of the following: - op. 30 no. 2 in B♭ minor - op. 30 no. 4 in B minor - op. 30 no. 5 in D - op. 38 no. 3 in E - op. 53 no. 3 in G minor - op. 85 no. 1 in F - op. 85 no. 2 in A minor - op. 85 no. 3 in E♭", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "MESSIAEN, O.", "t": "Le merle noir (from Petites esquisses d’oiseau) Leduc", "nat": "French", "era": "Modern", "focus": ["Colour and rhythm", "Spiritual expression", "Modern harmony"] },
  { "c": "MESSIAEN, O.", "t": "Plainte calme (from no. 7 from Préludes)", "nat": "French", "era": "Modern", "focus": ["Colour and rhythm", "Spiritual expression", "Modern harmony"] },
  { "c": "MESSIAEN, O.", "t": "Vingt regards sur l’enfant-Jésus, any one or more from nos. 1, 2, 4, 19", "nat": "French", "era": "Modern", "focus": ["Colour and rhythm", "Spiritual expression", "Modern harmony"] },
  { "c": "MILHAUD, D.", "t": "Trois Rag Caprices, op. 78 (all 3 movts)", "nat": "French", "era": "Modern", "focus": ["Polytonality", "French character", "Rhythmic vitality"] },
  { "c": "MOMPOU, F.", "t": "Scènes d’enfants (all 5 movts)", "nat": "Spanish", "era": "Modern", "focus": ["Spanish character", "Atmospheric writing", "Simplicity of means"] },
  { "c": "MORAWETZ, O.", "t": "Scherzo", "nat": "Canadian", "era": "Modern", "focus": ["Canadian character", "Modern style", "Technical clarity"] },
  { "c": "MOSZKOWSKI, M.", "t": "Étincelles, op. 36 no. 6", "nat": "Polish", "era": "Romantic", "focus": ["Romantic virtuosity", "Technical brilliance", "Dance character"] },
  { "c": "MOZART, W.A.", "t": "Sonata in C, K 309", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MOZART, W.A.", "t": "Sonata in D, K 311", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MOZART, W.A.", "t": "Sonata in A, K 331", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MOZART, W.A.", "t": "Sonata in F, K 332", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MOZART, W.A.", "t": "Sonata in B♭, K 333", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MOZART, W.A.", "t": "Sonata in C minor, K 457", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MOZART, W.A.", "t": "10 Variations on Unser Dummer Pöbel meint, K 455", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MOZART, W.A.", "t": "9 Variations on a minuet by Duport, K 573", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "MUCZYNSKI, R.", "t": "Six Preludes, op. 6, any three or more", "nat": "American", "era": "Modern", "focus": ["American character", "Modern harmony", "Clear texture"] },
  { "c": "PENTLAND, B.", "t": "Studies in Line (all 4 movts)", "nat": "Canadian", "era": "Modern", "focus": ["Canadian character", "Modern technique", "Linear writing"] },
  { "c": "PERSICHETTI, V.", "t": "Three Toccatinas, op. 142 (all 3)", "nat": "American", "era": "Modern", "focus": ["American style", "Modern harmony", "Technical clarity"] },
  { "c": "PETERSON, O.", "t": "Canadiana Suite, any two movts, played as a solo as written, with no improvisation Hal Leonard", "nat": "Canadian", "era": "Modern", "focus": ["Canadian character", "Jazz influence", "Expressive phrasing"] },
  { "c": "PONCE, M.", "t": "Malgré tout (A Pesar de Todo) for left hand alone", "nat": "Mexican", "era": "Romantic", "focus": ["Mexican character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "POULENC, F.", "t": "Five Impromptus (all 5)", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "POULENC, F.", "t": "Suite in C (all 3 movts)", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "POULENC, F.", "t": "Toccata (from Trois pièces) Heugel", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "POULENC, F.", "t": "Trois novelettes, nos. 1 and 2", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "PROKOFIEV, S.", "t": "Ten Pieces (from Cinderella), op. 97, any three or more", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "PROKOFIEV, S.", "t": "Visions fugitives, no. 14 and any other two", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "QUILTER, R.", "t": "Three Studies, op. 4, any one or more", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "RACHMANINOFF, S.", "t": "Morceaux de salon, op. 10, any two contrasting from nos. 1, 2, 3, 4, 6", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RACHMANINOFF, S.", "t": "Polichinelle in F# minor, op. 3 no. 4 (from Morceaux de fantaisie)", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RACHMANINOFF, S.", "t": "Prelude in E♭, op. 23 no. 6", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RACHMANINOFF, S.", "t": "Preludes, op. 32, nos. 5 and 10", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RACHMANINOFF, S.", "t": "Preludes, op. 32, nos. 5 and 12", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RACHMANINOFF, S.", "t": "Kreisler Liebesleid (from Piano Compositions vol. 2)", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "RAMEAU, J.-P.", "t": "Les cyclopes (from Pièces de clavecin)", "nat": "French", "era": "Baroque", "focus": ["French Baroque style", "Ornamentation", "Dance character"] },
  { "c": "RAVEL, M.", "t": "À la manière de Borodine: valse pour piano", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "RAVEL, M.", "t": "À la manière de Chabrier", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "RAVEL, M.", "t": "Pavane pour une infante défunte", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "RAWSTHORNE, A.", "t": "Sonatina for Piano OUP", "nat": "English", "era": "Modern", "focus": ["English character", "Modern harmony", "Structural clarity"] },
  { "c": "REGER, M.", "t": "Prelude and Fugue in A minor, op. 99 no. 3", "nat": "German", "era": "Romantic", "focus": ["Romantic polyphony", "Contrapuntal mastery", "Technical brilliance"] },
  { "c": "REINHOLD, H.", "t": "Impromptu in C# minor, op. 28 no. 3", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Technical clarity", "Lyrical phrasing"] },
  { "c": "REN, Y.", "t": "Silver Clouds Chasing the Moon / Colourful Clouds Chasing the Moon (from Chinese Piano Music: Works of the 20th Century – Henle) (from 30 Famous Chinese Piano Pieces – PMPH) Henle / People's Music Publishing House", "nat": "Chinese", "era": "Contemporary", "focus": ["Chinese character", "Contemporary arrangement", "Folk melody"] },
  { "c": "RESPIGHI, O.", "t": "Six Pieces for Piano, any one or more of the following: - Canone (no. 2) - Notturno (no. 3) - Intermezzo-Serenata (no. 6)", "nat": "Italian", "era": "Modern", "focus": ["Italian character", "Romantic expression", "Colouristic writing"] },
  { "c": "RZEWSKI, F.", "t": "Dreadful Memories (from Squares & North American Ballads)", "nat": "American", "era": "Contemporary", "focus": ["Political expression", "Extended techniques", "Contemporary style"] },
  { "c": "SANCAN, P.", "t": "Mouvement", "nat": "French", "era": "Modern", "focus": ["French character", "Technical virtuosity", "Modern style"] },
  { "c": "SCARLATTI, D.", "t": "Sonata in B minor, K 27", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "SCARLATTI, D.", "t": "Sonatas in G, K 259 and K 260", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "SCARLATTI, D.", "t": "Sonata in E minor, K 263 and Sonata in E, K 264", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "SCARLATTI, D.", "t": "Sonata in D, K 491", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "SCHMIDT, H.", "t": "Shimmer Canadian Music Centre", "nat": "Canadian", "era": "Contemporary", "focus": ["Canadian character", "Contemporary style", "Technical clarity"] },
  { "c": "SCHOENBERG, A.", "t": "Sechs kleine Klavierstücke, op. 19", "nat": "Austrian", "era": "Modern", "focus": ["Atonal style", "Expressionist writing", "Twelve-tone technique"] },
  { "c": "SCHUBERT, F.", "t": "Impromptu in E♭, op. 90 no. 2", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "SCHUBERT, F.", "t": "Impromptu in G♭, op. 90 no. 3", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "SCHUBERT, F.", "t": "Impromptu in F minor, op. 142 no. 1", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "SCHUBERT, F.", "t": "Sonata in A minor, op. 42 D 845", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "SCHUBERT, F.", "t": "Sonata in A, op. 120 D 664", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "SCHUBERT, F.", "t": "Sonata in A minor, op. 164 D 537", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "SCHULHOFF, E.", "t": "Suite dansante en jazz, WV 98, any two or more movts", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Jazz influence", "Modern style"] },
  { "c": "SCHUMANN, C.", "t": "Romance in A minor, op. 21 no. 1", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "Harmonic richness"] },
  { "c": "SCHUMANN, C.", "t": "Scherzo no. 1 in D minor, op. 10 or Scherzo no. 2 in C minor, op. 14 (no. 2 - from A Recital Anthology) Henle (no. 1) Trinity (no. 2)", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "Harmonic richness"] },
  { "c": "SCHUMANN, R.", "t": "Grillen (from Fantasiestücke, op. 12)", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "SCHUMANN, R.", "t": "Novelette no. 1 in F, op. 21", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "SCHUMANN, R.", "t": "Romance in B, op. 28 no. 3", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "SCRIABIN, A.", "t": "24 Preludes, op. 11, any two from nos. 3, 6, 8, 12, 13, 24", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "SCRIABIN, A.", "t": "Deux morceaux, op. 57, Désir (no. 1) and Caresse dansée (no. 2) Belaieff", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "SCRIABIN, A.", "t": "Deux poèmes, op. 32, no. 1 and/or no. 2", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "SCRIABIN, A.", "t": "Étude in B♭ minor, op. 8 no. 11", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "SCULTHORPE, P.", "t": "Mountains", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Indigenous influence", "Contemporary writing"] },
  { "c": "SCULTHORPE, P.", "t": "Night Pieces", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Indigenous influence", "Contemporary writing"] },
  { "c": "SCULTHORPE, P.", "t": "Sonatina", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Indigenous influence", "Contemporary writing"] },
  { "c": "SHOSTAKOVICH, D.", "t": "Polka from The Golden Age, op. 22b", "nat": "Russian", "era": "Modern", "focus": ["Soviet style", "Dramatic expression", "Modern harmony"] },
  { "c": "SHOSTAKOVICH, D.", "t": "Preludes, op. 34, nos. 3, 5, 11 and 19 (all four)", "nat": "Russian", "era": "Modern", "focus": ["Soviet style", "Dramatic expression", "Modern harmony"] },
  { "c": "SHOSTAKOVICH, D.", "t": "Preludes and Fugues, op. 87, any one or more of the following: - no. 2 in A minor - no. 7 in A - no. 22 in G minor - no. 23 in F", "nat": "Russian", "era": "Modern", "focus": ["Soviet style", "Dramatic expression", "Modern harmony"] },
  { "c": "SUTTON, G.", "t": "Blackheath Crosslight", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary style", "Atmospheric writing"] },
  { "c": "SZYMANOWSKI, K.", "t": "Étude no. 3, Andante – in modo d’una canzona (from 4 Etudes pour piano, op. 4)", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Impressionist colour", "Modern harmony"] },
  { "c": "SZYMANOWSKI, K.", "t": "Mazurkas, op. 50, any two contrasting", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Impressionist colour", "Modern harmony"] },
  { "c": "TCHAIKOVSKY, P.", "t": "Dumka, op. 59", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical expression", "Dramatic contrast"] },
  { "c": "TCHAIKOVSKY, P.", "t": "18 Pieces, op. 72, any one or more of the following: - Valse bluette (no. 11) - Un poco di Chopin (no. 15) - Valse à cinq temps (no. 16) - Passé lointain (no. 17)", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical expression", "Dramatic contrast"] },
  { "c": "TCHEREPNIN, A.", "t": "Chant (no. 5 from 5 Concert Studies, op. 52)", "nat": "Russian", "era": "Modern", "focus": ["Russian character", "Modern style", "Technical clarity"] },
  { "c": "TREMAIN, R.", "t": "Three Inventions, any one or more", "nat": "New Zealand", "era": "Contemporary", "focus": ["New Zealand character", "Contemporary style", "Contrapuntal writing"] },
  { "c": "TURINA, J.", "t": "Danzas fantásticas, op. 22", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "TURINA, J.", "t": "Mujeres Españolas, op. 17, any two or more movts", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "USTVOLSKAYA, G.", "t": "12 Preludes, any two or more from nos. 5, 6, 7, 8", "nat": "Russian", "era": "Contemporary", "focus": ["Russian character", "Stark expression", "Contemporary style"] },
  { "c": "WILKINSON, M.", "t": "Oiseaux d’eau (Water Birds) (no. 19 from Piano Portraits: 24 Vignettes in Diverse Styles)", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary style", "Expressive phrasing"] },
];