// Trinity College London Piano — LTCL Diploma Repertoire
// 2026 edition | Open pool — 306 works
// Performance: 37–43 min performance
// Source: trinitycollege.com/resource?id=8546

const DATA_TRINITY_LTCL = [
  { "c": "Albéniz", "t": "Iberia, any two contrasting pieces from books 1-4", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "Albéniz", "t": "La Vega (from The Alhambra, Suite for Piano)", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "Albéniz", "t": "Rapsodica Cubana, op. 66", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "Alkan", "t": "Trois morceaux dans le genre pathétique, op. 15, no. 1: Aime-moi", "nat": "French", "era": "Romantic", "focus": ["Technical virtuosity", "Romantic expression", "Extended form"] },
  { "c": "Anderson", "t": "Piano Etudes", "nat": "American", "era": "Contemporary", "focus": ["Contemporary etude", "Technical mastery", "Expressive phrasing"] },
  { "c": "Auerbach", "t": "24 Preludes, op. 41, no. 16 in B♭ minor", "nat": "Russian", "era": "Contemporary", "focus": ["Contemporary style", "Russian character", "Expressive phrasing"] },
  { "c": "Bach, J S", "t": "Aria variata alla maniera Italiana, BWV 989", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Capriccio in E, BWV 993", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Chromatic Fantasia & Fugue in D minor, BWV 903", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Concerto no. 3 in D minor, BWV 974 (after Marcello)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "English Suite no. 2 in A minor, BWV 807", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Partita no. 2 in C minor, BWV 826", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Partita no. 3 in A minor, BWV 827", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Partita no. 4 in D, BWV 828", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Partita no. 5 in G, BWV 829", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "The Well-Tempered Clavier book 1, any one or more of the following: - Prelude & Fugue in C# minor, BWV 849 - Prelude & Fugue in E♭, BWV 852 - Prelude & Fugue in E♭ minor, BWV 853 - Prelude & Fugue in G# minor, BWV 863 - Prelude & Fugue in B minor, BWV 869", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "The Well-Tempered Clavier book 2, any one or more of the following: - Prelude & Fugue in C#, BWV 872 - Prelude & Fugue in C# minor, BWV 873 - Prelude & Fugue in D# minor, BWV 877 - Prelude & Fugue in E minor, BWV 879 - Prelude & Fugue in G# minor, BWV 887 - Prelude & Fugue in B♭, BWV 890 - Prelude & Fugue in B♭ minor, BWV 891 - Prelude & Fugue in B, BWV 892 - Prelude & Fugue in B minor, BWV 893", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Toccata no. 1 in F# minor, BWV 910", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Toccata no. 2 in C minor, BWV 911", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Toccata no. 4 in D minor, BWV 913", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Toccata no. 6 in G minor, BWV 915", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Toccata no. 7 in G, BWV 916", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Toccata and Fugue in D minor, BWV 565 (both to be played)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Toccata in D minor (from The Alexander Siloti Collection)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Barber", "t": "Excursions, op. 20", "nat": "American", "era": "Modern", "focus": ["American Romantic style", "Lyrical expression", "Expressive phrasing"] },
  { "c": "Barber", "t": "Nocturne, op. 33", "nat": "American", "era": "Modern", "focus": ["American Romantic style", "Lyrical expression", "Expressive phrasing"] },
  { "c": "Barber", "t": "Souvenirs, op. 28, any three", "nat": "American", "era": "Modern", "focus": ["American Romantic style", "Lyrical expression", "Expressive phrasing"] },
  { "c": "Bartók", "t": "Allegro Barbaro", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "Bartók", "t": "3 Burlesques, op. 8c, Sz. 47", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "Bartók", "t": "Out of Doors (Im Freien) (all 5 movts)", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "Bartók", "t": "Two Romanian Dances, op. 8a, Sz. 43 Kalmus", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "Beach", "t": "Ballade in D♭, op. 6", "nat": "American", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "American style"] },
  { "c": "Beach", "t": "4 Sketches, op. 15, any two or more including no. 4", "nat": "American", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "American style"] },
  { "c": "Beethoven", "t": "Fantasia in G minor, op. 77", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in C, op. 2 no. 3", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in E♭, op. 7", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in D, op. 10 no. 3", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in B♭, op. 22", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in G, op. 31 no. 1", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in D minor, op. 31 no. 2 ‘Tempest’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in E♭, op. 31 no. 3 ‘Hunt’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in E♭, op. 81a ‘Les adieux’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Bennett", "t": "Sonata no. 1 in F minor, op. 13", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary technique", "Structural clarity"] },
  { "c": "Berg", "t": "Sonata, op. 1", "nat": "Austrian", "era": "Modern", "focus": ["Expressionist style", "Atonal writing", "Romantic roots"] },
  { "c": "Bernstein", "t": "Touches: Chorale, 8 Variations and Coda", "nat": "American", "era": "Modern", "focus": ["American character", "Rhythmic vitality", "Jazz influence"] },
  { "c": "Boëllmann", "t": "Sur la mer, op. 38", "nat": "French", "era": "Romantic", "focus": ["French character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Borodin", "t": "Scherzo in A♭ (no. VIII from Petite Suite)", "nat": "Russian", "era": "Romantic", "focus": ["Russian character", "Romantic expression", "Colouristic writing"] },
  { "c": "Boulanger", "t": "Thème et variations Tonger", "nat": "French", "era": "Modern", "focus": ["French character", "Expressive phrasing", "Modern style"] },
  { "c": "Bowen", "t": "Preludes, op. 102, any three", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Technical fluency"] },
  { "c": "Brahms", "t": "Capriccio in B minor, op. 76 no. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Capriccio in C# minor, op. 76 no. 5", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Capriccio in C, op. 76 no. 8", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Capriccio in G minor, op. 116 no. 3", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Capriccio in D minor, op. 116 no. 7", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Etude no. 1 in F minor after Chopin’s op. 25 no. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Intermezzo in E♭ minor, op. 118 no. 6", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Rhapsodies, op. 79 (both to be played)", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Rhapsody, op. 119 no. 4", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Variations on a Theme by Robert Schumann, op. 9", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Busoni", "t": "Turandots Frauengemach (no. 4 from Elegies, BV 249)", "nat": "Italian", "era": "Modern", "focus": ["Transcription technique", "Virtuosic display", "Baroque transformation"] },
  { "c": "Casella", "t": "Toccata, op. 6", "nat": "Italian", "era": "Modern", "focus": ["Italian character", "Modern harmony", "Neo-Classical style"] },
  { "c": "Chaminade", "t": "Sonata in C minor, op. 21", "nat": "French", "era": "Romantic", "focus": ["French character", "Lyrical melody", "Salon style"] },
  { "c": "Chasins", "t": "3 Chinese Pieces, op. 5 (all 3)", "nat": "American", "era": "Modern", "focus": ["American style", "Chinese influence", "Atmospheric writing"] },
  { "c": "Chopin", "t": "Ballades, any one of nos. 1, 2 or 4", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Barcarolle, op. 60", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Études, op. 10, any two contrasting", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Études, op. 25, any two contrasting", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Fantaisie in F minor, op. 49", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Introduction and Variations in E on a German Air, op. posth.", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Nocturne in F, op. 15 no. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Nocturne in C# minor, op. 27 no. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Nocturne in D♭, op. 27 no. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Nocturne in C minor, op. 48 no. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Polonaise in F# minor, op. 44", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Polonaise in A♭, op. 53", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Polonaise-fantasy in A♭, op. 61", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Rondo in C minor, op. 1", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Any of the four Scherzi", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Variations brillantes on a theme from Hérold’s ‘Ludovic’, op. 12", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Romance from Piano Concerto no. 1 in E minor, op. 11", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Clementi", "t": "Sonata in G minor, op. 50 no. 3 ‘Didona abbandonata’", "nat": "Italian", "era": "Classical", "focus": ["Classical form", "Technical fluency", "Clear phrasing"] },
  { "c": "Constantinescu", "t": "Joc Dobrogean – Toccata", "nat": "Romanian", "era": "Modern", "focus": ["Romanian character", "Rhythmic vitality", "Modern style"] },
  { "c": "Copland", "t": "Sonata", "nat": "American", "era": "Modern", "focus": ["American character", "Rhythmic vitality", "Modern harmony"] },
  { "c": "Coulthard", "t": "Four Etudes for Piano", "nat": "Canadian", "era": "Modern", "focus": ["Canadian character", "Modern style", "Technical mastery"] },
  { "c": "Coulthard", "t": "Image astrale", "nat": "Canadian", "era": "Modern", "focus": ["Canadian character", "Modern style", "Technical mastery"] },
  { "c": "Crumb", "t": "A Little Suite for Christmas, any three movts", "nat": "American", "era": "Contemporary", "focus": ["Extended techniques", "Atmospheric writing", "Contemporary style"] },
  { "c": "Cumming", "t": "24 Preludes for Solo Piano, any six or more", "nat": "Canadian", "era": "Contemporary", "focus": ["Canadian character", "Contemporary style", "Prelude texture"] },
  { "c": "Czerny", "t": "Variations on a Theme by Rode, ‘La Ricordanza’, op. 33", "nat": "Austrian", "era": "Classical", "focus": ["Technical etude", "Rapid figurations", "Even tone"] },
  { "c": "Debussy", "t": "Estampes, any one or more", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "Debussy", "t": "Images (book 1 or 2), any one or more movts", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "Debussy", "t": "L’isle joyeuse", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "Debussy", "t": "Masques", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "Debussy", "t": "Preludes for Piano book 1, any one or more of the following: - Le vent dans la plaine (no. 3) - Ce qu’a vu le vent d’ouest (no. 7) - La danse de Puck (no. 11)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "Debussy", "t": "Preludes for Piano book 2, any one or more of the following: - Les fées sont d’exquises danseuses (no. 4) - La terrasse des audiences (no. 7) - Ondine (no. 8) - Les tierces alternées (no. 11)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "Debussy", "t": "Toccata (from Pour le piano)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "Decaux", "t": "Clairs de lune, La mer (no. 4) plus at least one more from nos. 1, 2, 3 B-Note", "nat": "French", "era": "Modern", "focus": ["French Impressionism", "Atmospheric writing", "Modern harmony"] },
  { "c": "Dello Joio", "t": "Two Concert Études", "nat": "American", "era": "Modern", "focus": ["American style", "Rhythmic vitality", "Neo-Classical writing"] },
  { "c": "Diemer", "t": "Toccata Arsis Press", "nat": "American", "era": "Contemporary", "focus": ["American character", "Contemporary style", "Rhythmic vitality"] },
  { "c": "Dohnányi", "t": "4 Rhapsodies, op. 11, any one", "nat": "Hungarian", "era": "Romantic", "focus": ["Romantic virtuosity", "Hungarian character", "Technical brilliance"] },
  { "c": "Dohnányi", "t": "6 Concert Etudes, op. 28, any one or more Masters", "nat": "Hungarian", "era": "Romantic", "focus": ["Romantic virtuosity", "Hungarian character", "Technical brilliance"] },
  { "c": "Emmanuel", "t": "Sonatine no. 5, Alla francese, op. 22 (all 6 movts) Lemoine", "nat": "French", "era": "Modern", "focus": ["French character", "Modal harmony", "Modern style"] },
  { "c": "Englund", "t": "Introduction and Toccata Fennica Gehrman", "nat": "Finnish", "era": "Modern", "focus": ["Finnish character", "Modern style", "Technical clarity"] },
  { "c": "de Falla", "t": "Piezas españolas, any two or more", "nat": "Spanish", "era": "Modern", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "de Falla", "t": "Spanish Dance no. 1 (from La vida breve)", "nat": "Spanish", "era": "Modern", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "Farrenc", "t": "Air russe varié, op. 17", "nat": "French", "era": "Classical", "focus": ["French character", "Classical style", "Technical fluency"] },
  { "c": "Fauré", "t": "Barcarolle no. 5 in F# minor, op. 66", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "Fauré", "t": "Impromptu in A♭, op. 34 no. 3", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "Fauré", "t": "Nocturne no. 2, op. 33 or Nocturne no. 5, op. 37", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "Fauré", "t": "Nocturne in D♭, op. 63", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "Fauré", "t": "Nocturne in B minor, op. 119", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "Fauré", "t": "Valse Caprice in A, op. 30 no. 1", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "Fauré", "t": "Dolly Suite for solo piano (all 6 movts) Hamelle", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "Fauré", "t": "Après un rêve and Nell (from Favourite Melodies arranged by Grainger)", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "Ferguson", "t": "Piano Sonata in F minor, op. 8", "nat": "Irish", "era": "Modern", "focus": ["Dramatic expression", "Irish character", "Structural integrity"] },
  { "c": "Fišer", "t": "Sonata no. 1", "nat": "Czech", "era": "Modern", "focus": ["Contemporary technique", "Czech character", "Modern harmony"] },
  { "c": "Fricker", "t": "Studies, op. 38, nos. 2 and 4", "nat": "English", "era": "Modern", "focus": ["English character", "Modern technique", "Technical clarity"] },
  { "c": "Gershwin", "t": "Rhapsody in Blue (original piano solo version)", "nat": "American", "era": "Modern", "focus": ["Jazz influence", "American character", "Rhythmic vitality"] },
  { "c": "Ginastera", "t": "12 American Preludes, any four or more contrasting", "nat": "Argentine", "era": "Modern", "focus": ["Argentine character", "Rhythmic vitality", "Modern technique"] },
  { "c": "Ginastera", "t": "Danzas Argentinas, op. 2", "nat": "Argentine", "era": "Modern", "focus": ["Argentine character", "Rhythmic vitality", "Modern technique"] },
  { "c": "Ginastera", "t": "Suite de danzas criollas, op. 15 (all 5 movts)", "nat": "Argentine", "era": "Modern", "focus": ["Argentine character", "Rhythmic vitality", "Modern technique"] },
  { "c": "Glazunov", "t": "Theme and Variations, op. 72", "nat": "Russian", "era": "Romantic", "focus": ["Russian character", "Romantic expression", "Technical brilliance"] },
  { "c": "Gnattali", "t": "Manhosamente Grupo Editorial Todamérica", "nat": "Brazilian", "era": "Modern", "focus": ["Brazilian character", "Jazz influence", "Expressive phrasing"] },
  { "c": "Godowsky", "t": "Java Suite, any two or more movts", "nat": "Polish", "era": "Romantic", "focus": ["Transcription mastery", "Technical virtuosity", "Romantic style"] },
  { "c": "Gorecki", "t": "Four Preludes, op. 1", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Modern style", "Stark expression"] },
  { "c": "Gorecki", "t": "Sonata, op. 6", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Modern style", "Stark expression"] },
  { "c": "Gottschalk", "t": "Souvenir de Porto Rico (Marche des Gibaros), op. 31 or Souvenirs d’Andalousie, Caprice de concert sur la caña, op. 22", "nat": "American", "era": "Romantic", "focus": ["American character", "Creole influence", "Romantic virtuosity"] },
  { "c": "Gottschalk", "t": "The Banjo, op. 15", "nat": "American", "era": "Romantic", "focus": ["American character", "Creole influence", "Romantic virtuosity"] },
  { "c": "Grainger", "t": "To a Nordic Princess", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Folk elements", "Energetic playing"] },
  { "c": "Granados", "t": "Allegro de concierto", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Granados", "t": "Goyescas, any one or more", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Grieg", "t": "Ballade in G minor, op. 24", "nat": "Norwegian", "era": "Romantic", "focus": ["Norwegian character", "Romantic expression", "Folk elements"] },
  { "c": "Grieg", "t": "Improvisations on 2 Norwegian Folk Songs, op. 29 (both)", "nat": "Norwegian", "era": "Romantic", "focus": ["Norwegian character", "Romantic expression", "Folk elements"] },
  { "c": "Griffes", "t": "Roman Sketches, op. 7, The Fountain of the Acqua Paola (no. 3) plus one from nos. 1, 2, 4", "nat": "American", "era": "Modern", "focus": ["Impressionist colour", "American style", "Atmospheric writing"] },
  { "c": "Hamilton", "t": "September and October or November and December (from Months & Metamorphoses)", "nat": "Scottish", "era": "Modern", "focus": ["Scottish character", "Modern style", "Expressive phrasing"] },
  { "c": "Haydn", "t": "Sonata in E♭, Hob XVI/45", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "Haydn", "t": "Sonata in C, Hob XVI/50", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "Haydn", "t": "Sonata in E♭, Hob XVI/52", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Wit and character", "Clear phrasing"] },
  { "c": "Hindemith", "t": "Interludium and Fuga nona in B♭ (from Ludus Tonalis)", "nat": "German", "era": "Modern", "focus": ["Neo-Classical style", "Linear texture", "Modern harmony"] },
  { "c": "Hindemith", "t": "Interludium and Fuga seconda in G (from Ludus Tonalis)", "nat": "German", "era": "Modern", "focus": ["Neo-Classical style", "Linear texture", "Modern harmony"] },
  { "c": "Hindemith", "t": "Sonata no. 2 in G", "nat": "German", "era": "Modern", "focus": ["Neo-Classical style", "Linear texture", "Modern harmony"] },
  { "c": "Hindemith", "t": "Tanzstücke, op. 19 (all 4 movts)", "nat": "German", "era": "Modern", "focus": ["Neo-Classical style", "Linear texture", "Modern harmony"] },
  { "c": "Holland", "t": "Sonata for Piano (1952) EMI Australia", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Expressive phrasing", "Modern style"] },
  { "c": "Honegger", "t": "3 Pièces (Prélude, Hommage à Ravel, Danse)", "nat": "Swiss", "era": "Modern", "focus": ["Modern harmony", "Rhythmic drive", "Neo-Classical style"] },
  { "c": "Hummel", "t": "Sonata no. 3 in F minor, op. 20", "nat": "Austrian", "era": "Classical", "focus": ["Classical brilliance", "Technical fluency", "Elegant phrasing"] },
  { "c": "Hyde", "t": "Brownhill Creek in Spring", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Impressionist colour", "Expressive phrasing"] },
  { "c": "Ireland", "t": "Amberley Wild Brooks", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Ireland", "t": "April", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Ireland", "t": "Chelsea Reach (from London Pieces)", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Ireland", "t": "Ragamuffin", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Ireland", "t": "Rhapsody", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Ireland", "t": "Sarnia", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Ituarte", "t": "Ecos de México, Capricho de Concierto Performer’s Edition", "nat": "Mexican", "era": "Romantic", "focus": ["Mexican character", "Romantic expression", "Virtuosic display"] },
  { "c": "Janáček", "t": "Sonata I/X/1905", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Folk elements", "Modern harmony"] },
  { "c": "Janáček", "t": "Zdenčiny Variace (Zdenka’s Variations)", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Folk elements", "Modern harmony"] },
  { "c": "Johnson", "t": "Jazz Impromptu no. 1 Score Exchange", "nat": "American", "era": "Contemporary", "focus": ["Jazz influence", "American character", "Improvisatory style"] },
  { "c": "Jongen", "t": "Two Pieces, op. 33, Clair de lune (no. 1) and Soleil à midi (no. 2)", "nat": "Belgian", "era": "Romantic", "focus": ["Belgian character", "Romantic expression", "Impressionist colour"] },
  { "c": "Kabalevsky", "t": "Sonata no. 3 in F, op. 46", "nat": "Russian", "era": "Modern", "focus": ["Soviet style", "Rhythmic vitality", "Clear texture"] },
  { "c": "Kalomiris", "t": "Five Preludes, any three or more Piano Rare Scores", "nat": "Greek", "era": "Modern", "focus": ["Greek character", "Modern style", "Romantic expression"] },
  { "c": "Kaprálová", "t": "Grotesque Passacaglia Amos", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Modern style", "Expressive intensity"] },
  { "c": "Knussen", "t": "Prayer Bell Sketch", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary style", "Atmospheric writing"] },
  { "c": "Kurtág", "t": "Les adieux (from Játékok (Games) vol. VI)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Hungarian character", "Contemporary miniature", "Expressive intensity"] },
  { "c": "Lecuona", "t": "Ante el Escorial (original version, not ossia) (from Lecuona Piano Music) Hal Leonard", "nat": "Cuban", "era": "Modern", "focus": ["Cuban character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "Leighton", "t": "Fantasia contrappuntistica Novello", "nat": "English", "era": "Modern", "focus": ["English character", "Modern harmony", "Contrapuntal mastery"] },
  { "c": "Leighton", "t": "Six Studies (Study Variations), op. 56, any one or more Novello", "nat": "English", "era": "Modern", "focus": ["English character", "Modern harmony", "Contrapuntal mastery"] },
  { "c": "Leighton", "t": "Study no. 4 and Study no. 5 (from Five Studies) Novello", "nat": "English", "era": "Modern", "focus": ["English character", "Modern harmony", "Contrapuntal mastery"] },
  { "c": "Liebermann", "t": "Nocturne no. 2, op. 31 or Nocturne no. 8, op. 85", "nat": "American", "era": "Contemporary", "focus": ["Contemporary style", "Lyrical expression", "Technical mastery"] },
  { "c": "Ligeti", "t": "Capriccios 1 and 2", "nat": "Hungarian", "era": "Contemporary", "focus": ["Micropolyphony", "Contemporary technique", "Complex texture"] },
  { "c": "Ligeti", "t": "Musica ricercata (1951–53), any four", "nat": "Hungarian", "era": "Contemporary", "focus": ["Micropolyphony", "Contemporary technique", "Complex texture"] },
  { "c": "Lilburn", "t": "Sonata (1949) or Sonata (1956)", "nat": "New Zealand", "era": "Modern", "focus": ["New Zealand character", "Modern style", "Expressive phrasing"] },
  { "c": "Liszt", "t": "Aux cyprès de la Villa d’Este, I or II (from Années de pèlerinage, 3rd year)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Ballade no. 2 in B minor", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Bénédiction de Dieu dans la solitude (no. 3 from Harmonies poétiques et religieuses, S173)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Chapelle de Guillaume Tell, Vallée d’Obermann or Les cloches de Genève (from Années de pèlerinage, 1st year)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Concert Studies, any one or more", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Douze études d’exécution transcendente, any one or more", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Hungarian Rhapsodies, any one or more", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Les jeux d’eaux à la Villa d’Este (from Années de pèlerinage, 3rd year)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Paganini Studies, any one or more", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Rhapsodie Espagnole", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Rigoletto, Concert Paraphrase", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Sonetto del Petrarca 104 (from Années de pèlerinage, 2nd year)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Either of the Two Légendes", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Louie", "t": "Put On Your Running Shoes", "nat": "Canadian", "era": "Contemporary", "focus": ["Canadian character", "Contemporary style", "Atmospheric writing"] },
  { "c": "MacDowell", "t": "Etude de Concert, op. 36", "nat": "American", "era": "Romantic", "focus": ["American character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Mathias", "t": "Toccata alla danza Allegro/OUP archive", "nat": "Welsh", "era": "Modern", "focus": ["Welsh character", "Modern style", "Technical clarity"] },
  { "c": "Matthews, C.", "t": "Eleven Studies in Velocity, any four or more", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary technique", "Technical mastery"] },
  { "c": "Mendelssohn", "t": "Andante and Rondo Capriccioso, op. 14", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "Mendelssohn", "t": "Fantasy in F# minor, op. 28", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "Mendelssohn", "t": "Prelude & Fugue in E minor, op. 35 no. 1", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "Mendelssohn", "t": "Prelude & Fugue in B minor, op. 35 no. 3", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "Mendelssohn", "t": "Songs Without Words, op. 38 no. 5 in A minor and/or op. 53 no. 6 in A", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "Mendelssohn", "t": "Variations serieuses, op. 54", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "Messiaen", "t": "La buse variable (no. XI from Catalogue d’oiseaux 7e livre) Leduc", "nat": "French", "era": "Modern", "focus": ["Colour and rhythm", "Spiritual expression", "Modern harmony"] },
  { "c": "Messiaen", "t": "Préludes, any one or more from nos. 2, 3, 4, 5, 6, 8", "nat": "French", "era": "Modern", "focus": ["Colour and rhythm", "Spiritual expression", "Modern harmony"] },
  { "c": "Messiaen", "t": "Vingt regards sur l’enfant-Jésus, any one from nos. 8, 11, 13, 14, 15, 16", "nat": "French", "era": "Modern", "focus": ["Colour and rhythm", "Spiritual expression", "Modern harmony"] },
  { "c": "Montsalvatge", "t": "Sonatina pour Yvette", "nat": "Spanish", "era": "Modern", "focus": ["Spanish character", "Cuban influence", "Modern style"] },
  { "c": "Moszkowski", "t": "Caprice Espagnol, op. 37", "nat": "Polish", "era": "Romantic", "focus": ["Romantic virtuosity", "Technical brilliance", "Dance character"] },
  { "c": "Mozart", "t": "Rondo in A minor, K 511", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "Mozart", "t": "Sonata in A minor, K 310", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "Mozart", "t": "Sonata in D, K 576", "nat": "Austrian", "era": "Classical", "focus": ["Classical form", "Elegance and clarity", "Melodic phrasing"] },
  { "c": "Muczynski", "t": "Desperate Measures (Paganini Variations), op. 48", "nat": "American", "era": "Modern", "focus": ["American character", "Modern harmony", "Clear texture"] },
  { "c": "Novák", "t": "Songs of Winter Nights (Písně zimních nocí), op. 30, any two contrasting", "nat": "Czech", "era": "Romantic", "focus": ["Czech character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Paderewski", "t": "Caprice-Waltz (no. 5 from Album de Mai, op. 10)", "nat": "Polish", "era": "Romantic", "focus": ["Polish character", "Romantic expression", "Pianistic idiom"] },
  { "c": "Palmgren", "t": "En route, op. 9", "nat": "Finnish", "era": "Romantic", "focus": ["Finnish character", "Impressionist colour", "Lyrical phrasing"] },
  { "c": "Pann", "t": "The Cheese Grater (a mean two-step for piano)", "nat": "American", "era": "Contemporary", "focus": ["American character", "Contemporary style", "Rhythmic vitality"] },
  { "c": "Piazzolla", "t": "Suite para piano, op. 2 (all 3 movts)", "nat": "Argentine", "era": "Contemporary", "focus": ["Argentine tango", "Rhythmic vitality", "Expressive phrasing"] },
  { "c": "Pick-Mangiagalli", "t": "Danse d’Olaf (no. 2 from Deux lunaires, op. 33)", "nat": "Italian", "era": "Modern", "focus": ["Italian character", "Dance style", "Colouristic writing"] },
  { "c": "Pierné", "t": "Etude de concert in C minor, op. 13 Leduc", "nat": "French", "era": "Romantic", "focus": ["French character", "Technical virtuosity", "Romantic style"] },
  { "c": "Ponce", "t": "Ballada Mexicana Peermusic", "nat": "Mexican", "era": "Romantic", "focus": ["Mexican character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Ponce", "t": "Jarabe (no. 10 from Etudes de concert) Piano Rare Scores", "nat": "Mexican", "era": "Romantic", "focus": ["Mexican character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Poulenc", "t": "15 Improvisations, at least four movts", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "Poulenc", "t": "Intermezzo in A♭", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "Poulenc", "t": "Mélancolie", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "Poulenc", "t": "Napoli suite (all 3 movts)", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "Price", "t": "Fantasie nègre no. 1 in E minor (from Black Women Composers: A Century of Piano Music, 1893-1990)", "nat": "American", "era": "Modern", "focus": ["African-American character", "Romantic expression", "Spiritual influence"] },
  { "c": "Prokofiev", "t": "Romeo & Juliet, op. 75, any two movts", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Sarcasms, op. 17 Forberg", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Sonata no. 1 in F minor, op. 1", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Sonata no. 2 in D minor, op. 14", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Sonata no. 3 in A minor, op. 28", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Sonata no. 4 in C minor, op. 29", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Sonata no. 5 in C, op. 38", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Suggestion diabolique, op. 4 no. 4", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Toccata, op. 11 Forberg", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Rachmaninov", "t": "Études-tableaux, op. 33, any two contrasting pieces", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "Rachmaninov", "t": "Études-tableaux, op. 39, any one or more", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "Rachmaninov", "t": "Morceaux de salon, op. 10, no. 5 or no. 7", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "Rachmaninov", "t": "Preludes, op. 23, any one or more from nos. 2, 4, 5, 9", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "Rachmaninov", "t": "Preludes, op. 32, any one or more from nos. 1, 2, 3, 4, 6, 8, 9, 11, 13", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "Rachmaninov", "t": "Six moments musicaux, op. 16, any one or more from nos. 1, 2, 4, 6", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "Rautavaara", "t": "Passionale", "nat": "Finnish", "era": "Contemporary", "focus": ["Finnish character", "Contemporary style", "Atmospheric writing"] },
  { "c": "Ravel", "t": "Jeux d’eau", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "Ravel", "t": "Menuet antique", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "Ravel", "t": "Miroirs, any one or more", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "Ravel", "t": "Ondine (from Gaspard de la nuit)", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "Ravel", "t": "Sonatine", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "Ravel", "t": "Toccata (from Le tombeau de Couperin)", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "Respighi", "t": "Six Pieces for Piano, Studio (no. 5) Ludwig 239. Rimsky-Korsakov, transc. Rachmaninov The Flight of the Bumblebee", "nat": "Italian", "era": "Modern", "focus": ["Italian character", "Romantic expression", "Colouristic writing"] },
  { "c": "Ritchie", "t": "24 Preludes, any three or more contrasting", "nat": "New Zealand", "era": "Contemporary", "focus": ["New Zealand character", "Contemporary style", "Expressive phrasing"] },
  { "c": "Ritchie", "t": "Music for Tristan (from Caricatures)", "nat": "New Zealand", "era": "Contemporary", "focus": ["New Zealand character", "Contemporary style", "Expressive phrasing"] },
  { "c": "Rodgers", "t": "My Favorite Things", "nat": "American", "era": "Modern", "focus": ["American character", "Jazz influence", "Lyrical melody"] },
  { "c": "Rodgers", "t": "The Carousel Waltz", "nat": "American", "era": "Modern", "focus": ["American character", "Jazz influence", "Lyrical melody"] },
  { "c": "Roxburgh", "t": "Sonata", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary style", "Technical clarity"] },
  { "c": "Rzewski", "t": "Down by the Riverside (from Squares & North American Ballads)", "nat": "American", "era": "Contemporary", "focus": ["Political expression", "Extended techniques", "Contemporary style"] },
  { "c": "Rzewski", "t": "Piano Piece IV (from 4 Pieces)", "nat": "American", "era": "Contemporary", "focus": ["Political expression", "Extended techniques", "Contemporary style"] },
  { "c": "Saint-Saëns", "t": "Allegro appassionato, op. 70", "nat": "French", "era": "Romantic", "focus": ["French character", "Technical brilliance", "Elegant phrasing"] },
  { "c": "Saint-Saëns", "t": "Études, op. 52 or op. 111, any one or more", "nat": "French", "era": "Romantic", "focus": ["French character", "Technical brilliance", "Elegant phrasing"] },
  { "c": "Saint-Saëns", "t": "Études for left hand alone, op. 135, any one or more", "nat": "French", "era": "Romantic", "focus": ["French character", "Technical brilliance", "Elegant phrasing"] },
  { "c": "Sancan", "t": "Toccata", "nat": "French", "era": "Modern", "focus": ["French character", "Technical virtuosity", "Modern style"] },
  { "c": "Say", "t": "Paganini Jazz (without final ‘extra’ variations)", "nat": "Turkish", "era": "Contemporary", "focus": ["Turkish character", "Jazz influence", "Virtuosic display"] },
  { "c": "Scarlatti, D", "t": "Two Sonatas in C minor, K 115 and K 116", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "Scarlatti, D", "t": "Sonata in B♭, K 544 and Sonata in B♭, K 545", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "Scarlatti, D", "t": "Sonata in G minor, K 426 and Sonata in G, K 427", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "Schmidt, H.", "t": "Sprint Echo North Music", "nat": "Canadian", "era": "Contemporary", "focus": ["Canadian character", "Contemporary style", "Technical clarity"] },
  { "c": "Schoenberg", "t": "5 Pieces, op. 23 Hansen", "nat": "Austrian", "era": "Modern", "focus": ["Atonal style", "Expressionist writing", "Twelve-tone technique"] },
  { "c": "Schoenberg", "t": "Klavierstücke, op. 11", "nat": "Austrian", "era": "Modern", "focus": ["Atonal style", "Expressionist writing", "Twelve-tone technique"] },
  { "c": "Schubert", "t": "Impromptu in B♭, D 935", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "Schubert", "t": "Sonata in A minor, op. 143 D 784", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "Schulhoff", "t": "5 études de jazz", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Jazz influence", "Modern style"] },
  { "c": "Schulhoff", "t": "Sonata no. 1 Panton", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Jazz influence", "Modern style"] },
  { "c": "Schumann, C", "t": "Romance in G minor, op. 21 no. 3", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "Harmonic richness"] },
  { "c": "Schumann, C", "t": "Variations de concert sur la cavatine du Pirate de Bellini, op. 8", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Lyrical phrasing", "Harmonic richness"] },
  { "c": "Schumann, R", "t": "Abegg Variations, op. 1", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Allegro, op. 8", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Carnival Jest (from Vienna, op. 26)", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Novellette in D, op. 21 no. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Novellette in F# minor, op. 21 no. 8", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Papillons, op. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Sonata in G minor, op. 22", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Scriabin", "t": "Etude in D# minor, op. 8 no. 12", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "Scriabin", "t": "Fantasie in B minor, op. 28", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "Scriabin", "t": "Poème tragique, op. 34 Belaieff", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "Scriabin", "t": "Sonata no. 1 in F minor, op. 6", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "Scriabin", "t": "Sonata no. 4 in F#, op. 30", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "Scriabin", "t": "Waltz in A♭, op. 38 Belaieff", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "Seiber", "t": "Scherzando capriccioso", "nat": "Hungarian", "era": "Modern", "focus": ["Hungarian character", "Jazz influence", "Modern style"] },
  { "c": "Serocki", "t": "Suite of Preludes, nos. 1, 2 and 3", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Modern technique", "Structural clarity"] },
  { "c": "Shostakovich", "t": "Preludes and Fugues, op. 87, any one or more of the following: - no. 4 in E minor - no. 15 in D♭ - no. 17 in A♭ - no. 24 in D minor", "nat": "Russian", "era": "Modern", "focus": ["Soviet style", "Dramatic expression", "Modern harmony"] },
  { "c": "Sibelius", "t": "Six Impromptus, op. 5, no. 5 in B minor", "nat": "Finnish", "era": "Romantic", "focus": ["Finnish character", "Romantic expression", "Atmospheric writing"] },
  { "c": "Skalkottas", "t": "Andante religioso (no. 1 from 32 Piano Pieces)", "nat": "Greek", "era": "Modern", "focus": ["Greek character", "Twelve-tone technique", "Expressive intensity"] },
  { "c": "Slavický", "t": "Variations on a Silent Chord Amos", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Contemporary style", "Variation technique"] },
  { "c": "Smetana", "t": "Concert Study: Na břehu mořském (On the Seashore) Bärenreiter Praha", "nat": "Czech", "era": "Romantic", "focus": ["Czech character", "Nationalist expression", "Romantic style"] },
  { "c": "Stevenson", "t": "Fugue on a Fragment of Chopin Ronald Stevenson", "nat": "Scottish", "era": "Modern", "focus": ["Scottish character", "Contrapuntal mastery", "Romantic expression"] },
  { "c": "Stevenson", "t": "Peter Grimes Fantasy", "nat": "Scottish", "era": "Modern", "focus": ["Scottish character", "Contrapuntal mastery", "Romantic expression"] },
  { "c": "Stravinsky", "t": "Étude in F#, op. 7 no. 4 (from The Stravinsky Piano Collection)", "nat": "Russian", "era": "Modern", "focus": ["Neo-Classical style", "Rhythmic drive", "Modern harmony"] },
  { "c": "Szymanowski", "t": "9 Preludes, op. 1, any two or more", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Impressionist colour", "Modern harmony"] },
  { "c": "Szymanowski", "t": "Études, op. 4, either nos. 1 and 2 or nos. 2 and 3", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Impressionist colour", "Modern harmony"] },
  { "c": "Takemitsu", "t": "Les yeux clos II", "nat": "Japanese", "era": "Contemporary", "focus": ["Japanese character", "Atmospheric writing", "Contemporary style"] },
  { "c": "Takemitsu", "t": "Rain-Tree Sketches, no. 1 and/or no. 2", "nat": "Japanese", "era": "Contemporary", "focus": ["Japanese character", "Atmospheric writing", "Contemporary style"] },
  { "c": "Taktakishvili", "t": "Poem Piano Rare Scores", "nat": "Georgian", "era": "Modern", "focus": ["Georgian character", "Modern style", "Lyrical expression"] },
  { "c": "Tchaikovsky", "t": "18 Pieces, op. 72, any one or more from: - Impromptu in F minor (no. 1) - Polacca de concert (no. 7) - Scherzo-fantasie (no. 10) - Chant élegiaque (no. 14)", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical expression", "Dramatic contrast"] },
  { "c": "Tchaikovsky", "t": "Theme and Variations in F, op. 19 no. 6", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical expression", "Dramatic contrast"] },
  { "c": "Tippett", "t": "Sonata no. 2", "nat": "English", "era": "Modern", "focus": ["English character", "Complex rhythm", "Modern harmony"] },
  { "c": "Tsontakis", "t": "Ghost Variations", "nat": "American", "era": "Contemporary", "focus": ["American character", "Contemporary style", "Variation technique"] },
  { "c": "Tubin", "t": "Ballade in the Form of a Chaconne on a Theme by Mart Saar", "nat": "Estonian", "era": "Modern", "focus": ["Estonian character", "Modern harmony", "Expressive phrasing"] },
  { "c": "Vierne", "t": "12 préludes, op. 36, any two or more contrasting", "nat": "French", "era": "Romantic", "focus": ["French organ style", "Romantic harmony", "Atmospheric writing"] },
  { "c": "Vine", "t": "Bagatelles, any three or more", "nat": "Australian", "era": "Contemporary", "focus": ["Australian character", "Contemporary technique", "Modern harmony"] },
  { "c": "Vladigerov", "t": "Autumn Elegy, op. 15 no. 2", "nat": "Bulgarian", "era": "Modern", "focus": ["Bulgarian character", "Romantic expression", "Technical brilliance"] },
  { "c": "Vladigerov", "t": "Humoresque in A, op. 15 no. 3", "nat": "Bulgarian", "era": "Modern", "focus": ["Bulgarian character", "Romantic expression", "Technical brilliance"] },
  { "c": "Voříšek", "t": "Sonata quasi una Fantasia, op. 20", "nat": "Czech", "era": "Classical", "focus": ["Classical-Romantic style", "Technical fluency", "Expressive phrasing"] },
  { "c": "Walker, R.", "t": "Five Capriccios, set 1 or set 2 Novello", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary style", "Technical mastery"] },
  { "c": "Weber", "t": "Rondo brillante in E♭, op. 62", "nat": "German", "era": "Romantic", "focus": ["Early Romantic style", "Brilliant passage work", "Dramatic expression"] },
  { "c": "Webern", "t": "Variations, op. 27", "nat": "Austrian", "era": "Modern", "focus": ["Serial technique", "Twelve-tone style", "Concentrated expression"] },
  { "c": "Wladigeroff", "t": "Three Pieces, op. 15, any one or more", "nat": "Bulgarian", "era": "Modern", "focus": ["Bulgarian character", "Romantic expression", "Technical brilliance"] },
  { "c": "Zahra", "t": "No. III from Constellations, op. 32", "nat": "Maltese", "era": "Contemporary", "focus": ["Maltese character", "Contemporary style", "Expressive phrasing"] },
  { "c": "Zhang", "t": "In That Place Wholly Faraway", "nat": "Chinese", "era": "Contemporary", "focus": ["Chinese character", "Contemporary style", "Expressive phrasing"] },
];