// Trinity College London Piano — FTCL Diploma Repertoire
// 2026 edition | Open pool — 155 works
// Performance: 42–48 min performance
// Source: trinitycollege.com/resource?id=8546

const DATA_TRINITY_FTCL = [
  { "c": "Adams", "t": "American Berserk", "nat": "American", "era": "Contemporary", "focus": ["Minimalist style", "American character", "Rhythmic energy"] },
  { "c": "Alkan", "t": "Concerto da camera in C# minor, op. 10 no. 2", "nat": "French", "era": "Romantic", "focus": ["Technical virtuosity", "Romantic expression", "Extended form"] },
  { "c": "Alkan", "t": "Etudes in All the Major Keys, op. 35 nos. 1-6, any two contrasting", "nat": "French", "era": "Romantic", "focus": ["Technical virtuosity", "Romantic expression", "Extended form"] },
  { "c": "Bacewicz", "t": "Piano Sonata no. 2", "nat": "Polish", "era": "Modern", "focus": ["Contemporary technique", "Polish character", "Rhythmic drive"] },
  { "c": "Bach, J S", "t": "Partita no. 6 in E minor, BWV 830", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Chaconne from Violin Partita no. 2 in D minor, BWV 1004", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Toccata, Adagio and Fugue in C, BWV 564", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Bach, J S", "t": "Passacaglia, BWV 582 (from The Virtuoso Piano Transcription Series vol. 12)", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Baroque style", "Structural clarity"] },
  { "c": "Balakirev", "t": "Impromptu on Themes from Two Preludes of Chopin Könemann", "nat": "Russian", "era": "Romantic", "focus": ["Russian character", "Romantic virtuosity", "Technical brilliance"] },
  { "c": "Balakirev", "t": "Islamey – Oriental Fantasy", "nat": "Russian", "era": "Romantic", "focus": ["Russian character", "Romantic virtuosity", "Technical brilliance"] },
  { "c": "Barber", "t": "Sonata in E♭ minor, op. 26", "nat": "American", "era": "Modern", "focus": ["American Romantic style", "Lyrical expression", "Expressive phrasing"] },
  { "c": "Bartók", "t": "Rhapsody, op. 1 (1904)", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "Bartók", "t": "Sonata", "nat": "Hungarian", "era": "Modern", "focus": ["Folk elements", "Percussive technique", "Modern harmony"] },
  { "c": "Bax", "t": "Sonata no. 1 in F# minor Chapple", "nat": "Irish", "era": "Romantic", "focus": ["Lyrical expression", "Impressionist colour", "Irish character"] },
  { "c": "Beethoven", "t": "Eroica Variations, op. 35", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in C, op. 53 ‘Waldstein’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in F minor, op. 57 ‘Appassionata’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in A, op. 101", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in B♭, op. 106 ‘Hammerklavier’", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in E, op. 109", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in A♭, op. 110", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Beethoven", "t": "Sonata in C minor, op. 111", "nat": "German", "era": "Classical", "focus": ["Dramatic expression", "Classical form", "Dynamic contrast"] },
  { "c": "Bennett", "t": "Suite de pièces, op. 24 (all 6 movts)", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary technique", "Structural clarity"] },
  { "c": "Bernstein", "t": "Piano Sonata Boosey 25. Bernstein, transc. Tenenbaum West Side Story Musicnotes", "nat": "American", "era": "Modern", "focus": ["American character", "Rhythmic vitality", "Jazz influence"] },
  { "c": "Boulez", "t": "Sonata no. 1 Amphion", "nat": "French", "era": "Contemporary", "focus": ["Serial technique", "French avant-garde", "Complex texture"] },
  { "c": "Bowen", "t": "Sonata no. 5 in F minor, op. 72", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Technical fluency"] },
  { "c": "Brahms", "t": "Sonata in C, op. 1", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Sonata in F# minor, op. 2", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Sonata in F minor, op. 5", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "11 Variations in D on an Original Theme, op. 21 no. 1", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Variations and Fugue on a Theme of Handel in B♭, op. 24", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Brahms", "t": "Variations on a Theme of Paganini in A minor, op. 35, either book 1 or book 2", "nat": "German", "era": "Romantic", "focus": ["Romantic depth", "Harmonic richness", "Structural integrity"] },
  { "c": "Bridge", "t": "Sonata, H 160", "nat": "English", "era": "Modern", "focus": ["Expressive phrasing", "English character", "Modern harmony"] },
  { "c": "Britten", "t": "Night Piece (Notturno)", "nat": "English", "era": "Modern", "focus": ["Atmospheric writing", "English character", "Modern harmony"] },
  { "c": "Busoni", "t": "Sonatina no. 6, Kammer-Fantasie über Bizets Carmen, KiV 284", "nat": "Italian", "era": "Modern", "focus": ["Transcription technique", "Virtuosic display", "Baroque transformation"] },
  { "c": "Carter", "t": "Caténaires", "nat": "American", "era": "Contemporary", "focus": ["American character", "Complex rhythm", "Contemporary style"] },
  { "c": "Chopin", "t": "Andante spianato and Grande Polonaise, op. 22", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Sonata no. 2 in B♭ minor, op. 35", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Sonata no. 3 in B minor, op. 58", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Variations on ‘La ci darem la mano’, op. 2", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Chopin", "t": "Transcriptions of Etudes op. 10 and op. 25, any (including those for the left hand alone)", "nat": "Polish", "era": "Romantic", "focus": ["Romantic phrasing", "Lyrical melody", "Pianistic idiom"] },
  { "c": "Copland", "t": "Piano Variations", "nat": "American", "era": "Modern", "focus": ["American character", "Rhythmic vitality", "Modern harmony"] },
  { "c": "Corigliano", "t": "Etude Fantasy", "nat": "American", "era": "Contemporary", "focus": ["American character", "Contemporary style", "Dramatic expression"] },
  { "c": "Czerny", "t": "Toccata in C, op. 92", "nat": "Austrian", "era": "Classical", "focus": ["Technical etude", "Rapid figurations", "Even tone"] },
  { "c": "Debussy", "t": "Etudes, either book 1 or book 2", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "Debussy", "t": "Feux d’artifice (from Preludes for Piano book 2)", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "Debussy", "t": "Prélude à l'après-midi d’un faune", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Pedal technique", "Atmospheric writing"] },
  { "c": "Dussek", "t": "Sonata in F# minor, op. 61, ‘Elégie harmonique’ Edition HH", "nat": "Czech", "era": "Classical", "focus": ["Classical-Romantic style", "Expressive phrasing", "Technical fluency"] },
  { "c": "Dutilleux", "t": "Trois préludes Leduc", "nat": "French", "era": "Contemporary", "focus": ["French character", "Complex harmony", "Atmospheric writing"] },
  { "c": "Eiges", "t": "Sonata-Toccata no. 4, op. 15", "nat": "Russian", "era": "Modern", "focus": ["Russian character", "Technical virtuosity", "Modern style"] },
  { "c": "Fábregas", "t": "Mirage", "nat": "Spanish", "era": "Contemporary", "focus": ["Spanish character", "Contemporary style", "Atmospheric writing"] },
  { "c": "de Falla", "t": "Fantasia Bætica", "nat": "Spanish", "era": "Modern", "focus": ["Spanish character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "Fauré", "t": "Ballade, op. 19", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "Fauré", "t": "Theme & Variations in C# minor, op. 73", "nat": "French", "era": "Romantic", "focus": ["French style", "Lyrical phrasing", "Harmonic subtlety"] },
  { "c": "Feinberg", "t": "Sonata no. 1, op. 1", "nat": "Russian", "era": "Modern", "focus": ["Russian character", "Modern style", "Technical brilliance"] },
  { "c": "Franck", "t": "Prélude, choral et fugue, FWV 21", "nat": "Belgian", "era": "Romantic", "focus": ["Romantic depth", "Cyclic form", "Harmonic richness"] },
  { "c": "Franck", "t": "Prélude, aria et final, FWV 23", "nat": "Belgian", "era": "Romantic", "focus": ["Romantic depth", "Cyclic form", "Harmonic richness"] },
  { "c": "Gershwin", "t": "7 Virtuoso Etudes, any one or more Ivory Classics", "nat": "American", "era": "Modern", "focus": ["Jazz influence", "American character", "Rhythmic vitality"] },
  { "c": "Godowsky", "t": "Prelude and Fugue on B.A.C.H. for left hand alone", "nat": "Polish", "era": "Romantic", "focus": ["Transcription mastery", "Technical virtuosity", "Romantic style"] },
  { "c": "Grainger", "t": "In Dahomey (Cakewalk Smasher) Peters (out of print)", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Folk elements", "Energetic playing"] },
  { "c": "Griffes", "t": "Three Tone Pictures, op. 5 (all 3)", "nat": "American", "era": "Modern", "focus": ["Impressionist colour", "American style", "Atmospheric writing"] },
  { "c": "Gubaidulina", "t": "Chaconne", "nat": "Russian", "era": "Contemporary", "focus": ["Spiritual expression", "Complex texture", "Contemporary style"] },
  { "c": "Hamelin", "t": "Étude no. 3 in B minor ‘after Paganini-Liszt’", "nat": "Canadian", "era": "Contemporary", "focus": ["Virtuosic technique", "Contemporary style", "Technical mastery"] },
  { "c": "Hamelin", "t": "Etude no. 6 in D minor ‘Omaggio a Domenico Scarlatti’", "nat": "Canadian", "era": "Contemporary", "focus": ["Virtuosic technique", "Contemporary style", "Technical mastery"] },
  { "c": "Hamelin", "t": "Toccata on L’homme armé", "nat": "Canadian", "era": "Contemporary", "focus": ["Virtuosic technique", "Contemporary style", "Technical mastery"] },
  { "c": "Hindemith", "t": "Sonata no. 3 in B♭", "nat": "German", "era": "Modern", "focus": ["Neo-Classical style", "Linear texture", "Modern harmony"] },
  { "c": "Horowitz", "t": "Carmen Variations 1968 (2010 edition, L Edson Jeffery) waltercosand.com", "nat": "Russian", "era": "Modern", "focus": ["Virtuosic transcription", "Romantic brilliance", "Technical mastery"] },
  { "c": "Hummel", "t": "Sonata no. 5 in F# minor, op. 81", "nat": "Austrian", "era": "Classical", "focus": ["Classical brilliance", "Technical fluency", "Elegant phrasing"] },
  { "c": "Hyde", "t": "Firewheel", "nat": "Australian", "era": "Modern", "focus": ["Australian character", "Impressionist colour", "Expressive phrasing"] },
  { "c": "Ireland", "t": "Equinox", "nat": "English", "era": "Romantic", "focus": ["English character", "Romantic expression", "Lyrical phrasing"] },
  { "c": "Ives", "t": "The Celestial Railroad AMP (archive)", "nat": "American", "era": "Modern", "focus": ["American character", "Experimental technique", "Polytonality"] },
  { "c": "Kaprálová", "t": "Sonata appassionata, op. 6 Amos", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Modern style", "Expressive intensity"] },
  { "c": "Kapustin", "t": "3 Impromptus, op. 66", "nat": "Ukrainian", "era": "Contemporary", "focus": ["Jazz influence", "Technical virtuosity", "Contemporary style"] },
  { "c": "Kapustin", "t": "5 Études in Different Intervals", "nat": "Ukrainian", "era": "Contemporary", "focus": ["Jazz influence", "Technical virtuosity", "Contemporary style"] },
  { "c": "Kapustin", "t": "8 Concert Etudes, op. 40, any one or more", "nat": "Ukrainian", "era": "Contemporary", "focus": ["Jazz influence", "Technical virtuosity", "Contemporary style"] },
  { "c": "Kapustin", "t": "Sonata no. 12, op. 102", "nat": "Ukrainian", "era": "Contemporary", "focus": ["Jazz influence", "Technical virtuosity", "Contemporary style"] },
  { "c": "Kodály", "t": "Dances of Marosszek", "nat": "Hungarian", "era": "Modern", "focus": ["Hungarian character", "Folk elements", "Modern harmony"] },
  { "c": "Lecuona", "t": "Malagueña", "nat": "Cuban", "era": "Modern", "focus": ["Cuban character", "Rhythmic vitality", "Colouristic writing"] },
  { "c": "Liebermann", "t": "Gargoyles, op. 29 (all 4 movts)", "nat": "American", "era": "Contemporary", "focus": ["Contemporary style", "Lyrical expression", "Technical mastery"] },
  { "c": "Liebermann", "t": "Three Impromptus, op. 68", "nat": "American", "era": "Contemporary", "focus": ["Contemporary style", "Lyrical expression", "Technical mastery"] },
  { "c": "Ligeti", "t": "Études pour piano (book 1) (all as a set)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Micropolyphony", "Contemporary technique", "Complex texture"] },
  { "c": "Liszt", "t": "Après une lecture du Dante (Fantasia quasi sonata)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Funérailles (no. 7 from Harmonies poetiques et religieuses, S173)", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Grand galop chromatique, S219", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt", "t": "Sonata in B minor", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic technique", "Romantic expression", "Pianistic brilliance"] },
  { "c": "Liszt/Beethoven", "t": "Capriccio alla Turca from The Ruins of Athens", "nat": "Hungarian", "era": "Romantic", "focus": ["Transcription mastery", "Virtuosic display", "Romantic style"] },
  { "c": "Liszt/Gounod", "t": "Waltz from Faust – opera paraphrase", "nat": "Hungarian", "era": "Romantic", "focus": ["Opera paraphrase", "Virtuosic display", "Romantic style"] },
  { "c": "Longás", "t": "Torres Aragón", "nat": "Spanish", "era": "Modern", "focus": ["Spanish character", "Dance character", "Colouristic writing"] },
  { "c": "Lyapunov", "t": "Variations and Fugue on a Russian Theme, op. 49 Zimmermann", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Technical brilliance", "Expressive phrasing"] },
  { "c": "MacMillan", "t": "Piano Sonata", "nat": "Scottish", "era": "Contemporary", "focus": ["Scottish character", "Contemporary style", "Expressive intensity"] },
  { "c": "Martin", "t": "F No. VIII from Eight Preludes", "nat": "Swiss", "era": "Modern", "focus": ["Swiss character", "Modern harmony", "Expressive phrasing"] },
  { "c": "Martinů", "t": "Sonata no. 1", "nat": "Czech", "era": "Modern", "focus": ["Czech character", "Neo-Classical style", "Rhythmic vitality"] },
  { "c": "Medtner", "t": "Sonata Tragica, op. 39 no. 5", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Complex texture", "Structural integrity"] },
  { "c": "Mendelssohn", "t": "Sonata in B♭, op. 106 any reliable edition 96. Mendelssohn, transc. Rachmaninov Scherzo from A Midsummer Night’s Dream", "nat": "German", "era": "Romantic", "focus": ["Romantic grace", "Technical fluency", "Lyrical expression"] },
  { "c": "Messiaen", "t": "Quatre études de rythme, any one or more", "nat": "French", "era": "Modern", "focus": ["Colour and rhythm", "Spiritual expression", "Modern harmony"] },
  { "c": "Morel", "t": "F Étude de Sonorité no. 2 (from Deux études de sonorité)", "nat": "Canadian", "era": "Modern", "focus": ["Canadian character", "Technical brilliance", "Modern style"] },
  { "c": "Moszkowski", "t": "15 Études de virtuosité, op. 72, any two", "nat": "Polish", "era": "Romantic", "focus": ["Romantic virtuosity", "Technical brilliance", "Dance character"] },
  { "c": "Mussorgsky", "t": "Pictures at an Exhibition (all)", "nat": "Russian", "era": "Romantic", "focus": ["Russian character", "Character pieces", "Orchestral transcription"] },
  { "c": "Poulenc", "t": "Caprice in C (d’après la Finale du Bal masqué)", "nat": "French", "era": "Modern", "focus": ["French character", "Wit and irony", "Neo-Classical style"] },
  { "c": "Prokofiev", "t": "Sonata no. 6 in A, op. 82", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Sonata no. 7 in B♭, op. 83", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Sonata no. 8 in B♭, op. 84", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Prokofiev", "t": "Sonata no. 9 in C, op. 103", "nat": "Russian", "era": "Modern", "focus": ["Percussive technique", "Modern harmony", "Rhythmic drive"] },
  { "c": "Rachmaninov", "t": "Sonata no. 2 in B♭ minor, op. 36", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "Rachmaninov", "t": "Variations on a Theme of Chopin, op. 22", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "Rachmaninov", "t": "Variations on a Theme of Corelli, op. 42", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "Rachmaninov", "t": "Italian Polka", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical melody", "Pianistic richness"] },
  { "c": "Ravel", "t": "Gaspard de la nuit", "nat": "French", "era": "Modern", "focus": ["French impressionism", "Technical precision", "Colouristic writing"] },
  { "c": "Reger", "t": "Variations and Fugue on a Theme of Bach, op. 81", "nat": "German", "era": "Romantic", "focus": ["Romantic polyphony", "Contrapuntal mastery", "Technical brilliance"] },
  { "c": "Rihm", "t": "Klavierstück no. 5", "nat": "German", "era": "Contemporary", "focus": ["Contemporary style", "German expressionism", "Complex texture"] },
  { "c": "Roslavets", "t": "Sonata no. 1", "nat": "Russian", "era": "Modern", "focus": ["Russian character", "Modern style", "Technical clarity"] },
  { "c": "Rossini", "t": "Figaro’s Aria scorser.com", "nat": "Italian", "era": "Romantic", "focus": ["Opera transcription", "Bel canto style", "Virtuosic display"] },
  { "c": "Rzewski", "t": "Winnsboro Cotton Mill Blues or Which Side are You On? (from Squares & North American Ballads)", "nat": "American", "era": "Contemporary", "focus": ["Political expression", "Extended techniques", "Contemporary style"] },
  { "c": "Saint-Saëns", "t": "Danse macabre, op. 40", "nat": "French", "era": "Romantic", "focus": ["French character", "Technical brilliance", "Elegant phrasing"] },
  { "c": "Scarlatti, D", "t": "Sonata in D, K 119", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Binary form", "Keyboard brilliance"] },
  { "c": "Schlözer", "t": "2 Etudes, op. 1, no.1 or both Musescore", "nat": "Russian", "era": "Romantic", "focus": ["Romantic style", "Technical brilliance", "Expressive phrasing"] },
  { "c": "Schubert", "t": "Sonata in C minor, D 958", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "Schubert", "t": "Sonata in A, D 959", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "Schubert", "t": "Sonata in B♭, D 960", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "Schubert", "t": "Wanderer Fantasie, op. 15", "nat": "Austrian", "era": "Romantic", "focus": ["Classical-Romantic transition", "Lyrical expression", "Song-like phrasing"] },
  { "c": "Schumann, R", "t": "Carnaval, op. 9", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Fantasy in C, op. 17", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Kreisleriana, op. 16", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Sonata in F# minor, op. 11", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Sonata in F minor, op. 14", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Symphonic Études, op. 13", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Schumann, R", "t": "Toccata in C, op. 7", "nat": "German", "era": "Romantic", "focus": ["Romantic expression", "Character pieces", "Inner voices"] },
  { "c": "Scriabin", "t": "Sonata no. 8, op. 66", "nat": "Russian", "era": "Romantic", "focus": ["Late Romantic mysticism", "Complex harmony", "Expressive phrasing"] },
  { "c": "Serocki", "t": "Suite of Preludes, nos. 5, 6 and 7", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Modern technique", "Structural clarity"] },
  { "c": "Shchedrin", "t": "2 Polyphonic Pieces (both) Muzyka", "nat": "Russian", "era": "Contemporary", "focus": ["Russian character", "Contemporary style", "Rhythmic vitality"] },
  { "c": "Smetana", "t": "Macbeth and the Witches", "nat": "Czech", "era": "Romantic", "focus": ["Czech character", "Nationalist expression", "Romantic style"] },
  { "c": "Smetana", "t": "Sny (Rêves/Dreams), Zaniklé Štěstí (Lost Happiness) (no. 1) and Slavnost českých venkovanů (Festival of Czech Country Folk) (no. 6)", "nat": "Czech", "era": "Romantic", "focus": ["Czech character", "Nationalist expression", "Romantic style"] },
  { "c": "Smetana", "t": "Kaan Vltava (The Moldau) (from Má Vlast) Performer’s Edition", "nat": "Czech", "era": "Romantic", "focus": ["Czech character", "Nationalist expression", "Romantic style"] },
  { "c": "Sorabji", "t": "Fantasiettina Bardic", "nat": "English", "era": "Modern", "focus": ["Complex texture", "Extreme duration", "Virtuosic writing"] },
  { "c": "Stevenson", "t": "Beltane Bonfire", "nat": "Scottish", "era": "Modern", "focus": ["Scottish character", "Contrapuntal mastery", "Romantic expression"] },
  { "c": "Strauss, J.", "t": "Tritsch-Tratsch Polka", "nat": "Austrian", "era": "Romantic", "focus": ["Dance transcription", "Viennese waltz style", "Virtuosic display"] },
  { "c": "Strauss, J.", "t": "Concert Paraphrase on ‘Wine, Women and Song’ Cranz", "nat": "Austrian", "era": "Romantic", "focus": ["Dance transcription", "Viennese waltz style", "Virtuosic display"] },
  { "c": "Stravinsky", "t": "Four Études (from The Stravinsky Piano Collection)", "nat": "Russian", "era": "Modern", "focus": ["Neo-Classical style", "Rhythmic drive", "Modern harmony"] },
  { "c": "Stravinsky", "t": "Piano Rag Music", "nat": "Russian", "era": "Modern", "focus": ["Neo-Classical style", "Rhythmic drive", "Modern harmony"] },
  { "c": "Stravinsky", "t": "Serenade in A", "nat": "Russian", "era": "Modern", "focus": ["Neo-Classical style", "Rhythmic drive", "Modern harmony"] },
  { "c": "Stravinsky", "t": "Trois mouvements de Pétrouchka", "nat": "Russian", "era": "Modern", "focus": ["Neo-Classical style", "Rhythmic drive", "Modern harmony"] },
  { "c": "Stravinsky", "t": "Oiseau de feu: Danse infernale, Berceuse and Finale", "nat": "Russian", "era": "Modern", "focus": ["Neo-Classical style", "Rhythmic drive", "Modern harmony"] },
  { "c": "Szymanowski", "t": "Masques, op. 34", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Impressionist colour", "Modern harmony"] },
  { "c": "Szymanowski", "t": "Métopes, op. 29", "nat": "Polish", "era": "Modern", "focus": ["Polish character", "Impressionist colour", "Modern harmony"] },
  { "c": "Talma", "t": "Sonata no. 2", "nat": "American", "era": "Modern", "focus": ["American character", "Serial technique", "Expressive phrasing"] },
  { "c": "Tchaikovsky", "t": "Dance of the Four Swans Ivory Classics", "nat": "Russian", "era": "Romantic", "focus": ["Russian Romantic style", "Lyrical expression", "Dramatic contrast"] },
  { "c": "Tippett", "t": "Sonata no. 3", "nat": "English", "era": "Modern", "focus": ["English character", "Complex rhythm", "Modern harmony"] },
  { "c": "Tippett", "t": "Sonata no. 4", "nat": "English", "era": "Modern", "focus": ["English character", "Complex rhythm", "Modern harmony"] },
  { "c": "Villa-Lobos", "t": "A Prole do bebê, Suite no. 1 (all 8 movts)", "nat": "Brazilian", "era": "Modern", "focus": ["Brazilian character", "Folk elements", "Modern technique"] },
  { "c": "Vine", "t": "Piano Sonata no. 1", "nat": "Australian", "era": "Contemporary", "focus": ["Australian character", "Contemporary technique", "Modern harmony"] },
  { "c": "Vine", "t": "Piano Sonata no. 3", "nat": "Australian", "era": "Contemporary", "focus": ["Australian character", "Contemporary technique", "Modern harmony"] },
  { "c": "Vladigerov", "t": "Dilmano Dilbero Variations, op. 3", "nat": "Bulgarian", "era": "Modern", "focus": ["Bulgarian character", "Romantic expression", "Technical brilliance"] },
  { "c": "Weber", "t": "Sonata no. 1 in C, op. 24", "nat": "German", "era": "Romantic", "focus": ["Early Romantic style", "Brilliant passage work", "Dramatic expression"] },
  { "c": "Weissenberg", "t": "Six arrangements of songs sung by Charles Trenet (all)", "nat": "Bulgarian", "era": "Contemporary", "focus": ["Song arrangement", "Contemporary style", "Technical brilliance"] },
  { "c": "Wilkinson", "t": "Five Amori Paintings", "nat": "English", "era": "Contemporary", "focus": ["English character", "Contemporary style", "Expressive phrasing"] },
];