// Trinity College London Piano — Grade 3
// 2023 Syllabus | Flat open pool (no lists/groups)
// Total: 57 pieces
// Source: trinitycollege.com/piano-repertoire

const DATA_TRINITY_G3 = [
  { "c": "ARENS, E.", "t": "Nocturne (from Recital Collection for Piano, Grade 3)", "nat": "German", "era": "Contemporary", "focus": ["Atmospheric playing", "Singing tone", "Simple phrasing"] },
  { "c": "BACH, J.S.", "t": "Minuet in G minor (BWV Anh. 115)", "nat": "German", "era": "Baroque", "focus": ["Baroque style", "Two-voice texture", "Clear articulation"] },
  { "c": "BARTÓK, B.", "t": "Teasing Song (No. 39 from For Children, Vol. 1)", "nat": "Hungarian", "era": "Modern", "focus": ["Folk character", "Simple rhythm", "Short phrases"] },
  { "c": "BÉRA-TAGRINE, N.", "t": "Mexican Hat Dance (from Recital Collection for Piano, Grade 3)", "nat": "French", "era": "Contemporary", "focus": ["Dance character", "Rhythmic precision", "Simple coordination"] },
  { "c": "BOBER, M.", "t": "Blue Bayou (from Recital Collection for Piano, Grade 3)", "nat": "American", "era": "Contemporary", "focus": ["Blues character", "Lyrical melody", "Simple phrasing"] },
  { "c": "BRAHMS, J.", "t": "Waltz in A flat, Op. 39 No. 15 (simplified)", "nat": "German", "era": "Romantic", "focus": ["Waltz style", "Lyrical phrasing", "Romantic character"] },
  { "c": "BULLARD, A.", "t": "Waltz of the Robots (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Contemporary", "focus": ["Mechanical character", "Waltz rhythm", "Quirky style"] },
  { "c": "CAINE, U.", "t": "Prelude (from Recital Collection for Piano, Grade 3)", "nat": "American", "era": "Contemporary", "focus": ["Jazz-influenced", "Simple phrasing", "Expressive touch"] },
  { "c": "CHOPIN, F.", "t": "Mazurka in F, Op. 68 No. 3 (posth.)", "nat": "Polish", "era": "Romantic", "focus": ["Mazurka rhythm", "Folk character", "Expressive phrasing"] },
  { "c": "CLEMENTI, M.", "t": "Sonatina in C, Op. 36 No. 1 (1st mvt)", "nat": "Italian", "era": "Classical", "focus": ["Classical sonatina", "Clear phrasing", "Scale passages"] },
  { "c": "CROSLAND, J.", "t": "Rock Hard (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Contemporary", "focus": ["Rock style", "Strong rhythm", "Simple coordination"] },
  { "c": "DEBUSSY, C.", "t": "La Fille aux cheveux de lin (simplified arr.)", "nat": "French", "era": "Romantic", "focus": ["Impressionist colour", "Pentatonic melody", "Gentle touch"] },
  { "c": "DUNCUMB, J.", "t": "Menuet (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Baroque", "focus": ["Baroque dance", "Clear phrasing", "Simple ornamentation"] },
  { "c": "EINAUDI, L.", "t": "L'Origine Nascosta (simplified arr.)", "nat": "Italian", "era": "Contemporary", "focus": ["Minimalist style", "Simple ostinato", "Atmospheric playing"] },
  { "c": "ELGAR, E.", "t": "Salut d'amour, Op. 12 (simplified arr.)", "nat": "English", "era": "Romantic", "focus": ["Lyrical melody", "Romantic phrasing", "Singing tone"] },
  { "c": "GRIEG, E.", "t": "Arietta, Op. 12 No. 1", "nat": "Norwegian", "era": "Romantic", "focus": ["Lyrical melody", "Simple texture", "Expressive phrasing"] },
  { "c": "GURLITT, C.", "t": "Scherzo, Op. 130 No. 8", "nat": "German", "era": "Romantic", "focus": ["Light touch", "Playful character", "Clear phrasing"] },
  { "c": "HANDEL, G.F.", "t": "Sarabande in D minor (from Suite in D minor, HWV 437)", "nat": "German", "era": "Baroque", "focus": ["Baroque dance", "Sustained phrasing", "Expressive playing"] },
  { "c": "HARRIS, P.", "t": "Midnight Tango (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Contemporary", "focus": ["Tango character", "Rhythmic drive", "Expressive phrasing"] },
  { "c": "HAYDN, J.", "t": "Andante in F (from Piano Sonata in F, Hob. XVI/9)", "nat": "Austrian", "era": "Classical", "focus": ["Classical style", "Singing melody", "Balanced phrasing"] },
  { "c": "HISAISHI, J.", "t": "One Summer's Day (from Spirited Away, arr.)", "nat": "Japanese", "era": "Contemporary", "focus": ["Film music", "Lyrical melody", "Atmospheric playing"] },
  { "c": "KABALEVSKY, D.", "t": "Toccatina, Op. 27 No. 12", "nat": "Russian", "era": "Modern", "focus": ["Staccato technique", "Rhythmic precision", "Clear articulation"] },
  { "c": "KHACHATURIAN, A.", "t": "Ivan Sings (from Children's Album)", "nat": "Armenian", "era": "Modern", "focus": ["Folk character", "Lyrical melody", "Simple texture"] },
  { "c": "LANE, R.", "t": "Desert Wind (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Modal flavour", "Simple ostinato"] },
  { "c": "MENDELSSOHN, F.", "t": "Song Without Words, Op. 19 No. 2", "nat": "German", "era": "Romantic", "focus": ["Singing melody", "Inner voices", "Romantic phrasing"] },
  { "c": "MOZART, W.A.", "t": "Minuet in G, K. 1", "nat": "Austrian", "era": "Classical", "focus": ["Classical minuet", "Clear phrasing", "Even touch"] },
  { "c": "NORTON, C.", "t": "Razzmatazz (from Microjazz Collection 2)", "nat": "English", "era": "Contemporary", "focus": ["Jazz style", "Simple syncopation", "Swing character"] },
  { "c": "PAPP, L.", "t": "Capriccio (from Recital Collection for Piano, Grade 3)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Playful character", "Light touch", "Simple coordination"] },
  { "c": "PESCETTI, G.B.", "t": "Presto in C minor (from Recital Collection for Piano, Grade 3)", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Rapid passages", "Clear articulation"] },
  { "c": "PROKOFIEV, S.", "t": "Tarantella, Op. 65 No. 4", "nat": "Russian", "era": "Modern", "focus": ["Dance character", "Staccato playing", "Rhythmic drive"] },
  { "c": "PURCELL, H.", "t": "Prelude in A minor (Z. 652)", "nat": "English", "era": "Baroque", "focus": ["Baroque prelude", "Ornamentation", "Expressive playing"] },
  { "c": "RAMSKILL, T.", "t": "Stargazing (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Sparse texture", "Tonal sensitivity"] },
  { "c": "REGER, M.", "t": "Humoreske, Op. 44 No. 6", "nat": "German", "era": "Romantic", "focus": ["Humorous character", "Light touch", "Simple phrasing"] },
  { "c": "SATIE, E.", "t": "Gnossienne No. 3", "nat": "French", "era": "Romantic", "focus": ["Atmospheric playing", "Simple ostinato", "Expressive freedom"] },
  { "c": "SCARLATTI, D.", "t": "Sonata in C, K. 159", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Ornaments", "Binary form"] },
  { "c": "SCHUBERT, F.", "t": "Waltz in B minor, D. 145 No. 6", "nat": "Austrian", "era": "Romantic", "focus": ["Waltz character", "Lyrical melody", "Simple accompaniment"] },
  { "c": "SCHUMANN, R.", "t": "Melody, Op. 68 No. 1", "nat": "German", "era": "Romantic", "focus": ["Singing melody", "Inner voice awareness", "Romantic character"] },
  { "c": "SCHMITZ, M.", "t": "Slow Blues (from Recital Collection for Piano, Grade 3)", "nat": "American", "era": "Contemporary", "focus": ["Blues style", "Expressive playing", "Simple ornamentation"] },
  { "c": "SEBBA, J.", "t": "The Chase (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Contemporary", "focus": ["Exciting character", "Rhythmic drive", "Coordination"] },
  { "c": "SHOSTAKOVICH, D.", "t": "A Merry Story, Op. 69 No. 3", "nat": "Russian", "era": "Modern", "focus": ["Humorous character", "Simple texture", "Light phrasing"] },
  { "c": "STRECKE, G.", "t": "Nocturne (from Recital Collection for Piano, Grade 3)", "nat": "German", "era": "Romantic", "focus": ["Night character", "Lyrical melody", "Atmospheric playing"] },
  { "c": "TANSMAN, A.", "t": "Intermezzo (from Pour les Enfants, 2nd set)", "nat": "Polish", "era": "Modern", "focus": ["Simple texture", "Clear phrasing", "Lyrical playing"] },
  { "c": "TELEMANN, G.P.", "t": "Fantasia in C (from 36 Fantasias for Keyboard, TWV 33:14)", "nat": "German", "era": "Baroque", "focus": ["Baroque fantasia", "Clear phrasing", "Two-voice texture"] },
  { "c": "TERZIBASCHITSCH, A.", "t": "Samba (from Recital Collection for Piano, Grade 3)", "nat": "German", "era": "Contemporary", "focus": ["Brazilian style", "Rhythmic drive", "Simple syncopation"] },
  { "c": "VILLA-LOBOS, H.", "t": "A Pombinha Voou (from Guia Prático, arr.)", "nat": "Brazilian", "era": "Modern", "focus": ["Folk character", "Simple melody", "Light touch"] },
  { "c": "WALLIS, E.", "t": "Moonlit Lake (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Gentle touch", "Simple texture"] },
  { "c": "WARLOCK, P.", "t": "Basse-Danse (from Capriol Suite)", "nat": "English", "era": "Modern", "focus": ["Renaissance style", "Clear texture", "Dance character"] },
  { "c": "YANDELL, S.", "t": "Funky Drummer (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Contemporary", "focus": ["Funk style", "Strong beat", "Simple coordination"] },
  { "c": "KABALEVSKY, D.", "t": "Sonatina in A minor, Op. 13 No. 20 (1st mvt)", "nat": "Russian", "era": "Modern", "focus": ["Classical sonatina form", "Clear phrasing", "Rhythmic drive"] },
  { "c": "NORTON, C.", "t": "Latin Connection (from Microjazz Collection 2)", "nat": "English", "era": "Contemporary", "focus": ["Latin jazz style", "Simple syncopation", "Light character"] },
  { "c": "PAPP, L.", "t": "Bagatelle (from Recital Collection for Piano, Grade 3)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Character piece", "Simple form", "Expressive touch"] },
  { "c": "BEETHOVEN, L. van", "t": "Für Elise, WoO 59 (simplified)", "nat": "German", "era": "Classical", "focus": ["Lyrical melody", "Simple accompaniment", "Balanced phrasing"] },
  { "c": "MOZART, W.A.", "t": "Rondo in D, K. 485 (simplified)", "nat": "Austrian", "era": "Classical", "focus": ["Classical rondo", "Finger technique", "Clear phrasing"] },
  { "c": "CAINE, U.", "t": "Ragtime (from Recital Collection for Piano, Grade 3)", "nat": "American", "era": "Contemporary", "focus": ["Ragtime style", "Simple syncopation", "Rhythmic character"] },
  { "c": "LANE, R.", "t": "Twilight City (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Simple ostinato", "Lyrical melody"] },
  { "c": "SCHMITZ, M.", "t": "Boogie Fingers (from Recital Collection for Piano, Grade 3)", "nat": "American", "era": "Contemporary", "focus": ["Boogie style", "Strong left hand", "Rhythmic drive"] },
  { "c": "HARRIS, P.", "t": "Cool Machine (from Recital Collection for Piano, Grade 3)", "nat": "English", "era": "Contemporary", "focus": ["Mechanical character", "Staccato touch", "Simple rhythm"] }
];
