// ABRSM Piano 2025 & 2026 — Initial
// Total: 48 pieces  A:16 B:16 C:16
// Generated from official ABRSM Piano 2025 & 2026 Syllabus PDF

const DATA_ABRSM_INITIAL = [
  // LIST A — 16 pieces
{"l":"A","c":"HAUGHTON, Alan","t":"Gopak","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Dance character", "Musical expression"]},
{"l":"A","c":"WEDGWOOD, Pam","t":"Make Way for the King! (No. 1 from Up-Grade! Piano Grades 0–1)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"A","c":"TRAD. SWEDISH","t":"Björnen sover, arr. Bullard","nat":"Swedish","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"A","c":"COLDPLAY (arr. Dunlop)","t":"Clocks","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"A","c":"CARROLL, W.","t":"Raindrops (No. 4 from The Countryside)","nat":"English","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"A","c":"DIABELLI, A.","t":"Alla turca, Op. 149 No. 26","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Dance character", "Keyboard clarity"]},
{"l":"A","c":"DIABELLI, A.","t":"Scherzo","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Rhythmic precision", "Formal structure"]},
{"l":"A","c":"GURLITT, C.","t":"Dance (No. 2 from Das kleines Konzert, Op. 227)","nat":"German","era":"Classical","focus":["Classical phrasing", "Dance character", "Formal structure"]},
{"l":"A","c":"HUMBERT, G.","t":"The Black Forest Doll (No. 3 from Allerlei Spielzeug)","nat":"German","era":"Romantic","focus":["Expressive tone", "Character contrast", "Dynamic shaping"]},
{"l":"A","c":"KABALEVSKY, D.","t":"A Little Scherzo (No. 6 from 24 Little Pieces, Op. 39)","nat":"Russian","era":"Modern","focus":["Rhythmic precision", "Character contrast", "Finger independence"]},
{"l":"A","c":"MAXNER, Rebekah","t":"Zonko’s Big Adventure (from Rock This Town)","nat":"Canadian","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"A","c":"REINAGLE, A.","t":"Allegretto (No. 9 from 24 Short and Easy Pieces, Op. 1)","nat":"English","era":"Classical","focus":["Classical phrasing", "Finger independence", "Keyboard clarity"]},
{"l":"A","c":"SCHATTEL, Bertram","t":"Racing Against Each Other (No. 12 from For Rosalie and Finn)","nat":"German","era":"Contemporary","focus":["Contemporary idiom", "Rhythmic precision", "Musical expression"]},
{"l":"A","c":"TRAD. IRISH","t":"John Ryan’s Polka, arr. Blackwell","nat":"Irish","era":"Contemporary","focus":["Contemporary idiom", "Dance character", "Musical expression"]},
{"l":"A","c":"WEDGWOOD, Pam","t":"Mission Impossible (No. 11 from Up-Grade! Piano Grades 0–1)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"A","c":"WELLS, Elsie","t":"Donkey Ride (from Sea Pictures, Set 1)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Dance character", "Musical expression"]},
  // LIST B — 16 pieces
{"l":"B","c":"BEYER, F.","t":"Melody in G (No. 39 from École préliminaire de piano, Op. 101)","nat":"German","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"B","c":"CROSLAND, Ben","t":"King for a Day! (from Magic Beans!)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"FENTY, Robyn (arr. L'Estrange)","t":"Lift me up (from Black Panther: Wakanda Forever)","nat":"Barbadian","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"AGAY, D.","t":"Moonlit Pagoda","nat":"Hungarian-American","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"ARMSTRONG, June","t":"Butterfly","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"CHAMBERLAIN, Louise","t":"The Sad Little Pig (from Step It Up! Piano Grades 0–1)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"HALL, Pauline","t":"The Secret Garden","nat":"English","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"HAUGHTON, Alan","t":"Budgie (from Fun Club Piano Grades 0–1)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"MARSHALL, Karen","t":"Sprinkling Stardust","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"MATHEWS, Alison","t":"Sailing Under a Moonlit Sky","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"NORTON, Christopher","t":"Enchanted Castle (No. 6 from The Microjazz Christopher s Collection)","nat":"International","era":"Contemporary","focus":["Contemporary idiom", "Jazz/Pop style", "Musical expression"]},
{"l":"B","c":"ORFF, C.","t":"No. 1 (from Two Pieces) From","nat":"German","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"PESKETT, Phil","t":"A Dream on the Prairie","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Singing tone", "Musical expression"]},
{"l":"B","c":"SATIE, E.","t":"What the Little Princess Tulip Says (No. 2 from Satie: Menus propos enfantins)","nat":"French","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"TRAD. CHINESE","t":"Crescent Moon","nat":"Chinese","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"WEDGWOOD, Pam","t":"Whirleybird (No. 2 from Up-Grade! Piano Grades 0–1)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
  // LIST C — 16 pieces
{"l":"C","c":"ARMSTRONG, June","t":"The Elephant Herd (from Prehistoric Piano Time)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"JOLLIFFE, Edmund","t":"In the Dead of Night","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"WATTS, Sarah","t":"The Wibbly Waltz","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Dance character", "Musical expression"]},
{"l":"C","c":"GIBSON, George Barnett, Joel Laslett Pott & Fred","t":"Shotgun","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"WITHERS, B.","t":"Lean on Me","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"HALL, Pauline","t":"Stegosaurus Stomp (from Prehistoric)","nat":"English","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"HAMMOND, Heather","t":"Action Stations","nat":"English","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"TANNER, Mark","t":"Wonkey Donkey","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"HAUGHTON, Alan","t":"Treading Carefully","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"HEUMANN, Hans-Günter","t":"Piano Junior Blues","nat":"International","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
{"l":"C","c":"JOHN, Elton","t":"I Just Can’t Wait to Be King (from The Lion King)","nat":"English","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"KLOSE, Carol","t":"Those Creepy Crawly Things on the Cellar Floor Hal (Hal)","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"KNERR, Julie","t":"Detective Wombat Blues","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Jazz/Pop style", "Musical expression"]},
{"l":"C","c":"LAST, J. M.","t":"Ducks in the Pond","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"MARTIN, Gerald","t":"Boogie No. 1","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Jazz/Pop style", "Musical expression"]},
{"l":"C","c":"SEBBA, Jane","t":"The Grand Waltz","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Dance character", "Musical expression"]},
];
