// DATA_PRELIM — AMEB Piano Preliminary (9940)
// Series lists: S19, S18, S17, AustAnth, Manual
// Total: 93 pieces
const DATA_PRELIM = [
  {"l":"A","s":"S19","c":"HOOK, J.","t":"Gavotta (Lesson 1 from Guida di musica Op. 37)","nat":"British","era":"Classical","key":"Variable","focus":["Classical elegance", "Clear articulation", "Formal structure"]},
  {"l":"A","s":"S19","c":"KOTCHIE, J.","t":"Leaping lizards","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"A","s":"S19","c":"MILNE, E.","t":"Canon and on","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"A","s":"S19","c":"SWINSTEAD, F.","t":"Follow my leader No 7 from Work and play","nat":"British","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"A","s":"S18","c":"EAGLES, M.","t":"Let's sing a duet","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"A","s":"S18","c":"HIRSCHBERG, D.","t":"The little fisherman","nat":"German","era":"Romantic","key":"Variable","focus":["Expressive phrasing", "Singing tone", "Musical sensitivity"]},
  {"l":"A","s":"S18","c":"SPINDLER, F.","t":"Theme No 12 from Op. 308","nat":"German","era":"Romantic","key":"Variable","focus":["Romantic character", "Dynamic range", "Legato playing"]},
  {"l":"A","s":"S18","c":"TELEMANN, G. (arr. HODGSON)","t":"Minuet No 11 from TWV 34","nat":"German","era":"Baroque","key":"Variable","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
  {"l":"A","s":"S17","c":"COUPPEY, F. Le.","t":"Study No 2 from Op. 17","nat":"French","era":"Romantic","key":"Variable","focus":["Romantic warmth", "Melodic shaping", "Pianistic colour"]},
  {"l":"A","s":"S17","c":"McKERN, B.","t":"Scherzo","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"A","s":"S17","c":"MILNE, E.","t":"Salt and pepper from Very easy little peppers","nat":"British","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"A","s":"S17","c":"MILNE, E.","t":"The banjo","nat":"British","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"A","s":"Manual","c":"BART\u00d3K, B.","t":"Round dance No 10 from Kezd\u0151k zongoramuzsik\u00e1ja","nat":"Hungarian","era":"Modern","key":"Variable","focus":["Modern idiom", "Rhythmic precision", "Stylistic clarity"]},
  {"l":"A","s":"Manual","c":"CARLEY, I.","t":"Play-party No 3 from Eleven miniatures","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"A","s":"Manual","c":"CROSBY, A.","t":"Celebration (In my dreams)","nat":"Canadian","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"A","s":"Manual","c":"GURLITT, C.","t":"Allegro No 19 from The best traditional piano \u00e9tudes Book 2","nat":"German","era":"Romantic","key":"Variable","focus":["Emotional depth", "Tonal warmth", "Romantic idiom"]},
  {"l":"A","s":"Manual","c":"KABALEVSKY, D.","t":"A little tune No 1 and Polka No 2 from 24 little pieces Op. 39","nat":"Russian","era":"Modern","key":"Variable","focus":["Rhythmic energy", "Modern character", "Tonal contrast"]},
  {"l":"A","s":"Manual","c":"KABALEVSKY, D.","t":"A porcupine dance No 8 from 35 easy pieces Op. 89","nat":"Russian","era":"Modern","key":"Variable","focus":["Modern style", "Dynamic contrast", "Rhythmic drive"]},
  {"l":"A","s":"Manual","c":"KABALEVSKY, D.","t":"Funny event No 7 from 24 pieces for children Op. 39","nat":"Russian","era":"Modern","key":"Variable","focus":["Harmonic colour", "Precise articulation", "Modern phrasing"]},
  {"l":"A","s":"Manual","c":"K\u00d6HLER, L.","t":"Etude in A minor Op. 190 No 31","nat":"German","era":"Romantic","key":"Variable","focus":["Lyrical playing", "Musical depth", "Expressive character"]},
  {"l":"A","s":"Manual","c":"MOURET, J.","t":"La Montagnarde (The highlander)","nat":"French","era":"Baroque","key":"Variable","focus":["Baroque phrasing", "Dance character", "Ornamental detail"]},
  {"l":"A","s":"Manual","c":"M\u00dcLLER, A.","t":"Study (Andante) in A minor No 9","nat":"German","era":"Classical","key":"Variable","focus":["Classical phrasing", "Melodic clarity", "Period style"]},
  {"l":"A","s":"Manual","c":"REINAGLE, A.","t":"Minuet","nat":"British","era":"Classical","key":"Variable","focus":["Sonatina form", "Musical balance", "Classical character"]},
  {"l":"A","s":"Manual","c":"RYBA, J.","t":"Short invention No 1 and Short invention No 2","nat":"Czech","era":"Classical","key":"Variable","focus":["Clean technique", "Tonal clarity", "Classical idiom"]},
  {"l":"B","s":"S19","c":"GURLITT, C.","t":"Mutiger knabe (Brave boy) No 3 from Der Hausfreund Op. 197","nat":"German","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"B","s":"S19","c":"REINAGLE, A.","t":"Allegro No 4 from 24 short and easy pieces Op. 1","nat":"British","era":"Classical","key":"Variable","focus":["Classical elegance", "Clear articulation", "Formal structure"]},
  {"l":"B","s":"S19","c":"TAN, C-W.","t":"Keepsake mill (A child's garden of verses)","nat":"Singaporean","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"B","s":"S19","c":"VOGEL, M.","t":"Valsette","nat":"German","era":"Romantic","key":"Variable","focus":["Expressive phrasing", "Singing tone", "Musical sensitivity"]},
  {"l":"B","s":"S18","c":"BRESLAUR, E.","t":"Walzer No 25 from Op. 46","nat":"German","era":"Romantic","key":"Variable","focus":["Romantic character", "Dynamic range", "Legato playing"]},
  {"l":"B","s":"S18","c":"GURLITT, C.","t":"Andante No 35 from Op. 82","nat":"German","era":"Romantic","key":"Variable","focus":["Romantic warmth", "Melodic shaping", "Pianistic colour"]},
  {"l":"B","s":"S18","c":"HOOK, J.","t":"Tempo di minuetto (Position lesson II from Op. 37)","nat":"British","era":"Classical","key":"Variable","focus":["Classical phrasing", "Melodic clarity", "Period style"]},
  {"l":"B","s":"S18","c":"T\u00dcRK, D. (arr. FABER and FABER)","t":"Little dance","nat":"German","era":"Classical","key":"Variable","focus":["Sonatina form", "Musical balance", "Classical character"]},
  {"l":"B","s":"S17","c":"DUNCOMBE, W.","t":"Trumpet tune","nat":"British","era":"Baroque","key":"Variable","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
  {"l":"B","s":"S17","c":"HOOK, J.","t":"Allegretto No 4 from Op. 81","nat":"British","era":"Classical","key":"Variable","focus":["Clean technique", "Tonal clarity", "Classical idiom"]},
  {"l":"B","s":"S17","c":"REINAGLE, A.","t":"Allegretto No 11 from Op. 2","nat":"British","era":"Classical","key":"Variable","focus":["Melodic singing", "Phrase shaping", "Even tone"]},
  {"l":"B","s":"S17","c":"T\u00dcRK, D.","t":"Die Jugend tanzt No 32 from 120 Handst\u00fccke f\u00fcr angehende Klavierspieler","nat":"German","era":"Classical","key":"Variable","focus":["Classical balance", "Light touch", "Structural clarity"]},
  {"l":"B","s":"Manual","c":"BEYER, F.","t":"Circle dance No 60 from Vorschule in Klavierspiel Op. 101","nat":"German","era":"Romantic","key":"Variable","focus":["Emotional depth", "Tonal warmth", "Romantic idiom"]},
  {"l":"B","s":"Manual","c":"CLEMENTI, M.","t":"Arietta in C major","nat":"Italian","era":"Classical","key":"Variable","focus":["Period accuracy", "Musical grace", "Classical style"]},
  {"l":"B","s":"Manual","c":"DIABELLI, A.","t":"Vivace No 7 from Die ersten 12 Lektionen Op. 125","nat":"Austrian","era":"Classical","key":"Variable","focus":["Formal elegance", "Tonal control", "Classical phrasing"]},
  {"l":"B","s":"Manual","c":"H\u00c4SSLER, J.","t":"Minuetto (Piano repertoire: Baroque and Classical Level 1)","nat":"German","era":"Classical","key":"Variable","focus":["Dance character", "Classical precision", "Light elegance"]},
  {"l":"B","s":"Manual","c":"HAYDN, J.","t":"Allegretto in D major Hob IX:22 No 2","nat":"Austrian","era":"Classical","key":"Variable","focus":["Minuet grace", "Period style", "Expressive clarity"]},
  {"l":"B","s":"Manual","c":"HAYDN, J.","t":"Quadrille (Getting to Preliminary)","nat":"Austrian","era":"Classical","key":"Variable","focus":["Lyrical melody", "Classical poise", "Tonal balance"]},
  {"l":"B","s":"Manual","c":"HOOK, J.","t":"Gavotte (Discovering piano literature Book 1)","nat":"British","era":"Classical","key":"Variable","focus":["Sonatina style", "Technical fluency", "Musical proportion"]},
  {"l":"B","s":"Manual","c":"K\u00d6HLER, L.","t":"Song without words Op. 190 No 27","nat":"German","era":"Romantic","key":"Variable","focus":["Lyrical playing", "Musical depth", "Expressive character"]},
  {"l":"B","s":"Manual","c":"SPINDLER, F.","t":"Song without words (Melodious masterpieces Book 1)","nat":"German","era":"Romantic","key":"Variable","focus":["Romantic style", "Cantabile tone", "Phrase nuance"]},
  {"l":"B","s":"Manual","c":"WILTON, C.H.","t":"Moderato (1st mvt from Little sonata, Journey through the classics Book 2)","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"B","s":"Manual","c":"WILTON, C.H.","t":"Minuet (Andante) (2nd mvt from Little sonata, Journey through the classics Book 2)","nat":"British","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"C","s":"S19","c":"AGAY, D.","t":"Prelude to a puppet show","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"C","s":"S19","c":"COLBORNE-VEEL, J.","t":"The bicycle boy No 2 from Fifteen descriptive pieces","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"C","s":"S19","c":"GIFFORD, B.","t":"Binin gala (Light)","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"C","s":"S19","c":"KUME, N.","t":"Matsuri (Japanese festival)","nat":"Japanese","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"C","s":"S19","c":"ROUBOS, V.","t":"The peacock","nat":"American","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"C","s":"S18","c":"BAUMGARTNER, E.","t":"Mini toccata","nat":"American","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"C","s":"S18","c":"EL-DABH, H.","t":"Soufiane from Mekta' in the art of Kita' Book 2","nat":"Egyptian","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"C","s":"S18","c":"GILLOCK, W.","t":"Little flower girl of Paris","nat":"American","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"C","s":"S18","c":"McFARLANE, D.","t":"Creepy crawlies","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Stylistic flair", "Contemporary expression", "Musical colour"]},
  {"l":"C","s":"S18","c":"RICHERT, T.","t":"Bouncing ball","nat":"American","era":"Contemporary","key":"Variable","focus":["Australian character", "Contemporary style", "Musical identity"]},
  {"l":"C","s":"S17","c":"CHUA, S.","t":"Dripping fairy from Assorted fairies","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Dance character", "Contemporary idiom", "Rhythmic energy"]},
  {"l":"C","s":"S17","c":"HYDE, M.","t":"Gnomes marching","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Film character", "Contemporary style", "Expressive melody"]},
  {"l":"C","s":"S17","c":"SCHAWERSASCHWILI, T.","t":"Nun rate mal!","nat":"Georgian","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"C","s":"S17","c":"TRADITIONAL (arr. HEUMANN)","t":"Malague\u00f1a","nat":"Spanish","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"C","s":"AustAnth","c":"CARR-BOYD, A.","t":"Staccato imitation","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"C","s":"AustAnth","c":"JONES, M.","t":"Prayer of the swinging mantis","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"C","s":"AustAnth","c":"MAGEAU, M.","t":"Wandering wombat","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"C","s":"AustAnth","c":"SITSKY, L.","t":"Red Indian hand game song","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"C","s":"Manual","c":"ADAIR, Y.","t":"The bronze boar (Sketches from Hans Andersen)","nat":"British","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"C","s":"Manual","c":"BAUMGARTNER, E.","t":"Cool it! (Jazz piano basics: Encore)","nat":"American","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"C","s":"Manual","c":"BOBER, M.","t":"Stealth mode (Solo xtreme Book 2)","nat":"American","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"C","s":"Manual","c":"CORNICK, M.","t":"Chromatic blues for the left hand (30 easy piano studies)","nat":"British","era":"Contemporary","key":"Variable","focus":["Stylistic flair", "Contemporary expression", "Musical colour"]},
  {"l":"C","s":"Manual","c":"CROSBY, A.","t":"Angelfish (Freddie the frog)","nat":"Canadian","era":"Contemporary","key":"Variable","focus":["Australian character", "Contemporary style", "Musical identity"]},
  {"l":"C","s":"Manual","c":"CROSBY, A.","t":"Starfish at night (Exploring preliminary)","nat":"Canadian","era":"Contemporary","key":"Variable","focus":["Dance character", "Contemporary idiom", "Rhythmic energy"]},
  {"l":"C","s":"Manual","c":"DUNHILL, T.","t":"A little hush-song No 5 from First year pieces","nat":"British","era":"Modern","key":"Variable","focus":["Modern idiom", "Rhythmic precision", "Stylistic clarity"]},
  {"l":"C","s":"Manual","c":"DUNHILL, T.","t":"The old abbey No 4 from First year pieces","nat":"British","era":"Modern","key":"Variable","focus":["Rhythmic energy", "Modern character", "Tonal contrast"]},
  {"l":"C","s":"Manual","c":"DURO, S.","t":"A raggy tune (Finger jogging boogie)","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Film character", "Contemporary style", "Expressive melody"]},
  {"l":"C","s":"Manual","c":"DURO, S.","t":"Finger joggin' boogie (Finger joggin' boogie)","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"C","s":"Manual","c":"GILLOCK, W.","t":"Fog at sea (Exploring preliminary)","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"C","s":"Manual","c":"HAUGHTON, A.","t":"Ballerina (Roundabout)","nat":"British","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"C","s":"Manual","c":"HAUGHTON, A.","t":"Petite valse (Roundabout)","nat":"British","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"C","s":"Manual","c":"HOLLAND, D.","t":"Sea-gulls (Learn the piano Book 2)","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"C","s":"Manual","c":"HYDE, M.","t":"The new flute","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"C","s":"Manual","c":"KADOSA, P.","t":"Allegretto leggiero No 8 from 55 small piano pieces","nat":"Hungarian","era":"Modern","key":"Variable","focus":["Modern style", "Dynamic contrast", "Rhythmic drive"]},
  {"l":"C","s":"Manual","c":"KOD\u00c1LY, Z.","t":"Allegretto No 1 from Gyermekt\u00e1ncok","nat":"Hungarian","era":"Modern","key":"Variable","focus":["Harmonic colour", "Precise articulation", "Modern phrasing"]},
  {"l":"C","s":"Manual","c":"LAST, J.","t":"Ducks in the pond (Piano time pieces Book 3)","nat":"British","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"C","s":"Manual","c":"MILNE, E.","t":"Chase (Very easy little peppers)","nat":"British","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"C","s":"Manual","c":"NORTON, C.","t":"Struttin' No 3 (The microjazz collection 1)","nat":"British","era":"Contemporary","key":"Variable","focus":["Stylistic flair", "Contemporary expression", "Musical colour"]},
  {"l":"C","s":"Manual","c":"RAHBEE, D.G.","t":"Snowflakes gently falling (Exploring preliminary)","nat":"American","era":"Contemporary","key":"Variable","focus":["Australian character", "Contemporary style", "Musical identity"]},
  {"l":"C","s":"Manual","c":"SATIE, E.","t":"Profiter de ce qu'il a des cors aux pieds pour lui prendre son cerceau","nat":"French","era":"Modern","key":"Variable","focus":["Rhythmic vitality", "Modern harmony", "Musical directness"]},
  {"l":"C","s":"Manual","c":"SITSKY, L.","t":"Jewish folk song No 112 from Century Volume 3","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Dance character", "Contemporary idiom", "Rhythmic energy"]},
  {"l":"C","s":"Manual","c":"TANSMAN, A.","t":"Arabia from Happy time Book 1","nat":"Polish","era":"Modern","key":"Variable","focus":["Crisp rhythm", "Modern character", "Stylistic awareness"]},
  {"l":"C","s":"Manual","c":"WEDGWOOD, P.","t":"Antics (Up-grade! Piano grades 0-1)","nat":"British","era":"Contemporary","key":"Variable","focus":["Film character", "Contemporary style", "Expressive melody"]},
  {"l":"C","s":"Manual","c":"WEDGWOOD, P.","t":"Temple of doom (Up-grade! Piano grades 0-1)","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"C","s":"Manual","c":"WEDGWOOD, P.","t":"The brave knight (More up-grade! Piano grades 0-1)","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"C","s":"Manual","c":"WOODING, K.","t":"The house on the hill (Spooky piano time)","nat":"British","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]}
];
