// DATA_PRELIM_LEISURE — AMEB Piano for Leisure Preliminary (6330)
// Series lists: S4, S3, S2, S1, Manual
// Total: 71 pieces
const DATA_PRELIM_LEISURE = [
  {"l":"S4","s":"S4","c":"BIZET, G. (arr. MATZ)","t":"March of the Toreadors","nat":"French","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"S4","s":"S4","c":"BOBER, M.","t":"Saxophone blues","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"S4","s":"S4","c":"COUPPEY, F. Le.","t":"Bourr\u00e9e","nat":"French","era":"Romantic","key":"Variable","focus":["Expressive phrasing", "Singing tone", "Musical sensitivity"]},
  {"l":"S4","s":"S4","c":"DORNAN, M.","t":"Three plus two","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"S4","s":"S4","c":"GILLOCK, W.","t":"The singing Sioux","nat":"American","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"S4","s":"S4","c":"GURLITT, C.","t":"Moonlight variation","nat":"German","era":"Romantic","key":"Variable","focus":["Romantic character", "Dynamic range", "Legato playing"]},
  {"l":"S4","s":"S4","c":"HUTCHENS, F.","t":"March of the cubs","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"S4","s":"S4","c":"KOTCHIE, J.","t":"Just jazzin'","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"S4","s":"S4","c":"McFARLANE, D.","t":"Winter's day","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"S4","s":"S4","c":"MILNE, E.","t":"Square-o","nat":"British","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"S4","s":"S4","c":"NORTON, C.","t":"Full of confidence","nat":"British","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"S4","s":"S4","c":"TRADITIONAL (arr. HODGSON)","t":"Waltzing Matilda","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Stylistic flair", "Contemporary expression", "Musical colour"]},
  {"l":"S3","s":"S3","c":"BACH, J.C.","t":"Prelude","nat":"German","era":"Classical","key":"Variable","focus":["Classical elegance", "Clear articulation", "Formal structure"]},
  {"l":"S3","s":"S3","c":"BERLIN, I.","t":"March of the goblins","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"S3","s":"S3","c":"GOLDSTON, M.","t":"The Japanese koto","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"S3","s":"S3","c":"KOTCHIE, J.","t":"The mischievous basketball","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"S3","s":"S3","c":"LADD, R.","t":"Butcher boy rag","nat":"American","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"S3","s":"S3","c":"MORRICONE, E. (arr. MILNE)","t":"The good, the bad and the ugly","nat":"Italian","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"S3","s":"S3","c":"MOZART, W.A. (arr. BASTIEN)","t":"Aria","nat":"Austrian","era":"Classical","key":"Variable","focus":["Classical phrasing", "Melodic clarity", "Period style"]},
  {"l":"S3","s":"S3","c":"NORTON, C.","t":"Driving range","nat":"British","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"S3","s":"S3","c":"SCH\u00d6NMEHL, M.","t":"Sherlock Holmes","nat":"German","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"S3","s":"S3","c":"STORER, T.","t":"Beginner's blues","nat":"American","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"S3","s":"S3","c":"TRYNES, J.","t":"Hen-house hoe-down","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Stylistic flair", "Contemporary expression", "Musical colour"]},
  {"l":"S2","s":"S2","c":"GIBSON, J.","t":"From the top","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"S2","s":"S2","c":"GRUBER, F.","t":"C minor blues","nat":"Austrian","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"S2","s":"S2","c":"KOWALCHYK, G. and LANCASTER, E.","t":"Struttin' the blues","nat":"American","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"S2","s":"S2","c":"LADD, R.","t":"Woe is me","nat":"American","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"S2","s":"S2","c":"LOAM, H.","t":"A passing storm","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"S2","s":"S2","c":"MIER, M.","t":"Taco rock","nat":"American","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"S2","s":"S2","c":"MILNE, E.","t":"Safari","nat":"British","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"S2","s":"S2","c":"MOZART, W.A. (arr. SCHULTZ)","t":"L\u00e0 ci darem la mano","nat":"Austrian","era":"Classical","key":"Variable","focus":["Classical elegance", "Clear articulation", "Formal structure"]},
  {"l":"S2","s":"S2","c":"NOONA, W. and C.","t":"Major Melvin's military marching band","nat":"American","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"S2","s":"S2","c":"NORMAN, M. (arr. FABER and FABER)","t":"Theme","nat":"British","era":"Contemporary","key":"Variable","focus":["Stylistic flair", "Contemporary expression", "Musical colour"]},
  {"l":"S2","s":"S2","c":"NORTON, C.","t":"Two-handed blues","nat":"British","era":"Contemporary","key":"Variable","focus":["Australian character", "Contemporary style", "Musical identity"]},
  {"l":"S2","s":"S2","c":"RIMSKY-KORSAKOV, N. (arr. BROADSTOCK)","t":"Theme","nat":"Russian","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"S1","s":"S1","c":"BRAHMS, J.","t":"Lullaby","nat":"German","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"S1","s":"S1","c":"GOLDSTON, M.","t":"Simply jazzy","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"S1","s":"S1","c":"KABALEVSKY, D.","t":"Waltz","nat":"Russian","era":"Modern","key":"Variable","focus":["Modern idiom", "Rhythmic precision", "Stylistic clarity"]},
  {"l":"S1","s":"S1","c":"KOWALCHYK, G. and LANCASTER, E.","t":"Carefree boogie","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"S1","s":"S1","c":"MOZART, W.A.","t":"Minuet","nat":"Austrian","era":"Classical","key":"Variable","focus":["Classical elegance", "Clear articulation", "Formal structure"]},
  {"l":"S1","s":"S1","c":"OLSON, L.","t":"Cross-over blues","nat":"American","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"S1","s":"S1","c":"SAINT-SA\u00cbNS, C.","t":"Royal march of the lion","nat":"French","era":"Romantic","key":"Variable","focus":["Expressive phrasing", "Singing tone", "Musical sensitivity"]},
  {"l":"S1","s":"S1","c":"TINGLEY, C.","t":"Cubanera","nat":"American","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"S1","s":"S1","c":"TRADITIONAL (arr. BURK)","t":"Amazing grace","nat":"American","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"S1","s":"S1","c":"TRADITIONAL (arr. BURK)","t":"Brother James","nat":"British","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"S1","s":"S1","c":"TRADITIONAL (arr. HALL)","t":"Jamaican rumba","nat":"Jamaican","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"S1","s":"S1","c":"TRADITIONAL (arr. HAUN)","t":"Botany Bay","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"Manual","s":"Manual","c":"BASTIEN, J.","t":"Cheerleader boogie","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"Manual","s":"Manual","c":"BASTIEN, J.","t":"The man on the flying trapeze","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"Manual","s":"Manual","c":"BULLARD, A.","t":"Friday night rag","nat":"British","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"Manual","s":"Manual","c":"BULLARD, A.","t":"Living it up","nat":"British","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"Manual","s":"Manual","c":"BULLARD, A.","t":"Flying above the clouds","nat":"British","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"Manual","s":"Manual","c":"CULLEN, J.","t":"Paris promenade","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"Manual","s":"Manual","c":"GRITTON, A.","t":"Creepy crawly","nat":"British","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"Manual","s":"Manual","c":"HALL, C.","t":"Hong Kong ferry","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"Manual","s":"Manual","c":"HAUGHTON, A.","t":"Hop it!","nat":"British","era":"Contemporary","key":"Variable","focus":["Stylistic flair", "Contemporary expression", "Musical colour"]},
  {"l":"Manual","s":"Manual","c":"HEUMANN, H-G.","t":"Malague\u00f1a","nat":"German","era":"Contemporary","key":"Variable","focus":["Australian character", "Contemporary style", "Musical identity"]},
  {"l":"Manual","s":"Manual","c":"LENNON, J. (arr. FRITH)","t":"Imagine","nat":"British","era":"Contemporary","key":"Variable","focus":["Dance character", "Contemporary idiom", "Rhythmic energy"]},
  {"l":"Manual","s":"Manual","c":"MacDOWELL, E. (arr. COLE and PAUL)","t":"To a wild rose","nat":"American","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"Manual","s":"Manual","c":"MIER, M.","t":"Surfboard boogie","nat":"American","era":"Contemporary","key":"Variable","focus":["Film character", "Contemporary style", "Expressive melody"]},
  {"l":"Manual","s":"Manual","c":"NORTON, C.","t":"Creaking stairs","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"Manual","s":"Manual","c":"NORTON, C.","t":"Out of the mist","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"Manual","s":"Manual","c":"NORTON, C.","t":"Caribbean song","nat":"British","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"Manual","s":"Manual","c":"OFFENBACH, J. (arr. COLE and PAUL)","t":"Can-can","nat":"French","era":"Romantic","key":"Variable","focus":["Expressive phrasing", "Singing tone", "Musical sensitivity"]},
  {"l":"Manual","s":"Manual","c":"RODGERS, R.","t":"Do-re-mi","nat":"American","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"Manual","s":"Manual","c":"SCHAUM, J.","t":"Big beat","nat":"American","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"Manual","s":"Manual","c":"SHOSTAKOVICH, D.","t":"March No 1","nat":"Russian","era":"Modern","key":"Variable","focus":["Modern idiom", "Rhythmic precision", "Stylistic clarity"]},
  {"l":"Manual","s":"Manual","c":"TRADITIONAL (arr. FRITH)","t":"Scarborough fair","nat":"British","era":"Contemporary","key":"Variable","focus":["Stylistic flair", "Contemporary expression", "Musical colour"]},
  {"l":"Manual","s":"Manual","c":"WEDGWOOD, P.","t":"The brave knight","nat":"British","era":"Contemporary","key":"Variable","focus":["Character piece", "Contemporary style", "Musical personality"]},
  {"l":"Manual","s":"Manual","c":"WEDGWOOD, P.","t":"In the eyes of the tiger","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Rhythmic drive", "Musical energy"]},
  {"l":"Manual","s":"Manual","c":"WEDGWOOD, P.","t":"Temple of doom","nat":"British","era":"Contemporary","key":"Variable","focus":["Film character", "Contemporary style", "Expressive melody"]}
];
