// ABRSM Piano 2025 & 2026 — G5
// Total: 47 pieces  A:15 B:16 C:16
// Generated from official ABRSM Piano 2025 & 2026 Syllabus PDF

const DATA_ABRSM_G5 = [
  // LIST A — 15 pieces
{"l":"A","c":"BURGMÜLLER, J.F.F.","t":"La tarantelle (No. 20 from 25 études faciles et progressives, Op. 100)","nat":"German","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"A","c":"CLEMENTI","t":"Spiritoso (1st movt from Sonatina in C, Op. 36 No. 1)","nat":"Italian","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"ILES, Nikki","t":"Hook’s Hornpipe (from Piano Tales for Peter Pan)","nat":"English","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"A","c":"BACH, J.S.","t":"Invention No. 8 in F, BWV 779 J. J.","nat":"German","era":"Baroque","focus":["Baroque style", "Contrapuntal texture", "Keyboard clarity"]},
{"l":"A","c":"BEETHOVEN","t":"Bagatelle in G minor, Op. 119 No. 1 A","nat":"German","era":"Classical","focus":["Classical phrasing", "Hand coordination", "Formal structure"]},
{"l":"A","c":"CHAMINADE","t":"Gavotte (No. 5 from Album des enfants, Op. 123)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"A","c":"FIOCCO, J. H.","t":"Andante (from Pièces de clavecin, Op. 1)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"A","c":"GADE","t":"Ringeltanz (Boys’ Merry-go-round) (No. 2 from Gade: Children’s Christmas, Op. 36) More","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"A","c":"HAYDN","t":"Allegro (1st movt from Sonata in G, Hob. XVI:G1) Pp. Book Essential","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"HELLER, S.","t":"Study in E minor (No. 7 from 30 Progressive Studies, Op. 47)","nat":"International","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"A","c":"HUMMEL","t":"Allegro in C (No. 2 from Six pièces très faciles, Op. 52)","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"KUHLAU","t":"Allegro con spirito (1st movt from Sonatina in C, Op. 55 No. 1)","nat":"International","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"LEO","t":"Toccata No.","nat":"International","era":"Modern","focus":["Rhythmic precision", "Contrapuntal texture", "Character contrast"]},
{"l":"A","c":"MOZART","t":"Theme, Var. 1 and Var. 5 (from 12 Variations on Mozart: “Ah vous dirai-je, maman”, K. 265) K. Mozart: C","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Singing tone", "Formal structure"]},
{"l":"A","c":"SIFFORD, Jason","t":"Rondo Scherzando","nat":"International","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
  // LIST B — 16 pieces
{"l":"B","c":"ROMAN, Capaldi, Kohn, Kelleher, Barnes &","t":"Someone You Loved","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"IKEDA, Naoko","t":"Foggy Blues (from The Graded Piano Collection)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
{"l":"B","c":"SCHUBERT","t":"Waltz in B minor, D.","nat":"Austrian","era":"Romantic","focus":["Expressive tone", "Dance character", "Dynamic shaping"]},
{"l":"B","c":"BENNETT, R.R.","t":"Little Elegy","nat":"English","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"B","c":"GILLOCK","t":"Arabesque Sentimentale William","nat":"American","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"B","c":"GLIÈRE","t":"Evening (No. 5 from 8 Easy Pieces, Op. 43)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"GRANADOS","t":"La huérfana (No. 9 from Cuentos de las juventud, Op. 1)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"HELLER, S.","t":"Study in E minor, Op. 47 No. 15 S.","nat":"International","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"KIRCHNER, T.","t":"Andante (3rd movt from Sonatina in B-, Op. 70 No. 1)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"B","c":"LANE, Philip","t":"A Walk in the Park (No. 2 from Three Little Bites Philip at the Big Apple) (Goodmusic)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"MASSENET","t":"Mélodie (No. 5 from 10 Pièces de genre, Op. 10)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"MOMPOU","t":"La barca (from Impresiones íntimas) Mompou: Ediciones) Mompou","nat":"Spanish","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"PACHULSKI","t":"Prelude in C minor, Op. 8 No. 1 A","nat":"Polish","era":"Romantic","focus":["Expressive tone", "Contrapuntal texture", "Dynamic shaping"]},
{"l":"B","c":"SCHUMANN","t":"Von fremden Ländern und Menschen (No. 1 from Kinderscenen, Op. 15)","nat":"German","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"TRAD. KOREAN","t":"Arirang","nat":"Korean","era":"Contemporary","focus":["Contemporary idiom", "Singing tone", "Musical expression"]},
{"l":"B","c":"WEDGWOOD, Pam","t":"Beauly Abbey (from Up-Grade! Piano Grades 4–5)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
  // LIST C — 16 pieces
{"l":"C","c":"HISAISHI, Joe","t":"The Village in May (from My Neighbour Totoro)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"MIER, Martha","t":"Jackson Street Blues (from Jazz, Rags & Blues, Piano)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
{"l":"C","c":"PROKOFIEV","t":"La pluie et l'arc-en-ciel (No. 8 from Musiques d'enfants, Op. 65)","nat":"Russian","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"AGAY","t":"Blue Waltz","nat":"Hungarian-American","era":"Contemporary","focus":["Contemporary idiom", "Dance character", "Musical expression"]},
{"l":"C","c":"ALWYN","t":"The Sea is Angry","nat":"English","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"C","c":"ARLEN","t":"Stormy Weather","nat":"International","era":"Contemporary","focus":["Contemporary idiom", "Stylistic range", "Musical expression"]},
{"l":"C","c":"BAREILLES, Sara","t":"King of Anything","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"COOK, Alicia Augello","t":"If I Ain’t Got You","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"BARTÓK","t":"Winter Solstice Song (No. 38 from For Children, Vol. 1)","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"C","c":"BERWIN, Lindsey","t":"The Ghost Train (from All the Fun of the Fair)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"C","c":"BORISOVA-OLLAS, Victoria","t":"Silent Island","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"EINAUDI, Ludovico","t":"Elegy for the Arctic this","nat":"Italian","era":"Contemporary","focus":["Contemporary idiom", "Singing tone", "Musical expression"]},
{"l":"C","c":"MIER, Martha","t":"Tuxedo Jazz (from Jazz, Rags & Blues)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
{"l":"C","c":"PINTO","t":"March, Little Soldier! (No. 3 from Scenas Pinto: infantis) gliss. optional","nat":"International","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"C","c":"ROLLIN, Catherine","t":"Love Theme (from Lyric Moments)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"C","c":"STARER","t":"Bright Orange (from Sketches in Colour, Set One)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
];
