// ⚠️  DEPRECATED — This is an old skeleton file (titles only, no nat/era/focus fields).
// Use data_g5_1.js (DATA_G5) as the authoritative Grade 5 Comprehensive data source.
// This file is kept for reference only and is NOT used by any HTML page.
// data.js - AMEB Piano Grade 5 Full Syllabus (2026) — SKELETON / DEPRECATED
const SYLLABUS_DATA = [
  // --- LIST A ---
  { "l": "A", "s": "S19", "c": "BACH, J.C.F.", "t": "Allegro from Musikalische Nebenstunden Book 1" },
  { "l": "A", "s": "S19", "c": "DING, S.", "t": "Catching butterflies No 2 from Suite for children" },
  { "l": "A", "s": "S19", "c": "SCARLATTI, D.", "t": "Sonata K 149" },
  { "l": "A", "s": "S19", "c": "THIMAN, E.", "t": "Flood-time No 5 from Water pieces" },
  { "l": "A", "s": "S18", "c": "BACH, J.S.", "t": "Invention No 14 from BWV 785" },
  { "l": "A", "s": "S18", "c": "BURGMÜLLER, F.", "t": "Confidence No 1 from Op. 109" },
  { "l": "A", "s": "S18", "c": "SCARLATTI, D.", "t": "Sonata K 95" },
  { "l": "A", "s": "S18", "c": "ZIPOLI, D.", "t": "Giga 4th movement from Suite Op. 1 No 18" },
  { "l": "A", "s": "S17", "c": "BACH, J.S.", "t": "Invention No 3 from 15 inventions BWV 774" },
  { "l": "A", "s": "S17", "c": "BURGMÜLLER, F.", "t": "La source No 5 from Op. 109" },
  { "l": "A", "s": "S17", "c": "SEIXAS, C. de.", "t": "Toccata" },
  { "l": "A", "s": "S17", "c": "TANSMAN, A.", "t": "Gigue No 4 from Ten easy pieces" },
  { "l": "A", "s": "Manual", "c": "ARNE, T.", "t": "Gigue (Presto) 2nd movement from Sonata No 6 in G major (Thomas Augustine Arne: Eight sonatas – Kalmus)" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Invention No 8 in F major BWV 779" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Invention No 11 in G minor BWV 782" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Invention No 13 in A minor BWV 784" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Little prelude in D major BWV 925" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Little prelude in E major BWV 937" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Giguetta from Sarabande con partite BWV 990" },
  { "l": "A", "s": "Manual", "c": "BERENS, H.", "t": "Étude in F minor No 10 from Die Pflege der linken Hand Op. 89 Book II" },
  { "l": "A", "s": "Manual", "c": "COUPERIN, F.", "t": "Le moucheron No 8 from 6th ordre" },
  { "l": "A", "s": "Manual", "c": "CZERNY, C.", "t": "Étude in C major No 11 from Die Schule der Geläufigkeit Op. 299" },
  { "l": "A", "s": "Manual", "c": "CZERNY, C.", "t": "Étude in Eb major No 18 from Etudes de mécanisme Op. 849" },
  { "l": "A", "s": "Manual", "c": "FARRENC, L.", "t": "Étude in A major No 16 from 20 études de moyenne difficulté Op. 42" },
  { "l": "A", "s": "Manual", "c": "HANDEL, G.", "t": "Gigue (Presto) 4th movement from Suite in D minor HWV 436" },
  { "l": "A", "s": "Manual", "c": "HELLER, S.", "t": "Étude (Andantino con tenerezza) in Bb major No 16 from 25 études mélodiques Op. 45" },
  { "l": "A", "s": "Manual", "c": "HELLER, S.", "t": "Étude (Allegro) in G minor No 18 from 25 études mélodiques Op. 45" },
  { "l": "A", "s": "Manual", "c": "HELLER, S.", "t": "Étude (Allegro vivace) in C minor No 18 from 30 études progressives Op. 46" },
  { "l": "A", "s": "Manual", "c": "KABALEVSKY, D.", "t": "Étude (Allegro marcato) in F major No 24 from 30 pieces for children Op. 27" },
  { "l": "A", "s": "Manual", "c": "KABALEVSKY, D.", "t": "Étude (Allegro) in A major No 26 from 30 pieces for children Op. 27" },
  { "l": "A", "s": "Manual", "c": "KHACHATURIAN, A.", "t": "Étude from Detskiy al'bom No 1 (Children's Album No 1)" },
  { "l": "A", "s": "Manual", "c": "KÖHLER, L.", "t": "Study in E minor Op. 195" },
  { "l": "A", "s": "Manual", "c": "MARCELLO, B.", "t": "Presto 2nd movement from Sonata in G major" },
  { "l": "A", "s": "Manual", "c": "MOSZKOWSKI, M.", "t": "Étude (Vivace) No 2 from 20 petites études Op. 91 Book 1" },
  { "l": "A", "s": "Manual", "c": "NIELSEN, C.", "t": "Snurretoppen [Spinning top] No 2 from Humoreske-Bagateller Op. 11" },
  { "l": "A", "s": "Manual", "c": "PESCETTI, G.", "t": "Presto from Sonata No 6 in C minor" },
  { "l": "A", "s": "Manual", "c": "SCARLATTI, D.", "t": "Sonata in G major K 391" },
  { "l": "A", "s": "Manual", "c": "SCARLATTI, D.", "t": "Sonata in G major K 455" },
  { "l": "A", "s": "Manual", "c": "SHCHEDRIN, R.", "t": "Thirds No 5 from Notebook for young people" },
  { "l": "A", "s": "Manual", "c": "TELEMANN, G.", "t": "Vivace from Fantasia No 8 in G minor TWV 33:8" },
  { "l": "A", "s": "Manual", "c": "ZIPOLI, D.", "t": "Gavotta 4th movement from Keyboard Suite (Sonata) in B minor Op. 1 No 17" },

  // --- LIST B ---
  { "l": "B", "s": "S19", "c": "BENDA, G.", "t": "Sonatina from Sammlung Part 5" },
  { "l": "B", "s": "S19", "c": "CLEMENTI, M.", "t": "Monferrina No 7 Op. 49" },
  { "l": "B", "s": "S19", "c": "HUMMEL, J.", "t": "Scherzo No 45 from Anweisung" },
  { "l": "B", "s": "S19", "c": "MOZART, W.A.", "t": "Rondo (3rd movement of Sonata K 545)" },
  { "l": "B", "s": "S18", "c": "BEETHOVEN, L. van.", "t": "Bagatelle No 3 from Op. 33" },
  { "l": "B", "s": "S18", "c": "EBERL, A.", "t": "Rondo (3rd movement from Sonatine Op. 5)" },
  { "l": "B", "s": "S18", "c": "HAYDN, J.", "t": "Moderato (1st movement from Sonata Hob XVI:4)" },
  { "l": "B", "s": "S18", "c": "HUMMEL, J.", "t": "Alla Polacca No 53 from Anweisung" },
  { "l": "B", "s": "S17", "c": "DIABELLI, A.", "t": "Allegro moderato (1st movt of Sonatina No 4 Op. 168)" },
  { "l": "B", "s": "S17", "c": "DUSSEK, J.", "t": "Rondo (2nd movt of Sonatina No 6 Op. 20)" },
  { "l": "B", "s": "S17", "c": "HAYDN, J.", "t": "Finale (3rd movt from Divertimento Hob XVI/10)" },
  { "l": "B", "s": "S17", "c": "MOZART, W.", "t": "Rondo 4th movement of Divertimento K. Anh. 229/439b" },
  { "l": "B", "s": "Manual", "c": "BEETHOVEN, L. van.", "t": "Bagatelle (Allegretto) in G minor No 1 from 11 bagatelles Op. 119" },
  { "l": "B", "s": "Manual", "c": "BEETHOVEN, L. van.", "t": "Allegretto (2nd movt from Sonata Op. 14 No 1)" },
  { "l": "B", "s": "Manual", "c": "BEETHOVEN, L. van.", "t": "Scherzo and Trio (3rd movt from Sonata Op. 2 No 2)" },
  { "l": "B", "s": "Manual", "c": "BEETHOVEN, L. van.", "t": "Bagatelle No 6 Op. 33 (Henle)" },
  { "l": "B", "s": "Manual", "c": "BEETHOVEN, L. van.", "t": "Rondo in C major WoO 48 (Henle)" },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Con spirito (1st movt from Sonatina Op. 36 No 4)" },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Allegro con spirito (1st movt from Sonatina Op. 36 No 6)" },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Allegro (1st movt from Sonatina Op. 38 No 1)" },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Rondo (2nd movt from Sonatina Op. 38 No 2)" },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Allegro (1st movt from Sonatina Op. 38 No 3)" },
  { "l": "B", "s": "Manual", "c": "DIABELLI, A.", "t": "Rondo (3rd movt from Sonatina Op. 168 No 1)" },
  { "l": "B", "s": "Manual", "c": "DUSSEK, J.", "t": "Allegretto moderato (1st movt from Sonatina Op. 20 No 5)" },
  { "l": "B", "s": "Manual", "c": "HÄSSLER, J.", "t": "Allegro in Bb major (Henle)" },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Allegro 1st movement from Sonata Hob XVI:G1" },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Menuetto and Trio 2nd movement from Sonata in E major Hob. XVI:13" },
  { "l": "B", "s": "Manual", "c": "KUHLAU, F.", "t": "Allegro 1st movement from Sonatina in F major Op. 60 No 1" },
  { "l": "B", "s": "Manual", "c": "KUHLAU, F.", "t": "Rondo – Allegro 3rd movement from Sonatina in C major Op. 88 No 1" },
  { "l": "B", "s": "Manual", "c": "KUHLAU, F.", "t": "Allegro molto 1st movement from Sonatina in F major Op. 88 No 4" },
  { "l": "B", "s": "Manual", "c": "MOZART, W.", "t": "Allegro (1st movt from Viennese sonatina No 2)" },
  { "l": "B", "s": "Manual", "c": "PLEYEL, I.", "t": "Rondo – Allegretto (2nd movt from Sonatina II in F)" },
  { "l": "B", "s": "Manual", "c": "VOŘÍŠEK, J.V.", "t": "Rondeau mignon in C major Op. 18 No 2" },

  // --- LIST C ---
  { "l": "C", "s": "S19", "c": "CHAMINADE, C.", "t": "Élégie No 7 Op. 126" },
  { "l": "C", "s": "S19", "c": "GLIÈRE, R.", "t": "Prélude No 1 Op. 43" },
  { "l": "C", "s": "S19", "c": "GRANADOS, E.", "t": "Epílogo No 6 from Escenas románticas" },
  { "l": "C", "s": "S19", "c": "GRIEG, E.", "t": "Vöglein (Little bird) No 4 Op. 43" },
  { "l": "C", "s": "S18", "c": "CHAMINADE, C.", "t": "Tarentelle No 10 Op. 123" },
  { "l": "C", "s": "S18", "c": "GLIÈRE, R.", "t": "Rondo No 6 Op. 43" },
  { "l": "C", "s": "S18", "c": "HELLER, S.", "t": "Waltz No 7 Op. 97" },
  { "l": "C", "s": "S18", "c": "KÖLLING, C.", "t": "Lose Blätter No 2 Op. 147" },
  { "l": "C", "s": "S17", "c": "GLIÈRE, R.", "t": "Romanze No 7 Op. 31" },
  { "l": "C", "s": "S17", "c": "MACDOWELL, E.", "t": "Alla tarantella No 2 Op. 39" },
  { "l": "C", "s": "S17", "c": "SÉVERAC, D. de.", "t": "Invocation à Schumann from En vacances" },
  { "l": "C", "s": "S17", "c": "WOLLENHAUPT, H.", "t": "À la mazourka No 3b Op. 41" },
  { "l": "C", "s": "Manual", "c": "ALBÉNIZ, I.", "t": "Prelude 1st movt from España Op. 165" },
  { "l": "C", "s": "Manual", "c": "BEACH, A.", "t": "March No 4 from Children’s album Op. 36 (Young people’s album)" },
  { "l": "C", "s": "Manual", "c": "BRUCH, M.", "t": "Andante con Larghezzo No 6 from 6 Klavierstücke Op. 12" },
  { "l": "C", "s": "Manual", "c": "CHAMINADE, C.", "t": "Valse mignonne No 12 Op. 126" },
  { "l": "C", "s": "Manual", "c": "CHOPIN, F.", "t": "Polonaise in G minor Op. post./CT 161/KK IIa/1" },
  { "l": "C", "s": "Manual", "c": "CUI, C.", "t": "Spanish marionettes (Essential keyboard repertoire Volume 6)" },
  { "l": "C", "s": "Manual", "c": "GADE, N.", "t": "Kanzonette No 3 from Aquarellen Op. 19" },
  { "l": "C", "s": "Manual", "c": "GLIÈRE, R.", "t": "Valse in Bb major No 6 from 12 pièces enfantines Op. 31" },
  { "l": "C", "s": "Manual", "c": "GLIÈRE, R.", "t": "Mazurka No 3 from 8 pièces faciles Op. 43" },
  { "l": "C", "s": "Manual", "c": "GLIÈRE, R.", "t": "Arietta No 7 from 8 pièces faciles Op. 43" },
  { "l": "C", "s": "Manual", "c": "GRECHANINOV, A.", "t": "Ballade Op. 99 No 3 (The Grechaninov collection)" },
  { "l": "C", "s": "Manual", "c": "GRIEG, E.", "t": "Allegro ma non troppo No 1 from Poetische Tonbilder Op. 3" },
  { "l": "C", "s": "Manual", "c": "GRIEG, E.", "t": "Vals [Waltz] No 2 from Lyriske småstykker Op. 12" },
  { "l": "C", "s": "Manual", "c": "GRIEG, E.", "t": "Walzer No 7 from Neue Lyrische Stückchen Op. 38" },
  { "l": "C", "s": "Manual", "c": "HELLER, S.", "t": "Gedenkblatt No 7 from Notenbuch für Klein und Gross Op. 138" },
  { "l": "C", "s": "Manual", "c": "HELLER, S.", "t": "Scherzetto No 8 from Notenbuch für Klein und Gross Op. 138" },
  { "l": "C", "s": "Manual", "c": "MACDOWELL, E.", "t": "Gnomentanz [Dance of the gnomes] No 6 from 12 Etüden Op. 39" },
  { "l": "C", "s": "Manual", "c": "MAYKAPAR, S.", "t": "Tarantella No 6 from Miniatures Op. 33" },
  { "l": "C", "s": "Manual", "c": "MENDELSSOHN, F.", "t": "Venetianisches Gondellied No 6 in G minor from Lieder ohne Worte Op. 19b" },
  { "l": "C", "s": "Manual", "c": "NIELSEN, C.", "t": "Spilleværket [The musical clock] No 6 from Humoreske-Bagateller Op. 11" },
  { "l": "C", "s": "Manual", "c": "REGER, M.", "t": "Fast zu keck! No 12 from Aus der Jugendzeit Op. 17" },
  { "l": "C", "s": "Manual", "c": "REINECKE, C.", "t": "Moderato 1st movement from Sonatina Op. 98 No 2" },
  { "l": "C", "s": "Manual", "c": "SCHUMANN, R.", "t": "* * * No 30 from Album für die Jugend [Album for the young] Op. 68" },
  { "l": "C", "s": "Manual", "c": "SCHUMANN, R.", "t": "Lied italienischer Marinari [Italian Mariners' Song] No 36 from Album für die Jugend Op. 68" },
  { "l": "C", "s": "Manual", "c": "SCHUMANN, R.", "t": "Einsame Blumen [Lonely flowers] No 3 from Waldscenen Op. 82" },
  { "l": "C", "s": "Manual", "c": "SIBELIUS, J.", "t": "Joueur de harpe [The harpist] No 8 from 10 bagatelles Op. 34" },

  // --- LIST D ---
  { "l": "D", "s": "S19", "c": "CAPERS, V.", "t": "Waltz for Miles No 2 from Portraits in jazz" },
  { "l": "D", "s": "S19", "c": "GLANVILLE-HICKS, P.", "t": "Pastoral" },
  { "l": "D", "s": "S19", "c": "GREENAWAY, S.", "t": "Dawn of evening" },
  { "l": "D", "s": "S19", "c": "HANNAN, M.", "t": "Three Australian bird songs" },
  { "l": "D", "s": "S19", "c": "SANG, T.", "t": "Dance No 7 from Mongolian folk songs" },
  { "l": "D", "s": "S18", "c": "BARTÓK, B.", "t": "Merry Andrew No 139 (Mikrokosmos V)" },
  { "l": "D", "s": "S18", "c": "BENJAMIN, A.", "t": "Haunted house" },
  { "l": "D", "s": "S18", "c": "PROKOFIEV, S.", "t": "La pluie et l’arc-en-ciel No 8 Op. 65" },
  { "l": "D", "s": "S18", "c": "RUSSELL-SMITH, G.", "t": "Wistful prelude" },
  { "l": "D", "s": "S17", "c": "HANDEL, A.", "t": "Stalactite No 1 from Migrations in music" },
  { "l": "D", "s": "S17", "c": "IBERT, J.", "t": "A giddy girl No 4 from Histoires" },
  { "l": "D", "s": "S17", "c": "LUTOSŁAWSKI, W.", "t": "Marsz No 3 from 3 pieces for the young" },
  { "l": "D", "s": "S17", "c": "SITSKY, L.", "t": "Jewish folksong – dance" },
  { "l": "D", "s": "Anthology", "c": "BENJAMIN, A.", "t": "March (Australian Anthology)" },
  { "l": "D", "s": "Anthology", "c": "EAGLES, M.", "t": "Pastorale (Australian Anthology)" },
  { "l": "D", "s": "Manual", "c": "BAILEY, K.", "t": "Boogie rock (Jazzin' around 4)" },
  { "l": "D", "s": "Manual", "c": "BAILEY, K.", "t": "Left hand drive (Jazzin' around 5)" },
  { "l": "D", "s": "Manual", "c": "BARTÓK, B.", "t": "Harmonics No 102 (Mikrokosmos IV)" },
  { "l": "D", "s": "Manual", "c": "BARTÓK, B.", "t": "Stamping dance No 128 (Mikrokosmos V)" },
  { "l": "D", "s": "Manual", "c": "BRUMBY, C.", "t": "Arlecchino No 1 from Harlequinade" },
  { "l": "D", "s": "Manual", "c": "BRUMBY, C.", "t": "Columbina No 2 from Harlequinade" },
  { "l": "D", "s": "Manual", "c": "CHUA, S.", "t": "Around the world in 2 minutes … or less" },
  { "l": "D", "s": "Manual", "c": "CHUA, S.", "t": "Zeitgeist 22" },
  { "l": "D", "s": "Manual", "c": "COREA, C.", "t": "Children's song No 7 (Schott's 20th century piano classics)" },
  { "l": "D", "s": "Manual", "c": "CORNICK, M.", "t": "Blue ballad (Blue piano)" },
  { "l": "D", "s": "Manual", "c": "CORNICK, M.", "t": "First impression (Blue piano)" },
  { "l": "D", "s": "Manual", "c": "DE JONG, S.", "t": "In the wind (Australian piano miniatures)" },
  { "l": "D", "s": "Manual", "c": "DELLO JOIO, N.", "t": "Russian dancer (The Boosey and Hawkes 20th century piano collection)" },
  { "l": "D", "s": "Manual", "c": "DURHAM, B.", "t": "Birds in the swamp (Relaxation for piano: Back to nature)" },
  { "l": "D", "s": "Manual", "c": "EASTON, M.", "t": "High spirits No 2 from Moods" },
  { "l": "D", "s": "Manual", "c": "EASTON, M.", "t": "Practical jokes No 4 from Moods" },
  { "l": "D", "s": "Manual", "c": "HOLLAND, D.", "t": "Dancing shadows from Five story pieces for young pianists: Medium difficulty" },
  { "l": "D", "s": "Manual", "c": "HUTCHENS, F.", "t": "Two little birds (EMI Music Publishing)" },
  { "l": "D", "s": "Manual", "c": "HYDE, M.", "t": "Dragonflies (Wirripang)" },
  { "l": "D", "s": "Manual", "c": "HYDE, M.", "t": "Reverie (EMI Music Publishing)" },
  { "l": "D", "s": "Manual", "c": "KABALEVSKY, D.", "t": "Caprice No 28 from 30 pieces for children Op. 27" },
  { "l": "D", "s": "Manual", "c": "KABALEVSKY, D.", "t": "Cavalryman No 29 from 30 pieces for children Op. 27" },
  { "l": "D", "s": "Manual", "c": "KABALEVSKY, D.", "t": "A dramatic event No 30 from 30 pieces for children Op. 27" },
  { "l": "D", "s": "Manual", "c": "KHACHATURIAN, A.", "t": "Two ladies gossiping No 6 from Detskiy al'bom 2 (Children's Album No 2)" },
  { "l": "D", "s": "Manual", "c": "LUTOSŁAWSKI, W.", "t": "Allegro vivace 1st movement from Bukoliki" },
  { "l": "D", "s": "Manual", "c": "McCOMBE, C.", "t": "Asphyxed (Australian piano miniatures)" },
  { "l": "D", "s": "Manual", "c": "MILHAUD, D.", "t": "Romance (The century of invention)" },
  { "l": "D", "s": "Manual", "c": "PROKOFIEV, S.", "t": "Tarantella No 4 Op. 65" },
  { "l": "D", "s": "Manual", "c": "PROKOFIEV, S.", "t": "Marche No. 10 from Music for children Op. 65" },
  { "l": "D", "s": "Manual", "c": "SHOSTAKOVICH, D.", "t": "Country dance (Essential keyboard repertoire Volume 6: Baroque to Modern)" },
  { "l": "D", "s": "Manual", "c": "SITSKY, L.", "t": "Only one note No 108 and Interjections No 109 from Century Volume 3" },
  { "l": "D", "s": "Manual", "c": "TCHEREPNIN, A.", "t": "Bagatelle No 9 from Bagatelles: 10 pieces for piano Op. 5" },
  { "l": "D", "s": "Manual", "c": "VILLA-LOBOS, H.", "t": "Samba-lêlê No 4 from Guia pràtico Volume 2" },

  // --- COLLABORATIVE PIANO (List C/D) ---
  { "l": "Collab", "s": "List C", "c": "GRIEG, E.", "t": "Norwegian dance No 2 [Primo or Secondo] Op. 35" },
  { "l": "Collab", "s": "List C", "c": "MOSZKOWSKI, M.", "t": "Spanish dance No 2 in G minor [Primo or Secondo] Op. 12" },
  { "l": "Collab", "s": "List C", "c": "SCHUBERT, F.", "t": "March ('Kindermarsch') in G major [Primo or Secondo] D 928" },
  { "l": "Collab", "s": "List C", "c": "SCHUMANN, R.", "t": "Gartenmelodie No 3 [Secondo] Op. 85" },
  { "l": "Collab", "s": "List D", "c": "CORNICK, M.", "t": "Ringing the changes [Secondo] (Easy jazzy duets)" },
  { "l": "Collab", "s": "List D", "c": "CORNICK, M.", "t": "Conga 3rd movt [Primo] from Latin Suite No 1" },
  { "l": "Collab", "s": "List D", "c": "MILNE, E.", "t": "Mulga Bill [Primo or Secondo] (Pepperbox jazz)" },
  { "l": "Collab", "s": "List D", "c": "RAVEL, M.", "t": "Petit poucet No 2 [Secondo] from Mother Goose" }
];