// ABRSM G7 — 48 pieces
const DATA_ABRSM_G7 = [
  {"l":"A","c":"BEETHOVEN, L.","t":"Scherzo (3rd movt from Sonata in A, Op. 2 No. 2)","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Crisp fingerwork"]},
  {"l":"A","c":"YUYAMA, Akira","t":"Pop Corn (No. 18 from Confections: A Piano Sweet)","nat":"Japanese","era":"Modern","focus":["Rhythmic precision","Jazz/Pop style","Character contrast"]},
  {"l":"A","c":"DAQUIN, L.","t":"Le coucou (Rondeau: 1st movt from Troisième Piano suite)","nat":"French","era":"Baroque","focus":["Baroque style","Finger independence","Keyboard clarity"]},
  {"l":"A","c":"BACH, C.P.E.","t":"Allegro di molto (1st movt from Sonata in F minor, Wq. 63/6)","nat":"German","era":"Baroque","focus":["Baroque style","Formal structure","Keyboard clarity"]},
  {"l":"A","c":"BACH, J.S.","t":"Gigue (7th movt from French Suite No. 3 in B minor, BWV 814)","nat":"German","era":"Baroque","focus":["Baroque style","Finger independence","Keyboard clarity"]},
  {"l":"A","c":"BEETHOVEN, L.","t":"Menuetto and Trio (3rd movt from Sonata in D, Op. 10 No. 3)","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Dance character"]},
  {"l":"A","c":"GRIEG, E.","t":"Rigaudon (5th movt from Holberg Suite, Op. 40)","nat":"Norwegian","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"A","c":"HANDEL, G.F.","t":"Allemande and Courante (2nd and 3rd movts from Suite in D minor, HWV 437)","nat":"German","era":"Baroque","focus":["Baroque style","Dance character","Keyboard clarity"]},
  {"l":"A","c":"HAYDN, J.","t":"Moderato (1st movt from Sonata in E, Hob. XVI:31)","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Singing tone"]},
  {"l":"A","c":"KUHLAU, F.","t":"Allegro con spirito (1st movt from Sonatina in A, Op. 60 No. 1)","nat":"Danish","era":"Classical","focus":["Classical phrasing","Formal structure","Harmonic awareness"]},
  {"l":"A","c":"MOZART, W.A.","t":"Gigue in G, K. 574","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Hand coordination","Formal structure"]},
  {"l":"A","c":"PARADIES, D.","t":"Allegro (2nd movt from Sonata No. 6 in A)","nat":"Italian","era":"Modern","focus":["Rhythmic precision","Formal structure","Character contrast"]},
  {"l":"A","c":"RAMEAU, J.-P.","t":"Les sauvages (from Pièces de clavecin)","nat":"French","era":"Baroque","focus":["Baroque style","Finger independence","Keyboard clarity"]},
  {"l":"A","c":"SCARLATTI, D.","t":"Sonata in E, Kp. 380, L. 23","nat":"Italian","era":"Baroque","focus":["Baroque style","Formal structure","Keyboard clarity"]},
  {"l":"A","c":"SCHUMANN, C.","t":"Scherzo (No. 4 from Quatre pièces fugitives, Op. 15)","nat":"German","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"TURINA, J.","t":"El mercado (No. 5 from Miniaturas, Op. 52)","nat":"Spanish","era":"Modern","focus":["Rhythmic precision","Modern harmony","Character contrast"]},
  {"l":"B","c":"SCHUMANN, R.","t":"Winterzeit I (No. 38 from Album für die Jugend, Op. 68)","nat":"German","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"B","c":"GINASTERA, A.","t":"Adagietto pianissimo (No. 1 from Suite de danzas criollas, Op. 15)","nat":"Argentine","era":"Modern","focus":["Rhythmic precision","Modern harmony","Character contrast"]},
  {"l":"B","c":"MENDELSSOHN, F.","t":"Musical Sketch in B flat (No. 1 from Two Musical Sketches)","nat":"German","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"B","c":"BULLARD, Alan","t":"Prelude No. 9 (from 12 or 13 Preludes for Piano Solo, Set One)","nat":"English","era":"Contemporary","focus":["Contemporary idiom","Contrapuntal texture","Musical expression"]},
  {"l":"B","c":"DEBUSSY, C.","t":"The Little Shepherd (No. 5 from Children's Corner)","nat":"French","era":"Modern","focus":["Impressionist style","Singing tone","Musical expression"]},
  {"l":"B","c":"GÖRRES","t":"Children's Song (No. 11 from Bunte Reihen kurzer Klavierstücke, Op. 13)","nat":"German","era":"Modern","focus":["Rhythmic precision","Singing tone","Character contrast"]},
  {"l":"B","c":"HENSEL, F.M.","t":"Mélodie, Op. 4 No. 2","nat":"German","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"B","c":"ILYINSKY, A.","t":"Berceuse (No. 7 from Noure et Anitra, Op. 13)","nat":"Russian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"B","c":"LISZT, F.","t":"Consolation No. 5 in E (from Consolations, S. 172)","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"B","c":"LYADOV, A.","t":"Mazurka in F minor (No. 3 from Trois morceaux, Op. 57)","nat":"Russian","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"B","c":"MENDELSSOHN, F.","t":"Song without Words, Op. 19 No. 1","nat":"German","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"B","c":"RICHARDSON, A.","t":"Lento moderato (2nd movt from Sonatina in F, Op. 27)","nat":"English","era":"Modern","focus":["Rhythmic precision","Formal structure","Character contrast"]},
  {"l":"B","c":"RUBINSTEIN, A.","t":"Romance (No. 1 from Soirées à Saint-Petersbourg, Op. 44)","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Singing tone","Character contrast"]},
  {"l":"B","c":"RUSSELL, O.","t":"Jamaican Dance No. 2 (from Three Jamaican Dances)","nat":"English","era":"Modern","focus":["Rhythmic precision","Dance character","Character contrast"]},
  {"l":"B","c":"SCHUMANN, R.","t":"Kind im Einschlummern (No. 12 from Kinderscenen, Op. 15)","nat":"German","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"B","c":"WOLF, P. E.","t":"Nostalgia (Vágyódás) (No. 4 from Jazz Preludes Wolf-temperiertes Klavier 2)","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision","Jazz/Pop style","Character contrast"]},
  {"l":"C","c":"KAHN, E.","t":"The Watermill","nat":"German","era":"Modern","focus":["Rhythmic precision","Modern harmony","Character contrast"]},
  {"l":"C","c":"MACGREGOR, Joanna","t":"Lowside Blues","nat":"British","era":"Modern","focus":["Rhythmic precision","Jazz/Pop style","Character contrast"]},
  {"l":"C","c":"SHOSTAKOVICH, D.","t":"Allegretto (No. 1 from Three Fantastic Dances, Op. 5)","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Dance character","Character contrast"]},
  {"l":"C","c":"BARTÓK, B.","t":"Bagpipers: Allegretto (1st movt from Sonatina)","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision","Formal structure","Character contrast"]},
  {"l":"C","c":"YI, Chen","t":"Bamboo Dance II","nat":"Chinese-American","era":"Modern","focus":["Rhythmic precision","Dance character","Character contrast"]},
  {"l":"C","c":"GINASTERA, A.","t":"Tribute to Roberto Garcia Morillo (No. 6 from 12 American Preludes, Op. 12)","nat":"Argentine","era":"Modern","focus":["Rhythmic precision","Contrapuntal texture","Character contrast"]},
  {"l":"C","c":"GRIEG, E.","t":"Butterfly (No. 1 from Lyric Pieces, Book 3, Op. 43)","nat":"Norwegian","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"C","c":"GROVLEZ, G.","t":"Chanson du chasseur (No. 4 from L’Almanach aux images)","nat":"French","era":"Modern","focus":["Rhythmic precision","Singing tone","Character contrast"]},
  {"l":"C","c":"HOWARD, Bart","t":"Fly Me to the Moon","nat":"American","era":"Modern","focus":["Rhythmic precision","Modern harmony","Character contrast"]},
  {"l":"C","c":"KERN, J.","t":"Smoke Gets in Your Eyes (from Roberta), Lee","nat":"American","era":"Modern","focus":["Rhythmic precision","Modern harmony","Character contrast"]},
  {"l":"C","c":"MULSANT, Florentine","t":"Prélude No. 14 (from 24 Préludes pour piano, Op. 38)","nat":"French","era":"Modern","focus":["Rhythmic precision","Modern harmony","Character contrast"]},
  {"l":"C","c":"NORTON, Christopher","t":"Pop Bossa (No. 5 from Latin Preludes 2) Christopher","nat":"English","era":"Contemporary","focus":["Contemporary idiom","Jazz/Pop style","Musical expression"]},
  {"l":"C","c":"PIAZZOLLA, A.","t":"Milonga del ángel","nat":"Argentine","era":"Modern","focus":["Rhythmic precision","Modern harmony","Character contrast"]},
  {"l":"C","c":"UZOIGWE, J.","t":"Nigerian Dance No. 1 (from Four Nigerian Dances)","nat":"Nigerian","era":"Modern","focus":["Rhythmic precision","Dance character","Character contrast"]},
  {"l":"C","c":"VILLOLDO, A.","t":"El Choclo","nat":"Argentine","era":"Modern","focus":["Rhythmic precision","Modern harmony","Character contrast"]},
  {"l":"C","c":"VINE, C.","t":"Spartacus","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Rhythmic precision","Musical expression"]}
];
