// ABRSM Piano 2025 & 2026 — G7
// Total: 46 pieces  A:16 B:15 C:15
// Generated from official ABRSM Piano 2025 & 2026 Syllabus PDF

const DATA_ABRSM_G7 = [
  // LIST A — 16 pieces
{"l":"A","c":"BEETHOVEN","t":"Scherzo (3rd movt from Sonata in A, Op. 2 No. 2)","nat":"German","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"YUYAMA, Akira","t":"Pop Corn (No. 18 from Confections: A Piano Sweet)","nat":"Japanese","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
{"l":"A","c":"DAQUIN","t":"Le coucou (Rondeau: 1st movt from Troisième Piano suite)","nat":"French","era":"Baroque","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
{"l":"A","c":"BACH, C.P.E.","t":"Allegro di molto (1st movt from Sonata in Pp. F minor, Wq. 63/6) Book","nat":"German","era":"Baroque","focus":["Baroque style", "Formal structure", "Keyboard clarity"]},
{"l":"A","c":"BACH, J.S.","t":"Gigue (7th movt from French Suite No. 3 in J. B minor, BWV)","nat":"German","era":"Baroque","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
{"l":"A","c":"BEETHOVEN","t":"Menuetto and Trio (3rd movt from Sonata in D, Beethoven: Op. 10 No. 3) Beethoven: Beethoven","nat":"German","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"GRIEG","t":"Rigaudon (5th movt from Holberg Suite, Op. 40)","nat":"Norwegian","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"A","c":"HANDEL","t":"Allemande and Courante (2nd and 3rd movts Handel: from Suite in D minor, HWV)","nat":"German","era":"Baroque","focus":["Baroque style", "Dance character", "Keyboard clarity"]},
{"l":"A","c":"HAYDN","t":"Moderato (1st movt from Sonata in E, Haydn: Hob. XVI:31) Haydn","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"KUHLAU","t":"Allegro con spirito (1st movt from Sonatina in A, Op. 60 No. 1)","nat":"International","era":"Classical","focus":["Classical phrasing", "Formal structure", "Formal structure"]},
{"l":"A","c":"MOZART","t":"Gigue in G, K. 574 Pp.","nat":"Austrian","era":"Classical","focus":["Classical phrasing", "Hand coordination", "Formal structure"]},
{"l":"A","c":"PARADIES","t":"Allegro (2nd movt from Sonata No. 6 in A) Pp.","nat":"International","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"A","c":"RAMEAU","t":"Les sauvages (from Pièces de clavecin) Rameau: pp.","nat":"International","era":"Baroque","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
{"l":"A","c":"SCARLATTI, D.","t":"Sonata in E, Kp. 380, L. 23 Pp. Sonatas, D.","nat":"Italian","era":"Baroque","focus":["Baroque style", "Formal structure", "Keyboard clarity"]},
{"l":"A","c":"SCHUMANN, C.","t":"Scherzo (No. 4 from Quatre pièces fugitives, Op. 15)","nat":"International","era":"Romantic","focus":["Expressive tone", "Formal structure", "Dynamic shaping"]},
{"l":"A","c":"TURINA, Joaquín","t":"El mercado (No. 5 from Miniaturas, Op. 52)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
  // LIST B — 15 pieces
{"l":"B","c":"SCHUMANN","t":"Winterzeit I (No. 38 from Album für die Jugend, Op. 68)","nat":"German","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"GINASTERA","t":"Adagietto pianissimo (No. 1 from Suite de danzas criollas, Op. 15)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"B","c":"MENDELSSOHN","t":"Musical Sketch in B flat (No. 1 from Two Musical Sketches)","nat":"International","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"BULLARD, Alan","t":"Prelude No. 9 (from 12 or 13 Preludes for Piano Solo, Set One)","nat":"English","era":"Contemporary","focus":["Contemporary idiom", "Contrapuntal texture", "Musical expression"]},
{"l":"B","c":"GÖRRES","t":"Children's Song (No. 11 from Bunte Reihen kurzer Klavierstücke, Op. 13)","nat":"German","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"B","c":"HENSEL, F.M.","t":"Mélodie, Op. 4 No. 2","nat":"German","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"ILYINSKY","t":"Berceuse (No. 7 from Noure et Anitra, Op. 13)","nat":"Russian","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"B","c":"LISZT","t":"Consolation No. 5 in E (from Consolations, S. 172) Liszt: Liszt","nat":"Hungarian","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"B","c":"LYADOV","t":"Mazurka in F minor (No. 3 from Trois morceaux, Op. 57)","nat":"Russian","era":"Romantic","focus":["Expressive tone", "Dance character", "Dynamic shaping"]},
{"l":"B","c":"MENDELSSOHN","t":"Song without Words, Op. 19 No. 1 Mendelssohn","nat":"International","era":"Romantic","focus":["Expressive tone", "Singing tone", "Dynamic shaping"]},
{"l":"B","c":"RICHARDSON, A.","t":"Lento moderato (2nd movt from Sonatina in F, Op. 27)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"B","c":"RUBINSTEIN","t":"Romance (No. 1 from Soirées à Saint-Petersbourg, Op. 44)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"B","c":"RUSSELL, O.","t":"Jamaican Dance No. 2 (from Three Jamaican Dances)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"B","c":"SCHUMANN","t":"Kind im Einschlummern (No. 12 from Kinderscenen, Op. 15)","nat":"German","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"B","c":"WOLF, P. E.","t":"Nostalgia (Vágyódás) (No. 4 from Jazz Preludes Jazz Wolf-temperiertes Klavier 2) (EMB)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
  // LIST C — 15 pieces
{"l":"C","c":"KAHN","t":"The Watermill","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"MACGREGOR, Joanna","t":"Lowside Blues","nat":"International","era":"Modern","focus":["Rhythmic precision", "Jazz/Pop style", "Character contrast"]},
{"l":"C","c":"SHOSTAKOVICH","t":"Allegretto (No. 1 from Three Fantastic Dances, Op. 5)","nat":"Russian","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"C","c":"BARTÓK","t":"Bagpipers: Allegretto (1st movt from Sonatina) Bartók","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision", "Formal structure", "Character contrast"]},
{"l":"C","c":"YI, Chen","t":"Bamboo Dance II","nat":"International","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"C","c":"GINASTERA","t":"Tribute to Roberto Garcia Morillo (No. 6 from 12 American Preludes, Op. 12)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Contrapuntal texture", "Character contrast"]},
{"l":"C","c":"GRIEG","t":"Butterfly (No. 1 from Lyric Pieces, Book 3, Op. 43)","nat":"Norwegian","era":"Romantic","focus":["Expressive tone", "Lyrical phrasing", "Dynamic shaping"]},
{"l":"C","c":"GROVLEZ","t":"Chanson du chasseur (No. 4 from L’Almanach Grovlez: aux images) Beyond","nat":"International","era":"Modern","focus":["Rhythmic precision", "Singing tone", "Character contrast"]},
{"l":"C","c":"HOWARD, Bart","t":"Fly Me to the Moon","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"KERN","t":"Smoke Gets in Your Eyes (from Roberta), Lee","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"MULSANT, Florentine","t":"Prélude No. 14 (from 24 Préludes pour piano, Op. 38)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"NORTON, Christopher","t":"Pop Bossa (No. 5 from Latin Preludes 2) Christopher","nat":"International","era":"Contemporary","focus":["Contemporary idiom", "Jazz/Pop style", "Musical expression"]},
{"l":"C","c":"PIAZZOLLA","t":"Milonga del ángel Piazzolla","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
{"l":"C","c":"UZOIGWE","t":"Nigerian Dance No. 1 (from Four Nigerian Dances)","nat":"International","era":"Modern","focus":["Rhythmic precision", "Dance character", "Character contrast"]},
{"l":"C","c":"VILLOLDO","t":"El Choclo","nat":"International","era":"Modern","focus":["Rhythmic precision", "Modern harmony", "Character contrast"]},
];
