// ABRSM FRSM Piano Repertoire List
// Source: Piano FRSM Repertoire [7 Nov 2023] FINAL.pdf
// Valid from November 2023 until further notice
// Open repertoire pool — candidates programme from this list per qualification spec
// Total: 97 entries

const DATA_ABRSM_FRSM = [
  { "c": "ADAMS, John", "t": "Phrygian Gates", "nat": "American", "era": "Contemporary", "focus": ["Minimalist style", "Extended duration", "Gradual transformation"] },
  { "c": "ALBÉNIZ", "t": "Any one of the 12 pieces from 'Iberia', except Nos. 1, 2 and 4", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish idiom", "Colouristic virtuosity", "Rhythmic vitality"] },
  { "c": "ALBERGA, Eleanor", "t": "It's Time", "nat": "Jamaican", "era": "Contemporary", "focus": ["Contemporary idiom", "Expressive intensity", "Technical demands"] },
  { "c": "ALEXANDROV", "t": "Sonata No. 4, Op. 19: complete", "nat": "Russian", "era": "Modern", "focus": ["Sonata form", "Russian modernism", "Technical demands"] },
  { "c": "BACEWICZ", "t": "Sonata No. 2: complete", "nat": "Polish", "era": "Modern", "focus": ["Neo-classical style", "Rhythmic drive", "Structural rigour"] },
  { "c": "BACH, J.S.", "t": "Partita No. 6 in E minor, BWV 830: complete", "nat": "German", "era": "Baroque", "focus": ["Suite structure", "Baroque complexity", "Contrapuntal texture"] },
  { "c": "BACH, J.S./BUSONI", "t": "Chaconne in D minor (from Partita No. 2 for solo violin)", "nat": "German", "era": "Baroque", "focus": ["Transcription virtuosity", "Chaconne form", "Monumental scope"] },
  { "c": "BARBER", "t": "Sonata in E♭, Op. 26: complete", "nat": "American", "era": "Modern", "focus": ["Sonata form", "American modernism", "Fugal finale"] },
  { "c": "BARTÓK", "t": "Sonata (1926): complete", "nat": "Hungarian", "era": "Modern", "focus": ["Percussive texture", "Folk-influenced writing", "Technical demands"] },
  { "c": "BAX", "t": "Sonata No. 3 in G# minor: complete", "nat": "English", "era": "Romantic", "focus": ["Late-Romantic grandeur", "Sonata form", "Lush harmony"] },
  { "c": "BEETHOVEN", "t": "Sonata in C ('Waldstein'), Op. 53: complete", "nat": "German", "era": "Classical", "focus": ["Virtuosic writing", "Technical demands", "Heroic character"] },
  { "c": "BEETHOVEN", "t": "Sonata in F minor ('Appassionata'), Op. 57: complete", "nat": "German", "era": "Classical", "focus": ["Dramatic intensity", "Motivic unity", "Structural drama"] },
  { "c": "BEETHOVEN", "t": "Sonata in E♭ ('Les Adieux'), Op. 81a: complete", "nat": "German", "era": "Classical", "focus": ["Programmatic expression", "Farewell character", "Late Classical style"] },
  { "c": "BEETHOVEN", "t": "Sonata in A, Op. 101: complete", "nat": "German", "era": "Classical", "focus": ["Late style", "Contrapuntal mastery", "Inner voice singing"] },
  { "c": "BEETHOVEN", "t": "Sonata in E, Op. 109: complete", "nat": "German", "era": "Classical", "focus": ["Late style", "Variation finale", "Spiritual depth"] },
  { "c": "BEETHOVEN", "t": "Sonata in A♭, Op. 110: complete", "nat": "German", "era": "Classical", "focus": ["Late style", "Fugue and arioso", "Transcendent expression"] },
  { "c": "BEETHOVEN", "t": "Sonata in C minor, Op. 111: complete", "nat": "German", "era": "Classical", "focus": ["Final sonata", "Variation movement", "Spiritual transcendence"] },
  { "c": "BEETHOVEN", "t": "15 Variations and Fugue in E♭, Op. 35 ('Eroica Variations')", "nat": "German", "era": "Classical", "focus": ["Theme and variations", "Heroic character", "Contrapuntal mastery"] },
  { "c": "BERG", "t": "Sonata, Op. 1: complete", "nat": "Austrian", "era": "Modern", "focus": ["Late Romantic harmony", "Expressionist style", "Organic form"] },
  { "c": "BORTKIEWICZ", "t": "Vier Klavierstücke, Op. 65: complete", "nat": "Ukrainian", "era": "Romantic", "focus": ["Late-Romantic style", "Character pieces", "Lyrical writing"] },
  { "c": "BOULEZ", "t": "Sonata No. 1: complete", "nat": "French", "era": "Contemporary", "focus": ["Serial technique", "Structural complexity", "Modernist rigour"] },
  { "c": "BRAHMS", "t": "Sonata in C, Op. 1: complete", "nat": "German", "era": "Romantic", "focus": ["Early Romantic style", "Sonata form", "Youthful passion"] },
  { "c": "BRAHMS", "t": "Sonata in F# minor, Op. 2: complete", "nat": "German", "era": "Romantic", "focus": ["Early Romantic style", "Lyrical intensity", "Structural ambition"] },
  { "c": "BRAHMS", "t": "Sonata in F minor, Op. 5: complete", "nat": "German", "era": "Romantic", "focus": ["Grandest early sonata", "Romantic sweep", "Structural mastery"] },
  { "c": "BRAHMS", "t": "11 Variations in D on an Original Theme, Op. 21 No. 1", "nat": "German", "era": "Romantic", "focus": ["Theme and variations", "Contrapuntal texture", "Romantic idiom"] },
  { "c": "BRAHMS", "t": "25 Variations and Fugue on a Theme by Handel, Op. 24", "nat": "German", "era": "Romantic", "focus": ["Monumental variations", "Contrapuntal mastery", "Technical demands"] },
  { "c": "BRAHMS", "t": "28 Variations on a Theme by Paganini, Op. 35", "nat": "German", "era": "Romantic", "focus": ["Virtuosic études", "Theme and variations", "Technical demands"] },
  { "c": "BRIDGE", "t": "Sonata: complete", "nat": "English", "era": "Modern", "focus": ["Sonata form", "Expressive depth", "Harmonic ambiguity"] },
  { "c": "BUTLER, Martin", "t": "Lucifer's Banjo", "nat": "English", "era": "Contemporary", "focus": ["Wit and energy", "Contemporary idiom", "Rhythmic vitality"] },
  { "c": "BUTLER, Martin", "t": "On the Rocks", "nat": "English", "era": "Contemporary", "focus": ["Character piece", "Contemporary idiom", "Technical demands"] },
  { "c": "CARTER, E.", "t": "Two Thoughts about the Piano: complete", "nat": "American", "era": "Contemporary", "focus": ["Rhythmic complexity", "Contemporary idiom", "Expressive contrast"] },
  { "c": "CHAMINADE", "t": "Six études de concert, Op. 35: complete", "nat": "French", "era": "Romantic", "focus": ["Technical study", "Salon brilliance", "Complete set"] },
  { "c": "CHIN, Unsuk", "t": "Any two or more of the 6 'Piano Etudes'", "nat": "Korean", "era": "Contemporary", "focus": ["Extended technique", "Contemporary idiom", "Technical demands"] },
  { "c": "CHOPIN", "t": "Ballade No. 4 in F minor, Op. 52", "nat": "Polish", "era": "Romantic", "focus": ["Late masterwork", "Narrative sweep", "Technical demands"] },
  { "c": "CHOPIN", "t": "Fantaisie in F minor, Op. 49", "nat": "Polish", "era": "Romantic", "focus": ["Fantasia form", "Romantic sweep", "Dramatic contrast"] },
  { "c": "CHOPIN", "t": "Polonaise-Fantaisie in A♭, Op. 61", "nat": "Polish", "era": "Romantic", "focus": ["Late style", "Structural ambiguity", "Expressive depth"] },
  { "c": "CHOPIN", "t": "Sonata in B♭ minor, Op. 35: complete", "nat": "Polish", "era": "Romantic", "focus": ["Romantic drama", "Funeral march", "Sonata form"] },
  { "c": "CHOPIN", "t": "Sonata in B minor, Op. 58: complete", "nat": "Polish", "era": "Romantic", "focus": ["Romantic lyricism", "Sonata form", "Late style"] },
  { "c": "DUTILLEUX", "t": "Sonata: complete", "nat": "French", "era": "Contemporary", "focus": ["French modernism", "Sonata form", "Colouristic harmony"] },
  { "c": "FAURÉ", "t": "Ballade, Op. 19", "nat": "French", "era": "Romantic", "focus": ["Lyrical sweep", "Flowing melody", "Late-Romantic harmony"] },
  { "c": "FAURÉ", "t": "Theme and Variations in C# minor, Op. 73", "nat": "French", "era": "Romantic", "focus": ["Theme and variations", "Motivic development", "Late-Romantic harmony"] },
  { "c": "FRANCK", "t": "Prélude, Aria et Final, Op. 23", "nat": "Belgian", "era": "Romantic", "focus": ["Cyclic form", "Romantic grandeur", "Contrapuntal texture"] },
  { "c": "FRANCK", "t": "Prélude, Choral et Fugue, Op. 21", "nat": "Belgian", "era": "Romantic", "focus": ["Cyclic form", "Contrapuntal mastery", "Romantic spirituality"] },
  { "c": "GINASTERA", "t": "Sonata No. 1, Op. 22: complete", "nat": "Argentine", "era": "Modern", "focus": ["Toccata energy", "National idiom", "Structural ambition"] },
  { "c": "GRANADOS", "t": "Any two of the 6 pieces from 'Goyescas', Vols 1 and 2", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish idiom", "Romantic expression", "Colouristic virtuosity"] },
  { "c": "GUBAIDULINA, Sofia", "t": "Chaconne", "nat": "Russian", "era": "Contemporary", "focus": ["Chaconne form", "Spiritual expression", "Extended harmony"] },
  { "c": "GUBAIDULINA, Sofia", "t": "Musical Toys: complete", "nat": "Russian", "era": "Contemporary", "focus": ["Character pieces", "Contemporary idiom", "Imaginative writing"] },
  { "c": "GUBAIDULINA, Sofia", "t": "Sonata: complete", "nat": "Russian", "era": "Contemporary", "focus": ["Sonata form", "Spiritual intensity", "Contemporary idiom"] },
  { "c": "HENSELT", "t": "Any two of the '12 Études de salon', Op. 5", "nat": "German", "era": "Romantic", "focus": ["Technical study", "Romantic virtuosity", "Salon character"] },
  { "c": "HINDEMITH", "t": "Sonata No. 3 in B♭: complete", "nat": "German", "era": "Modern", "focus": ["Neo-classical style", "Rhythmic energy", "Contrapuntal texture"] },
  { "c": "LIEBERMANN, Lowell", "t": "Gargoyles, Op. 29: complete", "nat": "American", "era": "Contemporary", "focus": ["Character suite", "Technical demands", "Contemporary idiom"] },
  { "c": "LIGETI", "t": "Selected Études from Books 1 and 2 (Nos. 2/3/4/5/8/9/10/13)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Technical demands", "Complex polyrhythm", "Contemporary idiom"] },
  { "c": "LISZT", "t": "Après une Lecture de Dante (Fantasia quasi Sonata): No. 7 from 'Années de Pèlerinage: 2ème Année'", "nat": "Hungarian", "era": "Romantic", "focus": ["Programmatic virtuosity", "Fantasia form", "Romantic grandeur"] },
  { "c": "LISZT", "t": "Funérailles", "nat": "Hungarian", "era": "Romantic", "focus": ["Funeral march character", "Romantic grandeur", "Expressive depth"] },
  { "c": "LISZT", "t": "Mazeppa and/or Feux follets: No. 4 and/or No. 5 from '12 Études d'exécution transcendante'", "nat": "Hungarian", "era": "Romantic", "focus": ["Virtuosic transcendence", "Technical demands", "Programmatic character"] },
  { "c": "LISZT", "t": "Sonata in B minor: complete", "nat": "Hungarian", "era": "Romantic", "focus": ["Monumental sonata", "Cyclic form", "Romantic grandeur"] },
  { "c": "MACGREGOR, Joanna", "t": "Selected pieces after Nina Simone (Blackbird / Little Girl Blue / Good Bait)", "nat": "English", "era": "Contemporary", "focus": ["Jazz transcription", "Contemporary idiom", "Character writing"] },
  { "c": "MACMILLAN, James", "t": "Sonata: complete", "nat": "Scottish", "era": "Contemporary", "focus": ["Sonata form", "Scottish idiom", "Spiritual intensity"] },
  { "c": "MARTINŮ", "t": "Sonata No. 1: complete", "nat": "Czech", "era": "Modern", "focus": ["Sonata form", "Neo-classical style", "Czech idiom"] },
  { "c": "MEDTNER", "t": "Sonata tragica, Op. 39 No. 5: complete", "nat": "Russian", "era": "Romantic", "focus": ["Tragic expression", "Late-Romantic harmony", "Concentrated form"] },
  { "c": "MENDELSSOHN", "t": "Sonata in B♭, Op. 106: complete", "nat": "German", "era": "Romantic", "focus": ["Romantic lyricism", "Sonata form", "Youthful energy"] },
  { "c": "MESSIAEN", "t": "Île de feu 1 and 2", "nat": "French", "era": "Modern", "focus": ["Modes of limited transposition", "Spiritual fire", "Technical demands"] },
  { "c": "PRICE, F.", "t": "Fantasie nègre No. 1 in E minor", "nat": "American", "era": "Modern", "focus": ["African-American idiom", "Spiritual themes", "Romantic expression"] },
  { "c": "PRICE, F.", "t": "Fantasie nègre No. 2 in G minor", "nat": "American", "era": "Modern", "focus": ["African-American idiom", "Spiritual themes", "Romantic expression"] },
  { "c": "PROKOFIEV", "t": "Sonata No. 6 in A, Op. 82: complete", "nat": "Russian", "era": "Modern", "focus": ["War sonata", "Russian modernism", "Technical demands"] },
  { "c": "PROKOFIEV", "t": "Sonata No. 7 in B♭, Op. 83: complete", "nat": "Russian", "era": "Modern", "focus": ["War sonata", "Barbaric energy", "Technical demands"] },
  { "c": "PROKOFIEV", "t": "Sonata No. 8 in B♭, Op. 84: complete", "nat": "Russian", "era": "Modern", "focus": ["War sonata", "Lyrical depth", "Structural mastery"] },
  { "c": "PROKOFIEV", "t": "Sonata No. 9 in C, Op. 103: complete", "nat": "Russian", "era": "Modern", "focus": ["Sonata form", "Late style", "Lyrical expression"] },
  { "c": "RACHMANINOV", "t": "Sonata No. 2 in B♭ minor, Op. 36 (revised version 1931): complete", "nat": "Russian", "era": "Romantic", "focus": ["Romantic grandeur", "Technical demands", "Structural mastery"] },
  { "c": "RACHMANINOV", "t": "Variations on a Theme of Corelli, Op. 42", "nat": "Russian", "era": "Romantic", "focus": ["Theme and variations", "Late-Romantic harmony", "Technical demands"] },
  { "c": "RAVEL", "t": "Gaspard de la Nuit: complete", "nat": "French", "era": "Modern", "focus": ["Impressionist virtuosity", "Programmatic horror", "Technical demands"] },
  { "c": "RAVEL", "t": "Any two or more movts from 'Miroirs'", "nat": "French", "era": "Modern", "focus": ["Impressionist colour", "Evocative imagery", "Technical demands"] },
  { "c": "SCHOENBERG", "t": "Suite, Op. 25: complete", "nat": "Austrian", "era": "Modern", "focus": ["Twelve-tone technique", "Suite structure", "Expressionist rigour"] },
  { "c": "SCHUBERT", "t": "Fantasy in C ('The Wanderer'), Op. 15, D. 760", "nat": "Austrian", "era": "Romantic", "focus": ["Cyclic fantasy", "Romantic scope", "Technical demands"] },
  { "c": "SCHUBERT", "t": "Sonata in C minor, D. 958: complete", "nat": "Austrian", "era": "Romantic", "focus": ["Late style", "Dramatic intensity", "Structural depth"] },
  { "c": "SCHUBERT", "t": "Sonata in A, D. 959: complete", "nat": "Austrian", "era": "Romantic", "focus": ["Late style", "Lyrical grandeur", "Structural depth"] },
  { "c": "SCHUBERT", "t": "Sonata in B♭, D. 960: complete", "nat": "Austrian", "era": "Romantic", "focus": ["Final sonata", "Heavenly length", "Transcendent lyricism"] },
  { "c": "SCHUBERT/LISZT", "t": "Erlkönig and Gretchen am Spinnrade", "nat": "Austrian", "era": "Romantic", "focus": ["Song transcription", "Storytelling through piano", "Virtuosic writing"] },
  { "c": "SCHULHOFF", "t": "Suite dansante en jazz: complete", "nat": "Czech", "era": "Modern", "focus": ["Jazz idiom", "Dance suite", "Neoclassical writing"] },
  { "c": "SCHUMANN, C.", "t": "Soirées musicales, Op. 6: complete", "nat": "German", "era": "Romantic", "focus": ["Complete set", "Early Romantic style", "Character pieces"] },
  { "c": "SCHUMANN, R.", "t": "Carnaval, Op. 9: complete", "nat": "German", "era": "Romantic", "focus": ["Character suite", "Cryptic programme", "Romantic imagination"] },
  { "c": "SCHUMANN, R.", "t": "Fantasy in C, Op. 17", "nat": "German", "era": "Romantic", "focus": ["Romantic sweep", "Fantasy form", "Dedicated to Liszt"] },
  { "c": "SCHUMANN, R.", "t": "Kreisleriana, Op. 16: complete", "nat": "German", "era": "Romantic", "focus": ["Character suite", "Contrasting personalities", "Romantic expression"] },
  { "c": "SCHUMANN, R.", "t": "Symphonic Etudes, Op. 13: complete", "nat": "German", "era": "Romantic", "focus": ["Theme and variations", "Orchestral texture", "Technical demands"] },
  { "c": "SCHUMANN, R.", "t": "Toccata in C, Op. 7", "nat": "German", "era": "Romantic", "focus": ["Toccata style", "Virtuosic energy", "Technical demands"] },
  { "c": "SCRIABIN", "t": "Sonata No. 4 in F#, Op. 30: complete", "nat": "Russian", "era": "Romantic", "focus": ["Mystical character", "Late-Romantic harmony", "Flight imagery"] },
  { "c": "SCRIABIN", "t": "Sonata No. 5 in F#, Op. 53", "nat": "Russian", "era": "Modern", "focus": ["One-movement sonata", "Atonal foreshadowing", "Concentrated intensity"] },
  { "c": "STRAVINSKY", "t": "Serenade in A: complete", "nat": "Russian", "era": "Modern", "focus": ["Neo-classical style", "Suite structure", "Tonal clarity"] },
  { "c": "SZYMANOWSKI", "t": "Masques, Op. 34: complete", "nat": "Polish", "era": "Modern", "focus": ["Impressionist colour", "Polish modernism", "Technical demands"] },
  { "c": "SZYMANOWSKI", "t": "Metopes, Op. 29: complete", "nat": "Polish", "era": "Modern", "focus": ["Impressionist colour", "Mythological programme", "Technical demands"] },
  { "c": "SZYMANOWSKI", "t": "Variations in B♭ minor, Op. 3", "nat": "Polish", "era": "Romantic", "focus": ["Theme and variations", "Late-Romantic style", "Polish idiom"] },
  { "c": "TIPPETT", "t": "Sonata No. 3: complete", "nat": "English", "era": "Modern", "focus": ["Sonata form", "Rhythmic energy", "20th-century idiom"] },
  { "c": "TIPPETT", "t": "Sonata No. 4: complete", "nat": "English", "era": "Contemporary", "focus": ["Late style", "Sonata form", "Expressive depth"] },
  { "c": "VINE, Carl", "t": "Five Bagatelles: complete", "nat": "Australian", "era": "Contemporary", "focus": ["Australian character", "Contemporary idiom", "Character suite"] },
  { "c": "VINE, Carl", "t": "Sonata No. 1: complete", "nat": "Australian", "era": "Contemporary", "focus": ["Sonata form", "Australian character", "Contemporary idiom"] },
  { "c": "WEIR, Judith", "t": "The Art of Touching the Keyboard", "nat": "Scottish", "era": "Contemporary", "focus": ["Contemporary idiom", "Wit and clarity", "Keyboard character"] },
  { "c": "WILD, E.", "t": "Any one or two of the 'Seven Virtuoso Etudes based on Gershwin Songs'", "nat": "American", "era": "Contemporary", "focus": ["Jazz transcription", "Virtuosic writing", "Technical demands"] }
];
