// Trinity College London Piano — Grade 1
// 2023 Syllabus | Flat open pool (no lists/groups)
// Total: 57 pieces
// Source: trinitycollege.com/piano-repertoire

const DATA_TRINITY_G1 = [
  { "c": "ARENS, E.", "t": "Spring Mood (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Contemporary", "focus": ["Lyrical playing", "Simple phrasing", "Tonal control"] },
  { "c": "ARENS, E.", "t": "The March of the Tin Soldiers (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Contemporary", "focus": ["March character", "Staccato touch", "Rhythmic precision"] },
  { "c": "BATT, M.", "t": "Bright Eyes (arr. from Watership Down)", "nat": "English", "era": "Contemporary", "focus": ["Pop ballad", "Lyrical melody", "Simple arrangement"] },
  { "c": "BEETHOVEN, L. van", "t": "German Dance in G, WoO 8 No. 6", "nat": "German", "era": "Classical", "focus": ["Classical dance", "Clear phrasing", "Balanced texture"] },
  { "c": "BOBER, M.", "t": "Sunflower Waltz (from Recital Collection for Piano, Grade 1)", "nat": "American", "era": "Contemporary", "focus": ["Waltz style", "Singing tone", "Simple accompaniment"] },
  { "c": "BONIS, M.", "t": "Petite Valse (from Recital Collection for Piano, Grade 1)", "nat": "French", "era": "Romantic", "focus": ["Waltz character", "Gentle phrasing", "Light touch"] },
  { "c": "CHARLTON, R.", "t": "Funky Fingers (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Funk style", "Strong rhythm", "Simple coordination"] },
  { "c": "CLARKE, J.", "t": "Trumpet Voluntary (Arr.)", "nat": "English", "era": "Baroque", "focus": ["Baroque style", "Clear articulation", "Ceremonial character"] },
  { "c": "CLEAVER, D.", "t": "Afternoon Sun (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Gentle touch", "Simple phrasing"] },
  { "c": "CRAMER, J.B.", "t": "Study in C (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Classical", "focus": ["Technical fluency", "Even touch", "Scale passages"] },
  { "c": "CROSLAND, J.", "t": "The Haunted House (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Descriptive playing", "Atmospheric character", "Simple texture"] },
  { "c": "CROSLAND, J.", "t": "Rain Dance (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Rhythmic pattern", "Repetition", "Simple ostinato"] },
  { "c": "DIABELLI, A.", "t": "Melodie in A minor, Op. 149 No. 4", "nat": "Austrian", "era": "Classical", "focus": ["Classical phrasing", "Singing melody", "Even touch"] },
  { "c": "FERNANDEZ DIAZ, J.", "t": "Guajira (from Recital Collection for Piano, Grade 1)", "nat": "Cuban", "era": "Contemporary", "focus": ["Latin character", "Rhythmic precision", "Simple syncopation"] },
  { "c": "FURLER, S. / GUETTA, D. et al.", "t": "Titanium (arr.)", "nat": "Australian", "era": "Contemporary", "focus": ["Pop style", "Simple arrangement", "Lyrical melody"] },
  { "c": "DE GAMBARINI, E.", "t": "Minuet in G (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Baroque", "focus": ["Baroque dance", "Clear articulation", "Simple phrasing"] },
  { "c": "GARŚCIA, S.", "t": "Calypso (from Recital Collection for Piano, Grade 1)", "nat": "Spanish", "era": "Contemporary", "focus": ["Caribbean rhythm", "Light touch", "Simple syncopation"] },
  { "c": "GEROU, T.", "t": "Happy Thoughts (from Recital Collection for Piano, Grade 1)", "nat": "American", "era": "Contemporary", "focus": ["Cheerful character", "Simple melody", "Basic dynamics"] },
  { "c": "GOEDICKE, A.", "t": "A Sad Story, Op. 36 No. 3", "nat": "Russian", "era": "Romantic", "focus": ["Expressive playing", "Lyrical melody", "Simple phrasing"] },
  { "c": "GOODRICH, L.", "t": "Rock Around the World (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Rock style", "Strong rhythm", "Simple arrangement"] },
  { "c": "GRILL, J.C.", "t": "Scherzo in A minor (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Classical", "focus": ["Classical scherzo", "Light touch", "Clear phrasing"] },
  { "c": "GRUBER, F.", "t": "Silent Night (arr. Grade 1)", "nat": "Austrian", "era": "Romantic", "focus": ["Lyrical melody", "Simple texture", "Gentle touch"] },
  { "c": "HALL, N. / DRAYTON, C.", "t": "Pass and Move (It's the Liverpool Groove) (arr.)", "nat": "English", "era": "Contemporary", "focus": ["Pop style", "Simple arrangement", "Rhythmic character"] },
  { "c": "HANDEL, G.F.", "t": "Menuet in G minor (from Suite in G minor, HWV 434)", "nat": "German", "era": "Baroque", "focus": ["Baroque dance", "Two-voice texture", "Clear articulation"] },
  { "c": "HAWTHORN, J. / SUSCHITZKY, W.", "t": "Who's Afraid of the Big Bad Wolf? (arr.)", "nat": "American", "era": "Contemporary", "focus": ["Character piece", "Simple arrangement", "Playful style"] },
  { "c": "HOLIDAY, B. / HERZOG, A.", "t": "God Bless the Child (arr.)", "nat": "American", "era": "Contemporary", "focus": ["Jazz ballad", "Lyrical melody", "Simple arrangement"] },
  { "c": "HOLLAND, M.", "t": "Tap Dancing Cat (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Staccato playing", "Rhythmic character", "Playful style"] },
  { "c": "HORNER, J.", "t": "My Heart Will Go On (from Titanic, arr.)", "nat": "American", "era": "Contemporary", "focus": ["Film music", "Lyrical melody", "Simple arrangement"] },
  { "c": "HRADECKÝ, E.", "t": "Burlesque (from Recital Collection for Piano, Grade 1)", "nat": "Czech", "era": "Modern", "focus": ["Humorous character", "Simple texture", "Light touch"] },
  { "c": "KELLY, B.", "t": "Evening Song (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Lyrical playing", "Gentle touch", "Simple melody"] },
  { "c": "KIRKBY-MASON, B.", "t": "Rippling Brook (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Modern", "focus": ["Descriptive playing", "Flowing figurations", "Smooth legato"] },
  { "c": "LE COUPPEY, F.", "t": "Study in C, Op. 17 No. 4", "nat": "French", "era": "Romantic", "focus": ["Technical fluency", "Finger independence", "Even tone"] },
  { "c": "LI, Y.", "t": "Spring Breeze (from Recital Collection for Piano, Grade 1)", "nat": "Chinese", "era": "Contemporary", "focus": ["Lyrical playing", "Pentatonic character", "Smooth phrasing"] },
  { "c": "MIYOSHI, A.", "t": "Journey (from Recital Collection for Piano, Grade 1)", "nat": "Japanese", "era": "Contemporary", "focus": ["Atmospheric character", "Simple texture", "Gentle touch"] },
  { "c": "MOORE, C.", "t": "Snakes and Ladders (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Playful character", "Simple figurations", "Light touch"] },
  { "c": "MÜLLER, R.", "t": "A Lazy Afternoon (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Contemporary", "focus": ["Relaxed character", "Lyrical melody", "Simple phrasing"] },
  { "c": "NICHELMANN, C.", "t": "Menuet in D minor (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Baroque", "focus": ["Baroque dance", "Clear phrasing", "Two-voice texture"] },
  { "c": "NORTON, C.", "t": "Mañana (from Microjazz Collection 1)", "nat": "English", "era": "Contemporary", "focus": ["Latin jazz style", "Simple syncopation", "Relaxed character"] },
  { "c": "PAPP, L.", "t": "Scherzo (from Recital Collection for Piano, Grade 1)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Playful character", "Light touch", "Simple coordination"] },
  { "c": "PITTARELLO, G.", "t": "Haiku (from Recital Collection for Piano, Grade 1)", "nat": "Italian", "era": "Contemporary", "focus": ["Atmospheric playing", "Sparse texture", "Tonal sensitivity"] },
  { "c": "PROUDLER, G.", "t": "The Sad Clown (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Expressive playing", "Lyrical melody", "Simple phrasing"] },
  { "c": "REINAGLE, A.", "t": "Allegretto in F (from 24 Short and Easy Pieces, Op. 1)", "nat": "English", "era": "Classical", "focus": ["Classical style", "Clear phrasing", "Balanced texture"] },
  { "c": "RINGHAM, S.", "t": "Dragon Dance (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Exotic character", "Pentatonic flavour", "Rhythmic drive"] },
  { "c": "RODGERS, R.", "t": "My Favourite Things (arr.)", "nat": "American", "era": "Contemporary", "focus": ["Musical theatre", "Waltz character", "Simple arrangement"] },
  { "c": "SCHEIN, J.H.", "t": "Allemande in D minor (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Baroque", "focus": ["Baroque dance", "Smooth legato", "Simple counterpoint"] },
  { "c": "STRECKE, G.", "t": "Little Song (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Romantic", "focus": ["Lyrical melody", "Simple accompaniment", "Singing tone"] },
  { "c": "TANNER, P.", "t": "Rock a Little (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Rock style", "Simple arrangement", "Strong beat"] },
  { "c": "TERZIBASCHITSCH, A.", "t": "Bossa Nova (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Contemporary", "focus": ["Bossa nova style", "Simple syncopation", "Light touch"] },
  { "c": "TERZIBASCHITSCH, A.", "t": "Reggae (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Contemporary", "focus": ["Reggae style", "Off-beat rhythm", "Light touch"] },
  { "c": "TERZIBASCHITSCH, A.", "t": "Waltz (from Recital Collection for Piano, Grade 1)", "nat": "German", "era": "Contemporary", "focus": ["Waltz character", "Gentle phrasing", "Simple accompaniment"] },
  { "c": "TRAD. / HEUMANN, H.-G.", "t": "Amazing Grace (arr.)", "nat": "American", "era": "Contemporary", "focus": ["Folk hymn", "Lyrical melody", "Simple arrangement"] },
  { "c": "TÜRK, D.", "t": "Contredanse in G (from Little Pieces for Pianoforte Players)", "nat": "German", "era": "Classical", "focus": ["Classical dance", "Clear articulation", "Balanced form"] },
  { "c": "TÜRK, D.", "t": "Moderato in F (from Little Pieces for Pianoforte Players)", "nat": "German", "era": "Classical", "focus": ["Classical style", "Singing melody", "Even phrasing"] },
  { "c": "VAŇHAL, J.B.", "t": "Sonatina in C (1st mvt) (from Recital Collection for Piano, Grade 1)", "nat": "Czech", "era": "Classical", "focus": ["Classical sonatina", "Clear phrasing", "Balanced structure"] },
  { "c": "WELLS, H.", "t": "Twilight (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Gentle touch", "Simple phrasing"] },
  { "c": "WHITFIELD, N. / STRONG, B.", "t": "I Heard It Through the Grapevine (arr.)", "nat": "American", "era": "Contemporary", "focus": ["Soul/R&B style", "Simple arrangement", "Rhythmic character"] },
  { "c": "YANDELL, S.", "t": "Calypso Joe (from Recital Collection for Piano, Grade 1)", "nat": "English", "era": "Contemporary", "focus": ["Caribbean style", "Simple syncopation", "Light character"] }
];
