// DATA_G1_LEISURE — AMEB Piano for Leisure Grade 1 (6331)
// Series lists: S4, S3, S2, S1, Manual
// Total: 70 pieces
const DATA_G1_LEISURE = [
  {"l":"S4","s":"S4","c":"AUSTIN, J.","t":"Going Baroque","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"S4","s":"S4","c":"CHUA, S.","t":"Jive turkey","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"S4","s":"S4","c":"CLARKE, J. (arr. PURCELL arr. HALL)","t":"Trumpet tune","nat":"British","era":"Baroque","key":"Variable","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
  {"l":"S4","s":"S4","c":"COSTLEY, D.","t":"Dance of the gnomes","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"S4","s":"S4","c":"DURO, S.","t":"Warm starry nights","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"S4","s":"S4","c":"HAMMOND, D.","t":"Dudes keep struttin'","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"S4","s":"S4","c":"HANNAN, M.","t":"Prayer","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"S4","s":"S4","c":"NORTON, C.","t":"Sea bird","nat":"British","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"S4","s":"S4","c":"ROSSI, M.","t":"A wild chase","nat":"Italian","era":"Baroque","key":"Variable","focus":["Baroque phrasing", "Dance character", "Ornamental detail"]},
  {"l":"S4","s":"S4","c":"ROSSINI, G. (arr. HOWELL)","t":"Overture","nat":"Italian","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"S4","s":"S4","c":"SHORE, H. (arr. HODGSON)","t":"In dreams","nat":"Canadian","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"S4","s":"S4","c":"VERDI, G. (arr. HODGSON)","t":"La donna \u00e8 mobile","nat":"Italian","era":"Romantic","key":"Variable","focus":["Expressive phrasing", "Singing tone", "Musical sensitivity"]},
  {"l":"S3","s":"S3","c":"ANDERSSON, B. and ULVAEUS, B. (arr. WEDGWOOD)","t":"Thank you for the music","nat":"Swedish","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"S3","s":"S3","c":"BIZET, G. (arr. HALL)","t":"Toreador song","nat":"French","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"S3","s":"S3","c":"CHUA, S.","t":"Lonesome blues","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"S3","s":"S3","c":"DIAMOND, N. (arr. MILNE)","t":"I'm a believer","nat":"American","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"S3","s":"S3","c":"FISCHER, J.","t":"Praludium harpeggiato","nat":"German","era":"Baroque","key":"Variable","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
  {"l":"S3","s":"S3","c":"GIBSON, J., STAVRINOUDIS, P. and BAKER, D.","t":"Hot chilli rock","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"S3","s":"S3","c":"HICKS-WARD, M.","t":"Boogie blues","nat":"American","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"S3","s":"S3","c":"LLOYD-WEBBER, A. (arr. WASHTELL)","t":"Close every door to me","nat":"British","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"S3","s":"S3","c":"MARTINI, J.P. (arr. ALEXANDER)","t":"Plaisir d'amour","nat":"French","era":"Classical","key":"Variable","focus":["Classical elegance", "Clear articulation", "Formal structure"]},
  {"l":"S3","s":"S3","c":"ROLLIN, C.","t":"Animal chit chat","nat":"American","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"S3","s":"S3","c":"TCHAIKOVSKY, P. (arr. BASTIEN)","t":"Russian dance","nat":"Russian","era":"Romantic","key":"Variable","focus":["Expressive phrasing", "Singing tone", "Musical sensitivity"]},
  {"l":"S2","s":"S2","c":"BART\u00d3K, B.","t":"Dance","nat":"Hungarian","era":"Modern","key":"Variable","focus":["Modern idiom", "Rhythmic precision", "Stylistic clarity"]},
  {"l":"S2","s":"S2","c":"BAUMER, D.","t":"The mad hatter","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"S2","s":"S2","c":"CHUA, S.","t":"TV zombie","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"S2","s":"S2","c":"KEANE, D.","t":"The ambling armadillo","nat":"British","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"S2","s":"S2","c":"MIER, M.","t":"Ol' rocking chair blues","nat":"American","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"S2","s":"S2","c":"MILNE, E.","t":"Groovy movie","nat":"British","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"S2","s":"S2","c":"MIZZY, V. (arr. ALEXANDER)","t":"The Addams family theme","nat":"American","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"S2","s":"S2","c":"NORTON, C.","t":"Rag time","nat":"British","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"S2","s":"S2","c":"VERDI, G. (arr. BRIMHALL)","t":"Marcia trionfale","nat":"Italian","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"S2","s":"S2","c":"WEDGWOOD, P.","t":"Garage sale","nat":"British","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"S1","s":"S1","c":"ALEXANDER, D.","t":"Got those boogie blues","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"S1","s":"S1","c":"ANONYMOUS","t":"Air","nat":"International","era":"Baroque","key":"Variable","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
  {"l":"S1","s":"S1","c":"BAILEY, K.","t":"Scoobie du wup","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"S1","s":"S1","c":"DAQUIN, L-C.","t":"Christmas piece","nat":"French","era":"Baroque","key":"Variable","focus":["Baroque phrasing", "Dance character", "Ornamental detail"]},
  {"l":"S1","s":"S1","c":"GRIEG, E.","t":"In the hall of the mountain king","nat":"Norwegian","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"S1","s":"S1","c":"LIVINGSTON, J. and EVANS, R.","t":"Whatever will be will be","nat":"American","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"S1","s":"S1","c":"MOZART, W.A.","t":"The birdcatcher's song","nat":"Austrian","era":"Classical","key":"Variable","focus":["Classical elegance", "Clear articulation", "Formal structure"]},
  {"l":"S1","s":"S1","c":"RENFROW, J.","t":"Ragtime ecossaise","nat":"American","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"S1","s":"S1","c":"TANAKA, C.","t":"Child of light 2","nat":"Japanese","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"S1","s":"S1","c":"TRADITIONAL (arr. BASTIEN)","t":"Hava nagilah","nat":"Israeli","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"S1","s":"S1","c":"WEDGWOOD, P.","t":"Contra-flow!","nat":"British","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"Manual","s":"Manual","c":"BASTIEN, J.","t":"Hoe down","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"Manual","s":"Manual","c":"BASTIEN, J.","t":"New Orleans blues","nat":"American","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"Manual","s":"Manual","c":"BLACKWELL, A.","t":"Railroad blues","nat":"American","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"Manual","s":"Manual","c":"BOYD, B.","t":"Latin logic","nat":"American","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"Manual","s":"Manual","c":"BULLARD, A.","t":"Round the bend","nat":"British","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"Manual","s":"Manual","c":"CHAPPLE, B.","t":"Tango","nat":"British","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"Manual","s":"Manual","c":"CHUA, S.","t":"Cuckoo fairy","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"Manual","s":"Manual","c":"HANDEL, G. (arr. HALL)","t":"Hornpipe","nat":"German","era":"Baroque","key":"Variable","focus":["Baroque style", "Finger independence", "Keyboard clarity"]},
  {"l":"Manual","s":"Manual","c":"HALL, C.","t":"Mexican fiesta","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"Manual","s":"Manual","c":"LLOYD-WEBBER, A. (arr. MILNE)","t":"Phantom of the opera","nat":"British","era":"Contemporary","key":"Variable","focus":["Stylistic flair", "Contemporary expression", "Musical colour"]},
  {"l":"Manual","s":"Manual","c":"LLOYD-WEBBER, A. (arr. FRITH)","t":"Memory","nat":"British","era":"Contemporary","key":"Variable","focus":["Australian character", "Contemporary style", "Musical identity"]},
  {"l":"Manual","s":"Manual","c":"MACARDLE, P.","t":"Snowball rag","nat":"Australian","era":"Contemporary","key":"Variable","focus":["Dance character", "Contemporary idiom", "Rhythmic energy"]},
  {"l":"Manual","s":"Manual","c":"MIER, M.","t":"Seventh street blues","nat":"American","era":"Contemporary","key":"Variable","focus":["Film character", "Contemporary style", "Expressive melody"]},
  {"l":"Manual","s":"Manual","c":"MOZART, W.A.","t":"Minuet in F major KV 2","nat":"Austrian","era":"Classical","key":"Variable","focus":["Classical elegance", "Clear articulation", "Formal structure"]},
  {"l":"Manual","s":"Manual","c":"NORTON, C.","t":"Chant","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary style", "Musical expression", "Creative character"]},
  {"l":"Manual","s":"Manual","c":"NORTON, C.","t":"Stairway","nat":"British","era":"Contemporary","key":"Variable","focus":["Contemporary idiom", "Stylistic awareness", "Expressive playing"]},
  {"l":"Manual","s":"Manual","c":"NORTON, C.","t":"Tut-tuttin'","nat":"British","era":"Contemporary","key":"Variable","focus":["Creative expression", "Contemporary character", "Musical imagery"]},
  {"l":"Manual","s":"Manual","c":"NORTON, C.","t":"Samba band","nat":"British","era":"Contemporary","key":"Variable","focus":["Rhythmic feel", "Contemporary style", "Musical personality"]},
  {"l":"Manual","s":"Manual","c":"PALMER, W., MANUS, M. and LETHCO, A. (arr. MILNE)","t":"Calypso rhumba","nat":"American","era":"Contemporary","key":"Variable","focus":["Lyrical expression", "Contemporary idiom", "Technical fluency"]},
  {"l":"Manual","s":"Manual","c":"REJINO, M.","t":"Scavenger hunt","nat":"American","era":"Contemporary","key":"Variable","focus":["Musical narrative", "Contemporary character", "Expressive tone"]},
  {"l":"Manual","s":"Manual","c":"ROLLIN, C.","t":"Cool jump","nat":"American","era":"Contemporary","key":"Variable","focus":["Popular character", "Contemporary style", "Musical engagement"]},
  {"l":"Manual","s":"Manual","c":"ROSSINI, G. (arr. HALL)","t":"William Tell overture","nat":"Italian","era":"Romantic","key":"Variable","focus":["Romantic expression", "Lyrical melody", "Tonal colour"]},
  {"l":"Manual","s":"Manual","c":"SAINT-SA\u00cbNS, C. (arr. BARRATT)","t":"The elephant","nat":"French","era":"Romantic","key":"Variable","focus":["Expressive phrasing", "Singing tone", "Musical sensitivity"]},
  {"l":"Manual","s":"Manual","c":"SHOSTAKOVICH, D.","t":"Valse No 2","nat":"Russian","era":"Modern","key":"Variable","focus":["Modern idiom", "Rhythmic precision", "Stylistic clarity"]},
  {"l":"Manual","s":"Manual","c":"SIMON, P. (arr. FRITH)","t":"Bridge over troubled water","nat":"American","era":"Contemporary","key":"Variable","focus":["Jazz-influenced", "Contemporary idiom", "Rhythmic awareness"]},
  {"l":"Manual","s":"Manual","c":"TCHAIKOVSKY, P. (arr. BASTIEN)","t":"Swan lake","nat":"Russian","era":"Romantic","key":"Variable","focus":["Romantic character", "Dynamic range", "Legato playing"]}
];
