// Trinity College London Piano — Grade 2
// 2023 Syllabus | Flat open pool (no lists/groups)
// Total: 56 pieces
// Source: trinitycollege.com/piano-repertoire

const DATA_TRINITY_G2 = [
  { "c": "ARENS, E.", "t": "Roundelay (from Recital Collection for Piano, Grade 2)", "nat": "German", "era": "Contemporary", "focus": ["Lyrical playing", "Simple phrasing", "Musical shape"] },
  { "c": "BACH, J.S.", "t": "Minuet in G (BWV Anh. 114)", "nat": "German", "era": "Baroque", "focus": ["Baroque style", "Clear articulation", "Two-voice texture"] },
  { "c": "BARTÓK, B.", "t": "Pillow Dance (No. 30 from For Children, Vol. 2)", "nat": "Hungarian", "era": "Modern", "focus": ["Folk character", "Simple ostinato", "Rhythmic drive"] },
  { "c": "BEETHOVEN, L. van", "t": "Écossaise in G, WoO 23", "nat": "German", "era": "Classical", "focus": ["Dance character", "Clear phrasing", "Light touch"] },
  { "c": "BÉRA-TAGRINE, N.", "t": "Blue Waltz (from Recital Collection for Piano, Grade 2)", "nat": "French", "era": "Contemporary", "focus": ["Waltz style", "Blues inflection", "Gentle phrasing"] },
  { "c": "BOBER, M.", "t": "Sundance (from Recital Collection for Piano, Grade 2)", "nat": "American", "era": "Contemporary", "focus": ["Dance character", "Rhythmic precision", "Simple coordination"] },
  { "c": "BULLARD, A.", "t": "Turkish Moonlight (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Contemporary", "focus": ["Exotic character", "Modal flavour", "Atmospheric playing"] },
  { "c": "CAINE, U.", "t": "Song Without Words (from Recital Collection for Piano, Grade 2)", "nat": "American", "era": "Contemporary", "focus": ["Lyrical melody", "Singing tone", "Simple phrasing"] },
  { "c": "CROSLAND, J.", "t": "The Jester (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Contemporary", "focus": ["Humorous character", "Staccato playing", "Light touch"] },
  { "c": "DIABELLI, A.", "t": "Sonatina in F, Op. 168 No. 1 (1st mvt)", "nat": "Austrian", "era": "Classical", "focus": ["Classical sonatina", "Clear phrasing", "Balanced texture"] },
  { "c": "DRING, M.", "t": "Tarantella (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Modern", "focus": ["Dance character", "Rapid triplets", "Rhythmic drive"] },
  { "c": "DUNHILL, T.", "t": "A Sad Tale (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Modern", "focus": ["Expressive playing", "Simple phrasing", "Lyrical melody"] },
  { "c": "EINAUDI, L.", "t": "Una Mattina (simplified arr.)", "nat": "Italian", "era": "Contemporary", "focus": ["Minimalist style", "Atmospheric playing", "Simple ostinato"] },
  { "c": "ELGAR, E.", "t": "Chanson de Matin, Op. 15 No. 2 (arr.)", "nat": "English", "era": "Romantic", "focus": ["Lyrical melody", "Romantic phrasing", "Singing tone"] },
  { "c": "GEROU, T.", "t": "Safari (from Recital Collection for Piano, Grade 2)", "nat": "American", "era": "Contemporary", "focus": ["Descriptive playing", "Rhythmic drive", "Simple coordination"] },
  { "c": "GOEDICKE, A.", "t": "Dance, Op. 36 No. 7", "nat": "Russian", "era": "Romantic", "focus": ["Dance character", "Simple phrasing", "Rhythmic precision"] },
  { "c": "GRIEG, E.", "t": "Waltz in A minor, Op. 12 No. 2 (simplified)", "nat": "Norwegian", "era": "Romantic", "focus": ["Waltz style", "Romantic character", "Lyrical phrasing"] },
  { "c": "GURLITT, C.", "t": "Marche, Op. 130 No. 2", "nat": "German", "era": "Romantic", "focus": ["March character", "Clear phrasing", "Basic dynamics"] },
  { "c": "HANDEL, G.F.", "t": "Air in B flat (from Suite in B flat, HWV 440)", "nat": "German", "era": "Baroque", "focus": ["Baroque ornament", "Singing melody", "Clear articulation"] },
  { "c": "HARRIS, P.", "t": "Firecracker (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Contemporary", "focus": ["Explosive character", "Staccato touch", "Rhythmic drive"] },
  { "c": "HAYDN, J.", "t": "German Dance in D (Hob. IX/12 No. 3)", "nat": "Austrian", "era": "Classical", "focus": ["Classical dance", "Clear phrasing", "Light texture"] },
  { "c": "HEUMANN, H.-G.", "t": "Tango (from Recital Collection for Piano, Grade 2)", "nat": "German", "era": "Contemporary", "focus": ["Tango character", "Rhythmic precision", "Simple syncopation"] },
  { "c": "KHACHATURIAN, A.", "t": "Andantino (from Children's Album)", "nat": "Armenian", "era": "Modern", "focus": ["Lyrical melody", "Simple accompaniment", "Expressive touch"] },
  { "c": "LANE, R.", "t": "Night Ride (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Simple ostinato", "Evocative character"] },
  { "c": "LE COUPPEY, F.", "t": "Study in G, Op. 17 No. 6", "nat": "French", "era": "Romantic", "focus": ["Technical fluency", "Finger independence", "Even touch"] },
  { "c": "LYADOV, A.", "t": "A Trifle, Op. 2 No. 1", "nat": "Russian", "era": "Romantic", "focus": ["Character piece", "Simple phrasing", "Delicate touch"] },
  { "c": "MENDELSSOHN, F.", "t": "Song Without Words, Op. 102 No. 4 (simplified)", "nat": "German", "era": "Romantic", "focus": ["Singing tone", "Lyrical phrasing", "Romantic character"] },
  { "c": "NORTON, C.", "t": "Pendulum Swing (from Microjazz Collection 1)", "nat": "English", "era": "Contemporary", "focus": ["Jazz style", "Simple syncopation", "Swing character"] },
  { "c": "PAPP, L.", "t": "Invention (from Recital Collection for Piano, Grade 2)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Two-voice texture", "Simple counterpoint", "Clear phrasing"] },
  { "c": "PROKOFIEV, S.", "t": "Morning (from Music for Children, Op. 65 No. 1)", "nat": "Russian", "era": "Modern", "focus": ["Simple melody", "Clear texture", "Lyrical playing"] },
  { "c": "PURCELL, H.", "t": "Air in D minor (from A Choice Collection of Lessons)", "nat": "English", "era": "Baroque", "focus": ["Baroque style", "Ornamentation", "Singing melody"] },
  { "c": "RAMSKILL, T.", "t": "Enchanted Garden (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Gentle touch", "Simple figurations"] },
  { "c": "REINAGLE, A.", "t": "Tempo di Minuetto in A minor (from 24 Short and Easy Pieces, Op. 1)", "nat": "English", "era": "Classical", "focus": ["Classical minuet", "Clear phrasing", "Balanced texture"] },
  { "c": "REGER, M.", "t": "Humoreske, Op. 44 No. 1", "nat": "German", "era": "Romantic", "focus": ["Humorous character", "Simple texture", "Light phrasing"] },
  { "c": "RODGERS, R.", "t": "Edelweiss (from The Sound of Music, arr.)", "nat": "American", "era": "Contemporary", "focus": ["Waltz character", "Simple arrangement", "Lyrical melody"] },
  { "c": "SCARLATTI, D.", "t": "Minuet in C (K. 73b)", "nat": "Italian", "era": "Baroque", "focus": ["Baroque dance", "Clear articulation", "Two-voice texture"] },
  { "c": "SCHUBERT, F.", "t": "Ländler in A, D. 366 No. 3", "nat": "Austrian", "era": "Romantic", "focus": ["Dance character", "Lyrical melody", "Simple accompaniment"] },
  { "c": "SCHUMANN, R.", "t": "Sicilianisch, Op. 68 No. 11", "nat": "German", "era": "Romantic", "focus": ["Siciliano rhythm", "Lyrical phrasing", "Character piece"] },
  { "c": "SCHMITZ, M.", "t": "Jazz Cat (from Recital Collection for Piano, Grade 2)", "nat": "American", "era": "Contemporary", "focus": ["Jazz style", "Simple syncopation", "Swing character"] },
  { "c": "SATIE, E.", "t": "Gymnopédie No. 1 (simplified)", "nat": "French", "era": "Romantic", "focus": ["Atmospheric playing", "Simple texture", "Lyrical melody"] },
  { "c": "SEBBA, J.", "t": "Street Party (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Contemporary", "focus": ["Festive character", "Rhythmic drive", "Simple coordination"] },
  { "c": "SHOSTAKOVICH, D.", "t": "March, Op. 69 No. 1", "nat": "Russian", "era": "Modern", "focus": ["March character", "Staccato touch", "Rhythmic precision"] },
  { "c": "STRECKE, G.", "t": "Romance (from Recital Collection for Piano, Grade 2)", "nat": "German", "era": "Romantic", "focus": ["Lyrical melody", "Expressive playing", "Simple phrasing"] },
  { "c": "TANSMAN, A.", "t": "Mazurka (from Pour les Enfants, 1st set)", "nat": "Polish", "era": "Modern", "focus": ["Folk-influenced dance", "Rhythmic character", "Simple phrasing"] },
  { "c": "TÜRK, D.G.", "t": "Minuet in A minor (from Little Pieces for Pianoforte Players)", "nat": "German", "era": "Classical", "focus": ["Classical minuet", "Clear phrasing", "Simple ornamentation"] },
  { "c": "TERZIBASCHITSCH, A.", "t": "Latin Groove (from Recital Collection for Piano, Grade 2)", "nat": "German", "era": "Contemporary", "focus": ["Latin style", "Rhythmic drive", "Simple syncopation"] },
  { "c": "VILLA-LOBOS, H.", "t": "Polka do bebê (from A Prole do Bebê, Vol. 1 No. 2, arr.)", "nat": "Brazilian", "era": "Modern", "focus": ["Dance character", "Brazilian flavour", "Light touch"] },
  { "c": "WALLIS, E.", "t": "Lullaby (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Contemporary", "focus": ["Gentle character", "Smooth legato", "Simple melody"] },
  { "c": "WARLOCK, P.", "t": "Basse-Danse (from Capriol Suite, arr.)", "nat": "English", "era": "Modern", "focus": ["Renaissance dance style", "Clear texture", "Simple phrasing"] },
  { "c": "WITTHAUER, J.G.", "t": "Menuet in G (from Recital Collection for Piano, Grade 2)", "nat": "German", "era": "Baroque", "focus": ["Baroque dance", "Clear articulation", "Balanced form"] },
  { "c": "WRIGHT, C.", "t": "Electric Boogaloo (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Contemporary", "focus": ["Funk style", "Staccato playing", "Strong rhythm"] },
  { "c": "YANDELL, S.", "t": "Sneaky Pete (from Recital Collection for Piano, Grade 2)", "nat": "English", "era": "Contemporary", "focus": ["Character piece", "Staccato touch", "Playful style"] },
  { "c": "ZECHLIN, R.", "t": "Miniature (from Recital Collection for Piano, Grade 2)", "nat": "German", "era": "Modern", "focus": ["Simple texture", "Clear phrasing", "Controlled touch"] },
  { "c": "KABALEVSKY, D.", "t": "Clowns, Op. 39 No. 20", "nat": "Russian", "era": "Modern", "focus": ["Humorous character", "Staccato touch", "Simple coordination"] },
  { "c": "NORTON, C.", "t": "Straight Down the Line (from Microjazz Collection 1)", "nat": "English", "era": "Contemporary", "focus": ["Jazz style", "Steady beat", "Simple texture"] },
  { "c": "PAPP, L.", "t": "Night Music (from Recital Collection for Piano, Grade 2)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Atmospheric playing", "Simple texture", "Gentle touch"] }
];
