// AMEB Piano 2026 — AMusA (Associate in Music, Australia) — Level 3
// Exam code: 9950
// Program: 25–40 min | 1 work from List A + at least 3 from Lists B/C/D
// Min 3 different styles/historical periods required
// Source: 2026 AMEB Manual of Syllabuses (Music) pp.79–80

const DATA_AMUSA = [
  // LIST A — Major Works (one required)
  {"l":"A","c":"BACH, C.P.E.","t":"Sonata in A major H 186/W 55.4","nat":"German","era":"Baroque","focus":["Baroque style","Formal structure","Keyboard clarity"]},
  {"l":"A","c":"BACH, J.S.","t":"'French' Suite No. 5 in G major BWV 816","nat":"German","era":"Baroque","focus":["Baroque style","Dance character","Keyboard clarity"]},
  {"l":"A","c":"BEETHOVEN","t":"Sonata in F minor Op. 2 No. 1","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN","t":"Sonata in C minor Op. 10 No. 1","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN","t":"Sonata in F major Op. 10 No. 2","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN","t":"Sonata in C minor Op. 13 ('Pathétique')","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN","t":"Sonata in G major Op. 14 No. 2","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN","t":"Sonata in B♭ major Op. 22","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN","t":"Sonata in A♭ major Op. 26","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN","t":"Sonata in E♭ major Op. 27 No. 1","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN","t":"Sonata in D major Op. 28","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"BEETHOVEN","t":"Sonata in F♯ major Op. 78","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"CLEMENTI","t":"Sonata in B♭ major Op. 24 No. 2","nat":"Italian","era":"Classical","focus":["Classical phrasing","Formal structure","Finger independence"]},
  {"l":"A","c":"CLEMENTI","t":"Sonata in D major Op. 25 No. 6","nat":"Italian","era":"Classical","focus":["Classical phrasing","Formal structure","Finger independence"]},
  {"l":"A","c":"CLEMENTI","t":"Sonata in G major Op. 37 No. 2","nat":"Italian","era":"Classical","focus":["Classical phrasing","Formal structure","Finger independence"]},
  {"l":"A","c":"DUSSEK","t":"Sonata in B♭ major Op. 24 (c.96)","nat":"Czech","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"FIELD","t":"Sonata in A major No. 2 from Three Sonatas Op. 1 / H 8A","nat":"Irish","era":"Classical","focus":["Classical phrasing","Singing tone","Expressive tone"]},
  {"l":"A","c":"HAYDN","t":"Sonata in C minor Hob XVI:20","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"HAYDN","t":"Sonata in F major Hob XVI:23","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"HAYDN","t":"Sonata in E♭ major Hob XVI:28","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"HAYDN","t":"Sonata in B minor Hob XVI:32","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"HAYDN","t":"Sonata in D major Hob XVI:33","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"HAYDN","t":"Sonata in E minor Hob XVI:34","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"HAYDN","t":"Sonata in G major Hob XVI:39","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"HAYDN","t":"Sonata (Divertimento) in A♭ major Hob XVI:46","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"HAYDN","t":"Variations in F minor Hob XVII:6","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Variation technique","Expressive tone"]},
  {"l":"A","c":"KOŽELUCH","t":"Sonata in A minor Op. 26 No. 2","nat":"Czech","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"A","c":"MENDELSSOHN","t":"Sonata in G minor Op. 105","nat":"German","era":"Romantic","focus":["Expressive tone","Formal structure","Dynamic shaping"]},
  {"l":"A","c":"MOZART","t":"Sonata in C major K 279","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"MOZART","t":"Sonata in F major K 280","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"MOZART","t":"Sonata in B♭ major K 281","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"MOZART","t":"Sonata in G major K 283","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"MOZART","t":"Sonata in C major K 330","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"MOZART","t":"Sonata in F major K 332","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"MOZART","t":"Sonata in B♭ major K 333","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"MOZART","t":"Sonata in B♭ major K 570","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Hand coordination"]},
  {"l":"A","c":"SCHUBERT","t":"Sonata in A♭ minor D 537 / Op. 164","nat":"Austrian","era":"Romantic","focus":["Expressive tone","Formal structure","Lyrical phrasing"]},
  {"l":"A","c":"SCHUBERT","t":"Sonata in A major D 557","nat":"Austrian","era":"Romantic","focus":["Expressive tone","Formal structure","Lyrical phrasing"]},
  {"l":"A","c":"SCHUBERT","t":"Sonata in A♭ major D 664 / Op. 120","nat":"Austrian","era":"Romantic","focus":["Expressive tone","Formal structure","Lyrical phrasing"]},

  // LIST B — Contrapuntal Works
  {"l":"B","c":"BACH, J.S.","t":"Prelude (1st movt) from 'English' Suite in A minor BWV 807","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude (1st movt) from 'English' Suite in G minor BWV 808","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Sinfonia (1st movt) from Partita in C minor BWV 826","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Overture (1st movt) from Partita in D major BWV 828","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Toccata (1st movt) from Partita in E minor BWV 830","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in F major BWV 856 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in F♯ major BWV 858 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in F♯ minor BWV 859 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in G major BWV 860 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in G minor BWV 861 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in A major BWV 864 (WTC Book 1)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in C major BWV 870 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in C♯ major BWV 872 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in D minor BWV 875 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in E major BWV 878 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in A major BWV 888 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Prelude and Fugue in A minor BWV 889 (WTC Book 2)","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"BACH, J.S.","t":"Toccata in E minor BWV 914","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"HANDEL","t":"Courante and Gigue (3rd–4th movts) from Suite in A major HWV 426","nat":"German","era":"Baroque","focus":["Baroque style","Dance character","Keyboard clarity"]},
  {"l":"B","c":"HANDEL","t":"Adagio and Allegro (Fuga) (3rd–4th movts) from Suite in F major HWV 427","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"HANDEL","t":"Allegro (1st movt) from Suite in E minor HWV 429","nat":"German","era":"Baroque","focus":["Baroque style","Contrapuntal texture","Keyboard clarity"]},
  {"l":"B","c":"MENDELSSOHN","t":"Prelude and Fugue in F minor Op. 35 No. 5","nat":"German","era":"Romantic","focus":["Contrapuntal texture","Expressive tone","Dynamic shaping"]},
  {"l":"B","c":"REGER","t":"Präludium and Fugue in A minor Op. 99 No. 3","nat":"German","era":"Modern","focus":["Contrapuntal texture","Modern harmony","Rhythmic precision"]},
  {"l":"B","c":"SCHUMANN","t":"Fugue in D minor Op. 72 No. 2","nat":"German","era":"Romantic","focus":["Contrapuntal texture","Expressive tone","Dynamic shaping"]},
  {"l":"B","c":"SHOSTAKOVICH","t":"Prelude and Fugue in A minor No. 2 from 24 Preludes and Fugues Op. 87","nat":"Russian","era":"Modern","focus":["Contrapuntal texture","Modern harmony","Rhythmic precision"]},
  {"l":"B","c":"SHOSTAKOVICH","t":"Prelude and Fugue in E minor No. 4 from 24 Preludes and Fugues Op. 87","nat":"Russian","era":"Modern","focus":["Contrapuntal texture","Modern harmony","Rhythmic precision"]},
  {"l":"B","c":"SHOSTAKOVICH","t":"Prelude and Fugue in A♭ major No. 7 from 24 Preludes and Fugues Op. 87","nat":"Russian","era":"Modern","focus":["Contrapuntal texture","Modern harmony","Rhythmic precision"]},

  // LIST C — Romantic/Modern Character Pieces
  {"l":"C","c":"BEETHOVEN","t":"Fantasia Op. 77","nat":"German","era":"Classical","focus":["Classical phrasing","Expressive tone","Musical expression"]},
  {"l":"C","c":"BORTKIEWICZ","t":"Etude in D♭ major No. 8 from Dix etudes Op. 15","nat":"Russian","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"BORTKIEWICZ","t":"Etude in F♯ minor No. 9 from Dix etudes Op. 15","nat":"Russian","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"BRAHMS","t":"Rhapsody in G minor No. 2 from Two Rhapsodies Op. 79","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"BRAHMS","t":"Capriccio in D minor No. 7 from Fantasien Op. 116","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"BRAHMS","t":"Intermezzo in B♭ minor No. 2 from Three Intermezzos Op. 117","nat":"German","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"C","c":"BRAHMS","t":"Intermezzo in A major No. 2 from Clavierstücke Op. 118","nat":"German","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"C","c":"BRAHMS","t":"Romance in F major No. 5 from Clavierstücke Op. 118","nat":"German","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"C","c":"CHAMINADE","t":"Etude (Automne) in D♭ major No. 2 from 6 Etudes de concert Op. 35","nat":"French","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN","t":"Nocturne in B major No. 3 from Three Nocturnes Op. 9 / CT 110","nat":"Polish","era":"Romantic","focus":["Expressive tone","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"CHOPIN","t":"Nocturne in F♯ major No. 2 from Two Nocturnes Op. 15 / CT 112","nat":"Polish","era":"Romantic","focus":["Expressive tone","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"CHOPIN","t":"Nocturne in C♯ minor Op. 27 No. 1 / CT 114","nat":"Polish","era":"Romantic","focus":["Expressive tone","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"CHOPIN","t":"Nocturne in E♭ major No. 2 from Two Nocturnes Op. 55 / CT 123","nat":"Polish","era":"Romantic","focus":["Expressive tone","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"CHOPIN","t":"Etude in A♭ major No. 1 from Etudes Op. 25 / CT 26","nat":"Polish","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN","t":"Etude in F minor No. 2 from Etudes Op. 25 / CT 27","nat":"Polish","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN","t":"Etude in C minor No. 7 from Etudes Op. 25 / CT 32","nat":"Polish","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN","t":"Etude in G♭ major No. 9 from Etudes Op. 25 / CT 34","nat":"Polish","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN","t":"Waltz in F major Op. 34 No. 3 / CT 210","nat":"Polish","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN","t":"Waltz in A♭ major Op. 64 No. 3 / CT 214","nat":"Polish","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN","t":"Waltz in E minor Op. post. / B 56 / CT 222","nat":"Polish","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN","t":"Berceuse in D♭ major Op. 57 / CT 7","nat":"Polish","era":"Romantic","focus":["Expressive tone","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"CZERNY","t":"Study in G minor No. 50 from Die Kunst der Fingerfertigkeit Op. 740","nat":"Austrian","era":"Classical","focus":["Finger independence","Rhythmic precision","Technical mastery"]},
  {"l":"C","c":"FALLA, M. de","t":"Nocturno","nat":"Spanish","era":"Modern","focus":["Modern harmony","Expressive tone","Musical expression"]},
  {"l":"C","c":"FAURÉ","t":"Barcarolle No. 1 in A minor Op. 26","nat":"French","era":"Romantic","focus":["Expressive tone","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"FAURÉ","t":"Impromptu No. 2 in F minor Op. 31","nat":"French","era":"Romantic","focus":["Expressive tone","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"GLINKA, arr. BALAKIREV","t":"Zhavoronok [The Lark]","nat":"Russian","era":"Romantic","focus":["Expressive tone","Singing tone","Musical expression"]},
  {"l":"C","c":"LISZT","t":"Sonetto 47 del Petrarca No. 4 from Années de pèlerinage, Deuxième année S 161","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"LISZT","t":"Sonetto 104 del Petrarca No. 5 from Années de pèlerinage, Deuxième année S 161","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"LISZT","t":"Sonetto 123 del Petrarca No. 6 from Années de pèlerinage, Deuxième année S 161","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"LISZT","t":"Sposalizio No. 1 from Années de pèlerinage, Deuxième année S 161","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"LISZT","t":"Paysage No. 3 from Etudes d'exécution transcendante S 139","nat":"Hungarian","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"MENDELSSOHN","t":"Scherzo in E minor No. 2 from Trois fantaisies Op. 16","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"MENDELSSOHN","t":"Rondo Capriccioso Op. 14","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"RACHMANINOFF","t":"Elégie in E minor No. 1 from Morceaux de fantaisie Op. 3","nat":"Russian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF","t":"Prelude in D major No. 4 from 10 Preludes Op. 23","nat":"Russian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF","t":"Prelude in G major No. 5 from 13 Preludes Op. 32","nat":"Russian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF","t":"Prelude in G minor No. 12 from 13 Preludes Op. 32","nat":"Russian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF","t":"Etude-tableau (Grave) in C minor No. 3 from Etudes-tableaux Op. 33","nat":"Russian","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF","t":"Etude-tableau (Moderato) in G minor No. 8 from Etudes-tableaux Op. 33","nat":"Russian","era":"Romantic","focus":["Expressive tone","Finger independence","Dynamic shaping"]},
  {"l":"C","c":"SCHUMANN","t":"Grillen [Whims] No. 4 from Fantasiestücke Op. 12","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"SCHUMANN","t":"Sehr rasch in C minor No. 1 from Drei Fantasiestücke Op. 111","nat":"German","era":"Romantic","focus":["Expressive tone","Dynamic shaping","Musical expression"]},
  {"l":"C","c":"SKRYABIN","t":"Etude in A♭ major No. 8 from Douze études Op. 8","nat":"Russian","era":"Modern","focus":["Expressive tone","Modern harmony","Finger independence"]},
  {"l":"C","c":"SKRYABIN","t":"Etude in E♭ major No. 8 from Huit études Op. 42","nat":"Russian","era":"Modern","focus":["Expressive tone","Modern harmony","Finger independence"]},
  {"l":"C","c":"SKRYABIN","t":"Nocturne in D♭ major from Prélude et nocturne Op. 9","nat":"Russian","era":"Modern","focus":["Expressive tone","Singing tone","Musical expression"]},
  {"l":"C","c":"SZYMANOWSKI","t":"Prélude in C minor No. 7 from Nine Preludes Op. 1","nat":"Polish","era":"Modern","focus":["Modern harmony","Expressive tone","Musical expression"]},
  {"l":"C","c":"TCHAIKOVSKY","t":"Février: Carnaval No. 2 from Les saisons Op. 37b","nat":"Russian","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"TCHAIKOVSKY","t":"Août: La moisson No. 8 from Les saisons Op. 37b","nat":"Russian","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Dynamic shaping"]},
  {"l":"C","c":"TCHAIKOVSKY","t":"November: Troika No. 11 from Les saisons Op. 37b","nat":"Russian","era":"Romantic","focus":["Expressive tone","Dance character","Dynamic shaping"]},
  {"l":"C","c":"TCHAIKOVSKY","t":"Valse sentimentale No. 6 from Six morceaux Op. 51","nat":"Russian","era":"Romantic","focus":["Expressive tone","Dance character","Lyrical phrasing"]},
  {"l":"C","c":"TCHAIKOVSKY","t":"Méditation No. 5 from Dix-huit morceaux Op. 72","nat":"Russian","era":"Romantic","focus":["Expressive tone","Singing tone","Dynamic shaping"]},

  // LIST D — Australian & Contemporary Works
  {"l":"D","c":"AGNEW","t":"Will o' the Wisp II (Collected Edited Piano Works Vol. XI)","nat":"Australian","era":"Modern","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"ALBÉNIZ","t":"El puerto from Iberia Book 1","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Dance character","Musical expression"]},
  {"l":"D","c":"ALBÉNIZ","t":"Evocación from Iberia Book 1","nat":"Spanish","era":"Romantic","focus":["Expressive tone","Lyrical phrasing","Musical expression"]},
  {"l":"D","c":"BARTÓK","t":"Román kolinda-dallamok [Romanian Christmas Songs] Series 1 BB 67","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision","Modern harmony","Character contrast"]},
  {"l":"D","c":"BARTÓK","t":"Román népi táncok [Romanian Folk Dances] Sz 56 / BB 68","nat":"Hungarian","era":"Modern","focus":["Rhythmic precision","Dance character","Character contrast"]},
  {"l":"D","c":"BOULANGER, L.","t":"D'un vieux jardin No. 1 from Trois morceaux","nat":"French","era":"Modern","focus":["Impressionist style","Expressive tone","Musical expression"]},
  {"l":"D","c":"BRITTEN","t":"Night piece (Notturno)","nat":"English","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"CARMICHAEL","t":"A Courtly Dance No. 4 from Postcards (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"DEBUSSY","t":"Et la lune descend sur le temple qui fut No. 2 from Images 2ème série L 111","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"DEBUSSY","t":"Menuet No. 2 from Suite bergamasque L 75","nat":"French","era":"Modern","focus":["Impressionist style","Dance character","Musical expression"]},
  {"l":"D","c":"DEBUSSY","t":"La soirée dans Grenade No. 2 from Estampes L 100","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"DEBUSSY","t":"La danse de Puck No. 11 from Préludes Book 1 L 117","nat":"French","era":"Modern","focus":["Impressionist style","Character contrast","Musical expression"]},
  {"l":"D","c":"DEBUSSY","t":"Général Lavine – eccentric No. 6 from Préludes Book 2 L 123","nat":"French","era":"Modern","focus":["Impressionist style","Character contrast","Musical expression"]},
  {"l":"D","c":"DEBUSSY","t":"Ondine No. 8 from Préludes Book 2 L 123","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"DEBUSSY","t":"Hommage à S. Pickwick Esq. P.P.M.P.C. No. 9 from Préludes Book 2 L 123","nat":"French","era":"Modern","focus":["Impressionist style","Character contrast","Musical expression"]},
  {"l":"D","c":"DEBUSSY","t":"Pour les sonorités opposées No. 10 from Etudes L 136","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"GINASTERA","t":"Criolla No. 3 from Tres piezas Op. 6","nat":"Argentine","era":"Modern","focus":["Rhythmic precision","Dance character","Character contrast"]},
  {"l":"D","c":"GRAINGER","t":"Spoon River","nat":"Australian","era":"Modern","focus":["Contemporary idiom","Dance character","Musical expression"]},
  {"l":"D","c":"GRAINGER","t":"Irish Tune from County Derry","nat":"Australian","era":"Modern","focus":["Contemporary idiom","Lyrical phrasing","Musical expression"]},
  {"l":"D","c":"GREENBAUM","t":"Lost – The moon – Don't leave me here (1st movt from Ice Man)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"HAMMOND","t":"Anywhere (Australian Women Composers' Piano Anthology)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"HESSE","t":"Valse gracieuse (Australian Heritage Collection Vol. III)","nat":"Australian","era":"Romantic","focus":["Expressive tone","Dance character","Australian character"]},
  {"l":"D","c":"HYDE","t":"To a Skylark (Wirripang)","nat":"Australian","era":"Modern","focus":["Expressive tone","Lyrical phrasing","Australian character"]},
  {"l":"D","c":"HYDE","t":"Wet Night on the Highway (Wirripang)","nat":"Australian","era":"Modern","focus":["Expressive tone","Modern harmony","Australian character"]},
  {"l":"D","c":"IVES","t":"The Alcotts No. 3 from Piano Sonata No. 2 'Concord'","nat":"American","era":"Modern","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"KATS-CHERNIN","t":"Russian Rag (original version in B♭ minor)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"KOUVARAS","t":"Bundanon Rhapsody No. 5 from Bundanon Suite (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"LUTOSŁAWSKI","t":"Five Bukoliki [Bucolics]","nat":"Polish","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MESSIAEN","t":"Instants défunts No. 4 from Préludes I/2","nat":"French","era":"Modern","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MESSIAEN","t":"Regard de l'étoile No. 2 from Vingt regards sur l'enfant Jésus I/27","nat":"French","era":"Modern","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MESSIAEN","t":"Regard du temps No. 9 from Vingt regards sur l'enfant Jésus I/27","nat":"French","era":"Modern","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"MUNRO","t":"It's Time! Whitlam Rag No. 1 (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Rhythmic precision"]},
  {"l":"D","c":"OVERMAN","t":"Dance (Vivo e risoluto) No. 3 from 3 Dances (Piano Music of Meta Overman Vol. II)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Rhythmic precision"]},
  {"l":"D","c":"PARKER","t":"Arc-en-ciel [Rainbow] (Australian Heritage Collection Vol. I)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"PERTOUT","t":"Chant d'augmentation [Song of Augmentation] (Reed Music)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"PROKOFIEV","t":"Rigaudon No. 3 from Ten Pieces Op. 12","nat":"Russian","era":"Modern","focus":["Rhythmic precision","Character contrast","Modern harmony"]},
  {"l":"D","c":"PROKOFIEV","t":"The Young Juliet No. 4 from Ten Pieces from Romeo and Juliet Op. 75","nat":"Russian","era":"Modern","focus":["Expressive tone","Lyrical phrasing","Modern harmony"]},
  {"l":"D","c":"RAVEL","t":"Modéré (1st movt) from Sonatine","nat":"French","era":"Modern","focus":["Impressionist style","Formal structure","Musical expression"]},
  {"l":"D","c":"RAVEL","t":"Animé (3rd movt) from Sonatine","nat":"French","era":"Modern","focus":["Impressionist style","Rhythmic precision","Musical expression"]},
  {"l":"D","c":"RAVEL","t":"Oiseaux tristes No. 2 from Miroirs","nat":"French","era":"Modern","focus":["Impressionist style","Expressive tone","Musical expression"]},
  {"l":"D","c":"RAVEL","t":"La vallée des cloches No. 5 from Miroirs","nat":"French","era":"Modern","focus":["Impressionist style","Modern harmony","Musical expression"]},
  {"l":"D","c":"SABIN","t":"Another Look at Autumn (AMC)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
  {"l":"D","c":"SCHOENBERG","t":"Minuet and Trio No. 5 from Suite Op. 25","nat":"Austrian","era":"Contemporary","focus":["Contemporary idiom","Modern harmony","Musical expression"]},
  {"l":"D","c":"SKRYABIN","t":"Quatre préludes Op. 33","nat":"Russian","era":"Modern","focus":["Expressive tone","Modern harmony","Musical expression"]},
  {"l":"D","c":"VINE","t":"Any three of Five Bagatelles (Faber)","nat":"Australian","era":"Contemporary","focus":["Contemporary idiom","Australian character","Musical expression"]},
];
