// Precompile the Piano Butler drills app.
//   node precompile.js [in=drills.src.html] [out=drills.html]
// drills.src.html is the SOURCE: its app code is JSX in <script id="app-jsx" type="text/jsx-raw"> and the
// browser would have to compile it with babel-standalone on every visit (~6 s before the first screen).
// This script compiles that JSX once and writes the page that the site serves: the same page, with the
// compiled code in a plain <script> and no babel-standalone. Edit the SOURCE, never the output.
const fs = require('fs');
let Babel = null;
try { if (!process.env.PRECOMPILE_FORCE_CORE) Babel = require('@babel/standalone'); } catch (e) {}
// Always the classic runtime (React.createElement) in production form: the page loads React from a CDN <script>, so there is
// no module system and "react/jsx-runtime" / jsxDEV imports must never appear (newer Babel presets default to them).
const REACT_OPTS = { runtime: 'classic', development: false };
function compile(src) {
  if (Babel) return Babel.transform(src, { presets: [['react', REACT_OPTS]], compact: true, comments: false }).code;
  const core = require('@babel/core'); // fallback: @babel/core + @babel/preset-react (what the repo's node_modules has)
  return core.transformSync(src, { presets: [[require.resolve('@babel/preset-react'), REACT_OPTS]], compact: true, comments: false, babelrc: false, configFile: false }).code;
}
const inp = process.argv[2] || 'drills.src.html', outp = process.argv[3] || 'drills.html';
let h = fs.readFileSync(inp, 'utf8');

// 1. the JSX source block
const open = '<script id="app-jsx" type="text/jsx-raw">';
const i = h.indexOf(open); if (i < 0 || h.indexOf(open, i + 1) >= 0) throw new Error('app-jsx block: expected exactly one');
const j = h.indexOf('</script>', i); if (j < 0) throw new Error('app-jsx block not closed');
const src = h.slice(i + open.length, j);
// 2. the runtime compile loader that follows it
const lo = h.indexOf("<script>\ndocument.addEventListener('DOMContentLoaded', function() {\n  function tryCompile()", j);
if (lo < 0) throw new Error('loader not found');
const le = h.indexOf('</script>', lo);
const loader = h.slice(lo, le + '</script>'.length);
if (!/getElementById\('app-jsx'\)/.test(loader) || !/Babel\.transform/.test(loader)) throw new Error('loader is not the expected compile loader');
// 3. compile
let code = compile(src);
if (/jsx-runtime|jsx-dev-runtime|_jsxDEV|\bfrom\s*["']react/.test(code)) throw new Error('compiled code uses a JSX runtime import: it must use React.createElement');
new Function(code); // must parse
code = code.replace(/<\/script/gi, '<\\/script');
// 4. assemble: drop babel-standalone, replace the jsx block + loader with the compiled script
const babelTag = h.match(/[ \t]*<script src="https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/babel-standalone\/[^"]*"[^>]*><\/script>\n?/);
if (!babelTag) throw new Error('babel-standalone tag not found');
const between = h.slice(j + '</script>'.length, lo); // whitespace between the two blocks
let out = h.slice(0, i) + '<script id="app-js">\n' + code + '\n</script>' + between + h.slice(le + '</script>'.length);
out = out.replace(babelTag[0], '');
out = out.replace(/^(<!doctype html>\s*)/i, '$1<!-- GENERATED by precompile.js from drills.src.html: edit drills.src.html, not this file. -->\n');
if (/babel-standalone|text\/jsx-raw|Babel\.transform/.test(out)) throw new Error('leftover Babel reference');
fs.writeFileSync(outp, out);
console.log('precompile: ' + inp + ' (' + (h.length / 1e6).toFixed(2) + ' MB) -> ' + outp + ' (' + (out.length / 1e6).toFixed(2) + ' MB)');
