// Trinity College London Piano — Grade 4
// 2023 Syllabus | Flat open pool (no lists/groups)
// Total: 56 pieces
// Source: trinitycollege.com/piano-repertoire

const DATA_TRINITY_G4 = [
  { "c": "ARENS, E.", "t": "Etude in A minor (from Recital Collection for Piano, Grade 4)", "nat": "German", "era": "Contemporary", "focus": ["Technical development", "Finger independence", "Even tone"] },
  { "c": "BACH, J.S.", "t": "Two-Part Invention No. 4 in D minor, BWV 775", "nat": "German", "era": "Baroque", "focus": ["Counterpoint", "Finger independence", "Two-voice texture"] },
  { "c": "BARTÓK, B.", "t": "Fright (No. 39 from For Children, Vol. 2)", "nat": "Hungarian", "era": "Modern", "focus": ["Expressive playing", "Dramatic character", "Simple texture"] },
  { "c": "BEETHOVEN, L. van", "t": "Sonatina in G (Anh. 5 No. 1, 1st mvt)", "nat": "German", "era": "Classical", "focus": ["Classical sonatina", "Clear phrasing", "Scale passages"] },
  { "c": "BÉRA-TAGRINE, N.", "t": "Flamenco (from Recital Collection for Piano, Grade 4)", "nat": "French", "era": "Contemporary", "focus": ["Spanish character", "Rhythmic precision", "Expressive playing"] },
  { "c": "BOBER, M.", "t": "Rhapsody in Blue (simplified arr.)", "nat": "American", "era": "Contemporary", "focus": ["Jazz style", "Expressive playing", "Simple arrangement"] },
  { "c": "BRAHMS, J.", "t": "Intermezzo in E flat, Op. 117 No. 1 (simplified)", "nat": "German", "era": "Romantic", "focus": ["Lyrical melody", "Romantic phrasing", "Inner voices"] },
  { "c": "BULLARD, A.", "t": "Rhumba (from Recital Collection for Piano, Grade 4)", "nat": "English", "era": "Contemporary", "focus": ["Latin dance", "Rhythmic precision", "Simple syncopation"] },
  { "c": "CAINE, U.", "t": "Impromptu (from Recital Collection for Piano, Grade 4)", "nat": "American", "era": "Contemporary", "focus": ["Jazz-influenced", "Expressive freedom", "Simple phrasing"] },
  { "c": "CHOPIN, F.", "t": "Waltz in A minor, B. 150 (posth.)", "nat": "Polish", "era": "Romantic", "focus": ["Waltz style", "Expressive melody", "Simple accompaniment"] },
  { "c": "CLEMENTI, M.", "t": "Sonatina in G, Op. 36 No. 2 (1st mvt)", "nat": "Italian", "era": "Classical", "focus": ["Classical sonatina", "Scale technique", "Clear phrasing"] },
  { "c": "COREA, C.", "t": "Spain (simplified arr.)", "nat": "American", "era": "Contemporary", "focus": ["Jazz style", "Latin character", "Simple arrangement"] },
  { "c": "CROSLAND, J.", "t": "Boogie Blues (from Recital Collection for Piano, Grade 4)", "nat": "English", "era": "Contemporary", "focus": ["Blues style", "Strong left hand", "Rhythmic drive"] },
  { "c": "DEBUSSY, C.", "t": "Arabesque No. 1 (simplified)", "nat": "French", "era": "Romantic", "focus": ["Impressionist colour", "Flowing figurations", "Delicate touch"] },
  { "c": "ELGAR, E.", "t": "Chanson de Nuit, Op. 15 No. 1 (arr.)", "nat": "English", "era": "Romantic", "focus": ["Lyrical melody", "Romantic phrasing", "Singing tone"] },
  { "c": "FAURÉ, G.", "t": "Berceuse, Op. 56 No. 1 (simplified arr.)", "nat": "French", "era": "Romantic", "focus": ["Gentle character", "Rocking motion", "Lyrical melody"] },
  { "c": "GEROU, T.", "t": "Jazz Prelude (from Recital Collection for Piano, Grade 4)", "nat": "American", "era": "Contemporary", "focus": ["Jazz style", "Simple improvisation", "Expressive playing"] },
  { "c": "GRANADOS, E.", "t": "Spanish Dance No. 5 (Andaluza, simplified)", "nat": "Spanish", "era": "Romantic", "focus": ["Spanish character", "Guitar imitation", "Rhythmic drive"] },
  { "c": "GRIEG, E.", "t": "Lyric Piece: Elegy, Op. 38 No. 6 (simplified)", "nat": "Norwegian", "era": "Romantic", "focus": ["Expressive playing", "Singing melody", "Romantic phrasing"] },
  { "c": "HANDEL, G.F.", "t": "Air and Variations 'The Harmonious Blacksmith' (HWV 430, simplified)", "nat": "German", "era": "Baroque", "focus": ["Baroque ornament", "Variation technique", "Clear articulation"] },
  { "c": "HARRIS, P.", "t": "Latin Fever (from Recital Collection for Piano, Grade 4)", "nat": "English", "era": "Contemporary", "focus": ["Latin character", "Rhythmic drive", "Simple syncopation"] },
  { "c": "HAYDN, J.", "t": "Sonata in G, Hob. XVI/8 (1st mvt)", "nat": "Austrian", "era": "Classical", "focus": ["Classical sonata form", "Clear phrasing", "Ornamentation"] },
  { "c": "JOPLIN, S.", "t": "The Entertainer (simplified arr.)", "nat": "American", "era": "Romantic", "focus": ["Ragtime style", "Simple syncopation", "Clear structure"] },
  { "c": "KABALEVSKY, D.", "t": "A Little Joke, Op. 39 No. 6", "nat": "Russian", "era": "Modern", "focus": ["Humorous character", "Light touch", "Simple phrasing"] },
  { "c": "KHACHATURIAN, A.", "t": "Sonatina (1st mvt, simplified)", "nat": "Armenian", "era": "Modern", "focus": ["Folk-influenced style", "Rhythmic drive", "Clear structure"] },
  { "c": "LANE, R.", "t": "Stormy Weather (from Recital Collection for Piano, Grade 4)", "nat": "English", "era": "Contemporary", "focus": ["Dramatic character", "Dynamic contrast", "Expressive playing"] },
  { "c": "MENDELSSOHN, F.", "t": "Song Without Words, Op. 62 No. 1 'May Breezes'", "nat": "German", "era": "Romantic", "focus": ["Singing melody", "Accompaniment control", "Romantic phrasing"] },
  { "c": "MOZART, W.A.", "t": "Sonata in C, K. 545 (1st mvt, simplified)", "nat": "Austrian", "era": "Classical", "focus": ["Classical sonata form", "Scale technique", "Clear phrasing"] },
  { "c": "NORTON, C.", "t": "Silver Screen (from More Microjazz)", "nat": "English", "era": "Contemporary", "focus": ["Film style", "Atmospheric playing", "Simple arrangement"] },
  { "c": "PAPP, L.", "t": "Toccata (from Recital Collection for Piano, Grade 4)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Staccato technique", "Rhythmic drive", "Clear articulation"] },
  { "c": "PROKOFIEV, S.", "t": "Peter's Theme (from Peter and the Wolf, Op. 67, arr.)", "nat": "Russian", "era": "Modern", "focus": ["Descriptive playing", "Simple arrangement", "Lyrical character"] },
  { "c": "PURCELL, H.", "t": "Suite in G: Minuet (Z. 660)", "nat": "English", "era": "Baroque", "focus": ["Baroque dance", "Ornamentation", "Clear phrasing"] },
  { "c": "RAMSKILL, T.", "t": "Ocean Waves (from Recital Collection for Piano, Grade 4)", "nat": "English", "era": "Contemporary", "focus": ["Descriptive playing", "Flowing figurations", "Atmospheric character"] },
  { "c": "RAVEL, M.", "t": "Pavane pour une infante défunte (simplified arr.)", "nat": "French", "era": "Romantic", "focus": ["Stately character", "Lyrical melody", "Atmospheric playing"] },
  { "c": "SATIE, E.", "t": "Gymnopédie No. 2", "nat": "French", "era": "Romantic", "focus": ["Atmospheric playing", "Simple texture", "Expressive phrasing"] },
  { "c": "SCARLATTI, D.", "t": "Sonata in A, K. 208", "nat": "Italian", "era": "Baroque", "focus": ["Baroque style", "Ornaments", "Binary form"] },
  { "c": "SCHUBERT, F.", "t": "Impromptu in A flat, Op. 142 No. 2 (simplified)", "nat": "Austrian", "era": "Romantic", "focus": ["Lyrical melody", "Simple accompaniment", "Romantic character"] },
  { "c": "SCHUMANN, R.", "t": "Kinderszenen: Träumerei, Op. 15 No. 7 (simplified)", "nat": "German", "era": "Romantic", "focus": ["Dreamy character", "Inner voice balance", "Romantic phrasing"] },
  { "c": "SCHMITZ, M.", "t": "Cool Cat Jazz (from Recital Collection for Piano, Grade 4)", "nat": "American", "era": "Contemporary", "focus": ["Jazz style", "Simple syncopation", "Relaxed character"] },
  { "c": "SEBBA, J.", "t": "Midnight Express (from Recital Collection for Piano, Grade 4)", "nat": "English", "era": "Contemporary", "focus": ["Exciting character", "Rhythmic drive", "Simple coordination"] },
  { "c": "SHOSTAKOVICH, D.", "t": "Polka from The Age of Gold, Op. 22 (simplified arr.)", "nat": "Russian", "era": "Modern", "focus": ["Dance character", "Simple arrangement", "Rhythmic precision"] },
  { "c": "STRECKE, G.", "t": "Impromptu (from Recital Collection for Piano, Grade 4)", "nat": "German", "era": "Romantic", "focus": ["Expressive freedom", "Lyrical melody", "Romantic character"] },
  { "c": "TANSMAN, A.", "t": "Valse (from Pour les Enfants, 3rd set)", "nat": "Polish", "era": "Modern", "focus": ["Waltz style", "Simple texture", "Lyrical phrasing"] },
  { "c": "TELEMANN, G.P.", "t": "Fantasia in E minor (from 36 Fantasias, TWV 33:21)", "nat": "German", "era": "Baroque", "focus": ["Baroque fantasia", "Ornament", "Two-voice writing"] },
  { "c": "TERZIBASCHITSCH, A.", "t": "Tango Macabre (from Recital Collection for Piano, Grade 4)", "nat": "German", "era": "Contemporary", "focus": ["Tango style", "Dramatic character", "Rhythmic precision"] },
  { "c": "VILLA-LOBOS, H.", "t": "Polichinelo (from Prole do Bebê, Vol. 1)", "nat": "Brazilian", "era": "Modern", "focus": ["Dance character", "Brazilian flavour", "Rhythmic drive"] },
  { "c": "YANDELL, S.", "t": "The Devil's Trill (from Recital Collection for Piano, Grade 4)", "nat": "English", "era": "Contemporary", "focus": ["Dramatic character", "Trill technique", "Expressive playing"] },
  { "c": "NORTON, C.", "t": "Swingtime (from Microjazz Collection 3)", "nat": "English", "era": "Contemporary", "focus": ["Swing jazz", "Simple syncopation", "Relaxed character"] },
  { "c": "PAPP, L.", "t": "Fantasy (from Recital Collection for Piano, Grade 4)", "nat": "Hungarian", "era": "Contemporary", "focus": ["Expressive freedom", "Simple texture", "Atmospheric playing"] },
  { "c": "HARRIS, P.", "t": "Celtic Dawn (from Recital Collection for Piano, Grade 4)", "nat": "English", "era": "Contemporary", "focus": ["Celtic character", "Modal flavour", "Atmospheric playing"] },
  { "c": "CAINE, U.", "t": "Night Train (from Recital Collection for Piano, Grade 4)", "nat": "American", "era": "Contemporary", "focus": ["Blues style", "Simple ostinato", "Expressive playing"] },
  { "c": "LANE, R.", "t": "Bossa Nova Groove (from Recital Collection for Piano, Grade 4)", "nat": "English", "era": "Contemporary", "focus": ["Bossa nova style", "Simple syncopation", "Light touch"] },
  { "c": "SCHMITZ, M.", "t": "Ragtime Rag (from Recital Collection for Piano, Grade 4)", "nat": "American", "era": "Contemporary", "focus": ["Ragtime style", "Simple syncopation", "Clear structure"] },
  { "c": "BULLARD, A.", "t": "Night Walk (from Recital Collection for Piano, Grade 4)", "nat": "English", "era": "Contemporary", "focus": ["Atmospheric playing", "Gentle touch", "Simple phrasing"] },
  { "c": "BOBER, M.", "t": "Desert Song (from Recital Collection for Piano, Grade 4)", "nat": "American", "era": "Contemporary", "focus": ["Atmospheric character", "Modal flavour", "Simple ostinato"] },
  { "c": "ARENS, E.", "t": "Invention (from Recital Collection for Piano, Grade 4)", "nat": "German", "era": "Contemporary", "focus": ["Two-voice writing", "Simple counterpoint", "Clear phrasing"] }
];
