// AMEB Piano 2026 — Certificate of Performance (CertP) — Level 2
// Exam: 45 minutes total | Programme: 25–35 min
// One work required from each of Lists A, B, C, D; remainder from A, C or D
// Minimum 3 different styles/historical periods required
// General Knowledge test required (no Technical Work, Aural or Sight-reading)
// Source: 2026 AMEB Piano Syllabus pp.76–77 (Piano Syllabus 2026.pdf pages 56–57)

const DATA_CERTP = [

  // ── LIST A — Studies & Baroque/Early Works (27 pieces) ──────────────────

  {"l":"A","c":"BACH, J.S.","t":"Prelude and Fugue in A♭ major BWV 862 from Das Wohltemperierte Clavier Book 1","nat":"German","era":"Baroque","focus":["Baroque counterpoint","Contrapuntal texture","Keyboard clarity"]},
  {"l":"A","c":"BACH, J.S.","t":"Prelude and Fugue in C minor BWV 871 from Das Wohltemperierte Clavier Book 2","nat":"German","era":"Baroque","focus":["Baroque counterpoint","Contrapuntal texture","Keyboard clarity"]},
  {"l":"A","c":"CRAMER, J.","t":"Study (Moderato) in G major No 21 from 84 studies Op. 50 (No 20 in Cramer: 50 selected studies – Alfred)","nat":"German","era":"Classical","focus":["Technical facility","Finger independence","Even tone"]},
  {"l":"A","c":"CRAMER, J.","t":"Study (Moderato) in D major No 3 from 84 studies Op. 50 (No 6 in Cramer: 50 selected studies – Alfred)","nat":"German","era":"Classical","focus":["Technical facility","Finger independence","Even tone"]},
  {"l":"A","c":"CRAMER, J.","t":"Study (Vivace) in D major No 33 from 84 studies Op. 50 (No 13 in Cramer: 50 selected studies – Alfred)","nat":"German","era":"Classical","focus":["Technical facility","Finger independence","Velocity"]},
  {"l":"A","c":"CRAMER, J.","t":"Study (Maestoso energico) in B♭ major No 64 from 84 studies Op. 50 (No 25 in Cramer: 50 selected studies – Alfred)","nat":"German","era":"Classical","focus":["Technical facility","Finger strength","Expressive tone"]},
  {"l":"A","c":"CZERNY, C.","t":"Study in F major No 11 from Die Kunst der Fingerfertigkeit [The art of finger dexterity] Op. 740","nat":"Austrian","era":"Classical","focus":["Technical facility","Velocity","Finger independence"]},
  {"l":"A","c":"CZERNY, C.","t":"Study in A♭ major No 45 from Die Kunst der Fingerfertigkeit [The art of finger dexterity] Op. 740","nat":"Austrian","era":"Classical","focus":["Technical facility","Velocity","Finger independence"]},
  {"l":"A","c":"HANDEL, G.F.","t":"Capriccio in F major HWV 481","nat":"German","era":"Baroque","focus":["Baroque style","Ornamentation","Keyboard clarity"]},
  {"l":"A","c":"HENSEL, F.","t":"Übungsstück (Allegro Moderato) in C major (Hensel: Ausgewälte Klavierwerke (Erstausgabe) – Henle)","nat":"German","era":"Romantic","focus":["Technical facility","Finger independence","Expressive tone"]},
  {"l":"A","c":"HENSEL, F.","t":"Übungsstück (Allegro Moderato) in G minor (Hensel: Ausgewälte Klavierwerke (Erstausgabe) – Henle)","nat":"German","era":"Romantic","focus":["Technical facility","Finger independence","Expressive tone"]},
  {"l":"A","c":"LISZT, F.","t":"Etude (Molto agitato) in G minor No 6 from Etude in 12 Übungen Op. 6/LW A8 No 6/S 136","nat":"Hungarian","era":"Romantic","focus":["Technical facility","Velocity","Dynamic control"]},
  {"l":"A","c":"LISZT, F.","t":"Etude (Allegro non troppo) in B♭ minor No 12 from Etude in 12 Übungen Op. 6/LW A8 No 12/S 136","nat":"Hungarian","era":"Romantic","focus":["Technical facility","Velocity","Dynamic control"]},
  {"l":"A","c":"MACDOWELL, E.","t":"Scherzino No 11 from 12 Etüden Op. 39","nat":"American","era":"Romantic","focus":["Technical facility","Delicacy","Character"]},
  {"l":"A","c":"MOSCHELES, I.","t":"Etude (Allegro giocoso) in D minor No 6 from 24 études Op. 70 (24 études de perfectionnement – Schott)","nat":"Czech","era":"Romantic","focus":["Technical facility","Finger independence","Rhythmic precision"]},
  {"l":"A","c":"MOSCHELES, I.","t":"Etude (Agitato) in B♭ minor No 12 from 24 études Op. 70 (24 études de perfectionnement – Schott)","nat":"Czech","era":"Romantic","focus":["Technical facility","Expressive intensity","Finger independence"]},
  {"l":"A","c":"MOSZKOWSKI, M.","t":"Etude (Presto) in F major No 6 from 15 études de virtuosité Op. 72","nat":"German","era":"Romantic","focus":["Technical facility","Velocity","Brilliance"]},
  {"l":"A","c":"RAMEAU, J.-P.","t":"Gavotte and Doubles de la Gavotte [six doubles] in A minor from Nouvelles suites de pièces de clavecin (Pièces de clavecin (troisiéme recueil) – Bärenreiter)","nat":"French","era":"Baroque","focus":["Baroque style","Ornamentation","Variation technique"]},
  {"l":"A","c":"SCARLATTI, D.","t":"Sonata in E major K 28 (Scarlatti: 60 Sonatas Volume 1 – Schirmer)","nat":"Italian","era":"Baroque","focus":["Baroque style","Keyboard clarity","Hand crossing"]},
  {"l":"A","c":"SCARLATTI, D.","t":"Sonata in D major K 96 (Anthology of Baroque keyboard music – Alfred)","nat":"Italian","era":"Baroque","focus":["Baroque style","Keyboard clarity","Brilliance"]},
  {"l":"A","c":"SCARLATTI, D.","t":"Sonata in D major K 140","nat":"Italian","era":"Baroque","focus":["Baroque style","Keyboard clarity","Finger independence"]},
  {"l":"A","c":"SCARLATTI, D.","t":"Sonata in D minor K 141 (D. Scarlatti: Sonates Volume 3 – Heugel & Cie)","nat":"Italian","era":"Baroque","focus":["Baroque style","Keyboard clarity","Velocity"]},
  {"l":"A","c":"SCARLATTI, D.","t":"Sonata in F major K 366","nat":"Italian","era":"Baroque","focus":["Baroque style","Keyboard clarity","Elegance"]},
  {"l":"A","c":"SCARLATTI, D.","t":"Sonata in D major K 535 (D. Scarlatti: Sonates Volume 11 – Heugel & Cie)","nat":"Italian","era":"Baroque","focus":["Baroque style","Keyboard clarity","Rhythmic vitality"]},
  {"l":"A","c":"SCARLATTI, D.","t":"Sonata in B♭ major K 551 (D. Scarlatti: Sonates Volume 11 – Heugel & Cie)","nat":"Italian","era":"Baroque","focus":["Baroque style","Keyboard clarity","Elegance"]},
  {"l":"A","c":"SCHUMANN, C.","t":"Praeludium II and Fuga II in B♭ major No 2 from Drei Präludien und Fugen Op. 16 (Romantische Klaviermusik – Bärenreiter)","nat":"German","era":"Romantic","focus":["Contrapuntal texture","Expressive tone","Formal structure"]},
  {"l":"A","c":"SHOSTAKOVICH, D.","t":"Prelude and Fugue in D major No 5 from 24 preludes and fugues Op. 87","nat":"Russian","era":"Modern","focus":["Modern style","Contrapuntal texture","Expressive tone"]},
  {"l":"A","c":"SHOSTAKOVICH, D.","t":"Prelude and Fugue in E major No 9 from 24 preludes and fugues Op. 87","nat":"Russian","era":"Modern","focus":["Modern style","Contrapuntal texture","Expressive tone"]},

  // ── LIST B — Classical & Sonata Works (28 pieces) ────────────────────────

  {"l":"B","c":"BACH, C.P.E.","t":"Sonata in F minor H 173/W 57.6","nat":"German","era":"Baroque","focus":["Classical style","Formal structure","Expressive tone"]},
  {"l":"B","c":"BACH, J.C.","t":"Sonata in E major Op. 5 No 5 (Sonatas Volume I – Henle)","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Elegance"]},
  {"l":"B","c":"BACH, J.C.","t":"Sonata in B♭ major Op. 17 No 6 (Sonatas Volume II – Henle)","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Elegance"]},
  {"l":"B","c":"BACH, J.S.","t":"'French' Suite [No 3] in B minor BWV 814","nat":"German","era":"Baroque","focus":["Baroque style","Dance character","Keyboard clarity"]},
  {"l":"B","c":"BEETHOVEN, L. van","t":"Sonata in E major Op. 14 No 1 (Henle)","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Dynamic contrast"]},
  {"l":"B","c":"BEETHOVEN, L. van","t":"Rondo in G major Op. 51 No 2","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Elegance"]},
  {"l":"B","c":"BEETHOVEN, L. van","t":"Sonata in G major Op. 79 (Henle)","nat":"German","era":"Classical","focus":["Classical phrasing","Formal structure","Dynamic contrast"]},
  {"l":"B","c":"CLEMENTI, M.","t":"Sonata in A major Op. 10 No 1 (Clementi: Piano sonatas Volume 1 – Henle)","nat":"Italian","era":"Classical","focus":["Classical phrasing","Formal structure","Finger independence"]},
  {"l":"B","c":"CLEMENTI, M.","t":"Sonata in F minor Op. 13 No 6 (Clementi: Piano sonatas Volume 1 – Henle)","nat":"Italian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"B","c":"CLEMENTI, M.","t":"Sonata in G major Op. 25 No 2","nat":"Italian","era":"Classical","focus":["Classical phrasing","Formal structure","Finger independence"]},
  {"l":"B","c":"HAYDN, J.","t":"Sonata in G major Hob XVI:6","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Elegance"]},
  {"l":"B","c":"HAYDN, J.","t":"Sonata in D major Hob XVI:19","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Elegance"]},
  {"l":"B","c":"HAYDN, J.","t":"Sonata in D major Hob XVI:37","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Wit"]},
  {"l":"B","c":"HAYDN, J.","t":"Sonata in E♭ major Hob XVI:38","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Dynamic contrast"]},
  {"l":"B","c":"HAYDN, J.","t":"Sonata in D major Hob XVI:42","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Elegance"]},
  {"l":"B","c":"HAYDN, J.","t":"Sonata in G minor Hob XVI:44","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"B","c":"HAYDN, J.","t":"Sonata in F major Hob XVI:47","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Elegance"]},
  {"l":"B","c":"HAYDN, J.","t":"Sonata in C major Hob XVI:48","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Brilliance"]},
  {"l":"B","c":"HUMMEL, J.N.","t":"Sonata VII in G major (Musica Rara)","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Brilliance"]},
  {"l":"B","c":"MÉHUL, E.","t":"Sonata in D major Op. 1 No 1","nat":"French","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"B","c":"MÉHUL, E.","t":"Sonata in A major Op. 1 No 3","nat":"French","era":"Classical","focus":["Classical phrasing","Formal structure","Expressive tone"]},
  {"l":"B","c":"MOZART, W.A.","t":"Sonata in E♭ major K 282","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Elegance"]},
  {"l":"B","c":"MOZART, W.A.","t":"Rondo in A minor K 511","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Lyrical phrasing","Expressive tone"]},
  {"l":"B","c":"MOZART, W.A.","t":"Sonata in C major K 545","nat":"Austrian","era":"Classical","focus":["Classical phrasing","Formal structure","Clarity"]},
  {"l":"B","c":"POULENC, F.","t":"Suite for piano","nat":"French","era":"Modern","focus":["Modern style","Character","Wit"]},
  {"l":"B","c":"SCULTHORPE, P.","t":"Sonatina (Faber)","nat":"Australian","era":"Contemporary","focus":["Australian character","Contemporary style","Formal structure"]},
  {"l":"B","c":"SUTHERLAND, M.","t":"Sonatina (The piano works of Margaret Sutherland – All Music Publishing)","nat":"Australian","era":"Modern","focus":["Australian character","Modern style","Formal structure"]},

  // ── LIST C — Romantic Works (23 pieces) ──────────────────────────────────

  {"l":"C","c":"ARENSKY, A.","t":"Nocturne in D♭ major No 3 from 24 characteristic pieces Op. 36","nat":"Russian","era":"Romantic","focus":["Lyrical phrasing","Singing tone","Expressive tone"]},
  {"l":"C","c":"BRIDGE, F.","t":"Valse capricieuse No 3 from Three sketches (The Boosey and Hawkes 20th century piano collection: 1900-1945 – Boosey and Hawkes)","nat":"English","era":"Modern","focus":["Dance character","Delicacy","Expressive tone"]},
  {"l":"C","c":"CHOPIN, F.","t":"Polonaise in C minor Op. 26 No 1/CT 150","nat":"Polish","era":"Romantic","focus":["Romantic expression","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Polonaise in E♭ minor Op. 26 No 2/CT 151","nat":"Polish","era":"Romantic","focus":["Romantic expression","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Impromptu in A♭ major Op. 29/CT 43","nat":"Polish","era":"Romantic","focus":["Romantic expression","Lyrical phrasing","Flowing technique"]},
  {"l":"C","c":"CHOPIN, F.","t":"Mazurka in B minor Op. 33 No 4/CT 75","nat":"Polish","era":"Romantic","focus":["Dance character","Rubato","Expressive tone"]},
  {"l":"C","c":"CHOPIN, F.","t":"Polonaise in A major Op. 40 No 1/CT 152","nat":"Polish","era":"Romantic","focus":["Romantic expression","Dance character","Dynamic shaping"]},
  {"l":"C","c":"CHOPIN, F.","t":"Mazurka in C♯ minor Op. 50 No 3/CT 82","nat":"Polish","era":"Romantic","focus":["Dance character","Rubato","Expressive tone"]},
  {"l":"C","c":"CHOPIN, F.","t":"Fantasie-impromptu in C♯ minor Op. 66/CT 46","nat":"Polish","era":"Romantic","focus":["Romantic expression","Lyrical phrasing","Technical facility"]},
  {"l":"C","c":"FAURÉ, G.","t":"Allegro molto No 2 from Trois romances sans paroles Op. 17 No. 2 (Peters)","nat":"French","era":"Romantic","focus":["Lyrical phrasing","Singing tone","Expressive tone"]},
  {"l":"C","c":"GRIEG, E.","t":"Bryllupsdag på Troldhaugen [Wedding-day at Troldhaugen] No 6 from Lyrische Stücke [Lyric pieces] Op. 65","nat":"Norwegian","era":"Romantic","focus":["Romantic expression","Dynamic shaping","National character"]},
  {"l":"C","c":"HENSEL, F.","t":"Andante No 1 from 4 Lieder für das Pianoforte Op. 2","nat":"German","era":"Romantic","focus":["Lyrical phrasing","Singing tone","Expressive tone"]},
  {"l":"C","c":"HENSEL, F.","t":"Allegretto grazioso No 3 from 4 Lieder für das Pianoforte Op. 2","nat":"German","era":"Romantic","focus":["Lyrical phrasing","Elegance","Expressive tone"]},
  {"l":"C","c":"HENSEL, F.","t":"Andante cantabile in F minor No 3 from 4 Lieder für das Pianoforte Op. 6","nat":"German","era":"Romantic","focus":["Lyrical phrasing","Singing tone","Expressive tone"]},
  {"l":"C","c":"HENSEL, F.","t":"Allegro moderato No 1 from 4 Lieder für das Pianoforte Op. 8","nat":"German","era":"Romantic","focus":["Lyrical phrasing","Character","Expressive tone"]},
  {"l":"C","c":"HENSEL, F.","t":"Andante cantabile in D♭ major (Hensel: Ausgewälte Klavierwerke – Henle)","nat":"German","era":"Romantic","focus":["Lyrical phrasing","Singing tone","Expressive tone"]},
  {"l":"C","c":"HILL, M.","t":"The leafy lanes of Kent (AMC)","nat":"Australian","era":"Modern","focus":["Australian character","Lyrical phrasing","Expressive tone"]},
  {"l":"C","c":"LISZT, F.","t":"Au lac de Wallenstadt [At Lake Wallenstadt] No 2 from Années de pèlerinage: Premiere année LW A159/S 160","nat":"Hungarian","era":"Romantic","focus":["Romantic expression","Tone colour","Lyrical phrasing"]},
  {"l":"C","c":"LISZT, F.","t":"Notturno (O Lieb, so lang du lieben kannst) in A♭ major No 3 from Liebesträume LW A103/S 541","nat":"Hungarian","era":"Romantic","focus":["Romantic expression","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"MENDELSSOHN, F.","t":"Lieder ohne Worte (Presto e molto vivace) in E major No 3 from Lieder ohne Worte Op. 38","nat":"German","era":"Romantic","focus":["Romantic expression","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"RACHMANINOFF, S.","t":"Humoresque in G major [revised version 1940] No 5 from Morceaux de salon Op. 10","nat":"Russian","era":"Romantic","focus":["Romantic expression","Character","Dynamic shaping"]},
  {"l":"C","c":"RACHMANINOFF, S.","t":"Prélude in C♯ minor No 2 from Morceaux de fantaisie Op. 3","nat":"Russian","era":"Romantic","focus":["Romantic expression","Dynamic shaping","Tone colour"]},
  {"l":"C","c":"RACHMANINOFF, S.","t":"Mélodie in E major No 3 from Morceaux de fantaisie Op. 3 [Candidates may present the 1893 or 1940 version]","nat":"Russian","era":"Romantic","focus":["Romantic expression","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"RACHMANINOFF, S.","t":"Polichinelle in F♯ minor No 4 from Morceaux de fantaisie Op. 3","nat":"Russian","era":"Romantic","focus":["Romantic expression","Character","Dynamic shaping"]},
  {"l":"C","c":"SCHUBERT, F.","t":"Impromptu in G♭ major No 3 from 4 Impromptus D 899","nat":"Austrian","era":"Romantic","focus":["Lyrical phrasing","Singing tone","Flowing technique"]},
  {"l":"C","c":"SCHUMANN, R.","t":"Fabel No 6 from Fantasiestücke Op. 12","nat":"German","era":"Romantic","focus":["Romantic expression","Character","Expressive tone"]},
  {"l":"C","c":"SCHUMANN, R.","t":"Arabeske Op. 18","nat":"German","era":"Romantic","focus":["Romantic expression","Lyrical phrasing","Dynamic shaping"]},
  {"l":"C","c":"SCHUMANN, R.","t":"Novellette in F major No 1 from 8 Novelletten Op. 21","nat":"German","era":"Romantic","focus":["Romantic expression","Character","Dynamic shaping"]},
  {"l":"C","c":"SCHUMANN, R.","t":"Novellette in B minor No 9 from Bunte Blätter [Coloured leaves] Op. 99 (Schumann: Klavierwerke Band 1 – Henle)","nat":"German","era":"Romantic","focus":["Romantic expression","Character","Expressive tone"]},
  {"l":"C","c":"SCHUMANN, R. arr. LISZT, F.","t":"Liebeslied (Widmung) [Dedication] LW A133/S 566 (Boosey and Hawkes)","nat":"German","era":"Romantic","focus":["Romantic expression","Singing tone","Lyrical phrasing"]},
  {"l":"C","c":"SCRIABIN, A.","t":"Préludes Op. 11 Nos 13, 14, 15 & 16 (G♭, E♭ minor, D♭, B♭ minor) from Vingt-quatre preludes [24 preludes] Op. 11","nat":"Russian","era":"Romantic","focus":["Romantic expression","Tone colour","Lyrical phrasing"]},
  {"l":"C","c":"SCRIABIN, A.","t":"Quatre préludes Op. 22","nat":"Russian","era":"Romantic","focus":["Romantic expression","Tone colour","Lyrical phrasing"]},
  {"l":"C","c":"TCHAIKOVSKY, P.","t":"Polka de salon No 2 from Trois morceaux Op. 9 (Ausgewählte Klavierwerke Volume 2 – Peters)","nat":"Russian","era":"Romantic","focus":["Dance character","Elegance","Dynamic shaping"]},

  // ── LIST D — Modern & Contemporary Works (20 pieces) ─────────────────────

  {"l":"D","c":"ALBÉNIZ, I.","t":"Orientale No 2 from Cantos d'España Op. 232","nat":"Spanish","era":"Romantic","focus":["National character","Tone colour","Expressive tone"]},
  {"l":"D","c":"ALBÉNIZ, I.","t":"Cordoba No 4 from Cantos d'España Op. 232 (Celebration series: Piano repertoire Level 10 – Frederick Harris)","nat":"Spanish","era":"Romantic","focus":["National character","Tone colour","Expressive tone"]},
  {"l":"D","c":"ALBÉNIZ, I.","t":"Seguidillas No 5 from Cantos d'España Op. 232","nat":"Spanish","era":"Romantic","focus":["National character","Dance character","Rhythmic vitality"]},
  {"l":"D","c":"BAILEY, K.","t":"Drowsy bees and butterflies (Bailey)","nat":"Australian","era":"Contemporary","focus":["Australian character","Tone colour","Expressive tone"]},
  {"l":"D","c":"BARTÓK, B.","t":"Allegro barbaro Sz 49/BB 63","nat":"Hungarian","era":"Modern","focus":["Modern style","Rhythmic vitality","Percussive touch"]},
  {"l":"D","c":"BARTÓK, B.","t":"Petite suite Sz 105/BB 113","nat":"Hungarian","era":"Modern","focus":["Modern style","National character","Character"]},
  {"l":"D","c":"BENJAMIN, A.","t":"Scherzino (The Boosey and Hawkes 20th Century Piano Collection: 1900-1945 – Boosey and Hawkes)","nat":"Australian","era":"Modern","focus":["Australian character","Wit","Delicacy"]},
  {"l":"D","c":"BOULANGER, L.","t":"D'un jardin clair [Of a bright garden] (No 2 in Trois morceaux pour piano – Schirmer)","nat":"French","era":"Modern","focus":["Modern style","Tone colour","Expressive tone"]},
  {"l":"D","c":"CHUA, S.","t":"Rodeo (Scenes of childhood: Fourteen piano solos – Midnight Editions)","nat":"Australian","era":"Contemporary","focus":["Australian character","Rhythmic vitality","Character"]},
  {"l":"D","c":"COPLAND, A.","t":"Le chat et la souris [The cat and the mouse] (The Copland piano collection – Boosey and Hawkes)","nat":"American","era":"Modern","focus":["Modern style","Character","Wit"]},
  {"l":"D","c":"COPLAND, A.","t":"Night thoughts (The Copland piano collection – Boosey and Hawkes)","nat":"American","era":"Modern","focus":["Modern style","Expressive tone","Tone colour"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Les sons et les parfums tournent dans l'air du soir [The sounds and fragrances swirl through the evening air] No 4 from Préludes Book 1 L 117","nat":"French","era":"Modern","focus":["Impressionist style","Tone colour","Pedal technique"]},
  {"l":"D","c":"DEBUSSY, C.","t":"La puerta del vino [Wine door] No 3 from Préludes Book 2 L 123","nat":"French","era":"Modern","focus":["Impressionist style","Tone colour","National character"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Rêverie L 68","nat":"French","era":"Modern","focus":["Impressionist style","Lyrical phrasing","Tone colour"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Prélude 1st movement from Suite Bergamasque L 75","nat":"French","era":"Modern","focus":["Impressionist style","Tone colour","Pedal technique"]},
  {"l":"D","c":"DEBUSSY, C.","t":"Sarabande 2nd movement from Pour le piano L 95","nat":"French","era":"Modern","focus":["Impressionist style","Tone colour","Expressive tone"]},
  {"l":"D","c":"DEBUSSY, C.","t":"La plus que lente L 121","nat":"French","era":"Modern","focus":["Impressionist style","Tone colour","Dance character"]},
  {"l":"D","c":"DURHAM, B.","t":"Wind chimes (Blowing in the wind: Australia – Barbara Durham Music)","nat":"Australian","era":"Contemporary","focus":["Australian character","Tone colour","Contemporary style"]},
  {"l":"D","c":"FALLA, M. de","t":"Danza ritual del fuego [Ritual fire dance] from El amor brujo [Love, the magician]","nat":"Spanish","era":"Modern","focus":["National character","Rhythmic vitality","Tone colour"]},
  {"l":"D","c":"GINASTERA, A.","t":"Danza del viejo boyero [Dance of the old herdsman] No 1 and Danza de la moza donosa [Dance of the beautiful maiden] No 2 [to be performed as one work] from Danzas Argentinas Op. 2","nat":"Argentine","era":"Modern","focus":["National character","Rhythmic vitality","Dance character"]},
  {"l":"D","c":"GINASTERA, A.","t":"Rondó sobre temas infantiles argentines [Rondo on Argentine children's folk tunes]","nat":"Argentine","era":"Modern","focus":["National character","Rhythmic vitality","Character"]},
  {"l":"D","c":"GOULD, M.","t":"Boogie woogie etude (Anthology of American piano music – Alfred)","nat":"American","era":"Modern","focus":["Modern style","Rhythmic vitality","Character"]},
  {"l":"D","c":"HANDEL, A.","t":"The seduction of Andalucia (Australian Women Composers' Piano Anthology – Wirripang)","nat":"Australian","era":"Contemporary","focus":["Australian character","National character","Expressive tone"]},
  {"l":"D","c":"HOLLAND, D.","t":"Nocturne (Australian heritage collection Volume III – Wirripang)","nat":"Australian","era":"Contemporary","focus":["Australian character","Lyrical phrasing","Tone colour"]},
  {"l":"D","c":"HOLLAND, D.","t":"Piano rag (AMC)","nat":"Australian","era":"Contemporary","focus":["Australian character","Rhythmic vitality","Character"]},
  {"l":"D","c":"KABALEVSKY, D.","t":"Variations in A minor Op. 40 No 2 (Celebration series: Piano repertoire Level 10 – Frederick Harris)","nat":"Russian","era":"Modern","focus":["Modern style","Variation technique","Character"]},
  {"l":"D","c":"KHACHATURIAN, A.","t":"Tokkata [Toccata]","nat":"Armenian","era":"Modern","focus":["Modern style","Rhythmic vitality","Percussive touch"]},
  {"l":"D","c":"PROKOFIEV, S.","t":"The Montagues and the Capulets No 6 from Ten pieces from Romeo and Juliet Op. 75 (Hal Leonard)","nat":"Russian","era":"Modern","focus":["Modern style","Character","Dynamic shaping"]},
  {"l":"D","c":"PROKOFIEV, S.","t":"Gavotte (from Hamlet) Op. 77bis [Also published as Op. 77 No 4]","nat":"Russian","era":"Modern","focus":["Modern style","Dance character","Character"]},
  {"l":"D","c":"RAVEL, M.","t":"Pavane pour une infante défunte [Pavane for a dead princess]","nat":"French","era":"Modern","focus":["Impressionist style","Lyrical phrasing","Tone colour"]},
  {"l":"D","c":"SCHOENBERG, A.","t":"Sechs kleine Klavierstücke Op. 19","nat":"Austrian","era":"Modern","focus":["Modern style","Contemporary style","Expressive tone"]},
  {"l":"D","c":"SITSKY, L.","t":"Petra No 155 from Century (Century Volume 3 – Wirripang)","nat":"Australian","era":"Contemporary","focus":["Australian character","Contemporary style","Expressive tone"]},
  {"l":"D","c":"STRAVINSKY, I.","t":"Cadenza finale 4th movement from Serenade in A (Boosey and Hawkes)","nat":"Russian","era":"Modern","focus":["Modern style","Rhythmic vitality","Character"]},
  {"l":"D","c":"STRAVINSKY, I.","t":"Hymne 1st movement from Serenade in A (Boosey and Hawkes)","nat":"Russian","era":"Modern","focus":["Modern style","Tone colour","Expressive tone"]},
  {"l":"D","c":"SUTHERLAND, M.","t":"Valse descant (The piano works of Margaret Sutherland – All Music Publishing)","nat":"Australian","era":"Modern","focus":["Australian character","Dance character","Expressive tone"]},
  {"l":"D","c":"VILLA-LOBOS, H.","t":"Branquinha No 1 from Prole do bebê [The baby's family] Volume 1","nat":"Brazilian","era":"Modern","focus":["National character","Tone colour","Character"]},
  {"l":"D","c":"VILLA-LOBOS, H.","t":"Moreninha No 2 from Prole do bebê [The baby's family] Volume 1","nat":"Brazilian","era":"Modern","focus":["National character","Tone colour","Character"]},
  {"l":"D","c":"VILLA-LOBOS, H.","t":"Caboclinha No 3 from Prole do bebê [The baby's family] Volume 1","nat":"Brazilian","era":"Modern","focus":["National character","Tone colour","Rhythmic vitality"]},
  {"l":"D","c":"VILLA-LOBOS, H.","t":"Mulatinha No 4 from Prole do bebê [The baby's family] Volume 1","nat":"Brazilian","era":"Modern","focus":["National character","Tone colour","Character"]},
  {"l":"D","c":"VILLA-LOBOS, H.","t":"O Polichinello No 7 from Prole do bebê [The baby's family] Volume 1","nat":"Brazilian","era":"Modern","focus":["National character","Rhythmic vitality","Character"]},

];
