const MASTER_DATA = [
  // --- LIST A (Baroque & Studies) ---
  { "l": "A", "s": "S19", "c": "BACH, J.S.", "t": "Allemande (French Suite No 4 BWV 815)" },
  { "l": "A", "s": "S19", "c": "HANDEL, G.F.", "t": "Allegro (Suite HWV 432)" },
  { "l": "A", "s": "S19", "c": "HELLER, S.", "t": "Étude No 15 Op. 45" },
  { "l": "A", "s": "S19", "c": "MONOROSI, K.", "t": "Etude in A minor on a theme of Paganini No 20 (24 etudes Op. 1)" },
  { "l": "A", "s": "S18", "c": "BACH, J.S.", "t": "Menuet I and II (French Suite No 3 BWV 814)" },
  { "l": "A", "s": "S18", "c": "DAQUIN, L.", "t": "Le coucou" },
  { "l": "A", "s": "S18", "c": "LUTOSŁAWSKI, W.", "t": "Four-finger exercise No 1" },
  { "l": "A", "s": "S18", "c": "SCARLATTI, D.", "t": "Sonata K 35" },
  { "l": "A", "s": "S17", "c": "BACH, J.S.", "t": "Gigue (Suite No 6 BWV 817)" },
  { "l": "A", "s": "S17", "c": "BACH, J.S.", "t": "Sinfonia BWV 794" },
  { "l": "A", "s": "S17", "c": "HELLER, S.", "t": "Etude No 20 Op. 45" },
  { "l": "A", "s": "Manual", "c": "ALBÉNIZ, M.", "t": "Sonata in D major" },
  { "l": "A", "s": "Manual", "c": "BACH, C.P.E.", "t": "Presto in C minor H 230" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Courante (French Suite No 2 BWV 813)" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Sinfonia No 1 in C BWV 787" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Sinfonia No 3 in D BWV 789" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Sinfonia No 6 in E BWV 792" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Sinfonia No 9 in E minor BWV 793" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Gigue (French Suite No 3 BWV 814)" },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Little Prelude No 4 BWV 936" },
  { "l": "A", "s": "Manual", "c": "BURGMÜLLER, F.", "t": "Le retour de pâtre Op. 109 No 3" },
  { "l": "A", "s": "Manual", "c": "CHUA, S.", "t": "Study No 20 (Zeitgeist Book 2)" },
  { "l": "A", "s": "Manual", "c": "CIMAROSA, D.", "t": "Sonata in A major No 14" },
  { "l": "A", "s": "Manual", "c": "CZERNY, C.", "t": "Etude Op. 299 No 29" },
  { "l": "A", "s": "Manual", "c": "CZERNY, C.", "t": "Etude Op. 299 No 5" },
  { "l": "A", "s": "Manual", "c": "CZERNY, C.", "t": "Etude Op. 299 No 6" },
  { "l": "A", "s": "Manual", "c": "CZERNY, C.", "t": "Etude Op. 849 No 24" },
  { "l": "A", "s": "Manual", "c": "HANDEL, G.", "t": "Air con variazioni (Suite HWV 434)" },
  { "l": "A", "s": "Manual", "c": "HANDEL, G.", "t": "Sonatina in D minor HWV 581" },
  { "l": "A", "s": "Manual", "c": "HELLER, S.", "t": "Etude Op. 45 No 9" },
  { "l": "A", "s": "Manual", "c": "HELLER, S.", "t": "Etude Op. 45 No 21" },
  { "l": "A", "s": "Manual", "c": "HELLER, S.", "t": "Etude Op. 45 No 22" },
  { "l": "A", "s": "Manual", "c": "KREBS, J.", "t": "Courante in C major (Clavier-Übung)" },
  { "l": "A", "s": "Manual", "c": "MOSZKOWSKI, M.", "t": "Etude Op. 91 No 1" },
  { "l": "A", "s": "Manual", "c": "PURCELL, H.", "t": "Prelude (Suite Z 661)" },
  { "l": "A", "s": "Manual", "c": "SCARLATTI, D.", "t": "Sonata K 85" },
  { "l": "A", "s": "Manual", "c": "SCARLATTI, D.", "t": "Sonata K 3" },
  { "l": "A", "s": "Manual", "c": "TANSMAN, A.", "t": "Fughetta" },
  { "l": "A", "s": "Manual", "c": "TELEMANN, G.", "t": "Allegro (Fantasia No 4 TWV 33:4)" },
  { "l": "A", "s": "Manual", "c": "TELEMANN, G.", "t": "Vivace (Fantasia No 5 TWV 33:5)" },
  { "l": "A", "s": "Manual", "c": "TELEMANN, G.", "t": "Allegro (Fantasia No 9 TWV 33:9)" },

  // --- LIST B (Classical Sonatas) ---
  { "l": "B", "s": "S19", "c": "BEETHOVEN, L. van.", "t": "Andante (Sonata Op. 49 No 1)" },
  { "l": "B", "s": "S19", "c": "HAYDN, J.", "t": "Theme and Variations Hob XVII:2" },
  { "l": "B", "s": "S19", "c": "MARTÍNEZ, M. von.", "t": "Allegro (Sonata Op. 4)" },
  { "l": "B", "s": "S19", "c": "NEEFE, C.", "t": "Allegro di molto Fourth movement (6 neue Klaviersonaten)" },
  { "l": "B", "s": "S18", "c": "BACH, J.C.", "t": "Allegro (Sonata Op. 17 No 3)" },
  { "l": "B", "s": "S18", "c": "EBERL, A.", "t": "Allegro (Sonatine Op. 5)" },
  { "l": "B", "s": "S18", "c": "KOZELUCH, L.", "t": "Allegretto (Sonata Op. 35 No 3)" },
  { "l": "B", "s": "S18", "c": "SCHUMANN, C.", "t": "Scherzo No 4 Op. 15" },
  { "l": "B", "s": "S17", "c": "BACH, C.P.E.", "t": "Vivace (Sonata No 1 W 50)" },
  { "l": "B", "s": "S17", "c": "BEETHOVEN, L. van.", "t": "Six variations WoO 77" },
  { "l": "B", "s": "S17", "c": "HAYDN, J.", "t": "Finale (Sonata Hob XVI:21)" },
  { "l": "B", "s": "S17", "c": "VOŘÍŠEK, J.", "t": "Rondo No 1 Op. 18" },
  { "l": "B", "s": "Manual", "c": "BACH, C.P.E.", "t": "Allegro di molto (Sonata H 59)" },
  { "l": "B", "s": "Manual", "c": "BACH, J.C.", "t": "Allegretto (Sonata Op. 5 No 1)" },
  { "l": "B", "s": "Manual", "c": "BEETHOVEN, L. van.", "t": "Minuet (Sonata Op. 22)" },
  { "l": "B", "s": "Manual", "c": "BENDA, J.", "t": "Sonatina No 13 in C minor" },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Rondo (Sonatina Op. 36 No 4)" },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Presto (Sonatina Op. 36 No 5)" },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Allegro moderato (Sonatina Op. 38 No 2)" },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Allegretto (Sonatina Op. 38 No 3)" },
  { "l": "B", "s": "Manual", "c": "DIABELLI, A.", "t": "Allegro moderato (Sonatina Op. 151 No 3)" },
  { "l": "B", "s": "Manual", "c": "DUSSEK, J.", "t": "Moderato (Sonatina Op. 20 No 4)" },
  { "l": "B", "s": "Manual", "c": "DUSSEK, J.", "t": "Allegro (Sonatina Op. 20 No 6)" },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Moderato (Sonata Hob XVI:2)" },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Moderato (Sonata Hob XVI:13)" },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Finale (Sonata Hob XVI:14)" },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Finale (Sonata Hob XVI:27)" },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Scherzando (Sonata Hob XVI:36)" },
  { "l": "B", "s": "Manual", "c": "KUHLAU, F.", "t": "Allegro maestoso (Sonatina Op. 55 No 6)" },
  { "l": "B", "s": "Manual", "c": "KUHLAU, F.", "t": "Allegro con spirito (Sonatina Op. 60 No 2)" },
  { "l": "B", "s": "Manual", "c": "KUHLAU, F.", "t": "Allegro burlesco (Sonatina Op. 88 No 3)" },
  { "l": "B", "s": "Manual", "c": "MOZART, W.", "t": "Allegro (Sonata K 282)" },
  { "l": "B", "s": "Manual", "c": "MOZART, W.", "t": "Minuet and Trio (Sonata K 331)" },
  { "l": "B", "s": "Manual", "c": "PLEYEL, I.", "t": "Rondo (Sonatina III in G)" },
  { "l": "B", "s": "Manual", "c": "SCHUBERT, F.", "t": "Scherzo No 1 D 593" },

  // --- LIST C (Romantic & Collaborative) ---
  { "l": "C", "s": "S19", "c": "CHOPIN, F.", "t": "Mazurka Op. 7 No 1" },
  { "l": "C", "s": "S19", "c": "FARRENC, L.", "t": "Impromptu" },
  { "l": "C", "s": "S19", "c": "FIELD, J.", "t": "Nocturne H 59" },
  { "l": "C", "s": "S19", "c": "PAINE, J.", "t": "Rainy day Op. 26 No 6" },
  { "l": "C", "s": "S18", "c": "GRIEG, E.", "t": "Notturno Op. 54 No 4" },
  { "l": "C", "s": "S18", "c": "HILL, A.", "t": "Berceuse" },
  { "l": "C", "s": "S18", "c": "SÉVERAC, D. de.", "t": "Mimi se déguise en Marquise" },
  { "l": "C", "s": "S18", "c": "WOLLENHAUPT, H.", "t": "Scherzino Op. 29 No 6" },
  { "l": "C", "s": "S17", "c": "DELIBES, L.", "t": "Passepied No 6" },
  { "l": "C", "s": "S17", "c": "GADE, N.", "t": "Andantino" },
  { "l": "C", "s": "S17", "c": "GRIEG, E.", "t": "Allegro moderato Op. 3 No 5" },
  { "l": "C", "s": "S17", "c": "LYADOV, A.", "t": "Mazurka Op. 57 No 3" },
  { "l": "C", "s": "Manual", "c": "ALBÉNIZ, I.", "t": "Malagueña Op. 165" },
  { "l": "C", "s": "Manual", "c": "ALKAN, C.-V.", "t": "La chanson de la folle Op. 31 No 8" },
  { "l": "C", "s": "Manual", "c": "BENJAMIN, A.", "t": "Waltz (Fantasies Book 2)" },
  { "l": "C", "s": "Manual", "c": "BORTKIEWICZ, S.", "t": "Erster Schmerz Op. 14 No 5" },
  { "l": "C", "s": "Manual", "c": "CHOPIN, F.", "t": "Prelude in Db Op. 28 No 15" },
  { "l": "C", "s": "Manual", "c": "COLERIDGE-TAYLOR, S.", "t": "Tempo di minuetto Op. 74 No 3" },
  { "l": "C", "s": "Manual", "c": "GADE, N.", "t": "Scherzo Op. 19 No 2" },
  { "l": "C", "s": "Manual", "c": "GLIER, R.", "t": "Prelude Op. 31 No 1" },
  { "l": "C", "s": "Manual", "c": "GRANADOS, E.", "t": "Danza de la rosa" },
  { "l": "C", "s": "Manual", "c": "GRIEG, E.", "t": "In der Heimat Op. 43 No 3" },
  { "l": "C", "s": "Manual", "c": "GRIEG, E.", "t": "Puck Op. 71 No 3" },
  { "l": "C", "s": "Manual", "c": "GURLITT, C.", "t": "Allegretto grazioso Op. 107 No 4" },
  { "l": "C", "s": "Manual", "c": "GURLITT, C.", "t": "Moderato grazioso Op. 107 No 7" },
  { "l": "C", "s": "Manual", "c": "HENSEL, F.", "t": "Bagatelle No 1" },
  { "l": "C", "s": "Manual", "c": "HOFMANN, H.", "t": "Hungarian" },
  { "l": "C", "s": "Manual", "c": "KALINNIKOV, V.", "t": "Chanson triste" },
  { "l": "C", "s": "Manual", "c": "MACDOWELL, E.", "t": "Of a tailor and a bear Op. 4 No 2" },
  { "l": "C", "s": "Manual", "c": "MACDOWELL, E.", "t": "Song Op. 55 No 5" },
  { "l": "C", "s": "Manual", "c": "SCHUMANN, R.", "t": "Buntes blatt Op. 99 No 1" },
  { "l": "C", "s": "Manual", "c": "SKRYABIN, A.", "t": "Prelude Op. 11 No 2" },
  { "l": "C", "s": "Manual", "c": "SKRYABIN, A.", "t": "Prelude Op. 11 No 4" },

  // --- LIST D (Contemporary) ---
  { "l": "D", "s": "S19", "c": "BOWMAN, C.", "t": "Don Grant's dragonfly" },
  { "l": "D", "s": "S19", "c": "CAIROS-REGO, I. de.", "t": "Arabesque in A minor" },
  { "l": "D", "s": "S19", "c": "COWAN, C.", "t": "The clock maker" },
  { "l": "D", "s": "S19", "c": "EVANS, L.", "t": "The coral island" },
  { "l": "D", "s": "S19", "c": "KABALEVSKY, D.", "t": "Variations Op. 40 No 1" },
  { "l": "D", "s": "S18", "c": "BENJAMIN, A.", "t": "Silent and soft and slow descends the snow" },
  { "l": "D", "s": "S18", "c": "HANDEL, A.", "t": "Dreamboat blues" },
  { "l": "D", "s": "S18", "c": "SEIBER, M.", "t": "Ap agapak: variations" },
  { "l": "D", "s": "S18", "c": "TURINA, J.", "t": "Fiesta No 7 (Miniatures)" },
  { "l": "D", "s": "S17", "c": "IBERT, J.", "t": "La cage de cristal" },
  { "l": "D", "s": "S17", "c": "KATS-CHERNIN, E.", "t": "Cinema" },
  { "l": "D", "s": "S17", "c": "PROKOFIEV, S.", "t": "Soir Op. 65 No 11" },
  { "l": "D", "s": "AustAnth", "c": "AGNEW, R.", "t": "A child’s dream" },
  { "l": "D", "s": "AustAnth", "c": "BENJAMIN, A.", "t": "Dance at dawn" },
  { "l": "D", "s": "AustAnth", "c": "HYDE, M.", "t": "Tap tune" },
  { "l": "D", "s": "AustAnth", "c": "ISAACS, M.", "t": "Tender earth" },
  { "l": "D", "s": "AustAnth", "c": "MEALE, R.", "t": "Bagatelle" },
  { "l": "D", "s": "AustAnth", "c": "SITSKY, L.", "t": "Fantasia No 11, 'E'" },
  { "l": "D", "s": "Manual", "c": "BAILEY, K.", "t": "Dance on the nightingale floor" },
  { "l": "D", "s": "Manual", "c": "BAILEY, K.", "t": "Morning song" },
  { "l": "D", "s": "Manual", "c": "BAILEY, K.", "t": "Reflection" },
  { "l": "D", "s": "Manual", "c": "BARTÒK, B.", "t": "Grasshopper’s wedding" },
  { "l": "D", "s": "Manual", "c": "BARTÒK, B.", "t": "Andante (Three Rondos BB 92)" },
  { "l": "D", "s": "Manual", "c": "BARTÒK, B.", "t": "Bagpipe music (Mikrokosmos V)" },
  { "l": "D", "s": "Manual", "c": "BONSOR, B.", "t": "Feelin’ good" },
  { "l": "D", "s": "Manual", "c": "BONSOR, B.", "t": "Girl on a catwalk" },
  { "l": "D", "s": "Manual", "c": "BONSOR, B.", "t": "Willie Wagglestick's walkabout" },
  { "l": "D", "s": "Manual", "c": "BURLEIGH, H.", "t": "On bended knees" },
  { "l": "D", "s": "Manual", "c": "CHUA, S.", "t": "Yo ho ho and a bottle of rum" },
  { "l": "D", "s": "Manual", "c": "CORNICK, M.", "t": "Romance No 3" },
  { "l": "D", "s": "Manual", "c": "DEBUSSY, C.", "t": "The little shepherd" },
  { "l": "D", "s": "Manual", "c": "GERSHWIN, G.", "t": "Prelude (Novelette in fourths)" },
  { "l": "D", "s": "Manual", "c": "HYDE, M.", "t": "Woodland sketch" },
  { "l": "D", "s": "Manual", "c": "KABALEVSKY, D.", "t": "Sonatina Op. 13 No 1 (1st movt)" },
  { "l": "D", "s": "Manual", "c": "KABALEVSKY, D.", "t": "Novelette Op. 27 No 25" },
  { "l": "D", "s": "Manual", "c": "NORTON, C.", "t": "Prelude 5 (Bossa Nova)" },
  { "l": "D", "s": "Manual", "c": "PROKOFIEV, S.", "t": "Playing Tag Op. 65 No 9" },
  { "l": "D", "s": "Manual", "c": "RAVEL, M.", "t": "Prélude (1913)" },
  { "l": "D", "s": "Manual", "c": "SHOSTAKOVICH, D.", "t": "Lyric waltz" },
  { "l": "D", "s": "Manual", "c": "SHOSTAKOVICH, D.", "t": "Polka No 4" },
  { "l": "D", "s": "Manual", "c": "TCHEREPNIN, A.", "t": "Bagatelle Op. 5 No 4" },

  // --- COLLABORATIVE PIANO (Manual Lists Only) ---
  // List C (Collaborative)
  { "l": "C", "s": "Collab", "c": "BIZET, G.", "t": "La poupée No 3 [Secondo]" },
  { "l": "C", "s": "Collab", "c": "FAURÉ, G.", "t": "Berceuse No 1 [Secondo] from Dolly Op. 56" },
  { "l": "C", "s": "Collab", "c": "RACHMANINOFF, S.", "t": "Thème russe No 3 [Primo or Secondo]" },
  { "l": "C", "s": "Collab", "c": "SCHUMANN, R.", "t": "Trauer No 6 [Secondo] from Op. 85" },
  // List D (Collaborative)
  { "l": "D", "s": "Collab", "c": "CORNICK, M.", "t": "Blues in F [Secondo]" },
  { "l": "D", "s": "Collab", "c": "GRAINGER, P.", "t": "Country gardens No 22 [Primo]" },
  { "l": "D", "s": "Collab", "c": "NORTON, C.", "t": "Mambo [Primo or Secondo] from Latin duets" },
  { "l": "D", "s": "Collab", "c": "PETER-HORAS, T.", "t": "Tabasco [Primo or Secondo]" },
  { "l": "D", "s": "Collab", "c": "POULENC, F.", "t": "Sonata for four hands - Prelude (1st movt) [Primo]" }
];