// DATA_G6 — AMEB Piano Grade 6 Comprehensive (9946)
// Extracted from piano-repertoire_g6.html
// Total: 160 pieces — A:41, B:35, C:37, D:47
const DATA_G6 = [

  // --- LIST A ---
  { "l": "A", "s": "S19", "c": "BACH, J.S.", "t": "Allemande (French Suite No 4 BWV 815)", "nat": "German", "era": "Baroque", "key": "G Major", "focus": ["Baroque style", "Phrasing", "Ornamentation"] },
  { "l": "A", "s": "S19", "c": "HANDEL, G.F.", "t": "Allegro (Suite HWV 432)", "nat": "German-British", "era": "Baroque", "key": "Variable", "focus": ["Dance character", "Articulation", "Harpsichord style"] },
  { "l": "A", "s": "S19", "c": "HELLER, S.", "t": "Étude No 15 Op. 45", "nat": "Hungarian", "era": "Romantic", "key": "Variable", "focus": ["Technique", "Fluency", "Voice leading"] },
  { "l": "A", "s": "S19", "c": "MONOROSI, K.", "t": "Etude in A minor No 20 Op. 1", "nat": "Hungarian", "era": "Modern", "key": "A Minor", "focus": ["Left hand", "Dexterity", "Romantic expression"] },
  { "l": "A", "s": "S18", "c": "BACH, J.S.", "t": "Menuet I and II (French Suite No 3 BWV 814)", "nat": "German", "era": "Baroque", "key": "B Minor", "focus": ["Baroque style", "Elegance", "Rhythmic energy"] },
  { "l": "A", "s": "S18", "c": "DAQUIN, L.", "t": "Le coucou", "nat": "French", "era": "Baroque", "key": "G Major", "focus": ["Baroque character", "Imitation", "Counterpoint texture"] },
  { "l": "A", "s": "S18", "c": "LUTOSŁAWSKI, W.", "t": "Four-finger exercise No 1", "nat": "Polish", "era": "Modern", "key": "Variable", "focus": ["Technical work", "Precision", "Rhythmic drive"] },
  { "l": "A", "s": "S18", "c": "SCARLATTI, D.", "t": "Sonata K 35", "nat": "Italian", "era": "Baroque", "key": "Variable", "focus": ["Finger work", "Rapidity", "Modern idiom"] },
  { "l": "A", "s": "S17", "c": "BACH, J.S.", "t": "Gigue (Suite No 6 BWV 817)", "nat": "German", "era": "Baroque", "key": "Variable", "focus": ["Dance character", "Rhythm", "Baroque phrasing"] },
  { "l": "A", "s": "S17", "c": "BACH, J.S.", "t": "Sinfonia BWV 794", "nat": "German", "era": "Baroque", "key": "Variable", "focus": ["Three-part counterpoint", "Independence", "Dance character"] },
  { "l": "A", "s": "S17", "c": "HELLER, S.", "t": "Etude No 20 Op. 45", "nat": "Hungarian", "era": "Romantic", "key": "Variable", "focus": ["Flowing", "Grace", "Polyphonic awareness"] },
  { "l": "A", "s": "Manual", "c": "ALBÉNIZ, M.", "t": "Sonata in D major", "nat": "Spanish", "era": "Baroque", "key": "D Major", "focus": ["Classical form", "Dynamics", "Tonal colour"] },
  { "l": "A", "s": "Manual", "c": "BACH, C.P.E.", "t": "Presto in C minor H 230", "nat": "German", "era": "Classical", "key": "C Minor", "focus": ["Empfindsam style", "Expression", "Terraced dynamics"] },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Courante (French Suite No 2 BWV 813)", "nat": "German", "era": "Baroque", "key": "C Minor", "focus": ["Suite dance", "Baroque style", "Classical clarity"] },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Sinfonia No 1 in C BWV 787", "nat": "German", "era": "Baroque", "key": "C Major", "focus": ["Counterpoint", "Clarity", "Stylistic clarity"] },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Sinfonia No 3 in D BWV 789", "nat": "German", "era": "Baroque", "key": "D Major", "focus": ["Three-part", "Articulation", "Finger independence"] },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Sinfonia No 6 in E BWV 792", "nat": "German", "era": "Baroque", "key": "E Major", "focus": ["Baroque voice leading", "Texture", "Technical fluency"] },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Sinfonia No 9 in E minor BWV 793", "nat": "German", "era": "Baroque", "key": "E Minor", "focus": ["Expression", "Independence", "Velocity control"] },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Gigue (French Suite No 3 BWV 814)", "nat": "German", "era": "Baroque", "key": "A Minor", "focus": ["Dance rhythm", "Agility", "Tone evenness"] },
  { "l": "A", "s": "Manual", "c": "BACH, J.S.", "t": "Little Prelude No 4 BWV 936", "nat": "German", "era": "Baroque", "key": "C Major", "focus": ["Baroque style", "Melody", "Wrist flexibility"] },
  { "l": "A", "s": "Manual", "c": "BURGMÜLLER, F.", "t": "Le retour de pâtre Op. 109 No 3", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Lyrical melody", "Expression", "Finger equality"] },
  { "l": "A", "s": "Manual", "c": "CHUA, S.", "t": "Study No 20 (Zeitgeist Book 2)", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Contemporary style", "Technical", "Musical shaping"] },
  { "l": "A", "s": "Manual", "c": "CIMAROSA, D.", "t": "Sonata in A major No 14", "nat": "Italian", "era": "Classical", "key": "A Major", "focus": ["Classical form", "Clarity", "Extended technique"] },
  { "l": "A", "s": "Manual", "c": "CZERNY, C.", "t": "Etude Op. 299 No 29", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Velocity", "Precision", "Formal structure"] },
  { "l": "A", "s": "Manual", "c": "CZERNY, C.", "t": "Etude Op. 299 No 5", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Finger work", "Scales", "Balanced phrasing"] },
  { "l": "A", "s": "Manual", "c": "CZERNY, C.", "t": "Etude Op. 299 No 6", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Hand independence", "Rhythm", "Elegant articulation"] },
  { "l": "A", "s": "Manual", "c": "CZERNY, C.", "t": "Etude Op. 849 No 24", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Agility", "Coordination", "Harmonic awareness"] },
  { "l": "A", "s": "Manual", "c": "HANDEL, G.", "t": "Air con variazioni (Suite HWV 434)", "nat": "German-British", "era": "Baroque", "key": "Variable", "focus": ["Variation form", "Expression", "Textural balance"] },
  { "l": "A", "s": "Manual", "c": "HANDEL, G.", "t": "Sonatina in D minor HWV 581", "nat": "German-British", "era": "Baroque", "key": "D Minor", "focus": ["Baroque form", "Articulation", "Articulation clarity"] },
  { "l": "A", "s": "Manual", "c": "HELLER, S.", "t": "Etude Op. 45 No 9", "nat": "Hungarian", "era": "Romantic", "key": "Variable", "focus": ["Melody", "Phrasing", "Technical agility"] },
  { "l": "A", "s": "Manual", "c": "HELLER, S.", "t": "Etude Op. 45 No 21", "nat": "Hungarian", "era": "Romantic", "key": "Variable", "focus": ["Voicing", "Expression", "Cantabile"] },
  { "l": "A", "s": "Manual", "c": "HELLER, S.", "t": "Etude Op. 45 No 22", "nat": "Hungarian", "era": "Romantic", "key": "Variable", "focus": ["Hand control", "Dynamics", "Pedal technique"] },
  { "l": "A", "s": "Manual", "c": "KREBS, J.", "t": "Courante in C major (Clavier-Übung)", "nat": "German", "era": "Baroque", "key": "C Major", "focus": ["Suite dance", "Fluency", "Emotional depth"] },
  { "l": "A", "s": "Manual", "c": "MOSZKOWSKI, M.", "t": "Etude Op. 91 No 1", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Bravura", "Technique", "Ornamentation"] },
  { "l": "A", "s": "Manual", "c": "PURCELL, H.", "t": "Prelude (Suite Z 661)", "nat": "British", "era": "Baroque", "key": "Variable", "focus": ["Baroque style", "Articulation", "Lyrical phrasing"] },
  { "l": "A", "s": "Manual", "c": "SCARLATTI, D.", "t": "Sonata K 85", "nat": "Italian", "era": "Baroque", "key": "Variable", "focus": ["Rapid figuration", "Clarity", "Harpsichord style"] },
  { "l": "A", "s": "Manual", "c": "SCARLATTI, D.", "t": "Sonata K 3", "nat": "Italian", "era": "Baroque", "key": "Variable", "focus": ["Harpsichord style", "Rhythm", "Rhythmic drive"] },
  { "l": "A", "s": "Manual", "c": "TANSMAN, A.", "t": "Fughetta", "nat": "Polish-French", "era": "Modern", "key": "Variable", "focus": ["Fugal form", "Counterpoint", "Counterpoint texture"] },
  { "l": "A", "s": "Manual", "c": "TELEMANN, G.", "t": "Allegro (Fantasia No 4 TWV 33:4)", "nat": "German", "era": "Baroque", "key": "Variable", "focus": ["Baroque style", "Expression", "Stylistic clarity"] },
  { "l": "A", "s": "Manual", "c": "TELEMANN, G.", "t": "Vivace (Fantasia No 5 TWV 33:5)", "nat": "German", "era": "Baroque", "key": "Variable", "focus": ["Dance character", "Rhythm", "Baroque phrasing"] },
  { "l": "A", "s": "Manual", "c": "TELEMANN, G.", "t": "Allegro (Fantasia No 9 TWV 33:9)", "nat": "German", "era": "Baroque", "key": "Variable", "focus": ["Baroque form", "Articulation", "Baroque phrasing"] },

  // --- LIST B ---
  { "l": "B", "s": "S19", "c": "BEETHOVEN, L. van.", "t": "Andante (Sonata Op. 49 No 1)", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Phrasing", "Ornamentation"] },
  { "l": "B", "s": "S19", "c": "HAYDN, J.", "t": "Theme and Variations Hob XVII:2", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Theme & variations", "Expression", "Classical clarity"] },
  { "l": "B", "s": "S19", "c": "MARTÍNEZ, M. von.", "t": "Allegro (Sonata Op. 4)", "nat": "Spanish", "era": "Classical", "key": "Variable", "focus": ["Classical style", "Melody", "Formal structure"] },
  { "l": "B", "s": "S19", "c": "NEEFE, C.", "t": "Allegro di molto (Sonata No 2)", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Vigor", "Balanced phrasing"] },
  { "l": "B", "s": "S18", "c": "BACH, J.C.", "t": "Allegro (Sonata Op. 17 No 3)", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Articulation", "Elegant articulation"] },
  { "l": "B", "s": "S18", "c": "EBERL, A.", "t": "Allegro (Sonatine Op. 5)", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Classical elegance", "Melody", "Harmonic awareness"] },
  { "l": "B", "s": "S18", "c": "KOZELUCH, L.", "t": "Allegretto (Sonata Op. 35 No 3)", "nat": "Czech", "era": "Classical", "key": "Variable", "focus": ["Classical style", "Grace", "Textural balance"] },
  { "l": "B", "s": "S18", "c": "SCHUMANN, C.", "t": "Scherzo No 4 Op. 15", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Scherzo form", "Character", "Dynamic shaping"] },
  { "l": "B", "s": "S17", "c": "BACH, C.P.E.", "t": "Vivace (Sonata No 1 W 50)", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Empfindsam", "Expression", "Romantic expression"] },
  { "l": "B", "s": "S17", "c": "BEETHOVEN, L. van.", "t": "Six variations WoO 77", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Variation form", "Virtuosity", "Stylistic grace"] },
  { "l": "B", "s": "S17", "c": "HAYDN, J.", "t": "Finale (Sonata Hob XVI:21)", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Rhythm", "Melodic shaping"] },
  { "l": "B", "s": "S17", "c": "VOŘÍŠEK, J.", "t": "Rondo No 1 Op. 18", "nat": "Czech", "era": "Classical", "key": "Variable", "focus": ["Rondo form", "Grace", "Accompaniment balance"] },
  { "l": "B", "s": "Manual", "c": "BACH, C.P.E.", "t": "Allegro di molto (Sonata H 59)", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Empfindsam style", "Drama", "Singing tone"] },
  { "l": "B", "s": "Manual", "c": "BACH, J.C.", "t": "Allegretto (Sonata Op. 5 No 1)", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Elegance", "Phrasing"] },
  { "l": "B", "s": "Manual", "c": "BEETHOVEN, L. van.", "t": "Minuet (Sonata Op. 22)", "nat": "German", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Character", "Touch variety"] },
  { "l": "B", "s": "Manual", "c": "BENDA, J.", "t": "Sonatina No 13 in C minor", "nat": "Czech", "era": "Classical", "key": "C Minor", "focus": ["Classical form", "Expression", "Musical sensitivity"] },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Rondo (Sonatina Op. 36 No 4)", "nat": "Italian", "era": "Classical", "key": "Variable", "focus": ["Rondo form", "Virtuosity", "Expressive playing"] },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Presto (Sonatina Op. 36 No 5)", "nat": "Italian", "era": "Classical", "key": "Variable", "focus": ["Fast tempo", "Clarity", "Tone control"] },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Allegro moderato (Sonatina Op. 38 No 2)", "nat": "Italian", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Grace", "Classical clarity"] },
  { "l": "B", "s": "Manual", "c": "CLEMENTI, M.", "t": "Allegretto (Sonatina Op. 38 No 3)", "nat": "Italian", "era": "Classical", "key": "Variable", "focus": ["Classical elegance", "Melody", "Formal structure"] },
  { "l": "B", "s": "Manual", "c": "DIABELLI, A.", "t": "Allegro moderato (Sonatina Op. 151 No 3)", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Classical style", "Grace", "Balanced phrasing"] },
  { "l": "B", "s": "Manual", "c": "DUSSEK, J.", "t": "Moderato (Sonatina Op. 20 No 4)", "nat": "Czech", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Elegance", "Elegant articulation"] },
  { "l": "B", "s": "Manual", "c": "DUSSEK, J.", "t": "Allegro (Sonatina Op. 20 No 6)", "nat": "Czech", "era": "Classical", "key": "Variable", "focus": ["Classical style", "Virtuosity", "Harmonic awareness"] },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Moderato (Sonata Hob XVI:2)", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Grace", "Textural balance"] },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Moderato (Sonata Hob XVI:13)", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Classical style", "Melody", "Dynamic shaping"] },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Finale (Sonata Hob XVI:14)", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Finale form", "Rhythm", "Stylistic grace"] },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Finale (Sonata Hob XVI:27)", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Classical finale", "Character", "Melodic shaping"] },
  { "l": "B", "s": "Manual", "c": "HAYDN, J.", "t": "Scherzando (Sonata Hob XVI:36)", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Playful character", "Rhythm", "Accompaniment balance"] },
  { "l": "B", "s": "Manual", "c": "KUHLAU, F.", "t": "Allegro maestoso (Sonatina Op. 55 No 6)", "nat": "German-Danish", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Majesty", "Singing tone"] },
  { "l": "B", "s": "Manual", "c": "KUHLAU, F.", "t": "Allegro con spirito (Sonatina Op. 60 No 2)", "nat": "German-Danish", "era": "Classical", "key": "Variable", "focus": ["Classical style", "Spirit", "Phrasing"] },
  { "l": "B", "s": "Manual", "c": "KUHLAU, F.", "t": "Allegro burlesco (Sonatina Op. 88 No 3)", "nat": "German-Danish", "era": "Classical", "key": "Variable", "focus": ["Burlesque character", "Humor", "Touch variety"] },
  { "l": "B", "s": "Manual", "c": "MOZART, W.", "t": "Allegro (Sonata K 282)", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Classical form", "Elegance", "Musical sensitivity"] },
  { "l": "B", "s": "Manual", "c": "MOZART, W.", "t": "Minuet and Trio (Sonata K 331)", "nat": "Austrian", "era": "Classical", "key": "Variable", "focus": ["Minuet form", "Character", "Expressive playing"] },
  { "l": "B", "s": "Manual", "c": "PLEYEL, I.", "t": "Rondo (Sonatina III in G)", "nat": "Austrian-French", "era": "Classical", "key": "G Major", "focus": ["Rondo form", "Grace", "Tone control"] },
  { "l": "B", "s": "Manual", "c": "SCHUBERT, F.", "t": "Scherzo No 1 D 593", "nat": "Austrian", "era": "Romantic", "key": "Variable", "focus": ["Scherzo form", "Expression", "Classical clarity"] },

  // --- LIST C ---
  { "l": "C", "s": "S19", "c": "CHOPIN, F.", "t": "Mazurka Op. 7 No 1", "nat": "Polish", "era": "Romantic", "key": "Variable", "focus": ["Mazurka character", "Rubato", "Tonal colour"] },
  { "l": "C", "s": "S19", "c": "FARRENC, L.", "t": "Impromptu", "nat": "French", "era": "Romantic", "key": "Variable", "focus": ["Romantic expression", "Virtuosity", "Tonal colour"] },
  { "l": "C", "s": "S19", "c": "FIELD, J.", "t": "Nocturne H 59", "nat": "British", "era": "Romantic", "key": "Variable", "focus": ["Nocturne style", "Lyricism", "Tonal colour"] },
  { "l": "C", "s": "S19", "c": "PAINE, J.", "t": "Rainy day Op. 26 No 6", "nat": "American", "era": "Romantic", "key": "Variable", "focus": ["Romantic expression", "Atmosphere", "Cantabile"] },
  { "l": "C", "s": "S18", "c": "GRIEG, E.", "t": "Notturno Op. 54 No 4", "nat": "Norwegian", "era": "Romantic", "key": "Variable", "focus": ["Nocturne character", "Lyricism", "Cantabile"] },
  { "l": "C", "s": "S18", "c": "HILL, A.", "t": "Berceuse", "nat": "British", "era": "Romantic", "key": "Variable", "focus": ["Lullaby", "Sustain pedal", "Pedal technique"] },
  { "l": "C", "s": "S18", "c": "SÉVERAC, D. de.", "t": "Mimi se déguise en Marquise", "nat": "French", "era": "Romantic", "key": "Variable", "focus": ["Character piece", "Expression", "Emotional depth"] },
  { "l": "C", "s": "S18", "c": "WOLLENHAUPT, H.", "t": "Scherzino Op. 29 No 6", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Scherzino form", "Character", "Lyrical phrasing"] },
  { "l": "C", "s": "S17", "c": "DELIBES, L.", "t": "Passepied No 6", "nat": "French", "era": "Romantic", "key": "Variable", "focus": ["Baroque dance", "Grace", "Dynamic range"] },
  { "l": "C", "s": "S17", "c": "GADE, N.", "t": "Andantino", "nat": "Danish", "era": "Romantic", "key": "Variable", "focus": ["Romantic expression", "Melody", "Character"] },
  { "l": "C", "s": "S17", "c": "GRIEG, E.", "t": "Allegro moderato Op. 3 No 5", "nat": "Norwegian", "era": "Romantic", "key": "Variable", "focus": ["Norwegian character", "Expression", "Character"] },
  { "l": "C", "s": "S17", "c": "LYADOV, A.", "t": "Mazurka Op. 57 No 3", "nat": "Russian", "era": "Romantic", "key": "Variable", "focus": ["Mazurka character", "Grace", "Creative character"] },
  { "l": "C", "s": "Manual", "c": "ALBÉNIZ, I.", "t": "Malagueña Op. 165", "nat": "Spanish", "era": "Romantic", "key": "Variable", "focus": ["Spanish character", "Virtuosity", "Stylistic freedom"] },
  { "l": "C", "s": "Manual", "c": "ALKAN, C.-V.", "t": "La chanson de la folle Op. 31 No 8", "nat": "French", "era": "Romantic", "key": "Variable", "focus": ["Romantic expression", "Virtuosity", "Tonal colour"] },
  { "l": "C", "s": "Manual", "c": "BENJAMIN, A.", "t": "Waltz (Fantasies Book 2)", "nat": "British", "era": "Modern", "key": "Variable", "focus": ["Waltz character", "Grace", "Tonal colour"] },
  { "l": "C", "s": "Manual", "c": "BORTKIEWICZ, S.", "t": "Erster Schmerz Op. 14 No 5", "nat": "Russian", "era": "Romantic", "key": "Variable", "focus": ["Romantic expression", "Lyricism", "Rhythmic energy"] },
  { "l": "C", "s": "Manual", "c": "CHOPIN, F.", "t": "Prelude in Db Op. 28 No 15", "nat": "Polish", "era": "Romantic", "key": "D Flat Major", "focus": ["Romantic expression", "Virtuosity", "Contemporary flavour"] },
  { "l": "C", "s": "Manual", "c": "COLERIDGE-TAYLOR, S.", "t": "Tempo di minuetto Op. 74 No 3", "nat": "British", "era": "Romantic", "key": "Variable", "focus": ["Minuetto form", "Grace", "Contemporary flavour"] },
  { "l": "C", "s": "Manual", "c": "GADE, N.", "t": "Scherzo Op. 19 No 2", "nat": "Danish", "era": "Romantic", "key": "Variable", "focus": ["Scherzo form", "Character", "Imagination"] },
  { "l": "C", "s": "Manual", "c": "GLIER, R.", "t": "Prelude Op. 31 No 1", "nat": "Russian", "era": "Romantic", "key": "Variable", "focus": ["Romantic expression", "Lyricism", "Tonal colour"] },
  { "l": "C", "s": "Manual", "c": "GRANADOS, E.", "t": "Danza de la rosa", "nat": "Spanish", "era": "Romantic", "key": "Variable", "focus": ["Spanish character", "Virtuosity", "Romantic expression"] },
  { "l": "C", "s": "Manual", "c": "GRIEG, E.", "t": "In der Heimat Op. 43 No 3", "nat": "Norwegian", "era": "Romantic", "key": "Variable", "focus": ["Norwegian character", "Expression", "Tonal colour"] },
  { "l": "C", "s": "Manual", "c": "GRIEG, E.", "t": "Puck Op. 71 No 3", "nat": "Norwegian", "era": "Romantic", "key": "Variable", "focus": ["Character piece", "Lightness", "Musical shaping"] },
  { "l": "C", "s": "Manual", "c": "GURLITT, C.", "t": "Allegretto grazioso Op. 107 No 4", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Romantic grace", "Expression", "Cantabile"] },
  { "l": "C", "s": "Manual", "c": "GURLITT, C.", "t": "Moderato grazioso Op. 107 No 7", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Romantic expression", "Grace", "Lyrical phrasing"] },
  { "l": "C", "s": "Manual", "c": "HENSEL, F.", "t": "Bagatelle No 1", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Bagatelle form", "Lyricism", "Emotional depth"] },
  { "l": "C", "s": "Manual", "c": "HOFMANN, H.", "t": "Hungarian", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Hungarian character", "Expression", "Lyrical phrasing"] },
  { "l": "C", "s": "Manual", "c": "KALINNIKOV, V.", "t": "Chanson triste", "nat": "Russian", "era": "Romantic", "key": "Variable", "focus": ["Sad character", "Lyricism", "Dynamic range"] },
  { "l": "C", "s": "Manual", "c": "MACDOWELL, E.", "t": "Of a tailor and a bear Op. 4 No 2", "nat": "American", "era": "Romantic", "key": "Variable", "focus": ["Character piece", "Humor", "Expressive nuance"] },
  { "l": "C", "s": "Manual", "c": "MACDOWELL, E.", "t": "Song Op. 55 No 5", "nat": "American", "era": "Romantic", "key": "Variable", "focus": ["Song form", "Lyricism", "Character"] },
  { "l": "C", "s": "Manual", "c": "SCHUMANN, R.", "t": "Buntes blatt Op. 99 No 1", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Character piece", "Expression", "Creative character"] },
  { "l": "C", "s": "Manual", "c": "SKRYABIN, A.", "t": "Prelude Op. 11 No 2", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Impressionistic harmony", "Expression", "Stylistic freedom"] },
  { "l": "C", "s": "Manual", "c": "SKRYABIN, A.", "t": "Prelude Op. 11 No 4", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Impressionistic harmony", "Lyricism", "Modern idiom"] },

  // --- LIST D ---
  { "l": "D", "s": "S19", "c": "BOWMAN, C.", "t": "Don Grant's dragonfly", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Character piece", "Imagery", "Rhythmic energy"] },
  { "l": "D", "s": "S19", "c": "CAIROS-REGO, I. de.", "t": "Arabesque in A minor", "nat": "Portuguese", "era": "Modern", "key": "A Minor", "focus": ["Romantic form", "Lyricism", "Extended technique"] },
  { "l": "D", "s": "S19", "c": "COWAN, C.", "t": "The clock maker", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Character piece", "Imagery", "Modern idiom"] },
  { "l": "D", "s": "S19", "c": "EVANS, L.", "t": "The coral island", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Descriptive", "Atmosphere", "Creative expression"] },
  { "l": "D", "s": "S19", "c": "KABALEVSKY, D.", "t": "Variations Op. 40 No 1", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Variation form", "Expression", "Contemporary idiom"] },
  { "l": "D", "s": "S18", "c": "BENJAMIN, A.", "t": "Silent and soft and slow descends the snow", "nat": "British", "era": "Modern", "key": "Variable", "focus": ["Romantic expression", "Atmosphere", "Stylistic clarity"] },
  { "l": "D", "s": "S18", "c": "HANDEL, A.", "t": "Dreamboat blues", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Blues character", "Contemporary", "Contemporary technique"] },
  { "l": "D", "s": "S18", "c": "SEIBER, M.", "t": "Ap agapak: variations", "nat": "Hungarian", "era": "Modern", "key": "Variable", "focus": ["Variation form", "Expression", "Tonal exploration"] },
  { "l": "D", "s": "S18", "c": "TURINA, J.", "t": "Fiesta Op. Miniaturas No 7", "nat": "Spanish", "era": "Modern", "key": "Variable", "focus": ["Spanish character", "Virtuosity", "Tonal exploration"] },
  { "l": "D", "s": "S17", "c": "IBERT, J.", "t": "La cage de cristal", "nat": "French", "era": "Modern", "key": "Variable", "focus": ["Impressionistic", "Imagery", "Character"] },
  { "l": "D", "s": "S17", "c": "KATS-CHERNIN, E.", "t": "Cinema", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Contemporary character", "Imagery", "Rhythmic precision"] },
  { "l": "D", "s": "S17", "c": "PROKOFIEV, S.", "t": "Soir Op. 65 No 11", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Modern character", "Expression", "Rhythmic imagination"] },
  { "l": "D", "s": "Anthology", "c": "AGNEW, R.", "t": "A child's dream", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Character piece", "Imagery", "Musical imagination"] },
  { "l": "D", "s": "Anthology", "c": "BENJAMIN, A.", "t": "Dance at dawn", "nat": "British", "era": "Modern", "key": "Variable", "focus": ["Dance character", "Expression", "Stylistic awareness"] },
  { "l": "D", "s": "Anthology", "c": "HYDE, M.", "t": "Tap tune", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Dance character", "Rhythm", "Creative character"] },
  { "l": "D", "s": "Anthology", "c": "ISAACS, M.", "t": "Tender earth", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Romantic expression", "Lyricism", "Sound colour"] },
  { "l": "D", "s": "Anthology", "c": "MEALE, R.", "t": "Bagatelle", "nat": "Australian", "era": "Modern", "key": "Variable", "focus": ["Bagatelle form", "Expression", "Modern character"] },
  { "l": "D", "s": "Anthology", "c": "SITSKY, L.", "t": "Fantasia No 11, 'E'", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Fantasia form", "Virtuosity", "Stylistic freedom"] },
  { "l": "D", "s": "Manual", "c": "BAILEY, K.", "t": "Dance on the nightingale floor", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Dance character", "Expression", "Creative character"] },
  { "l": "D", "s": "Manual", "c": "BAILEY, K.", "t": "Morning song", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Song character", "Lyricism", "Stylistic freedom"] },
  { "l": "D", "s": "Manual", "c": "BAILEY, K.", "t": "Reflection", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Introspective", "Expression", "Musical imagery"] },
  { "l": "D", "s": "Manual", "c": "BARTÓK, B.", "t": "Grasshopper's wedding", "nat": "Hungarian", "era": "Modern", "key": "Variable", "focus": ["Character piece", "Humor", "Tonal colour"] },
  { "l": "D", "s": "Manual", "c": "BARTÓK, B.", "t": "Andante (Three Rondos BB 92)", "nat": "Hungarian", "era": "Modern", "key": "Variable", "focus": ["Rondo form", "Expression", "Musical imagery"] },
  { "l": "D", "s": "Manual", "c": "BARTÓK, B.", "t": "Bagpipe music (Mikrokosmos V)", "nat": "Hungarian", "era": "Modern", "key": "Variable", "focus": ["Folk character", "Rhythm", "Tonal colour"] },
  { "l": "D", "s": "Manual", "c": "BONSOR, B.", "t": "Feelin' good", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Character piece", "Expression", "Expressive range"] },
  { "l": "D", "s": "Manual", "c": "BONSOR, B.", "t": "Girl on a catwalk", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Character piece", "Rhythm", "Expressive range"] },
  { "l": "D", "s": "Manual", "c": "BONSOR, B.", "t": "Willie Wagglestick's walkabout", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Character piece", "Humor", "Contemporary flavour"] },
  { "l": "D", "s": "Manual", "c": "BURLEIGH, H.", "t": "On bended knees", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Spiritual idiom", "Expression", "Character projection"] },
  { "l": "D", "s": "Manual", "c": "CHUA, S.", "t": "Yo ho ho and a bottle of rum", "nat": "Australian", "era": "Contemporary", "key": "Variable", "focus": ["Character piece", "Humor", "Contemporary flavour"] },
  { "l": "D", "s": "Manual", "c": "CORNICK, M.", "t": "Romance No 3", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Romance form", "Lyricism", "Imagination"] },
  { "l": "D", "s": "Manual", "c": "DEBUSSY, C.", "t": "The little shepherd", "nat": "French", "era": "Modern", "key": "Variable", "focus": ["Impressionistic", "Imagery", "Extended technique"] },
  { "l": "D", "s": "Manual", "c": "GERSHWIN, G.", "t": "Prelude (Novelette in fourths)", "nat": "American", "era": "Modern", "key": "Variable", "focus": ["Jazz character", "Modernism", "Character projection"] },
  { "l": "D", "s": "Manual", "c": "HYDE, M.", "t": "Woodland sketch", "nat": "Australian", "era": "Modern", "key": "Variable", "focus": ["Descriptive", "Atmosphere", "Imagination"] },
  { "l": "D", "s": "Manual", "c": "KABALEVSKY, D.", "t": "Sonatina Op. 13 No 1 (1st movt)", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Sonata form", "Expression", "Rhythmic energy"] },
  { "l": "D", "s": "Manual", "c": "KABALEVSKY, D.", "t": "Sonatina Op. 13 No 1 (3rd movt)", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Sonata form", "Rhythmic drive", "Finger dexterity"] },
  { "l": "D", "s": "Manual", "c": "KABALEVSKY, D.", "t": "Novelette Op. 27 No 25", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Novelette form", "Character", "Stylistic clarity"] },
  { "l": "D", "s": "Manual", "c": "NORTON, C.", "t": "Prelude 5 (Bossa Nova)", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Bossa nova character", "Rhythm", "Stylistic clarity"] },
  { "l": "D", "s": "Manual", "c": "PROKOFIEV, S.", "t": "Playing Tag Op. 65 No 9", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Character piece", "Humor", "Creative expression"] },
  { "l": "D", "s": "Manual", "c": "RAVEL, M.", "t": "Prélude (1913)", "nat": "French", "era": "Modern", "key": "Variable", "focus": ["Impressionistic", "Tone colour", "Contemporary technique"] },
  { "l": "D", "s": "Manual", "c": "SHOSTAKOVICH, D.", "t": "Lyric waltz", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Waltz character", "Expression", "Tonal exploration"] },
  { "l": "D", "s": "Manual", "c": "SHOSTAKOVICH, D.", "t": "Polka No 4", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Dance character", "Rhythm", "Character"] },
  { "l": "D", "s": "Manual", "c": "TCHEREPNIN, A.", "t": "Bagatelle Op. 5 No 4", "nat": "Russian", "era": "Modern", "key": "Variable", "focus": ["Bagatelle form", "Expression", "Rhythmic precision"] },

  // --- COLLABORATIVE (듀엣) ---
  { "l": "C", "s": "Collab", "c": "BIZET, G.", "t": "La poupée No 3 [Secondo]", "nat": "French", "era": "Romantic", "key": "Variable", "focus": ["Duet form", "Accompaniment", "Stylistic clarity"] },
  { "l": "C", "s": "Collab", "c": "FAURÉ, G.", "t": "Berceuse No 1 [Secondo] from Dolly Op. 56", "nat": "French", "era": "Romantic", "key": "Variable", "focus": ["Lullaby", "Secondo", "Musical imagery"] },
  { "l": "C", "s": "Collab", "c": "RACHMANINOFF, S.", "t": "Thème russe No 3 [Primo or Secondo]", "nat": "Russian", "era": "Romantic", "key": "Variable", "focus": ["Duet", "Romantic", "Tonal colour"] },
  { "l": "C", "s": "Collab", "c": "SCHUMANN, R.", "t": "Trauer No 6 [Secondo] from Op. 85", "nat": "German", "era": "Romantic", "key": "Variable", "focus": ["Duet form", "Secondo", "Expressive range"] },
  { "l": "D", "s": "Collab", "c": "CORNICK, M.", "t": "Blues in F [Secondo]", "nat": "British", "era": "Contemporary", "key": "F Major", "focus": ["Blues character", "Secondo", "Contemporary flavour"] },
  { "l": "D", "s": "Collab", "c": "GRAINGER, P.", "t": "Country gardens No 22 [Primo]", "nat": "Australian-British", "era": "Modern", "key": "Variable", "focus": ["Folk arrangement", "Primo", "Contemporary idiom"] },
  { "l": "D", "s": "Collab", "c": "NORTON, C.", "t": "Mambo [Primo or Secondo] from Latin duets", "nat": "British", "era": "Contemporary", "key": "Variable", "focus": ["Latin character", "Duet", "Musical imagination"] },
  { "l": "D", "s": "Collab", "c": "PETER-HORAS, T.", "t": "Tabasco [Primo or Secondo]", "nat": "Romanian", "era": "Contemporary", "key": "Variable", "focus": ["Latin character", "Virtuosity", "Tonal exploration"] },
  { "l": "D", "s": "Collab", "c": "POULENC, F.", "t": "Sonata for four hands - Prelude (1st movt) [Primo]", "nat": "French", "era": "Modern", "key": "Variable", "focus": ["Duet form", "Primo", "Rhythmic imagination"] }

];
